'use strict';
const {randomUUID}=require('node:crypto');
const {assertRole}=require('../../core/auth/rbac');
const {writeAudit}=require('../../core/audit/audit-log');
function createProjectService({db,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db)throw new TypeError('db is required.');const cid=a=>String(a?.companyId||'default'),manage=a=>assertRole(a,['admin','manager','director']);
 const cents=(v,label)=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<0)throw new Error(`${label} invalido.`);return n;};
 function requireProject(id,a){const p=db.prepare('SELECT * FROM projects WHERE id=? AND company_id=?').get(String(id),cid(a));if(!p)throw new Error('Projeto nao encontrado.');return p;}
 function setBudget(id,budgetCents,a=null){manage(a);requireProject(id,a);const n=cents(budgetCents,'Orcamento');db.prepare('UPDATE projects SET budget_cents=?,updated_at=? WHERE id=? AND company_id=?').run(n,String(now()),String(id),cid(a));writeAudit(db,{action:'projects.budget.set',entity:'project',entityId:String(id),actor:a,context:{budgetCents:n}},now);return projectSummary(id,a);}
 function addTime(id,i={},a=null){manage(a);requireProject(id,a);const hours=Number(i.hours);if(!Number.isFinite(hours)||hours<=0)throw new Error('Horas invalidas.');const cost=cents(i.hourlyCostCents??0,'Custo hora'),rate=cents(i.billableRateCents??0,'Valor hora'),entryId=String(i.id||idFactory('ptime')),workedAt=String(i.workedAt||now()).slice(0,10),ts=String(now());db.prepare('INSERT INTO project_time_entries(id,company_id,project_id,user_id,hours,hourly_cost_cents,billable_rate_cents,worked_at,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(entryId,cid(a),String(id),i.userId||a?.userId||null,hours,cost,rate,workedAt,i.notes||null,ts);writeAudit(db,{action:'projects.time.add',entity:'project',entityId:String(id),actor:a,context:{hours,hourlyCostCents:cost}},now);return db.prepare('SELECT * FROM project_time_entries WHERE id=?').get(entryId);}
 function addCost(id,kind,i={},a=null){manage(a);requireProject(id,a);const amount=cents(i.amountCents,'Valor'),entryId=String(i.id||idFactory('pcost')),description=String(i.description||kind).trim();if(!description)throw new Error('Descricao obrigatoria.');db.prepare('INSERT INTO project_cost_entries(id,company_id,project_id,kind,description,amount_cents,occurred_at,source_type,source_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(entryId,cid(a),String(id),kind,description,amount,String(i.occurredAt||now()).slice(0,10),i.sourceType||null,i.sourceId||null,String(now()));return{...db.prepare('SELECT * FROM project_cost_entries WHERE id=?').get(entryId),amountCents:amount};}
 const addExpense=(id,i,a)=>addCost(id,'EXPENSE',i,a),addMaterialCost=(id,i,a)=>addCost(id,'MATERIAL',i,a);
 function addRevenue(id,i={},a=null){manage(a);requireProject(id,a);const amount=cents(i.amountCents,'Valor'),entryId=String(i.id||idFactory('prev')),description=String(i.description||'Receita').trim();db.prepare('INSERT INTO project_revenue_entries(id,company_id,project_id,kind,description,amount_cents,occurred_at,source_type,source_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(entryId,cid(a),String(id),String(i.kind||'DIRECT'),description,amount,String(i.occurredAt||now()).slice(0,10),i.sourceType||null,i.sourceId||null,String(now()));return{...db.prepare('SELECT * FROM project_revenue_entries WHERE id=?').get(entryId),amountCents:amount};}
 function createMilestone(id,i={},a=null){manage(a);requireProject(id,a);const milestoneId=String(i.id||idFactory('milestone')),ts=String(now());db.prepare("INSERT INTO project_milestones(id,company_id,project_id,name,due_at,amount_cents,status,created_at,updated_at) VALUES(?,?,?,?,?,?,'OPEN',?,?)").run(milestoneId,cid(a),String(id),String(i.name||'Marco'),i.dueAt||null,cents(i.amountCents??0,'Valor'),ts,ts);return db.prepare('SELECT * FROM project_milestones WHERE id=?').get(milestoneId);}
 function projectSummary(id,a=null){const p=requireProject(id,a),companyId=cid(a);const time=db.prepare('SELECT COALESCE(SUM(hours*hourly_cost_cents),0) cost,COALESCE(SUM(hours*billable_rate_cents),0) billable FROM project_time_entries WHERE company_id=? AND project_id=?').get(companyId,String(id)),direct=db.prepare('SELECT COALESCE(SUM(amount_cents),0) n FROM project_cost_entries WHERE company_id=? AND project_id=?').get(companyId,String(id)),rev=db.prepare('SELECT COALESCE(SUM(amount_cents),0) n FROM project_revenue_entries WHERE company_id=? AND project_id=?').get(companyId,String(id));const timeCostCents=Math.round(Number(time?.cost||0)),directCostCents=Number(direct?.n||0),costCents=timeCostCents+directCostCents,revenueCents=Number(rev?.n||0),budgetCents=Number(p.budget_cents||0);return{id:p.id,name:p.name,budgetCents,timeCostCents,directCostCents,costCents,revenueCents,profitCents:revenueCents-costCents,budgetVarianceCents:budgetCents-costCents,billableTimeCents:Math.round(Number(time?.billable||0))};}
 const profitability=(id,a)=>projectSummary(id,a);
 return{setBudget,addTime,addExpense,addMaterialCost,addRevenue,createMilestone,projectSummary,profitability};
}
module.exports={createProjectService};
