'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
const {positiveQuantity}=require('../inventory/inventory-rules');
const {assertCents}=require('../shared/money');

function createManufacturingService({db,catalog,inventory,inventoryReservations,retail,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!catalog||!inventory||!inventoryReservations||!retail)throw new TypeError('manufacturing dependencies are required.');
 const cid=a=>String(a?.companyId||'default');
 const manage=a=>assertRole(a,['admin','manager']);
 const operate=a=>assertRole(a,['admin','manager','operator']);
 const systemActor=a=>({userId:a?.userId||'system',role:'system',companyId:cid(a)});
 const mapComponent=r=>r&&({id:r.id,manufacturingOrderId:r.manufacturing_order_id,productId:r.product_id,quantityPerUnit:Number(r.quantity_per_unit),requiredQuantity:Number(r.required_quantity),consumedQuantity:Number(r.consumed_quantity),plannedUnitCostCents:Number(r.planned_unit_cost_cents),actualCostCents:Number(r.actual_cost_cents),reservationId:r.reservation_id||null,createdAt:r.created_at,updatedAt:r.updated_at});
 const components=id=>db.prepare('SELECT * FROM manufacturing_order_components WHERE manufacturing_order_id=? ORDER BY created_at,id').all(String(id)).map(mapComponent);
 const outputs=id=>db.prepare('SELECT * FROM manufacturing_outputs WHERE manufacturing_order_id=? ORDER BY created_at,id').all(String(id)).map(r=>({id:r.id,quantity:Number(r.quantity),unitCostCents:Number(r.unit_cost_cents),inventoryMovementId:r.inventory_movement_id||null,createdAt:r.created_at}));
 const losses=id=>db.prepare('SELECT * FROM manufacturing_losses WHERE manufacturing_order_id=? ORDER BY created_at,id').all(String(id)).map(r=>({id:r.id,lossType:r.loss_type,productId:r.product_id,quantity:Number(r.quantity),reason:r.reason,inventoryMovementId:r.inventory_movement_id||null,createdAt:r.created_at}));
 const costs=id=>db.prepare('SELECT * FROM manufacturing_cost_entries WHERE manufacturing_order_id=? ORDER BY created_at,id').all(String(id)).map(r=>({id:r.id,costType:r.cost_type,description:r.description,amountCents:Number(r.amount_cents),createdAt:r.created_at}));
 const mapOrder=r=>r&&({id:r.id,companyId:r.company_id,branchId:r.branch_id||null,productId:r.product_id,bomId:r.bom_id,bomVersion:Number(r.bom_version),locationId:r.location_id,outputLocationId:r.output_location_id,status:r.status,plannedQuantity:Number(r.planned_quantity),completedQuantity:Number(r.completed_quantity),scrapQuantity:Number(r.scrap_quantity),plannedStartAt:r.planned_start_at||null,dueAt:r.due_at||null,releasedAt:r.released_at||null,startedAt:r.started_at||null,completedAt:r.completed_at||null,cancelledAt:r.cancelled_at||null,cancellationReason:r.cancellation_reason||null,plannedMaterialCostCents:Number(r.planned_material_cost_cents),actualMaterialCostCents:Number(r.actual_material_cost_cents),additionalCostCents:Number(r.additional_cost_cents),actualTotalCostCents:Number(r.actual_total_cost_cents),createdBy:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at,components:components(r.id),outputs:outputs(r.id),losses:losses(r.id),costs:costs(r.id)});
 function getOrder(id,actor=null){return mapOrder(db.prepare('SELECT * FROM manufacturing_orders WHERE id=? AND company_id=?').get(String(id),cid(actor)));}
 function requireOrder(id,actor){const o=getOrder(id,actor);if(!o)throw new Error('Ordem de producao nao encontrada.');return o;}
 function activeBom(productId){const bom=retail.activeBom(productId);if(!bom||!bom.items?.length)throw new Error('Produto sem ficha tecnica ativa.');return bom;}
 function snapshotRows(orderId,bom,plannedQuantity,ts){let planned=0;const rows=[];for(const item of bom.items){const product=catalog.requireActiveProduct(item.productId),required=positiveQuantity(Number(item.quantity)*plannedQuantity,'Necessidade'),cost=Number(product.costCents||0);planned+=Math.round(required*cost);rows.push({id:idFactory('mfgc'),orderId,productId:product.id,quantityPerUnit:Number(item.quantity),requiredQuantity:required,plannedUnitCostCents:cost,createdAt:ts});}return{rows,planned};}
 function insertSnapshot(orderId,rows){const ins=db.prepare('INSERT INTO manufacturing_order_components(id,manufacturing_order_id,product_id,quantity_per_unit,required_quantity,consumed_quantity,planned_unit_cost_cents,actual_cost_cents,reservation_id,created_at,updated_at) VALUES(?,?,?,?,?,0,?,0,NULL,?,?)');for(const x of rows)ins.run(x.id,orderId,x.productId,x.quantityPerUnit,x.requiredQuantity,x.plannedUnitCostCents,x.createdAt,x.createdAt);}
 function createOrder(input={},actor=null){manage(actor);const product=catalog.requireActiveProduct(input.productId),bom=activeBom(product.id),planned=positiveQuantity(input.plannedQuantity,'Quantidade planejada'),location=inventory.requireLocation(input.locationId),output=inventory.requireLocation(input.outputLocationId||input.locationId),id=String(input.id||idFactory('mfg')),ts=String(now()),snap=snapshotRows(id,bom,planned,ts);return withTransaction(db,()=>{db.prepare("INSERT INTO manufacturing_orders(id,company_id,branch_id,product_id,bom_id,bom_version,location_id,output_location_id,status,planned_quantity,completed_quantity,scrap_quantity,planned_start_at,due_at,planned_material_cost_cents,actual_material_cost_cents,additional_cost_cents,actual_total_cost_cents,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'PLANNED',?,0,0,?,?,?,0,0,0,?,?,?)").run(id,cid(actor),input.branchId||null,product.id,bom.id,bom.version,location.id,output.id,planned,input.plannedStartAt||null,input.dueAt||null,snap.planned,actor?.userId||null,ts,ts);insertSnapshot(id,snap.rows);writeAudit(db,{action:'manufacturing.order.create',entity:'manufacturing-order',entityId:id,actor,context:{productId:product.id,plannedQuantity:planned,bomId:bom.id,bomVersion:bom.version}},now);return getOrder(id,actor);});}
 function updatePlanned(id,input={},actor=null){manage(actor);const o=requireOrder(id,actor);if(o.status!=='PLANNED')throw new Error('Somente OP planejada pode ser alterada.');const planned=input.plannedQuantity===undefined?o.plannedQuantity:positiveQuantity(input.plannedQuantity,'Quantidade planejada'),location=input.locationId?inventory.requireLocation(input.locationId).id:o.locationId,output=input.outputLocationId?inventory.requireLocation(input.outputLocationId).id:o.outputLocationId,ts=String(now());return withTransaction(db,()=>{let plannedCost=0;for(const c of o.components){const required=c.quantityPerUnit*planned;plannedCost+=Math.round(required*c.plannedUnitCostCents);db.prepare('UPDATE manufacturing_order_components SET required_quantity=?,updated_at=? WHERE id=?').run(required,ts,c.id);}db.prepare('UPDATE manufacturing_orders SET planned_quantity=?,location_id=?,output_location_id=?,planned_start_at=?,due_at=?,planned_material_cost_cents=?,updated_at=? WHERE id=? AND company_id=?').run(planned,location,output,input.plannedStartAt===undefined?o.plannedStartAt:input.plannedStartAt,input.dueAt===undefined?o.dueAt:input.dueAt,plannedCost,ts,o.id,cid(actor));return getOrder(o.id,actor);});}
 function refreshBom(id,actor=null){manage(actor);const o=requireOrder(id,actor);if(o.status!=='PLANNED')throw new Error('Ficha tecnica so pode ser atualizada em OP planejada.');const bom=activeBom(o.productId),ts=String(now()),snap=snapshotRows(o.id,bom,o.plannedQuantity,ts);return withTransaction(db,()=>{db.prepare('DELETE FROM manufacturing_order_components WHERE manufacturing_order_id=?').run(o.id);insertSnapshot(o.id,snap.rows);db.prepare('UPDATE manufacturing_orders SET bom_id=?,bom_version=?,planned_material_cost_cents=?,updated_at=? WHERE id=? AND company_id=?').run(bom.id,bom.version,snap.planned,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.order.refresh-bom',entity:'manufacturing-order',entityId:o.id,actor,context:{bomId:bom.id,bomVersion:bom.version}},now);return getOrder(o.id,actor);});}
 function shortages(id,actor=null){const o=requireOrder(id,actor),items=[];for(const c of o.components){const reservation=c.reservationId?inventoryReservations.getReservation(c.reservationId):null,covered=reservation?.status==='ACTIVE'?reservation.remainingQuantity:0,remaining=Math.max(c.requiredQuantity-c.consumedQuantity-covered,0);if(remaining<=0)continue;const available=Math.max(inventoryReservations.getAvailable(c.productId,o.locationId),0);if(available<remaining)items.push({componentId:c.id,productId:c.productId,requiredQuantity:remaining,availableQuantity:available,missingQuantity:remaining-available});}return items;}
 function release(id,actor=null){manage(actor);let o=requireOrder(id,actor);if(o.status==='RELEASED')return{...o,shortages:[]};if(o.status!=='PLANNED')throw new Error('OP nao pode ser liberada neste status.');const missing=shortages(o.id,actor);if(missing.length)return{...o,shortages:missing};const ts=String(now());return withTransaction(db,()=>{for(const c of o.components){const remaining=c.requiredQuantity-c.consumedQuantity;if(remaining<=0)continue;const reservation=inventoryReservations.reserve({productId:c.productId,locationId:o.locationId,quantity:remaining,sourceType:'manufacturing-order',sourceId:c.id},actor);db.prepare('UPDATE manufacturing_order_components SET reservation_id=?,updated_at=? WHERE id=?').run(reservation.id,ts,c.id);}db.prepare("UPDATE manufacturing_orders SET status='RELEASED',released_at=?,updated_at=? WHERE id=? AND company_id=?").run(ts,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.order.release',entity:'manufacturing-order',entityId:o.id,actor,context:{}},now);return{...getOrder(o.id,actor),shortages:[]};});}
 function start(id,actor=null){operate(actor);const o=requireOrder(id,actor);if(o.status!=='RELEASED')throw new Error('OP nao pode ser iniciada neste status.');const ts=String(now());db.prepare("UPDATE manufacturing_orders SET status='IN_PROGRESS',started_at=?,updated_at=? WHERE id=? AND company_id=?").run(ts,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.order.start',entity:'manufacturing-order',entityId:o.id,actor,context:{}},now);return getOrder(o.id,actor);}
 function consumeComponent(id,componentId,input={},actor=null){operate(actor);const o=requireOrder(id,actor);if(o.status!=='IN_PROGRESS')throw new Error('OP nao esta em producao.');const c=o.components.find(x=>x.id===String(componentId));if(!c)throw new Error('Componente da OP nao encontrado.');const q=positiveQuantity(input.quantity,'Quantidade'),remaining=c.requiredQuantity-c.consumedQuantity;if(q>remaining)throw new Error('Consumo excede necessidade do componente.');if(!c.reservationId)throw new Error('Componente sem reserva.');const product=catalog.requireActiveProduct(c.productId),unitCost=Number(product.costCents||c.plannedUnitCostCents||0),cost=Math.round(q*unitCost),ts=String(now());return withTransaction(db,()=>{inventoryReservations.consume(c.reservationId,q,{sourceType:'manufacturing-consumption',sourceId:o.id,unitCostCents:unitCost},actor);db.prepare('UPDATE manufacturing_order_components SET consumed_quantity=consumed_quantity+?,actual_cost_cents=actual_cost_cents+?,updated_at=? WHERE id=?').run(q,cost,ts,c.id);db.prepare('UPDATE manufacturing_orders SET actual_material_cost_cents=actual_material_cost_cents+?,updated_at=? WHERE id=? AND company_id=?').run(cost,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.component.consume',entity:'manufacturing-order',entityId:o.id,actor,context:{componentId:c.id,productId:c.productId,quantity:q,costCents:cost}},now);return getOrder(o.id,actor);});}
 function addCost(id,input={},actor=null){manage(actor);const o=requireOrder(id,actor);if(!['RELEASED','IN_PROGRESS'].includes(o.status))throw new Error('Custo nao pode ser registrado neste status.');const type=String(input.costType||'').toUpperCase();if(!['LABOR','OVERHEAD','OTHER'].includes(type))throw new Error('Tipo de custo invalido.');const description=String(input.description||'').trim();if(!description)throw new Error('Descricao do custo obrigatoria.');const amount=assertCents(input.amountCents,'amountCents');if(amount<=0)throw new Error('Valor do custo deve ser positivo.');const entryId=idFactory('mfgcost'),ts=String(now());db.prepare('INSERT INTO manufacturing_cost_entries(id,manufacturing_order_id,cost_type,description,amount_cents,created_by,created_at) VALUES(?,?,?,?,?,?,?)').run(entryId,o.id,type,description,amount,actor?.userId||null,ts);db.prepare('UPDATE manufacturing_orders SET additional_cost_cents=additional_cost_cents+?,updated_at=? WHERE id=? AND company_id=?').run(amount,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.cost.add',entity:'manufacturing-order',entityId:o.id,actor,context:{costType:type,amountCents:amount}},now);return getOrder(o.id,actor);}
 function reportLoss(id,input={},actor=null){operate(actor);const o=requireOrder(id,actor);if(o.status!=='IN_PROGRESS')throw new Error('OP nao esta em producao.');const type=String(input.lossType||'').toUpperCase();if(!['COMPONENT','OUTPUT'].includes(type))throw new Error('Tipo de perda invalido.');const q=positiveQuantity(input.quantity,'Quantidade'),reason=String(input.reason||'').trim();if(!reason)throw new Error('Motivo da perda obrigatorio.');const productId=String(input.productId||'');const product=catalog.requireActiveProduct(productId);if(type==='COMPONENT'&&!o.components.some(c=>c.productId===product.id))throw new Error('Produto nao e componente da OP.');if(type==='OUTPUT'&&product.id!==o.productId)throw new Error('Refugo deve usar produto acabado da OP.');if(type==='OUTPUT'&&o.completedQuantity+o.scrapQuantity+q>o.plannedQuantity)throw new Error('Refugo excede quantidade planejada.');const lossId=idFactory('mfgloss'),ts=String(now());return withTransaction(db,()=>{let movement=null,cost=0;if(type==='COMPONENT'){const unit=Number(product.costCents||0);cost=Math.round(q*unit);movement=inventory.move({productId:product.id,locationId:o.locationId,delta:-q,unitCostCents:unit,sourceType:'manufacturing-loss',sourceId:o.id},systemActor(actor));db.prepare('UPDATE manufacturing_orders SET actual_material_cost_cents=actual_material_cost_cents+?,updated_at=? WHERE id=? AND company_id=?').run(cost,ts,o.id,cid(actor));}else db.prepare('UPDATE manufacturing_orders SET scrap_quantity=scrap_quantity+?,updated_at=? WHERE id=? AND company_id=?').run(q,ts,o.id,cid(actor));db.prepare('INSERT INTO manufacturing_losses(id,manufacturing_order_id,loss_type,product_id,quantity,reason,inventory_movement_id,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(lossId,o.id,type,product.id,q,reason,movement?.id||null,actor?.userId||null,ts);writeAudit(db,{action:'manufacturing.loss.report',entity:'manufacturing-order',entityId:o.id,actor,context:{lossType:type,productId:product.id,quantity:q,reason,costCents:cost}},now);return getOrder(o.id,actor);});}
 function reportOutput(id,input={},actor=null){operate(actor);const o=requireOrder(id,actor);if(o.status!=='IN_PROGRESS')throw new Error('OP nao esta em producao.');const q=positiveQuantity(input.quantity,'Quantidade'),allow=Boolean(input.allowOverproduction);if(o.completedQuantity+o.scrapQuantity+q>o.plannedQuantity){if(!allow)throw new Error('Apontamento excede quantidade planejada.');manage(actor);}const ts=String(now()),totalNow=o.actualMaterialCostCents+o.additionalCostCents,unitCost=Math.round(totalNow/Math.max(o.completedQuantity+q,1));return withTransaction(db,()=>{const movement=inventory.move({productId:o.productId,locationId:o.outputLocationId,delta:q,unitCostCents:unitCost,sourceType:'manufacturing-output',sourceId:o.id},systemActor(actor)),outputId=idFactory('mfgout');db.prepare('INSERT INTO manufacturing_outputs(id,manufacturing_order_id,quantity,unit_cost_cents,inventory_movement_id,created_by,created_at) VALUES(?,?,?,?,?,?,?)').run(outputId,o.id,q,unitCost,movement.id,actor?.userId||null,ts);db.prepare('UPDATE manufacturing_orders SET completed_quantity=completed_quantity+?,updated_at=? WHERE id=? AND company_id=?').run(q,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.output.report',entity:'manufacturing-order',entityId:o.id,actor,context:{quantity:q,unitCostCents:unitCost}},now);return getOrder(o.id,actor);});}
 function complete(id,actor=null){manage(actor);const o=requireOrder(id,actor);if(o.status==='COMPLETED')return o;if(o.status!=='IN_PROGRESS')throw new Error('OP nao pode ser concluida neste status.');if(o.completedQuantity+o.scrapQuantity<o.plannedQuantity)throw new Error('Quantidade produzida/refugada ainda nao fecha o planejado.');const ts=String(now()),actualTotal=o.actualMaterialCostCents+o.additionalCostCents;return withTransaction(db,()=>{for(const c of o.components){if(!c.reservationId)continue;const r=inventoryReservations.getReservation(c.reservationId);if(r?.status==='ACTIVE')inventoryReservations.release(r.id,actor);}db.prepare("UPDATE manufacturing_orders SET status='COMPLETED',actual_total_cost_cents=?,completed_at=?,updated_at=? WHERE id=? AND company_id=?").run(actualTotal,ts,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.order.complete',entity:'manufacturing-order',entityId:o.id,actor,context:{actualTotalCostCents:actualTotal}},now);return getOrder(o.id,actor);});}
 function cancel(id,input={},actor=null){manage(actor);const o=requireOrder(id,actor);if(o.status==='COMPLETED')throw new Error('OP concluida nao pode ser cancelada diretamente.');if(o.status==='CANCELLED')return o;const reason=String(input.reason||'').trim();if(!reason)throw new Error('Motivo do cancelamento obrigatorio.');const ts=String(now());return withTransaction(db,()=>{for(const c of o.components){if(!c.reservationId)continue;const r=inventoryReservations.getReservation(c.reservationId);if(r?.status==='ACTIVE')inventoryReservations.release(r.id,actor);}db.prepare("UPDATE manufacturing_orders SET status='CANCELLED',cancelled_at=?,cancellation_reason=?,updated_at=? WHERE id=? AND company_id=?").run(ts,reason,ts,o.id,cid(actor));writeAudit(db,{action:'manufacturing.order.cancel',entity:'manufacturing-order',entityId:o.id,actor,context:{reason}},now);return getOrder(o.id,actor);});}
 function listOrders({status=null,productId=null,locationId=null,limit=100,offset=0}={},actor=null){const clauses=['company_id=?'],params=[cid(actor)];if(status){clauses.push('status=?');params.push(String(status).toUpperCase());}if(productId){clauses.push('product_id=?');params.push(String(productId));}if(locationId){clauses.push('location_id=?');params.push(String(locationId));}params.push(Math.min(200,Math.max(1,Number(limit)||100)),Math.max(0,Number(offset)||0));return db.prepare(`SELECT * FROM manufacturing_orders WHERE ${clauses.join(' AND ')} ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?`).all(...params).map(mapOrder);}
 return{createOrder,getOrder,listOrders,updatePlanned,refreshBom,shortages,release,start,consumeComponent,addCost,reportLoss,reportOutput,complete,cancel};
}
module.exports={createManufacturingService};
