'use strict';
const {randomUUID}=require('node:crypto');
const {assertRole}=require('../../core/auth/rbac');

function createMrpService({db,inventory,inventoryReservations,procurementRequisitions,manufacturing,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!inventory||!inventoryReservations||!procurementRequisitions||!manufacturing)throw new TypeError('MRP dependencies are required.');
 const cid=a=>String(a?.companyId||'default');
 const manage=a=>assertRole(a,['admin','manager']);
 function openDemand(companyId,locationId){return db.prepare(`SELECT c.id component_id,c.product_id,c.required_quantity,c.consumed_quantity,c.reservation_id,o.id order_id,o.status,o.location_id FROM manufacturing_order_components c JOIN manufacturing_orders o ON o.id=c.manufacturing_order_id WHERE o.company_id=? AND o.location_id=? AND o.status IN ('PLANNED','RELEASED','IN_PROGRESS')`).all(String(companyId),String(locationId));}
 function linked(companyId,productId,locationId){
  const links=db.prepare(`SELECT l.requisition_id,l.quantity FROM manufacturing_procurement_links l JOIN purchase_requisitions r ON r.id=l.requisition_id WHERE l.company_id=? AND l.product_id=? AND l.location_id=? AND r.status!='CANCELLED'`).all(String(companyId),String(productId),String(locationId));
  let total=0;
  for(const link of links){
   const supply=db.prepare(`SELECT COUNT(DISTINCT po.id) order_count,COALESCE(SUM(CASE WHEN po.status IN ('DRAFT','ORDERED','PARTIALLY_RECEIVED') THEN MAX(poi.quantity-poi.received_quantity,0) ELSE 0 END),0) outstanding FROM procurement_awards a JOIN purchase_order_sources s ON s.award_id=a.id JOIN purchase_orders po ON po.id=s.order_id JOIN purchase_order_items poi ON poi.order_id=po.id AND poi.product_id=? WHERE a.requisition_id=?`).get(String(productId),String(link.requisition_id));
   total+=Number(supply?.order_count||0)>0?Math.min(Number(link.quantity),Number(supply?.outstanding||0)):Number(link.quantity);
  }
  return total;
 }
 function calculate({locationId=null}={},actor=null){const companyId=cid(actor),locations=locationId?[inventory.requireLocation(locationId)]:inventory.listLocations();const items=[];for(const location of locations){const demandRows=openDemand(companyId,location.id),productIds=new Set(demandRows.map(x=>x.product_id));for(const row of db.prepare('SELECT id FROM products WHERE active=1 AND track_stock=1 AND min_stock>0').all())productIds.add(row.id);for(const productId of productIds){const product=db.prepare('SELECT id,name,min_stock,target_stock FROM products WHERE id=? AND active=1').get(String(productId));if(!product)continue;const physical=inventory.getBalance(product.id,location.id),reserved=Math.max(physical-inventoryReservations.getAvailable(product.id,location.id),0),rows=demandRows.filter(x=>x.product_id===product.id),causingOrders=[];let productionDemand=0;for(const r of rows){let remaining=Math.max(Number(r.required_quantity)-Number(r.consumed_quantity),0);if(r.reservation_id){const own=inventoryReservations.getReservation(r.reservation_id);if(own?.status==='ACTIVE')remaining=Math.max(remaining-own.remainingQuantity,0);}productionDemand+=remaining;if(remaining>0)causingOrders.push({orderId:r.order_id,componentId:r.component_id,quantity:remaining,status:r.status});}const availableUnreserved=physical-reserved,minStock=Number(product.min_stock||0),targetStock=Math.max(Number(product.target_stock==null?minStock:product.target_stock),minStock),projected=availableUnreserved-productionDemand,grossNeed=Math.max(targetStock-projected,0),linkedRequisitionQuantity=linked(companyId,product.id,location.id),netRequirement=Math.max(grossNeed-linkedRequisitionQuantity,0);if(productionDemand>0||minStock>0||netRequirement>0||linkedRequisitionQuantity>0)items.push({productId:product.id,productName:product.name,locationId:location.id,physical,reserved,availableUnreserved,productionDemand,minStock,targetStock,linkedRequisitionQuantity,netRequirement,causingOrders});}}return{companyId,locationId:locationId||null,items};}
 function existingRequisitions(companyId,locationId){const ids=db.prepare('SELECT DISTINCT requisition_id FROM manufacturing_procurement_links WHERE company_id=? AND location_id=? ORDER BY created_at DESC').all(String(companyId),String(locationId)).map(x=>x.requisition_id),out=[];for(const id of ids){const r=procurementRequisitions.getRequisition(id);if(r&&r.status!=='CANCELLED')out.push(r);}return out;}
 function createForItems(items,locationId,justification,sourcePrefix,actor,orderId=null){if(!items.length)return existingRequisitions(cid(actor),locationId);const requisition=procurementRequisitions.createRequisition({locationId,justification,items:items.map(x=>({productId:x.productId,quantity:x.netRequirement??x.missingQuantity}))},actor),ts=String(now());for(const x of items){const quantity=Number(x.netRequirement??x.missingQuantity),sourceKey=`${sourcePrefix}:${cid(actor)}:${locationId}:${x.productId}:${requisition.id}`;db.prepare('INSERT OR IGNORE INTO manufacturing_procurement_links(id,company_id,manufacturing_order_id,product_id,location_id,requisition_id,quantity,source_key,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(idFactory('mfgreq'),cid(actor),orderId,x.productId,locationId,requisition.id,quantity,sourceKey,ts);}return[requisition];}
 function generateMrpRequisition({locationId}={},actor=null){manage(actor);const location=inventory.requireLocation(locationId),result=calculate({locationId:location.id},actor),need=result.items.filter(x=>x.netRequirement>0),requisitions=createForItems(need,location.id,'Necessidade de materiais gerada pelo MRP','MRP',actor);return{...result,requisitions};}
 function generateShortageRequisition(orderId,actor=null){manage(actor);const order=manufacturing.getOrder(orderId,actor);if(!order)throw new Error('Ordem de producao nao encontrada.');const shortages=manufacturing.shortages(order.id,actor);if(!shortages.length)return{orderId:order.id,shortages:[],requisitions:existingRequisitions(cid(actor),order.locationId)};const already=new Map(db.prepare(`SELECT product_id,COALESCE(SUM(quantity),0) q FROM manufacturing_procurement_links l JOIN purchase_requisitions r ON r.id=l.requisition_id WHERE l.company_id=? AND l.manufacturing_order_id=? AND r.status!='CANCELLED' GROUP BY product_id`).all(cid(actor),order.id).map(x=>[x.product_id,Number(x.q)])),need=shortages.map(x=>({...x,missingQuantity:Math.max(x.missingQuantity-(already.get(x.productId)||0),0)})).filter(x=>x.missingQuantity>0),requisitions=createForItems(need,order.locationId,`Falta de material da OP ${order.id}`,'OP',actor,order.id);return{orderId:order.id,shortages,requisitions};}
 return{calculate,generateMrpRequisition,generateShortageRequisition};
}
module.exports={createMrpService};
