'use strict';
const {randomUUID}=require('node:crypto');
const {assertRole}=require('../../core/auth/rbac');
const {writeAudit}=require('../../core/audit/audit-log');
function createCrmService({db,contacts,salesAdmin,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!contacts||!salesAdmin)throw new TypeError('crm dependencies are required.');const cid=a=>String(a?.companyId||'default'),manage=a=>assertRole(a,['admin','manager','director']);
 function ensureStages(a){const companyId=cid(a),count=Number(db.prepare('SELECT COUNT(*) n FROM crm_stages WHERE company_id=?').get(companyId)?.n||0);if(count)return;const ins=db.prepare('INSERT INTO crm_stages(company_id,id,name,sort_order,status_kind,active) VALUES(?,?,?,?,?,1)');for(const s of [['new','Novo',10,'OPEN'],['qualified','Qualificado',20,'OPEN'],['proposal','Proposta',30,'OPEN'],['won','Ganho',40,'WON'],['lost','Perdido',50,'LOST']])ins.run(companyId,...s);}
 const leadMap=r=>r&&({id:r.id,companyId:r.company_id,name:r.name,email:r.email||null,phone:r.phone||null,source:r.source||null,status:r.status,ownerId:r.owner_id||null,convertedCustomerId:r.converted_customer_id||null,lossReason:r.loss_reason||null,createdAt:r.created_at,updatedAt:r.updated_at});
 function getLead(id,a){return leadMap(db.prepare('SELECT * FROM crm_leads WHERE company_id=? AND id=?').get(cid(a),String(id)));}
 function createLead(i={},a=null){manage(a);const id=String(i.id||idFactory('lead')),name=String(i.name||'').trim();if(!name)throw new Error('Nome do lead obrigatorio.');const ts=String(now());db.prepare("INSERT INTO crm_leads(id,company_id,name,email,phone,source,status,owner_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'OPEN',?,?,?)").run(id,cid(a),name,i.email||null,i.phone||null,i.source||null,i.ownerId||a?.userId||null,ts,ts);writeAudit(db,{action:'crm.lead.create',entity:'crm-lead',entityId:id,actor:a,context:{source:i.source||null}},now);return getLead(id,a);}
 function convertLeadToCustomer(id,i={},a=null){manage(a);const lead=getLead(id,a);if(!lead)throw new Error('Lead nao encontrado.');if(lead.convertedCustomerId)return contacts.getContact(lead.convertedCustomerId);if(lead.status==='LOST')throw new Error('Lead perdido nao pode ser convertido.');const customer=contacts.createCustomer({name:i.name||lead.name,email:i.email||lead.email,phone:i.phone||lead.phone,taxId:i.taxId||null,address:i.address||{}},a);db.prepare("UPDATE crm_leads SET status='CONVERTED',converted_customer_id=?,updated_at=? WHERE company_id=? AND id=?").run(customer.id,String(now()),cid(a),lead.id);writeAudit(db,{action:'crm.lead.convert',entity:'crm-lead',entityId:lead.id,actor:a,context:{customerId:customer.id}},now);return customer;}
 const oppMap=r=>r&&({id:r.id,companyId:r.company_id,leadId:r.lead_id||null,customerId:r.customer_id||null,name:r.name,stageId:r.stage_id,expectedRevenueCents:Number(r.expected_revenue_cents),probabilityPercent:Number(r.probability_percent),ownerId:r.owner_id||null,lossReason:r.loss_reason||null,quoteOrderId:r.quote_order_id||null,createdAt:r.created_at,updatedAt:r.updated_at});
 function getOpportunity(id,a){return oppMap(db.prepare('SELECT * FROM crm_opportunities WHERE company_id=? AND id=?').get(cid(a),String(id)));}
 function createOpportunity(i={},a=null){manage(a);ensureStages(a);const id=String(i.id||idFactory('opp')),name=String(i.name||'').trim();if(!name)throw new Error('Nome da oportunidade obrigatorio.');if(i.leadId&&!getLead(i.leadId,a))throw new Error('Lead nao encontrado.');if(i.customerId)contacts.requireCustomer(i.customerId);const amount=Number(i.expectedRevenueCents||0);if(!Number.isSafeInteger(amount)||amount<0)throw new Error('Receita esperada invalida.');const ts=String(now());db.prepare("INSERT INTO crm_opportunities(id,company_id,lead_id,customer_id,name,stage_id,expected_revenue_cents,probability_percent,owner_id,created_at,updated_at) VALUES(?,?,?,?,?,'new',?,?,?, ?,?)").run(id,cid(a),i.leadId||null,i.customerId||null,name,amount,Number(i.probabilityPercent||0),i.ownerId||a?.userId||null,ts,ts);return getOpportunity(id,a);}
 function moveOpportunity(id,stageId,a=null,{lossReason=null}={}){manage(a);ensureStages(a);const o=getOpportunity(id,a);if(!o)throw new Error('Oportunidade nao encontrada.');const stage=db.prepare('SELECT * FROM crm_stages WHERE company_id=? AND id=? AND active=1').get(cid(a),String(stageId));if(!stage)throw new Error('Etapa de CRM invalida.');if(stage.status_kind==='LOST'&&!String(lossReason||'').trim())throw new Error('Motivo de perda obrigatorio.');db.prepare('UPDATE crm_opportunities SET stage_id=?,loss_reason=?,probability_percent=?,updated_at=? WHERE company_id=? AND id=?').run(stage.id,stage.status_kind==='LOST'?String(lossReason):null,stage.status_kind==='WON'?100:o.probabilityPercent,String(now()),cid(a),o.id);return getOpportunity(o.id,a);}
 function addActivity(i={},a=null){manage(a);if(i.leadId&&!getLead(i.leadId,a))throw new Error('Lead nao encontrado.');if(i.opportunityId&&!getOpportunity(i.opportunityId,a))throw new Error('Oportunidade nao encontrada.');if(!i.leadId&&!i.opportunityId)throw new Error('Atividade precisa de lead ou oportunidade.');const id=String(i.id||idFactory('crm-activity')),subject=String(i.subject||'').trim();if(!subject)throw new Error('Assunto obrigatorio.');const ts=String(now());db.prepare("INSERT INTO crm_activities(id,company_id,lead_id,opportunity_id,kind,subject,due_at,status,owner_id,notes,created_at) VALUES(?,?,?,?,?,?,?,'OPEN',?,?,?)").run(id,cid(a),i.leadId||null,i.opportunityId||null,String(i.kind||'TASK').toUpperCase(),subject,i.dueAt||null,i.ownerId||a?.userId||null,i.notes||null,ts);return db.prepare('SELECT * FROM crm_activities WHERE company_id=? AND id=?').get(cid(a),id);}
 function listActivities({leadId=null,opportunityId=null,status=null}={},a=null){const c=['company_id=?'],p=[cid(a)];for(const [col,val] of [['lead_id',leadId],['opportunity_id',opportunityId],['status',status]])if(val){c.push(`${col}=?`);p.push(String(val));}return db.prepare(`SELECT * FROM crm_activities WHERE ${c.join(' AND ')} ORDER BY COALESCE(due_at,created_at),created_at`).all(...p).map(r=>({id:r.id,leadId:r.lead_id||null,opportunityId:r.opportunity_id||null,kind:r.kind,subject:r.subject,dueAt:r.due_at||null,status:r.status,ownerId:r.owner_id||null,notes:r.notes||null,createdAt:r.created_at}));}
 function completeActivity(id,a=null){manage(a);const ts=String(now()),result=db.prepare("UPDATE crm_activities SET status='DONE',completed_at=? WHERE company_id=? AND id=? AND status='OPEN'").run(ts,cid(a),String(id));if(!result.changes)throw new Error('Atividade indisponivel.');return db.prepare('SELECT * FROM crm_activities WHERE company_id=? AND id=?').get(cid(a),String(id));}
 function convertOpportunityToQuote(id,i={},a=null){manage(a);const o=getOpportunity(id,a);if(!o)throw new Error('Oportunidade nao encontrada.');if(o.quoteOrderId)return salesAdmin.getOrder(o.quoteOrderId);let customerId=o.customerId;if(!customerId&&o.leadId){const lead=getLead(o.leadId,a);customerId=lead?.convertedCustomerId||convertLeadToCustomer(o.leadId,{},a).id;}if(!customerId)throw new Error('Oportunidade sem cliente.');const quote=salesAdmin.createQuote({customerId,locationId:i.locationId||'MAIN',items:i.items,notes:i.notes||`CRM ${o.name}`},a);db.prepare('UPDATE crm_opportunities SET customer_id=?,quote_order_id=?,stage_id=?,updated_at=? WHERE company_id=? AND id=?').run(customerId,quote.id,'proposal',String(now()),cid(a),o.id);return quote;}
 function pipelineSummary(a=null){ensureStages(a);const stages=db.prepare('SELECT * FROM crm_stages WHERE company_id=? AND active=1 ORDER BY sort_order,id').all(cid(a)),rows=db.prepare('SELECT * FROM crm_opportunities WHERE company_id=?').all(cid(a));const byStage={};for(const s of stages)byStage[s.id]={name:s.name,count:0,expectedRevenueCents:0,statusKind:s.status_kind};for(const o of rows){if(!byStage[o.stage_id])continue;byStage[o.stage_id].count++;byStage[o.stage_id].expectedRevenueCents+=Number(o.expected_revenue_cents||0);}return{totalOpportunities:rows.length,expectedRevenueCents:rows.reduce((s,x)=>s+Number(x.expected_revenue_cents||0),0),byStage};}
 return{createLead,getLead,convertLeadToCustomer,createOpportunity,getOpportunity,moveOpportunity,addActivity,listActivities,completeActivity,convertOpportunityToQuote,pipelineSummary};
}
module.exports={createCrmService};
