'use strict';const test=require('node:test');const assert=require('node:assert/strict');const {createErpRuntime}=require('../js/core/erp-runtime');const a={userId:'admin',role:'admin',companyId:'default'};
test('P0-P2 utilities cover BI, branch, alerts, pricing, workflows, assets, OS, maintenance and projects',()=>{let n=0;const r=createErpRuntime({idFactory:p=>p+'-'+(++n)});try{
const br=r.operations.createBranch({code:'F1',name:'Filial 1'},a);assert.equal(br.company_id,'default');const dash=r.operations.saveDashboard({name:'Executivo',layout:[{id:'sales',x:0,y:0,w:2,h:1}]},a);assert.equal(r.operations.listDashboards(a)[0].id,dash.id);
const al=r.operations.createAlert({entityKind:'stock',entityId:'P1',title:'Repor',dueAt:'2026-09-26T00:00:00.000Z',severity:'warning'},a);assert.equal(r.operations.alertAction(al.id,'ack',{},a).status,'acknowledged');const no=r.operations.notify({title:'Teste',priority:'high'},a);assert.equal(r.operations.markRead(no.id,a).status,'read');
const p=r.catalog.createProduct({id:'P1',name:'Produto',sku:'SKU',salePriceCents:1000,trackStock:false},a);const pt=r.operations.createPriceTable({name:'Atacado',items:[{productId:p.id,minQuantity:10,unitPriceCents:900,discountPercent:10}]},a);assert.equal(r.operations.quotePrice(pt.id,p.id,10,a).unitPriceCents,810);
const w=r.operations.createWorkflow({name:'Generico',states:['OPEN','DONE'],initialState:'OPEN',transitions:[{from:'OPEN',to:'DONE'}]},a);const wi=r.operations.startWorkflow({workflowId:w.id,subjectKind:'order',subjectId:'1'},a);assert.equal(r.operations.transition(wi.id,'DONE',a).state,'DONE');
const ap=r.operations.requestApproval({subjectKind:'discount',subjectId:'1',steps:[{approverIds:['admin']}]},a);assert.equal(r.operations.decideApproval(ap.id,'approved',a).status,'approved');
const asset=r.operations.createAsset({code:'EQ1',name:'Escavadeira',type:'EQUIPMENT',meterValue:100},a);const os=r.operations.createServiceOrder({assetId:asset.id,number:'OS1',title:'Revisao'},a);assert.equal(r.operations.setServiceOrderStatus(os.id,'CLOSED',a).status,'CLOSED');const mp=r.operations.createMaintenancePlan({assetId:asset.id,name:'250h',intervalMeter:250},a);assert.ok(mp.id);
const pr=r.operations.createProject({code:'OB1',name:'Obra 1',startDate:'2026-09-01',endDate:'2026-12-01'},a);r.operations.addTask(pr.id,{name:'Fundacao',startDate:'2026-09-01',endDate:'2026-09-20',progress:50},a);assert.equal(r.operations.project(pr.id,a).tasks.length,1);
const bi=r.businessIntelligence.overview();assert.ok(bi.sales&&bi.inventory);
}finally{r.close()}});