'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {createErpRuntime}=require('../js/core/erp-runtime');
const admin={userId:'admin',role:'admin'};
function ofx({amount='-100.00',fitid='TX-1',name='FORNECEDOR TESTE',date='20260925',type='DEBIT'}={}){return `<OFX><BANKMSGSRSV1><STMTTRNRS><STMTRS><BANKTRANLIST><STMTTRN><TRNTYPE>${type}<DTPOSTED>${date}120000[-3:BRT]<TRNAMT>${amount}<FITID>${fitid}<NAME>${name}</STMTTRN></BANKTRANLIST></STMTRS></STMTTRNRS></BANKMSGSRSV1></OFX>`;}
function fixture(){let n=0;const rt=createErpRuntime({dbPath:':memory:',now:()=> '2026-09-25T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});rt.finance.createAccount({id:'B1',name:'Banco 1',type:'BANK'},admin);rt.finance.createAccount({id:'B2',name:'Banco 2',type:'BANK'},admin);return rt;}

test('OFX preview is read-only and commits are source-idempotent while distinct FITIDs coexist',async()=>{const rt=fixture();const content=`<OFX><BANKMSGSRSV1><STMTTRNRS><STMTRS><BANKTRANLIST><STMTTRN><TRNTYPE>CREDIT<DTPOSTED>20260925120000[-3:BRT]<TRNAMT>100.00<FITID>PIX-A<NAME>PIX CLIENTE</STMTTRN><STMTTRN><TRNTYPE>CREDIT<DTPOSTED>20260925120000[-3:BRT]<TRNAMT>100.00<FITID>PIX-B<NAME>PIX CLIENTE</STMTTRN></BANKTRANLIST></STMTRS></STMTTRNRS></BANKMSGSRSV1></OFX>`;const preview=await rt.bankStatements.preview({accountId:'B1',sourceName:'x.ofx',content});assert.equal(preview.transactions.length,2);assert.equal(rt.bankStatements.listTransactions().length,0);const first=await rt.bankStatements.commit({accountId:'B1',sourceName:'x.ofx',content},admin);assert.equal(first.inserted,2);const second=await rt.bankStatements.commit({accountId:'B1',sourceName:'x2.ofx',content},admin);assert.equal(second.inserted,0);assert.equal(second.duplicates,2);const rows=rt.bankStatements.listTransactions({accountId:'B1'});assert.equal(rows.length,2);assert.notEqual(rows[0].sourceFingerprint,rows[1].sourceFingerprint);assert.equal(rows[0].businessFingerprint,rows[1].businessFingerprint);rt.close();});

test('reconciliation suggestion never settles before explicit confirmation and confirmation is idempotent',async()=>{const rt=fixture();const entry=rt.finance.createEntry({kind:'PAYABLE',description:'FORNECEDOR TESTE',amountCents:10000,dueAt:'2026-09-25T12:00:00.000Z'},admin);await rt.bankStatements.commit({accountId:'B1',sourceName:'p.ofx',content:ofx()},admin);const suggestions=await rt.financeReconciliation.suggest({accountId:'B1'});const match=suggestions.find(x=>x.entryId===entry.id);assert.ok(match);assert.equal(rt.finance.getEntry(entry.id).openCents,10000);const first=rt.financeReconciliation.confirm({transactionId:match.transactionId,entryId:entry.id,amountCents:10000,idempotencyKey:'accept-1'},admin);const second=rt.financeReconciliation.confirm({transactionId:match.transactionId,entryId:entry.id,amountCents:10000,idempotencyKey:'accept-1'},admin);assert.equal(second.id,first.id);assert.equal(rt.finance.getEntry(entry.id).openCents,0);assert.equal(rt.finance.getEntry(entry.id).settlements.length,1);rt.close();});

test('own-account transfer marks statement transactions without creating income or expense entries',async()=>{const rt=fixture();await rt.bankStatements.commit({accountId:'B1',sourceName:'out.ofx',content:ofx({amount:'-500.00',fitid:'OUT',name:'TRANSFERENCIA PROPRIA'})},admin);await rt.bankStatements.commit({accountId:'B2',sourceName:'in.ofx',content:ofx({amount:'500.00',fitid:'IN',name:'TRANSFERENCIA PROPRIA',type:'CREDIT'})},admin);const before=rt.finance.listEntries().length,pairs=await rt.financeReconciliation.suggestTransfers();assert.equal(pairs.length,1);const transfer=rt.financeReconciliation.confirmTransfer({...pairs[0],idempotencyKey:'transfer-1'},admin);assert.equal(transfer.status,'CONFIRMED');assert.equal(rt.finance.listEntries().length,before);assert.ok(rt.bankStatements.listTransactions().every(x=>x.matchStatus==='TRANSFERRED'));rt.close();});

test('recurrence is restart-idempotent and day 31 clamps to month end',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'erp-rec-'));const dbPath=path.join(dir,'erp.sqlite');try{let n=0;let rt=createErpRuntime({dbPath,now:()=> '2027-02-28T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});rt.financeRecurrences.createRule({id:'R1',kind:'PAYABLE',description:'Aluguel',categoryId:'RENT',amountCents:10000,startDate:'2027-01-31',dueDay:31,maxOccurrences:3},admin);assert.equal(rt.financeRecurrences.generateDue({asOf:'2027-02-28'},admin).length,2);assert.deepEqual(rt.finance.listEntries().map(e=>e.dueAt.slice(0,10)),['2027-01-31','2027-02-28']);rt.close();rt=createErpRuntime({dbPath,now:()=> '2027-02-28T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});assert.equal(rt.financeRecurrences.generateDue({asOf:'2027-02-28'},admin).length,0);assert.equal(rt.finance.listEntries().length,2);rt.close();}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('derived alert presentation state never mutates finance and negative projection is reported',()=>{const rt=fixture();const overdue=rt.finance.createEntry({kind:'PAYABLE',description:'Vencida',amountCents:5000,dueAt:'2026-09-20T12:00:00.000Z'},admin);rt.finance.createEntry({kind:'PAYABLE',description:'Futura',amountCents:90000,dueAt:'2026-09-30T12:00:00.000Z'},admin);const before=rt.finance.getSummary({asOf:'2026-09-25T12:00:00.000Z'});const rows=rt.financeAlerts.list();const alert=rows.find(x=>x.entryId===overdue.id&&x.kind==='OVERDUE_PAYABLE');assert.ok(alert);assert.ok(rows.some(x=>x.kind==='NEGATIVE_CASH_PROJECTION'));rt.financeAlerts.markRead(alert.key);rt.financeAlerts.hide(alert.key);assert.ok(!rt.financeAlerts.list().some(x=>x.key===alert.key));const hidden=rt.financeAlerts.list({includeHidden:true}).find(x=>x.key===alert.key);assert.ok(hidden.readAt&&hidden.hiddenAt);assert.deepEqual(rt.finance.getSummary({asOf:'2026-09-25T12:00:00.000Z'}),before);rt.close();});
