'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{createErpRuntime}=require('../js/core/erp-runtime');
const actor={userId:'admin',role:'admin',companyId:'default'};
function setup(){let n=0;const r=createErpRuntime({idFactory:p=>`${p}-${++n}`});r.inventory.createLocation({id:'MAIN',name:'Principal'},actor);const supplier=r.contacts.createSupplier({id:'SUP1',name:'Fornecedor Fiscal',taxId:'12345678000199'},actor);const p=r.catalog.createProduct({id:'P1',name:'Insumo',sku:'P1',costCents:500,salePriceCents:1000,trackStock:true},actor);r.fiscal.saveSettings({provider:'acbr-local',environment:'homologation',cnpj:'12345678000195',stateRegistration:'123',legalName:'Teste',crt:'1',seriesNfce:'1',seriesNfe:'2',seriesNfse:'3',address:{}},actor);r.fiscal.saveProfile({id:'PF',name:'Perfil',ncm:'61091000',cfop:'5102',origin:'0',csosn:'102',pisCst:'49',cofinsCst:'49',unit:'UN',ibsCbsCst:'000',cClassTrib:'000001'},actor);r.fiscal.assignProduct(p.id,{profileId:'PF'},actor);return{r,supplier,p};}
function receive(r,id,key){const po=r.procurement.createPurchaseOrder({id:`PO-${id}`,supplierId:'SUP1',locationId:'MAIN',items:[{productId:'P1',quantity:2,unitCostCents:500}]},actor);r.procurement.submitPurchaseOrder(po.id,actor);return r.procurement.receivePurchaseOrder(po.id,{id, idempotencyKey:key,items:[{productId:'P1',quantity:2}]},actor);}
const counts=r=>({movements:r.db.prepare('SELECT COUNT(*) c FROM inventory_movements').get().c,finance:r.db.prepare('SELECT COUNT(*) c FROM financial_entries').get().c});

test('incoming NF-e links to purchase receipt as authorized without duplicating receipt effects',()=>{const{r}=setup();try{const receipt=receive(r,'REC1','rec1'),before=counts(r);const doc=r.fiscalInteroperability.linkInboundPurchaseReceipt(receipt.id,{idempotencyKey:'in-1',accessKey:'35123456789012345678901234567890123456789012',series:'1',number:456,xml:'<NFe/>',issuerTaxId:'12345678000199'},actor);assert.equal(doc.sourceType,'PURCHASE_RECEIPT');assert.equal(doc.documentType,'nfe');assert.equal(doc.direction,'INBOUND');assert.equal(doc.operationKind,'INBOUND_LINK');assert.equal(doc.status,'AUTHORIZED');assert.equal(doc.accessKey,'35123456789012345678901234567890123456789012');assert.equal(doc.snapshot.external.issuerTaxId,'12345678000199');assert.deepEqual(counts(r),before);assert.equal(r.fiscalInteroperability.linkInboundPurchaseReceipt(receipt.id,{idempotencyKey:'in-1',accessKey:doc.accessKey,series:'1',number:456,issuerTaxId:'12345678000199'},actor).id,doc.id);}finally{r.close();}});

test('supplier return relates inbound NF-e when available and stays explicit when unavailable',()=>{const{r}=setup();try{const receipt=receive(r,'REC2','rec2');const inbound=r.fiscalInteroperability.linkInboundPurchaseReceipt(receipt.id,{idempotencyKey:'in-2',accessKey:'35111111111111111111111111111111111111111111',series:'1',number:10,issuerTaxId:'12345678000199'},actor);const ret=r.procurementReturns.createReturn(receipt.id,{id:'PRET2',idempotencyKey:'pret2',reason:'Avaria',items:[{productId:'P1',quantity:1}]},actor);const before=counts(r),out=r.fiscalInteroperability.prepareSource({sourceType:'PURCHASE_RETURN',sourceId:ret.id,idempotencyKey:'tax-pret2'},actor).documents[0];assert.equal(out.parentDocumentId,inbound.id);assert.equal(out.operationKind,'RETURN');assert.equal(out.snapshot.originalDocumentStatus,'RELATED');assert.deepEqual(counts(r),before);
 const receipt2=receive(r,'REC3','rec3');const ret2=r.procurementReturns.createReturn(receipt2.id,{id:'PRET3',idempotencyKey:'pret3',reason:'Erro',items:[{productId:'P1',quantity:1}]},actor);const out2=r.fiscalInteroperability.prepareSource({sourceType:'PURCHASE_RETURN',sourceId:ret2.id,idempotencyKey:'tax-pret3'},actor).documents[0];assert.equal(out2.parentDocumentId,null);assert.equal(out2.snapshot.originalDocumentStatus,'NO_INBOUND_DOCUMENT');}finally{r.close();}});
