'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{createErpRuntime}=require('../js/core/erp-runtime');
const actor={userId:'admin',role:'admin',companyId:'default'};
function setup(){let n=0;const r=createErpRuntime({idFactory:p=>`${p}-${++n}`});r.inventory.createLocation({id:'MAIN',name:'Principal'},actor);const customer=r.contacts.createCustomer({id:'C1',name:'Cliente'},actor);const p=r.catalog.createProduct({id:'P1',name:'Produto',sku:'P1',costCents:400,salePriceCents:1000,trackStock:true},actor);r.inventory.move({productId:p.id,locationId:'MAIN',delta:20,sourceType:'seed',sourceId:'ret'},actor);r.fiscal.saveSettings({provider:'acbr-local',environment:'homologation',cnpj:'12345678000195',stateRegistration:'123',legalName:'Teste',crt:'1',seriesNfce:'1',seriesNfe:'2',seriesNfse:'3',address:{}},actor);r.fiscal.saveProfile({id:'PF',name:'Perfil',ncm:'61091000',cfop:'5102',origin:'0',csosn:'102',pisCst:'49',cofinsCst:'49',unit:'UN',ibsCbsCst:'000',cClassTrib:'000001'},actor);r.fiscal.assignProduct(p.id,{profileId:'PF'},actor);return{r,customer,p};}
const counts=r=>({stock:r.db.prepare('SELECT COUNT(*) c FROM inventory_movements').get().c,finance:r.db.prepare('SELECT COUNT(*) c FROM financial_entries').get().c});

test('POS return points to original fiscal document and does not repeat refund or stock',()=>{const{r,customer}=setup();try{const cash=r.retail.openCash({locationId:'MAIN',openingCents:0},actor),sale=r.retail.createSale({id:'SALE1',sessionId:cash.id,customerId:customer.id,idempotencyKey:'s1',items:[{productId:'P1',quantity:2}],payments:[{method:'CASH',amountCents:2000}]},actor);const original=r.fiscalInteroperability.prepareSource({sourceType:'POS_SALE',sourceId:sale.id,idempotencyKey:'tax-s1'},actor).documents[0];const ret=r.retail.returnSale(sale.id,{id:'RET1',idempotencyKey:'r1',reason:'Troca',refundMethod:'CASH',items:[{saleItemId:sale.items[0].id,quantity:1}]},actor);const before=counts(r);const fiscal=r.fiscalInteroperability.prepareSource({sourceType:'POS_RETURN',sourceId:ret.id,idempotencyKey:'tax-r1'},actor).documents[0];assert.equal(fiscal.operationKind,'RETURN');assert.equal(fiscal.parentDocumentId,original.id);assert.equal(fiscal.documentType,'nfce');assert.equal(fiscal.snapshot.originalDocumentStatus,'RELATED');assert.deepEqual(counts(r),before);assert.equal(r.fiscalInteroperability.prepareSource({sourceType:'POS_RETURN',sourceId:ret.id,idempotencyKey:'tax-r1'},actor).documents[0].id,fiscal.id);}finally{r.close();}});

test('administrative return without original fiscal document remains explicit and never fabricates reference',()=>{const{r,customer}=setup();try{const order=r.salesAdmin.createQuote({id:'Q2',customerId:customer.id,locationId:'MAIN',items:[{productId:'P1',quantity:1}]},actor);r.salesAdmin.confirmOrder(order.id,actor);const invoice=r.salesAdmin.invoiceOrder(order.id,{id:'INV2',idempotencyKey:'inv2'},actor);const ret=r.retail.returnAdminInvoice(invoice.id,{id:'ARET2',idempotencyKey:'ar2',reason:'Defeito',items:[{invoiceItemId:invoice.items[0].id,quantity:1}]},actor);const before=counts(r);const fiscal=r.fiscalInteroperability.prepareSource({sourceType:'ADMIN_RETURN',sourceId:ret.id,idempotencyKey:'tax-ar2'},actor).documents[0];assert.equal(fiscal.operationKind,'RETURN');assert.equal(fiscal.documentType,'nfe');assert.equal(fiscal.parentDocumentId,null);assert.equal(fiscal.snapshot.originalDocumentStatus,'NO_ORIGINAL_DOCUMENT');assert.equal(fiscal.snapshot.originalAccessKey??null,null);assert.deepEqual(counts(r),before);}finally{r.close();}});
