'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createErpRuntime}=require('../js/core/erp-runtime');
const manager={userId:'m1',role:'manager'};function fx(){let n=0;const rt=createErpRuntime({idFactory:p=>`${p}-${++n}`,now:()=> '2026-09-25T12:00:00.000Z'});rt.catalog.createProduct({id:'P1',sku:'P1',name:'Produto',trackStock:true},manager);rt.inventory.createLocation({id:'A',name:'A'},manager);rt.inventory.createLocation({id:'B',name:'B'},manager);return rt;}

test('inventory operations schema exists',()=>{const rt=fx();try{assert.equal(rt.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='inventory_operations'").get().name,'inventory_operations');}finally{rt.close();}});

test('adjustments and transfers are atomic idempotent and append-only',()=>{const rt=fx();try{const a=rt.inventoryOperations.adjust({idempotencyKey:'adj-1',productId:'P1',locationId:'A',quantity:10,direction:'IN',reason:'saldo inicial'},manager);const retry=rt.inventoryOperations.adjust({idempotencyKey:'adj-1',productId:'P1',locationId:'A',quantity:10,direction:'IN',reason:'saldo inicial'},manager);assert.equal(a.id,retry.id);assert.equal(rt.inventory.getBalance('P1','A'),10);const tx=rt.inventoryOperations.transfer({idempotencyKey:'tx-1',productId:'P1',fromLocationId:'A',toLocationId:'B',quantity:4,reason:'reposicao'},manager);assert.equal(rt.inventoryOperations.transfer({idempotencyKey:'tx-1',productId:'P1',fromLocationId:'A',toLocationId:'B',quantity:4,reason:'reposicao'},manager).id,tx.id);assert.equal(rt.inventory.getBalance('P1','A'),6);assert.equal(rt.inventory.getBalance('P1','B'),4);assert.equal(rt.inventory.listMovements({sourceType:'inventory-transfer',sourceId:tx.id}).length,2);assert.ok(rt.db.prepare("SELECT 1 FROM domain_events WHERE aggregate_id=? AND type='inventory.stock.changed'").get(tx.id));}finally{rt.close();}});

test('invalid transfer leaves both locations untouched',()=>{const rt=fx();try{rt.inventoryOperations.adjust({idempotencyKey:'seed',productId:'P1',locationId:'A',quantity:2,direction:'IN',reason:'seed'},manager);assert.throws(()=>rt.inventoryOperations.transfer({idempotencyKey:'bad-same',productId:'P1',fromLocationId:'A',toLocationId:'A',quantity:1,reason:'x'},manager),/diferentes/i);assert.throws(()=>rt.inventoryOperations.transfer({idempotencyKey:'bad-stock',productId:'P1',fromLocationId:'A',toLocationId:'B',quantity:3,reason:'x'},manager),/insuficiente/i);assert.equal(rt.inventory.getBalance('P1','A'),2);assert.equal(rt.inventory.getBalance('P1','B'),0);assert.equal(rt.inventoryOperations.listOperations().filter(x=>x.idempotencyKey.startsWith('bad')).length,0);}finally{rt.close();}});

test('reversal creates compensating movements instead of deleting history',()=>{const rt=fx();try{const op=rt.inventoryOperations.adjust({idempotencyKey:'in',productId:'P1',locationId:'A',quantity:5,direction:'IN',reason:'entrada'},manager);const reversal=rt.inventoryOperations.reverse(op.id,{idempotencyKey:'rev',reason:'correcao'},manager);assert.equal(reversal.type,'REVERSAL');assert.equal(reversal.reversesOperationId,op.id);assert.equal(rt.inventory.getBalance('P1','A'),0);assert.equal(rt.inventory.listMovements({productId:'P1',locationId:'A'}).length,2);assert.throws(()=>rt.inventoryOperations.reverse(op.id,{idempotencyKey:'rev-2',reason:'duplicada'},manager),/revertida/i);}finally{rt.close();}});
