'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createErpRuntime}=require('../js/core/erp-runtime');const {createLocalServer}=require('../server/local-server');
const admin={userId:'admin',role:'admin'},operator={userId:'op',role:'operator'};
function fx(){let n=0;return createErpRuntime({dbPath:':memory:',now:()=> '2026-09-25T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});}
function seed(rt){rt.catalog.createProduct({id:'P1',sku:'P1',name:'Produto',costCents:1000,salePriceCents:2000,trackStock:true,minStock:5,targetStock:12,removalStrategy:'FEFO'},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);}
test('advanced inventory persists lots serials positions and FEFO pick plan',()=>{const rt=fx();try{seed(rt);const late=rt.inventoryDepth.createLot({id:'L2',productId:'P1',locationId:'MAIN',code:'L2',expiresAt:'2027-12-31'},admin);const early=rt.inventoryDepth.createLot({id:'L1',productId:'P1',locationId:'MAIN',code:'L1',expiresAt:'2026-12-31'},admin);rt.inventoryDepth.receiveTracked({productId:'P1',locationId:'MAIN',lotId:late.id,quantity:5},admin);rt.inventoryDepth.receiveTracked({productId:'P1',locationId:'MAIN',lotId:early.id,quantity:4},admin);const plan=rt.inventoryDepth.recommendPick({productId:'P1',locationId:'MAIN',quantity:6});assert.equal(plan.strategy,'FEFO');assert.equal(plan.plan[0].lotId,'L1');assert.equal(plan.plan[0].quantity,4);assert.equal(plan.plan[1].lotId,'L2');assert.throws(()=>rt.inventoryDepth.recommendPick({productId:'P1',locationId:'MAIN',quantity:99}),/insuficiente/i);assert.throws(()=>rt.inventoryDepth.createLot({productId:'P1',locationId:'MAIN',code:'X'},operator),/Autorizacao|Permissao/i);}finally{rt.close();}});
test('cycle count requires recount on divergence and posts adjustment only when closed',()=>{const rt=fx();try{seed(rt);const lot=rt.inventoryDepth.createLot({productId:'P1',locationId:'MAIN',code:'L1'},admin);rt.inventoryDepth.receiveTracked({productId:'P1',locationId:'MAIN',lotId:lot.id,quantity:10},admin);let cycle=rt.inventoryDepth.startCycleCount({locationId:'MAIN',requireRecount:true},admin);cycle=rt.inventoryDepth.count({cycleCountId:cycle.id,lineId:cycle.lines[0].id,quantity:8},admin);assert.equal(cycle.lines[0].status,'NEEDS_RECOUNT');assert.throws(()=>rt.inventoryDepth.closeCycle(cycle.id,admin),/pendentes/i);cycle=rt.inventoryDepth.count({cycleCountId:cycle.id,lineId:cycle.lines[0].id,quantity:8,recount:true},admin);assert.equal(cycle.lines[0].status,'COUNTED');rt.inventoryDepth.closeCycle(cycle.id,admin);assert.equal(rt.inventory.getBalance('P1','MAIN'),8);assert.equal(rt.inventoryDepth.listPositions({productId:'P1'})[0].quantity,8);}finally{rt.close();}});
test('losses and replenishment/ABC analytics use canonical inventory movements',()=>{const rt=fx();try{seed(rt);rt.inventory.move({productId:'P1',locationId:'MAIN',delta:10,unitCostCents:1000,sourceType:'seed',sourceId:'1'},admin);rt.inventoryDepth.recordLoss({productId:'P1',locationId:'MAIN',quantity:2,kind:'DAMAGE',reason:'Quebra'},admin);const a=rt.inventoryDepth.analytics();assert.equal(a.losses[0].kind,'DAMAGE');assert.equal(a.losses[0].quantity,2);assert.equal(a.abc[0].class,'A');rt.inventory.move({productId:'P1',locationId:'MAIN',delta:-4,sourceType:'use',sourceId:'2'},admin);const r=rt.inventoryDepth.replenishment();assert.equal(r[0].productId,'P1');assert.equal(r[0].suggestedQuantity,8);}finally{rt.close();}});
test('advanced inventory API is authenticated and exposes traceability analytics and cycle count',async()=>{const rt=fx();seed(rt);const user=rt.auth.createUser({id:'admin',username:'admin',name:'Admin',role:'admin',password:'senha'});const server=createLocalServer({runtime:rt,host:'127.0.0.1',port:0});try{const address=await server.start(),base=`http://${address.host}:${address.port}`;const login=await fetch(base+'/api/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'admin',password:'senha'})});const token=(await login.json()).token;const api=(path,opts={})=>fetch(base+path,{...opts,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(opts.headers||{})}});assert.equal((await fetch(base+'/api/v1/inventory/analytics')).status,401);let r=await api('/api/v1/inventory/lots',{method:'POST',body:JSON.stringify({productId:'P1',locationId:'MAIN',code:'API-L1',expiresAt:'2026-11-01'})});assert.equal(r.status,201);const lot=await r.json();r=await api('/api/v1/inventory/positions',{method:'POST',body:JSON.stringify({productId:'P1',locationId:'MAIN',lotId:lot.id,quantity:3})});assert.equal(r.status,201);r=await api('/api/v1/inventory/pick-plan?productId=P1&locationId=MAIN&quantity=2');assert.equal(r.status,200);assert.equal((await r.json()).plan[0].lotId,lot.id);r=await api('/api/v1/inventory/analytics');assert.equal(r.status,200);assert.ok(Array.isArray((await r.json()).abc));}finally{await server.stop();rt.close();}});
