'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {createErpRuntime}=require('../js/core/erp-runtime');

const admin={userId:'admin',role:'admin',companyId:'default'};
const operator={userId:'operator',role:'operator',companyId:'default'};
function setup(){let n=0;const r=createErpRuntime({now:()=> '2026-09-26T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});r.inventory.createLocation({id:'MAIN',name:'Principal'},admin);r.catalog.createProduct({id:'C1',name:'Componente 1',sku:'C1',costCents:100,salePriceCents:200,trackStock:true},admin);r.catalog.createProduct({id:'C2',name:'Componente 2',sku:'C2',costCents:200,salePriceCents:300,trackStock:true},admin);const fg=r.catalog.createProduct({id:'FG',name:'Produto acabado',sku:'FG',costCents:0,salePriceCents:2000,trackStock:true},admin);r.retail.setProductRetail(fg.id,{productType:'MANUFACTURED'},admin);r.retail.createBom(fg.id,{items:[{productId:'C1',quantity:2},{productId:'C2',quantity:1}]},admin);return{r,fg};}

test('manufacturing snapshots BOM, reserves atomically and executes physical production',()=>{const {r}=setup();try{assert.ok(r.manufacturing);const op=r.manufacturing.createOrder({id:'OP1',productId:'FG',plannedQuantity:2,locationId:'MAIN',outputLocationId:'MAIN'},admin);assert.equal(op.status,'PLANNED');assert.equal(op.components.length,2);assert.deepEqual(op.components.map(x=>[x.productId,x.requiredQuantity]),[['C1',4],['C2',2]]);const shortage=r.manufacturing.release(op.id,admin);assert.equal(shortage.status,'PLANNED');assert.equal(shortage.shortages.length,2);assert.equal(r.inventoryReservations.listReservations({sourceType:'manufacturing-order'}).length,0);r.inventory.move({productId:'C1',locationId:'MAIN',delta:4,sourceType:'seed',sourceId:'1'},admin);r.inventory.move({productId:'C2',locationId:'MAIN',delta:2,sourceType:'seed',sourceId:'2'},admin);const released=r.manufacturing.release(op.id,admin);assert.equal(released.status,'RELEASED');assert.equal(released.components.filter(x=>x.reservationId).length,2);assert.equal(r.manufacturing.start(op.id,operator).status,'IN_PROGRESS');for(const c of released.components)r.manufacturing.consumeComponent(op.id,c.id,{quantity:c.requiredQuantity},operator);r.manufacturing.addCost(op.id,{costType:'LABOR',description:'Mao de obra',amountCents:1000},admin);r.manufacturing.reportOutput(op.id,{quantity:1},operator);r.manufacturing.reportLoss(op.id,{lossType:'OUTPUT',productId:'FG',quantity:1,reason:'Refugo'},operator);const done=r.manufacturing.complete(op.id,admin);assert.equal(done.status,'COMPLETED');assert.equal(done.completedQuantity,1);assert.equal(done.scrapQuantity,1);assert.equal(done.actualMaterialCostCents,800);assert.equal(done.additionalCostCents,1000);assert.equal(done.actualTotalCostCents,1800);assert.equal(r.inventory.getBalance('FG','MAIN'),1);assert.equal(r.finance.listEntries().filter(x=>x.sourceType==='manufacturing-order').length,0);}finally{r.close();}});

test('manufacturing order keeps BOM snapshot until explicit refresh',()=>{const {r}=setup();try{const first=r.manufacturing.createOrder({id:'OP1',productId:'FG',plannedQuantity:1,locationId:'MAIN',outputLocationId:'MAIN'},admin);r.retail.createBom('FG',{items:[{productId:'C1',quantity:5}]},admin);assert.deepEqual(r.manufacturing.getOrder(first.id,admin).components.map(x=>[x.productId,x.requiredQuantity]),[['C1',2],['C2',1]]);const refreshed=r.manufacturing.refreshBom(first.id,admin);assert.deepEqual(refreshed.components.map(x=>[x.productId,x.requiredQuantity]),[['C1',5]]);}finally{r.close();}});

test('MRP calculates only uncovered demand and creates purchase requisition idempotently',()=>{const {r}=setup();try{assert.ok(r.mrp);r.manufacturing.createOrder({id:'OP2',productId:'FG',plannedQuantity:2,locationId:'MAIN',outputLocationId:'MAIN'},admin);const result=r.mrp.calculate({locationId:'MAIN'},admin);const c1=result.items.find(x=>x.productId==='C1'),c2=result.items.find(x=>x.productId==='C2');assert.equal(c1.netRequirement,4);assert.equal(c2.netRequirement,2);const generated=r.mrp.generateMrpRequisition({locationId:'MAIN'},admin);assert.equal(generated.requisitions.length,1);const req=generated.requisitions[0];assert.equal(req.items.length,2);const again=r.mrp.generateMrpRequisition({locationId:'MAIN'},admin);assert.equal(again.requisitions[0].id,req.id);assert.equal(r.procurementRequisitions.listRequisitions().length,1);}finally{r.close();}});
