'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createErpRuntime}=require('../js/core/erp-runtime');
const admin={userId:'admin',role:'admin'},operator={userId:'op',role:'operator'};function fx(){let n=0;return createErpRuntime({dbPath:':memory:',idFactory:p=>`${p}-${++n}`});}

test('customers suppliers categories and products persist locally',()=>{const rt=fx();const customer=rt.contacts.createCustomer({id:'C1',name:'Cliente A'},admin);const supplier=rt.contacts.createSupplier({id:'S1',name:'Fornecedor A'},admin);const cat=rt.catalog.createCategory({id:'CAT',name:'Geral'},admin);const product=rt.catalog.createProduct({id:'P1',sku:'SKU1',name:'Produto',categoryId:cat.id,costCents:500,salePriceCents:900,trackStock:true},admin);assert.equal(customer.kind,'CUSTOMER');assert.equal(supplier.kind,'SUPPLIER');assert.equal(product.costCents,500);assert.equal(rt.catalog.getProduct('P1').sku,'SKU1');rt.close();});

test('contact editing preserves kind and inactive records remain addressable',()=>{const rt=fx();try{const customer=rt.contacts.createCustomer({id:'C1',name:'Cliente A',email:'a@x.test'},admin);const updated=rt.contacts.updateContact(customer.id,{name:'Cliente B',phone:'16999999999',kind:'SUPPLIER'},admin);assert.equal(updated.name,'Cliente B');assert.equal(updated.phone,'16999999999');assert.equal(updated.kind,'CUSTOMER');assert.throws(()=>rt.contacts.updateContact(customer.id,{name:'X'},operator),/Autorizacao|Permissao/i);rt.contacts.setActive(customer.id,false,admin);assert.equal(rt.contacts.list({kind:'CUSTOMER'}).length,0);assert.equal(rt.contacts.list({kind:'CUSTOMER',includeInactive:true}).length,1);assert.equal(rt.contacts.getContact(customer.id).active,false);rt.contacts.setActive(customer.id,true,admin);assert.equal(rt.contacts.getContact(customer.id).active,true);}finally{rt.close();}});

test('categories and products support whitelisted editing and activation lifecycle',()=>{const rt=fx();try{const cat=rt.catalog.createCategory({id:'CAT',name:'Original'},admin);const other=rt.catalog.createCategory({id:'CAT2',name:'Outra'},admin);const product=rt.catalog.createProduct({id:'P1',sku:'SKU1',name:'Produto',categoryId:cat.id,costCents:500,salePriceCents:900,trackStock:true},admin);assert.equal(rt.catalog.updateCategory(cat.id,{name:'Renomeada'},admin).name,'Renomeada');assert.equal(rt.catalog.setCategoryActive(cat.id,false,admin).active,false);assert.equal(rt.catalog.setCategoryActive(cat.id,true,admin).active,true);const updated=rt.catalog.updateProduct(product.id,{name:'Produto B',sku:'B-001',categoryId:other.id,salePriceCents:2590,trackStock:false},admin);assert.equal(updated.name,'Produto B');assert.equal(updated.sku,'B-001');assert.equal(updated.categoryId,other.id);assert.equal(updated.salePriceCents,2590);assert.equal(updated.trackStock,false);rt.catalog.setCategoryActive(other.id,false,admin);assert.throws(()=>rt.catalog.updateProduct(product.id,{categoryId:other.id},admin),/inativa/i);rt.catalog.setCategoryActive(other.id,true,admin);assert.throws(()=>rt.catalog.updateProduct(product.id,{salePriceCents:-1},admin),/negativo|invalido/i);assert.throws(()=>rt.catalog.updateProduct(product.id,{name:'X'},operator),/Autorizacao|Permissao/i);}finally{rt.close();}});

test('inventory prevents invalid and negative tracked movements',()=>{const rt=fx();rt.catalog.createProduct({id:'P1',sku:'SKU1',name:'Produto',costCents:500,salePriceCents:900,trackStock:true},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);assert.throws(()=>rt.inventory.move({productId:'X',locationId:'MAIN',delta:1,sourceType:'test',sourceId:'1'},admin),/produto/i);rt.inventory.move({productId:'P1',locationId:'MAIN',delta:10,sourceType:'initial',sourceId:'1'},admin);assert.equal(rt.inventory.getBalance('P1','MAIN'),10);assert.throws(()=>rt.inventory.move({productId:'P1',locationId:'MAIN',delta:-11,sourceType:'test',sourceId:'2'},admin),/insuficiente/i);rt.close();});

test('inventory reservations enforce available stock and can release or consume',()=>{const rt=fx();rt.catalog.createProduct({id:'P1',sku:'SKU1',name:'Produto',costCents:500,salePriceCents:900,trackStock:true},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);rt.inventory.move({productId:'P1',locationId:'MAIN',delta:10,sourceType:'initial',sourceId:'1'},admin);const r=rt.inventoryLogistics.reserve({productId:'P1',locationId:'MAIN',quantity:6,sourceType:'order',sourceId:'O1'},admin);assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),4);assert.throws(()=>rt.inventoryLogistics.reserve({productId:'P1',locationId:'MAIN',quantity:5,sourceType:'order',sourceId:'O2'},admin),/disponivel|insuficiente/i);rt.inventoryLogistics.release(r.id,admin);assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),10);const r2=rt.inventoryLogistics.reserve({productId:'P1',locationId:'MAIN',quantity:4,sourceType:'order',sourceId:'O3'},admin);rt.inventoryLogistics.consume(r2.id,admin);assert.equal(rt.inventory.getBalance('P1','MAIN'),6);assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),6);rt.close();});

test('inactive customers suppliers products and locations are rejected by dependent operations',()=>{const rt=fx();const customer=rt.contacts.createCustomer({id:'C1',name:'Cliente A'},admin);const supplier=rt.contacts.createSupplier({id:'S1',name:'Fornecedor A'},admin);rt.contacts.setActive(customer.id,false,admin);rt.contacts.setActive(supplier.id,false,admin);assert.throws(()=>rt.contacts.requireCustomer('C1'),/inativo/i);assert.throws(()=>rt.contacts.requireSupplier('S1'),/inativo/i);rt.catalog.createProduct({id:'P1',sku:'SKU1',name:'Produto',costCents:500,salePriceCents:900,trackStock:true},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);rt.catalog.setProductActive('P1',false,admin);assert.throws(()=>rt.inventory.move({productId:'P1',locationId:'MAIN',delta:1,sourceType:'test',sourceId:'1'},admin),/inativo/i);rt.close();});
