'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createErpRuntime}=require('../js/core/erp-runtime');const {createLocalServer}=require('../server/local-server');
async function fx(){let n=0;const runtime=createErpRuntime({idFactory:p=>`${p}-${++n}`});const admin=runtime.auth.createUser({id:'admin',username:'admin',name:'Admin',role:'admin',password:'senha'});runtime.auth.createUser({id:'manager',username:'manager',name:'Manager',role:'manager',password:'senha'}, {userId:admin.id,role:'admin'});runtime.auth.createUser({id:'operator',username:'operator',name:'Operator',role:'operator',password:'senha'}, {userId:admin.id,role:'admin'});const server=createLocalServer({runtime,host:'127.0.0.1',port:0});const addr=await server.start(),base=`http://${addr.host}:${addr.port}`;async function login(username){const r=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'senha'})});return (await r.json()).token;}async function api(token,path,method='GET',body){return fetch(`${base}${path}`,{method,headers:{authorization:`Bearer ${token}`,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});}return{runtime,server,login,api,close:async()=>{await server.stop();runtime.close();}};}
async function data(r){const body=await r.json();assert.ok(r.ok,`${r.status} ${JSON.stringify(body)}`);return body;}

test('master data item routes support edit deactivate reactivate and bounded pagination',async()=>{const ctx=await fx();try{const manager=await ctx.login('manager'),operator=await ctx.login('operator');const c=await data(await ctx.api(manager,'/api/v1/customers','POST',{id:'C1',name:'Cliente A'}));assert.equal((await data(await ctx.api(manager,`/api/v1/customers/${c.id}`))).name,'Cliente A');const edited=await data(await ctx.api(manager,`/api/v1/customers/${c.id}`,'PATCH',{name:'Cliente B'}));assert.equal(edited.name,'Cliente B');assert.equal((await ctx.api(operator,`/api/v1/customers/${c.id}`,'PATCH',{name:'X'})).status,403);assert.equal((await data(await ctx.api(manager,`/api/v1/customers/${c.id}/deactivate`,'POST',{}))).active,false);assert.equal((await data(await ctx.api(manager,`/api/v1/customers/${c.id}/reactivate`,'POST',{}))).active,true);
const cat=await data(await ctx.api(manager,'/api/v1/product-categories','POST',{id:'CAT',name:'Geral'}));assert.equal((await data(await ctx.api(manager,`/api/v1/product-categories/${cat.id}`,'PATCH',{name:'Nova'}))).name,'Nova');const p=await data(await ctx.api(manager,'/api/v1/products','POST',{id:'P1',name:'Produto',sku:'A',categoryId:cat.id,salePriceCents:1000,costCents:500}));assert.equal((await data(await ctx.api(manager,`/api/v1/products/${p.id}`,'PATCH',{salePriceCents:1200}))).salePriceCents,1200);
await data(await ctx.api(manager,'/api/v1/customers','POST',{id:'C2',name:'Cliente C'}));const page=await data(await ctx.api(manager,'/api/v1/customers?page=1&pageSize=1'));assert.equal(page.page,1);assert.equal(page.pageSize,1);assert.equal(page.total,2);assert.equal(page.items.length,1);const bounded=await data(await ctx.api(manager,'/api/v1/customers?pageSize=999'));assert.equal(bounded.pageSize,200);
}finally{await ctx.close();}});
