'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{createErpRuntime}=require('../js/core/erp-runtime');

const admin={userId:'admin',role:'admin',companyId:'default'};
function setup(){let n=0;const rt=createErpRuntime({now:()=> '2026-09-26T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);rt.inventory.createLocation({id:'SECOND',name:'Secundário'},admin);rt.catalog.createProduct({id:'P-HARD',sku:'P-HARD',name:'Produto hardening',salePriceCents:1000,trackStock:true},admin);rt.inventory.move({productId:'P-HARD',locationId:'MAIN',delta:5,sourceType:'seed',sourceId:'hardening'},admin);return rt;}

test('POS idempotency prevents duplicate sale and duplicate stock/finance effects',()=>{const rt=setup();try{const cash=rt.retail.openCash({locationId:'MAIN',openingCents:0},admin);const input={sessionId:cash.id,idempotencyKey:'sale-same-click',items:[{productId:'P-HARD',quantity:1}],payments:[{method:'CASH',amountCents:1000}]};const first=rt.retail.createSale(input,admin);const second=rt.retail.createSale(input,admin);assert.equal(second.id,first.id);assert.equal(rt.inventory.getBalance('P-HARD','MAIN'),4);assert.equal(rt.db.prepare("SELECT COUNT(*) c FROM pos_sales WHERE idempotency_key='sale-same-click'").get().c,1);assert.equal(rt.db.prepare("SELECT COUNT(*) c FROM financial_entries WHERE source_type='pos-sale' AND source_id=?").get(first.id).c,1);}finally{rt.close();}});

test('return idempotency restores stock only once',()=>{const rt=setup();try{const cash=rt.retail.openCash({locationId:'MAIN',openingCents:0},admin);const sale=rt.retail.createSale({sessionId:cash.id,idempotencyKey:'sale-return-base',items:[{productId:'P-HARD',quantity:1}],payments:[{method:'CASH',amountCents:1000}]},admin);const input={reason:'Troca',refundMethod:'CASH',idempotencyKey:'return-same-click'};const first=rt.retail.returnSale(sale.id,input,admin);const second=rt.retail.returnSale(sale.id,input,admin);assert.equal(second.id,first.id);assert.equal(rt.inventory.getBalance('P-HARD','MAIN'),5);assert.equal(rt.db.prepare("SELECT COUNT(*) c FROM sales_returns WHERE idempotency_key='return-same-click'").get().c,1);}finally{rt.close();}});

test('transfer rejects invalid repeated transitions and keeps balances consistent',()=>{const rt=setup();try{const t=rt.retail.requestTransfer({productId:'P-HARD',fromLocationId:'MAIN',toLocationId:'SECOND',quantity:2,reason:'Reposição',idempotencyKey:'transfer-hard'},admin);rt.retail.transitionTransfer(t.id,'ship',admin);assert.equal(rt.inventory.getBalance('P-HARD','MAIN'),3);assert.equal(rt.inventory.getBalance('P-HARD','SECOND'),0);assert.throws(()=>rt.retail.transitionTransfer(t.id,'ship',admin),/status/i);assert.equal(rt.inventory.getBalance('P-HARD','MAIN'),3);rt.retail.transitionTransfer(t.id,'receive',admin);assert.equal(rt.inventory.getBalance('P-HARD','SECOND'),2);assert.throws(()=>rt.retail.transitionTransfer(t.id,'receive',admin),/transito|trânsito|status/i);assert.equal(rt.inventory.getBalance('P-HARD','SECOND'),2);}finally{rt.close();}});

test('sale and transfer fail atomically when stock or payment is invalid',()=>{const rt=setup();try{const cash=rt.retail.openCash({locationId:'MAIN',openingCents:0},admin);const before=rt.inventory.getBalance('P-HARD','MAIN');assert.throws(()=>rt.retail.createSale({sessionId:cash.id,idempotencyKey:'bad-payment',items:[{productId:'P-HARD',quantity:1}],payments:[{method:'CASH',amountCents:999}]},admin),/Pagamentos/i);assert.equal(rt.inventory.getBalance('P-HARD','MAIN'),before);assert.throws(()=>rt.retail.requestTransfer({productId:'P-HARD',fromLocationId:'MAIN',toLocationId:'SECOND',quantity:999,reason:'Sem saldo',idempotencyKey:'bad-transfer'},admin),/insuficiente/i);assert.equal(rt.inventory.getBalance('P-HARD','MAIN'),before);}finally{rt.close();}});
