'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createErpRuntime}=require('../js/core/erp-runtime');
const admin={userId:'admin',role:'admin'},manager={userId:'manager',role:'manager'},director={userId:'director',role:'director'};
function fx(){let n=0;const rt=createErpRuntime({idFactory:p=>`${p}-${++n}`,now:()=> '2026-09-25T12:00:00.000Z'});rt.contacts.createSupplier({id:'S1',name:'Fornecedor A'},admin);rt.contacts.createSupplier({id:'S2',name:'Fornecedor B'},admin);rt.catalog.createProduct({id:'P1',name:'Produto 1',sku:'P1',trackStock:true},admin);rt.catalog.createProduct({id:'P2',name:'Produto 2',sku:'P2',trackStock:true},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);return rt;}
function prepareQuotes(rt){const req=rt.procurementRequisitions.createRequisition({id:'REQ1',locationId:'MAIN',justification:'Reposicao',items:[{productId:'P1',quantity:10},{productId:'P2',quantity:5}]},manager);rt.procurementRequisitions.submitForQuotation(req.id,manager);const q1=rt.procurementQuotations.createQuotation({id:'Q1',requisitionId:req.id,supplierId:'S1',freightCents:100,paymentDays:15,validUntil:'2026-10-10',items:[{productId:'P1',unitCostCents:100,availableQuantity:10,deliveryDays:5},{productId:'P2',unitCostCents:300,availableQuantity:5,deliveryDays:5}]},manager);const q2=rt.procurementQuotations.createQuotation({id:'Q2',requisitionId:req.id,supplierId:'S2',freightCents:100,paymentDays:30,validUntil:'2026-10-10',items:[{productId:'P1',unitCostCents:120,availableQuantity:10,deliveryDays:1},{productId:'P2',unitCostCents:200,availableQuantity:5,deliveryDays:2}]},manager);rt.procurementQuotations.submitQuotation(q1.id,manager);rt.procurementQuotations.submitQuotation(q2.id,manager);return{req,q1,q2};}

test('advanced procurement schema and director role are available',()=>{const rt=fx();try{for(const name of ['purchase_requisitions','supplier_quotations','procurement_awards','procurement_approval_requests','purchase_returns','supplier_credits','financial_entry_adjustments'])assert.ok(rt.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(name),name);const first=rt.auth.createUser({username:'root',name:'Root',role:'admin',password:'x'});const d=rt.auth.createUser({username:'director',name:'Diretor',role:'director',password:'x'},{userId:first.id,role:'admin'});assert.equal(d.role,'director');}finally{rt.close();}});

test('requisitions accept multiple quotations and scoring suggests a split without mutating awards',()=>{const rt=fx();try{const {req}=prepareQuotes(rt);assert.equal(rt.procurementQuotations.listQuotations({requisitionId:req.id}).length,2);assert.equal(rt.procurementPricing.listPriceHistory({productId:'P1'}).length,2);rt.settings.set('procurement.scoringWeights',{price:100,freight:0,delivery:0,payment:0,availability:0,reliability:0},admin);const before=rt.db.prepare('SELECT COUNT(*) n FROM procurement_awards').get().n;const suggestion=rt.procurementScoring.suggest(req.id);assert.equal(suggestion.items.find(x=>x.productId==='P1').selected.supplierId,'S1');assert.equal(suggestion.items.find(x=>x.productId==='P2').selected.supplierId,'S2');assert.ok(suggestion.explanation.length>0);assert.equal(rt.db.prepare('SELECT COUNT(*) n FROM procurement_awards').get().n,before);}finally{rt.close();}});

test('multi-supplier award uses snapshot multi-level approval and generates one PO per supplier',()=>{const rt=fx();try{const {req}=prepareQuotes(rt);rt.settings.set('procurement.scoringWeights',{price:100,freight:0,delivery:0,payment:0,availability:0,reliability:0},admin);rt.settings.set('procurement.approvalPolicy',[{minCents:0,maxCents:null,levels:[{level:1,roles:['manager']},{level:2,roles:['director']}]}],admin);const award=rt.procurementAwards.createAwardFromSuggestion(req.id,manager);assert.equal(new Set(award.items.map(x=>x.supplierId)).size,2);const approval=rt.procurementApprovals.submitAwardForApproval(award.id,manager);assert.equal(approval.currentLevel,1);rt.settings.set('procurement.approvalPolicy',[{minCents:0,maxCents:null,levels:[{level:1,roles:['admin']}]}],admin);let next=rt.procurementApprovals.approveLevel(approval.id,{reason:'ok'},manager);assert.equal(next.currentLevel,2);next=rt.procurementApprovals.approveLevel(approval.id,{reason:'ok'},director);assert.equal(next.status,'APPROVED');assert.equal(JSON.parse(next.policySnapshotJson)[0].roles[0],'manager');const orders=rt.procurementAwards.generateOrders(award.id,manager);assert.equal(orders.length,2);assert.equal(rt.procurementAwards.generateOrders(award.id,manager).length,2);const changed=rt.procurementAwards.updateAward(award.id,{items:award.items.map((x,i)=>({...x,quantity:i===0?x.quantity+1:x.quantity}))},manager);assert.notEqual(changed.id,award.id);assert.equal(rt.procurementAwards.getAward(award.id).status,'SUPERSEDED');assert.equal(changed.status,'DRAFT');assert.equal(rt.procurementApprovals.getApproval(approval.id).status,'INVALIDATED');}finally{rt.close();}});

test('receipt variance stays visible and excess above tolerance requires explicit authorization',()=>{const rt=fx();try{rt.settings.set('procurement.receiptExcessTolerancePercent',2,admin);const po=rt.procurement.createPurchaseOrder({supplierId:'S1',locationId:'MAIN',items:[{productId:'P1',quantity:100,unitCostCents:100}]},manager);rt.procurement.submitPurchaseOrder(po.id,manager);const first=rt.procurement.receivePurchaseOrder(po.id,{idempotencyKey:'r1',items:[{productId:'P1',quantity:92}]},manager);assert.equal(first.items[0].missingQuantity,8);assert.equal(first.items[0].status,'PARTIAL');assert.throws(()=>rt.procurement.receivePurchaseOrder(po.id,{idempotencyKey:'r2',items:[{productId:'P1',quantity:11}]},manager),/autoriza/i);assert.equal(rt.inventory.getBalance('P1','MAIN'),92);const second=rt.procurement.receivePurchaseOrder(po.id,{idempotencyKey:'r2',items:[{productId:'P1',quantity:11}],excessAuthorization:{reason:'Aceite fornecedor'}},manager);assert.equal(second.items[0].receivedTotal,103);assert.equal(second.items[0].excessQuantity,3);assert.equal(second.items[0].status,'EXCESS');assert.equal(rt.inventory.getBalance('P1','MAIN'),103);assert.equal(rt.finance.getEntry(second.payableEntryId).amountCents,1100);}finally{rt.close();}});

test('supplier return reduces open payable and creates supplier credit only for already settled value',()=>{const rt=fx();try{const po=rt.procurement.createPurchaseOrder({supplierId:'S1',locationId:'MAIN',items:[{productId:'P1',quantity:10,unitCostCents:100}]},manager);rt.procurement.submitPurchaseOrder(po.id,manager);const receipt=rt.procurement.receivePurchaseOrder(po.id,{idempotencyKey:'rec',items:[{productId:'P1',quantity:10}]},manager);const ret=rt.procurementReturns.createReturn(receipt.id,{idempotencyKey:'ret1',reason:'Avaria',items:[{productId:'P1',quantity:2}]},manager);assert.equal(ret.totalCents,200);assert.equal(rt.inventory.getBalance('P1','MAIN'),8);assert.equal(rt.finance.getEntry(receipt.payableEntryId).amountCents,800);assert.equal(rt.supplierCredits.listSupplierCredits({supplierId:'S1'}).length,0);
rt.finance.settleEntry(receipt.payableEntryId,{amountCents:800,method:'PIX'},manager);const ret2=rt.procurementReturns.createReturn(receipt.id,{idempotencyKey:'ret2',reason:'Defeito',items:[{productId:'P1',quantity:1}]},manager);assert.equal(ret2.totalCents,100);const credits=rt.supplierCredits.listSupplierCredits({supplierId:'S1'});assert.equal(credits.length,1);assert.equal(credits[0].openCents,100);assert.equal(rt.inventory.getBalance('P1','MAIN'),7);}finally{rt.close();}});
