'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createErpRuntime}=require('../js/core/erp-runtime');
const admin={userId:'admin',role:'admin'},manager={userId:'manager',role:'manager'},operator={userId:'op',role:'operator'};
function fixture(){let n=0;const rt=createErpRuntime({dbPath:':memory:',now:()=> '2026-09-25T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});rt.contacts.createSupplier({id:'S1',name:'Fornecedor'},admin);rt.catalog.createProduct({id:'P1',sku:'P1',name:'Produto',costCents:500,salePriceCents:900,trackStock:true},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);return rt;}
function createOrder(rt,quantity=10,unitCostCents=700){return rt.procurement.createPurchaseOrder({supplierId:'S1',locationId:'MAIN',expectedAt:'2026-10-10T12:00:00.000Z',items:[{productId:'P1',quantity,unitCostCents}]},manager);}

test('procurement mutations require manager or admin',()=>{const rt=fixture();assert.throws(()=>rt.procurement.createPurchaseOrder({supplierId:'S1',locationId:'MAIN',items:[{productId:'P1',quantity:1,unitCostCents:700}]},operator),/Autorizacao/i);rt.close();});

test('partial and full receipts move stock, update weighted cost and create payables',()=>{const rt=fixture();rt.inventory.move({productId:'P1',locationId:'MAIN',delta:10,sourceType:'initial',sourceId:'stock'},admin);const order=createOrder(rt);rt.procurement.submitPurchaseOrder(order.id,manager);const first=rt.procurement.receivePurchaseOrder(order.id,{idempotencyKey:'r1',dueAt:'2026-10-15T12:00:00.000Z',items:[{productId:'P1',quantity:4}]},manager);assert.equal(first.totalCents,2800);assert.equal(first.items[0].quantity,4);assert.equal(rt.procurement.getPurchaseOrder(order.id).status,'PARTIALLY_RECEIVED');assert.equal(rt.inventory.getBalance('P1','MAIN'),14);assert.equal(rt.catalog.getProduct('P1').costCents,557);const payable1=rt.finance.getEntry(first.payableEntryId);assert.equal(payable1.kind,'PAYABLE');assert.equal(payable1.sourceType,'purchase-receipt');assert.equal(payable1.sourceId,first.id);assert.equal(payable1.categoryId,'PURCHASES');const second=rt.procurement.receivePurchaseOrder(order.id,{idempotencyKey:'r2',items:[{productId:'P1',quantity:6}]},manager);assert.equal(rt.procurement.getPurchaseOrder(order.id).status,'RECEIVED');assert.equal(rt.inventory.getBalance('P1','MAIN'),20);assert.equal(rt.catalog.getProduct('P1').costCents,600);assert.ok(second.payableEntryId);rt.close();});

test('receipt idempotency returns the same receipt without duplicating stock or payable',()=>{const rt=fixture();const order=createOrder(rt,3,1000);rt.procurement.submitPurchaseOrder(order.id,admin);const first=rt.procurement.receivePurchaseOrder(order.id,{idempotencyKey:'same',items:[{productId:'P1',quantity:3}]},admin);const second=rt.procurement.receivePurchaseOrder(order.id,{idempotencyKey:'same',items:[{productId:'P1',quantity:3}]},admin);assert.equal(second.id,first.id);assert.equal(rt.inventory.getBalance('P1','MAIN'),3);assert.equal(rt.finance.listEntries({kind:'PAYABLE'}).length,1);assert.equal(rt.procurement.listReceipts({purchaseOrderId:order.id}).length,1);rt.close();});

test('finance failure rolls back receipt, stock, cost and received quantities atomically',()=>{const rt=fixture();const order=createOrder(rt,2,1000);rt.procurement.submitPurchaseOrder(order.id,admin);const beforeCost=rt.catalog.getProduct('P1').costCents;const original=rt.finance.createEntry;rt.finance.createEntry=()=>{throw new Error('finance-down');};assert.throws(()=>rt.procurement.receivePurchaseOrder(order.id,{idempotencyKey:'rollback',items:[{productId:'P1',quantity:2}]},admin),/finance-down/);rt.finance.createEntry=original;assert.equal(rt.inventory.getBalance('P1','MAIN'),0);assert.equal(rt.catalog.getProduct('P1').costCents,beforeCost);assert.equal(rt.procurement.listReceipts({purchaseOrderId:order.id}).length,0);const refreshed=rt.procurement.getPurchaseOrder(order.id);assert.equal(refreshed.items[0].receivedQuantity,0);assert.equal(refreshed.status,'ORDERED');rt.close();});
