'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {createErpRuntime}=require('../js/core/erp-runtime');
const admin={userId:'admin',role:'admin'};
function fixture(){let n=0;const rt=createErpRuntime({dbPath:':memory:',now:()=> '2026-09-25T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});rt.contacts.createSupplier({id:'S1',name:'Fornecedor'},admin);rt.contacts.createCustomer({id:'C1',name:'Cliente'},admin);rt.catalog.createProduct({id:'P1',sku:'P1',name:'Produto',costCents:500,salePriceCents:1000,trackStock:true},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);const po=rt.procurement.createPurchaseOrder({supplierId:'S1',locationId:'MAIN',items:[{productId:'P1',quantity:10,unitCostCents:600}]},admin);rt.procurement.submitPurchaseOrder(po.id,admin);const receipt=rt.procurement.receivePurchaseOrder(po.id,{idempotencyKey:'receipt',items:[{productId:'P1',quantity:10}]},admin);const order=rt.salesAdmin.createQuote({customerId:'C1',locationId:'MAIN',items:[{productId:'P1',quantity:2,unitPriceCents:1000}]},admin);rt.salesAdmin.confirmOrder(order.id,admin);const invoice=rt.salesAdmin.invoiceOrder(order.id,{idempotencyKey:'invoice',items:[{productId:'P1',quantity:2}]},admin);return{rt,receipt,invoice};}

test('accrual management uses administrative invoice snapshots without counting purchases twice',()=>{const {rt,invoice}=fixture();const sales=rt.reports.buildSalesSummary({from:'2026-09-25',to:'2026-09-25',basis:'accrual'});assert.equal(sales.netSalesCents,2000);assert.equal(sales.estimatedCostCents,1200);assert.equal(sales.estimatedMarginCents,800);const dre=rt.financeManagement.dre({basis:'accrual',from:'2026-09-25',to:'2026-09-25'});assert.equal(dre.revenueCents,2000);assert.equal(dre.costCents,1200);assert.equal(dre.expenseCents,0);assert.equal(dre.resultCents,800);assert.ok(dre.groups.some(g=>g.id==='ADMIN_SALES'));assert.ok(dre.groups.some(g=>g.id==='ADMIN_COGS'));const source=fs.readFileSync('js/domains/finance/finance-management.js','utf8');for(const forbidden of ['PDV_SALES','PDV_COGS','Vendas PDV'])assert.ok(!source.includes(forbidden),forbidden);assert.equal(rt.finance.getEntry(invoice.receivableEntryId).openCents,2000);rt.close();});

test('cash DRE recognizes only active settlements and reversals remove realization',()=>{const {rt,invoice}=fixture();let cash=rt.financeManagement.dre({basis:'cash',from:'2026-09-25',to:'2026-09-25'});assert.equal(cash.revenueCents,0);assert.equal(cash.costCents,0);const paid=rt.finance.settleEntry(invoice.receivableEntryId,{amountCents:1000,method:'PIX'},admin);cash=rt.financeManagement.dre({basis:'cash',from:'2026-09-25',to:'2026-09-25'});assert.equal(cash.revenueCents,1000);assert.equal(cash.costCents,600);assert.equal(cash.resultCents,400);rt.finance.reverseSettlement(paid.settlement.id,{reason:'estorno',actor:admin});cash=rt.financeManagement.dre({basis:'cash',from:'2026-09-25',to:'2026-09-25'});assert.equal(cash.revenueCents,0);assert.equal(cash.costCents,0);rt.close();});

test('cashflow includes operational settlements and projects open payables and receivables',()=>{const {rt,receipt,invoice}=fixture();rt.finance.settleEntry(receipt.payableEntryId,{amountCents:2000,method:'PIX'},admin);rt.finance.settleEntry(invoice.receivableEntryId,{amountCents:500,method:'PIX'},admin);const flow=rt.financeManagement.cashflow({from:'2026-09-25',to:'2026-09-25',projectionDays:30});assert.equal(flow.realizedInflowCents,500);assert.equal(flow.realizedOutflowCents,2000);assert.equal(flow.projectedReceivableCents,1500);assert.equal(flow.projectedPayableCents,4000);assert.equal(flow.projectedClosingDeltaCents,-4000);rt.close();});

test('dashboard comparison and operational reports use ERP tables',()=>{const {rt}=fixture();const dashboard=rt.financeManagement.dashboard({from:'2026-09-01',to:'2026-09-30'});assert.equal(dashboard.revenueCents,2000);assert.equal(dashboard.resultCents,800);assert.ok(dashboard.projections['7']);assert.ok(dashboard.projections['30']);assert.ok(dashboard.projections['90']);const compare=rt.financeManagement.compare({basis:'accrual',from:'2026-09-01',to:'2026-09-30',previousFrom:'2026-08-01',previousTo:'2026-08-31'});assert.equal(compare.delta.revenueCents,2000);assert.equal(rt.reports.buildPurchaseSummary({from:'2026-09-01',to:'2026-09-30'}).receivedCents,6000);assert.equal(rt.reports.buildInventorySummary().products,1);rt.close();});
