'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {createErpRuntime}=require('../js/core/erp-runtime');
const admin={userId:'admin',role:'admin'},manager={userId:'manager',role:'manager'},operator={userId:'op',role:'operator'};
function fixture(){let n=0;const rt=createErpRuntime({dbPath:':memory:',now:()=> '2026-09-25T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});rt.contacts.createCustomer({id:'C1',name:'Cliente'},admin);rt.catalog.createProduct({id:'P1',sku:'P1',name:'Produto',costCents:500,salePriceCents:1000,trackStock:true},admin);rt.inventory.createLocation({id:'MAIN',name:'Principal'},admin);rt.inventory.move({productId:'P1',locationId:'MAIN',delta:10,sourceType:'initial',sourceId:'stock'},admin);return rt;}
function quote(rt,qty=5){return rt.salesAdmin.createQuote({customerId:'C1',locationId:'MAIN',items:[{productId:'P1',quantity:qty,unitPriceCents:1000}]},manager);}

test('administrative sales require manager/admin and confirm reserves stock without checkout context',()=>{const rt=fixture();assert.throws(()=>rt.salesAdmin.createQuote({customerId:'C1',locationId:'MAIN',items:[{productId:'P1',quantity:1}]},operator),/Autorizacao/i);const order=quote(rt,5);const confirmed=rt.salesAdmin.confirmOrder(order.id,manager);assert.equal(confirmed.status,'CONFIRMED');assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),5);const source=fs.readFileSync('js/domains/sales-admin/sales-admin-service.js','utf8');for(const forbidden of ['terminalId','operatorId','payments','sale-service'])assert.ok(!source.includes(forbidden),forbidden);rt.close();});

test('partial and full administrative invoices consume stock, snapshot cost and create receivable',()=>{const rt=fixture();const order=quote(rt,5);rt.salesAdmin.confirmOrder(order.id,manager);const first=rt.salesAdmin.invoiceOrder(order.id,{idempotencyKey:'inv-1',dueAt:'2026-10-10T12:00:00.000Z',items:[{productId:'P1',quantity:2}]},manager);assert.equal(first.totalCents,2000);assert.equal(first.totalCostCents,1000);assert.equal(first.items[0].unitCostCents,500);assert.equal(rt.inventory.getBalance('P1','MAIN'),8);assert.equal(rt.salesAdmin.getOrder(order.id).status,'PARTIALLY_INVOICED');assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),5);const receivable=rt.finance.getEntry(first.receivableEntryId);assert.equal(receivable.kind,'RECEIVABLE');assert.equal(receivable.categoryId,'SALES');assert.equal(receivable.sourceType,'sales-admin-invoice');assert.equal(receivable.sourceId,first.id);rt.catalog.updateCost('P1',700,admin);const second=rt.salesAdmin.invoiceOrder(order.id,{idempotencyKey:'inv-2',items:[{productId:'P1',quantity:3}]},manager);assert.equal(second.totalCostCents,2100);assert.equal(rt.inventory.getBalance('P1','MAIN'),5);assert.equal(rt.salesAdmin.getOrder(order.id).status,'INVOICED');assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),5);rt.close();});

test('administrative invoice idempotency does not duplicate stock or receivable',()=>{const rt=fixture();const order=quote(rt,2);rt.salesAdmin.confirmOrder(order.id,admin);const first=rt.salesAdmin.invoiceOrder(order.id,{idempotencyKey:'same',items:[{productId:'P1',quantity:2}]},admin);const second=rt.salesAdmin.invoiceOrder(order.id,{idempotencyKey:'same',items:[{productId:'P1',quantity:2}]},admin);assert.equal(second.id,first.id);assert.equal(rt.inventory.getBalance('P1','MAIN'),8);assert.equal(rt.finance.listEntries({kind:'RECEIVABLE'}).length,1);assert.equal(rt.salesAdmin.listInvoices({orderId:order.id}).length,1);rt.close();});

test('receivable failure rolls back invoice, stock, reservation and invoiced quantity',()=>{const rt=fixture();const order=quote(rt,3);rt.salesAdmin.confirmOrder(order.id,admin);const original=rt.finance.createEntry;rt.finance.createEntry=()=>{throw new Error('finance-down');};assert.throws(()=>rt.salesAdmin.invoiceOrder(order.id,{idempotencyKey:'rollback',items:[{productId:'P1',quantity:2}]},admin),/finance-down/);rt.finance.createEntry=original;assert.equal(rt.inventory.getBalance('P1','MAIN'),10);assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),7);assert.equal(rt.salesAdmin.listInvoices({orderId:order.id}).length,0);const refreshed=rt.salesAdmin.getOrder(order.id);assert.equal(refreshed.items[0].invoicedQuantity,0);assert.equal(refreshed.status,'CONFIRMED');rt.close();});

test('cancelling a confirmed order releases remaining reservations',()=>{const rt=fixture();const order=quote(rt,4);rt.salesAdmin.confirmOrder(order.id,admin);assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),6);const cancelled=rt.salesAdmin.cancelOrder(order.id,{reason:'cliente desistiu'},admin);assert.equal(cancelled.status,'CANCELLED');assert.equal(rt.inventoryLogistics.getAvailable('P1','MAIN'),10);rt.close();});
