'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {createErpRuntime}=require('../js/core/erp-runtime');

const admin={userId:'admin',role:'admin',companyId:'default'};
const operator={userId:'operator',role:'operator',companyId:'default'};

function setup(){let n=0;const r=createErpRuntime({now:()=> '2026-09-26T12:00:00.000Z',idFactory:p=>`${p}-${++n}`});const customer=r.contacts.createCustomer({id:'C1',name:'Cliente OS'},admin);const part=r.catalog.createProduct({id:'P1',name:'Peca',sku:'PEC-1',costCents:500,salePriceCents:1000,trackStock:true},admin);r.inventory.move({productId:part.id,locationId:'MAIN',delta:5,sourceType:'seed',sourceId:'seed'},admin);return{r,customer,part};}

test('catalog supports SERVICE without stock and rejects tracked service',()=>{const {r}=setup();try{const p=r.catalog.createProduct({id:'S1',name:'Mao de obra',sku:'SERV-1',salePriceCents:2500,trackStock:false},admin);const service=r.retail.setProductRetail(p.id,{productType:'SERVICE'},admin);assert.equal(service.productType,'SERVICE');assert.equal(service.trackStock,false);const tracked=r.catalog.createProduct({id:'S2',name:'Servico invalido',sku:'SERV-2',salePriceCents:1000,trackStock:true},admin);assert.throws(()=>r.retail.setProductRetail(tracked.id,{productType:'SERVICE'},admin),/estoque|service|servi/i);}finally{r.close();}});

test('shared reservation service subtracts active reservations and consumes atomically',()=>{const {r,part}=setup();try{assert.ok(r.inventoryReservations);assert.equal(r.inventoryReservations.getAvailable(part.id,'MAIN'),5);const reservation=r.inventoryReservations.reserve({productId:part.id,locationId:'MAIN',quantity:3,sourceType:'test',sourceId:'T1'},admin);assert.equal(reservation.status,'ACTIVE');assert.equal(r.inventoryReservations.getAvailable(part.id,'MAIN'),2);const partial=r.inventoryReservations.consume(reservation.id,2,{sourceType:'test-consume',sourceId:'T1'},admin);assert.equal(partial.status,'ACTIVE');assert.equal(partial.remainingQuantity,1);assert.equal(r.inventory.getBalance(part.id,'MAIN'),3);const final=r.inventoryReservations.consume(reservation.id,1,{sourceType:'test-consume',sourceId:'T1'},admin);assert.equal(final.status,'CONSUMED');assert.equal(final.remainingQuantity,0);assert.equal(r.inventory.getBalance(part.id,'MAIN'),2);}finally{r.close();}});

test('existing service_order is enriched instead of duplicated and waits for missing parts',()=>{const {r,customer,part}=setup();try{const svcProduct=r.catalog.createProduct({id:'S1',name:'Diagnostico',sku:'SERV-1',salePriceCents:3000,trackStock:false},admin);r.retail.setProductRetail(svcProduct.id,{productType:'SERVICE'},admin);const header=r.operations.createServiceOrder({id:'OS1',customerId:customer.id,number:'OS-1',title:'Reparo'},admin);const enriched=r.serviceOrders.updateOpen(header.id,{locationId:'MAIN',diagnosis:'Falha detectada',technicianUserId:'operator'},admin);assert.equal(enriched.id,header.id);r.serviceOrders.addLine(header.id,{lineType:'SERVICE',productId:svcProduct.id,quantity:1,unitPriceCents:3000},admin);r.serviceOrders.addLine(header.id,{lineType:'PART',productId:part.id,quantity:7,unitPriceCents:1200},admin);const approved=r.serviceOrders.approve(header.id,{},admin);assert.equal(approved.status,'WAITING_PARTS');assert.equal(approved.shortages.length,1);assert.equal(approved.shortages[0].productId,part.id);assert.throws(()=>r.serviceOrders.start(header.id,operator),/pe[cç]a|material|aguard/i);}finally{r.close();}});

test('service order completes with consumed parts only and a single receivable',()=>{const {r,customer,part}=setup();try{const svcProduct=r.catalog.createProduct({id:'S1',name:'Reparo',sku:'SERV-1',salePriceCents:3000,trackStock:false},admin);r.retail.setProductRetail(svcProduct.id,{productType:'SERVICE'},admin);r.operations.createServiceOrder({id:'OS1',customerId:customer.id,number:'OS-1',title:'Reparo'},admin);r.serviceOrders.updateOpen('OS1',{locationId:'MAIN',dueAt:'2026-09-30T12:00:00.000Z'},admin);r.serviceOrders.addLine('OS1',{lineType:'SERVICE',productId:svcProduct.id,quantity:1,unitPriceCents:3000},admin);const partLine=r.serviceOrders.addLine('OS1',{lineType:'PART',productId:part.id,quantity:2,unitPriceCents:1200},admin);assert.equal(r.serviceOrders.approve('OS1',{},admin).status,'APPROVED');assert.equal(r.serviceOrders.start('OS1',operator).status,'IN_PROGRESS');r.serviceOrders.consumePart('OS1',partLine.id,{quantity:1},operator);const completed=r.serviceOrders.complete('OS1',{idempotencyKey:'complete-1'},admin);assert.equal(completed.status,'COMPLETED');assert.equal(completed.serviceTotalCents,3000);assert.equal(completed.partsTotalCents,1200);assert.equal(completed.totalCents,4200);assert.ok(completed.receivableEntryId);const entries=r.finance.listEntries().filter(x=>x.sourceType==='service-order'&&x.sourceId==='OS1');assert.equal(entries.length,1);assert.equal(entries[0].amountCents,4200);const repeated=r.serviceOrders.complete('OS1',{idempotencyKey:'complete-1'},admin);assert.equal(repeated.receivableEntryId,completed.receivableEntryId);assert.equal(r.finance.listEntries().filter(x=>x.sourceType==='service-order'&&x.sourceId==='OS1').length,1);}finally{r.close();}});
