'use strict';const {randomUUID}=require('node:crypto');const {assertRole}=require('./auth/rbac');
function createOperationsSuite({db,now=()=>new Date().toISOString(),idFactory=p=>p+'-'+randomUUID()}={}){const cid=a=>String(a?.companyId||'default'),ts=()=>String(now()),manager=a=>assertRole(a,['admin','manager','director']);
 const parse=(v,d)=>{try{return JSON.parse(v||JSON.stringify(d))}catch{return d}},one=(sql,...x)=>db.prepare(sql).get(...x),all=(sql,...x)=>db.prepare(sql).all(...x);
 function createBranch(i={},a){manager(a);const id=String(i.id||idFactory('branch'));db.prepare('INSERT INTO company_branches(id,company_id,code,name,active,created_at,updated_at) VALUES(?,?,?,?,1,?,?)').run(id,cid(a),String(i.code||'').trim(),String(i.name||'').trim(),ts(),ts());return one('SELECT * FROM company_branches WHERE id=?',id)}
 const listBranches=a=>all('SELECT * FROM company_branches WHERE company_id=? AND active=1 ORDER BY name',cid(a));
 function saveDashboard(i={},a){const id=String(i.id||idFactory('dash'));db.prepare('INSERT INTO dashboard_layouts(id,company_id,user_id,name,layout_json,filters_json,is_default,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,layout_json=excluded.layout_json,filters_json=excluded.filters_json,is_default=excluded.is_default,updated_at=excluded.updated_at').run(id,cid(a),a?.userId||null,String(i.name||'Meu dashboard'),JSON.stringify(i.layout||[]),JSON.stringify(i.filters||{}),i.isDefault?1:0,ts());return getDashboard(id,a)}
 function getDashboard(id,a){const r=one('SELECT * FROM dashboard_layouts WHERE id=? AND company_id=?',String(id),cid(a));return r&&{...r,layout:parse(r.layout_json,[]),filters:parse(r.filters_json,{})}}
 const listDashboards=a=>all('SELECT id FROM dashboard_layouts WHERE company_id=? AND (user_id=? OR user_id IS NULL) ORDER BY is_default DESC,name',cid(a),a?.userId||'').map(x=>getDashboard(x.id,a));
 function createAlert(i={},a){const id=String(i.id||idFactory('alert'));db.prepare("INSERT INTO operational_alerts(id,company_id,entity_kind,entity_id,title,due_at,severity,status,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,'active',?,?)").run(id,cid(a),String(i.entityKind||'system'),String(i.entityId||'general'),String(i.title||'Alerta'),String(i.dueAt||ts()),String(i.severity||'info'),JSON.stringify(i.metadata||{}),ts());return one('SELECT * FROM operational_alerts WHERE id=?',id)}
 const listAlerts=a=>all("SELECT * FROM operational_alerts WHERE company_id=? AND status!='dismissed' ORDER BY COALESCE(snoozed_until,due_at),id",cid(a));
 function alertAction(id,action,i={},a){const r=one('SELECT * FROM operational_alerts WHERE id=? AND company_id=?',id,cid(a));if(!r)throw new Error('Alerta nao encontrado.');if(action==='ack')db.prepare("UPDATE operational_alerts SET status='acknowledged',acknowledged_at=?,acknowledged_by=? WHERE id=?").run(ts(),a.userId,id);else if(action==='snooze')db.prepare("UPDATE operational_alerts SET status='active',snoozed_until=? WHERE id=?").run(String(i.until),id);else if(action==='dismiss')db.prepare("UPDATE operational_alerts SET status='dismissed',dismissed_at=?,dismissed_by=?,dismiss_reason=? WHERE id=?").run(ts(),a.userId,String(i.reason||''),id);else throw new Error('Acao invalida.');return one('SELECT * FROM operational_alerts WHERE id=?',id)}
 function notify(i={},a){const id=String(i.id||idFactory('notification'));db.prepare("INSERT INTO notifications(id,company_id,title,body,priority,status,entity_kind,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,'unread',?,?,?,?)").run(id,cid(a),String(i.title||'Notificacao'),String(i.body||''),String(i.priority||'normal'),i.entityKind||null,i.entityId||null,JSON.stringify(i.metadata||{}),ts());return one('SELECT * FROM notifications WHERE id=?',id)}
 const notifications=a=>all("SELECT * FROM notifications WHERE company_id=? ORDER BY status='unread' DESC,created_at DESC",cid(a));
 function markRead(id,a){db.prepare("UPDATE notifications SET status='read',read_at=?,read_by=? WHERE id=? AND company_id=?").run(ts(),a.userId,id,cid(a));return one('SELECT * FROM notifications WHERE id=?',id)}
 function createPriceTable(i={},a){manager(a);const id=String(i.id||idFactory('price'));db.prepare('INSERT INTO price_tables(id,company_id,name,active,created_at,updated_at) VALUES(?,?,?,1,?,?)').run(id,cid(a),String(i.name||'Tabela'),ts(),ts());for(const x of i.items||[])db.prepare('INSERT INTO price_table_items(id,price_table_id,product_id,min_quantity,unit_price_cents,discount_percent) VALUES(?,?,?,?,?,?)').run(idFactory('price-item'),id,String(x.productId),Number(x.minQuantity||1),Number(x.unitPriceCents),Number(x.discountPercent||0));return price(id,a)}
 function price(id,a){const h=one('SELECT * FROM price_tables WHERE id=? AND company_id=?',id,cid(a));return h&&{...h,items:all('SELECT * FROM price_table_items WHERE price_table_id=? ORDER BY product_id,min_quantity DESC',id)}}
 function quotePrice(tableId,productId,qty,a){const t=price(tableId,a);if(!t)throw new Error('Tabela nao encontrada.');const x=t.items.filter(v=>v.product_id===String(productId)&&Number(v.min_quantity)<=Number(qty)).sort((a,b)=>b.min_quantity-a.min_quantity)[0];if(!x)throw new Error('Preco nao configurado.');return{unitPriceCents:Math.round(Number(x.unit_price_cents)*(1-Number(x.discount_percent)/100)),rule:x}}
 function createWorkflow(i={},a){manager(a);const id=String(i.id||idFactory('workflow')),states=[...new Set(i.states||[])],initial=String(i.initialState||states[0]||'OPEN');if(!states.includes(initial))states.unshift(initial);const def={states,transitions:i.transitions||[]};db.prepare('INSERT INTO workflow_definitions(id,company_id,name,initial_state,definition_json,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)').run(id,cid(a),String(i.name||id),initial,JSON.stringify(def),ts(),ts());return one('SELECT * FROM workflow_definitions WHERE id=?',id)}
 function startWorkflow(i={},a){const w=one('SELECT * FROM workflow_definitions WHERE id=? AND company_id=? AND active=1',String(i.workflowId),cid(a));if(!w)throw new Error('Workflow nao encontrado.');const id=String(i.id||idFactory('workflow-instance'));db.prepare('INSERT INTO workflow_instances(id,company_id,workflow_id,subject_kind,subject_id,state,data_json,history_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,cid(a),w.id,String(i.subjectKind),String(i.subjectId),w.initial_state,JSON.stringify(i.data||{}),'[]',ts(),ts());return one('SELECT * FROM workflow_instances WHERE id=?',id)}
 function transition(id,to,a){const x=one('SELECT * FROM workflow_instances WHERE id=? AND company_id=?',id,cid(a));if(!x)throw new Error('Fluxo nao encontrado.');const w=one('SELECT * FROM workflow_definitions WHERE id=?',x.workflow_id),d=parse(w.definition_json,{}),rule=(d.transitions||[]).find(t=>String(t.from)===x.state&&String(t.to)===String(to));if(!rule)throw new Error('Transicao nao permitida.');const h=parse(x.history_json,[]);h.push({from:x.state,to:String(to),actorId:a.userId,at:ts()});db.prepare('UPDATE workflow_instances SET state=?,history_json=?,updated_at=? WHERE id=?').run(String(to),JSON.stringify(h),ts(),id);return one('SELECT * FROM workflow_instances WHERE id=?',id)}
 function requestApproval(i={},a){const id=String(i.id||idFactory('approval')),steps=(i.steps||[]).map(s=>({approverIds:s.approverIds||[],minApprovals:Number(s.minApprovals||1),decisions:[]}));if(!steps.length)throw new Error('Etapas de aprovacao obrigatorias.');db.prepare("INSERT INTO generic_approvals(id,company_id,subject_kind,subject_id,requested_by,status,current_step,steps_json,history_json,created_at,updated_at) VALUES(?,?,?,?,?,'pending',0,?,'[]',?,?)").run(id,cid(a),String(i.subjectKind),String(i.subjectId),a.userId,JSON.stringify(steps),ts(),ts());return approval(id,a)}
 function approval(id,a){const r=one('SELECT * FROM generic_approvals WHERE id=? AND company_id=?',id,cid(a));return r&&{...r,steps:parse(r.steps_json,[]),history:parse(r.history_json,[])}}
 function decideApproval(id,decision,a){const r=approval(id,a);if(!r||r.status!=='pending')throw new Error('Aprovacao indisponivel.');const s=r.steps[r.current_step];if(s.approverIds.length&&!s.approverIds.includes(a.userId))throw new Error('Usuario nao autorizado.');if(s.decisions.some(d=>d.actorId===a.userId))throw new Error('Decisao duplicada.');s.decisions.push({actorId:a.userId,decision,at:ts()});let status='pending',step=r.current_step;if(decision==='rejected')status='rejected';else if(new Set(s.decisions.filter(d=>d.decision==='approved').map(d=>d.actorId)).size>=s.minApprovals){step++;if(step>=r.steps.length){status='approved';step=r.steps.length-1}}const h=[...r.history,{actorId:a.userId,decision,step:r.current_step,at:ts()}];db.prepare('UPDATE generic_approvals SET status=?,current_step=?,steps_json=?,history_json=?,updated_at=? WHERE id=?').run(status,step,JSON.stringify(r.steps),JSON.stringify(h),ts(),id);return approval(id,a)}
 function createAsset(i={},a){manager(a);const id=String(i.id||idFactory('asset'));db.prepare("INSERT INTO assets(id,company_id,branch_id,code,name,type,serial_number,meter_value,status,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?, 'ACTIVE',?,?,?)").run(id,cid(a),i.branchId||null,String(i.code),String(i.name),String(i.type||'EQUIPMENT'),i.serialNumber||null,Number(i.meterValue||0),JSON.stringify(i.metadata||{}),ts(),ts());return one('SELECT * FROM assets WHERE id=?',id)}
 const listAssets=a=>all('SELECT * FROM assets WHERE company_id=? ORDER BY name',cid(a));
 function createServiceOrder(i={},a){const id=String(i.id||idFactory('os')),number=String(i.number||Date.now());db.prepare("INSERT INTO service_orders(id,company_id,branch_id,asset_id,customer_id,number,title,description,status,priority,opened_at,due_at,history_json,created_by,updated_at) VALUES(?,?,?,?,?,?,?,?,'OPEN',?,?,?,?,?,?)").run(id,cid(a),i.branchId||null,i.assetId||null,i.customerId||null,number,String(i.title),String(i.description||''),String(i.priority||'NORMAL'),ts(),i.dueAt||null,'[]',a.userId,ts());return one('SELECT * FROM service_orders WHERE id=?',id)}
 function setServiceOrderStatus(id,status,a){const r=one('SELECT * FROM service_orders WHERE id=? AND company_id=?',id,cid(a));if(!r)throw new Error('OS nao encontrada.');const h=parse(r.history_json,[]);h.push({from:r.status,to:String(status),actorId:a.userId,at:ts()});db.prepare('UPDATE service_orders SET status=?,closed_at=?,history_json=?,updated_at=? WHERE id=?').run(String(status),String(status)==='CLOSED'?ts():null,JSON.stringify(h),ts(),id);return one('SELECT * FROM service_orders WHERE id=?',id)}
 const listServiceOrders=a=>all('SELECT * FROM service_orders WHERE company_id=? ORDER BY opened_at DESC',cid(a));
 function createMaintenancePlan(i={},a){manager(a);const id=String(i.id||idFactory('maintenance')),days=i.intervalDays==null?null:Number(i.intervalDays),meter=i.intervalMeter==null?null:Number(i.intervalMeter),next=days?new Date(Date.now()+days*86400000).toISOString():null;db.prepare('INSERT INTO maintenance_plans(id,company_id,asset_id,name,interval_days,interval_meter,last_done_at,last_meter,next_due_at,next_meter,active,created_at,updated_at) VALUES(?,?,?,?,?,?,NULL,NULL,?,?,1,?,?)').run(id,cid(a),String(i.assetId),String(i.name),days,meter,next,meter,ts(),ts());return one('SELECT * FROM maintenance_plans WHERE id=?',id)}
 function completeMaintenance(id,i={},a){const p=one('SELECT * FROM maintenance_plans WHERE id=? AND company_id=?',id,cid(a));if(!p)throw new Error('Plano nao encontrado.');const at=String(i.performedAt||ts()),mv=i.meterValue==null?null:Number(i.meterValue),next=p.interval_days?new Date(Date.parse(at)+Number(p.interval_days)*86400000).toISOString():null,nextMeter=p.interval_meter&&mv!=null?mv+Number(p.interval_meter):null;db.prepare('INSERT INTO maintenance_history(id,company_id,plan_id,service_order_id,performed_at,meter_value,notes,created_by) VALUES(?,?,?,?,?,?,?,?)').run(idFactory('mh'),cid(a),id,i.serviceOrderId||null,at,mv,i.notes||null,a.userId);db.prepare('UPDATE maintenance_plans SET last_done_at=?,last_meter=?,next_due_at=?,next_meter=?,updated_at=? WHERE id=?').run(at,mv,next,nextMeter,ts(),id);return one('SELECT * FROM maintenance_plans WHERE id=?',id)}
 const dueMaintenance=a=>all("SELECT p.*,a.name asset_name FROM maintenance_plans p JOIN assets a ON a.id=p.asset_id WHERE p.company_id=? AND p.active=1 AND ((p.next_due_at IS NOT NULL AND p.next_due_at<=?) OR (p.next_meter IS NOT NULL AND a.meter_value>=p.next_meter)) ORDER BY p.next_due_at",cid(a),ts());
 function createProject(i={},a){manager(a);const id=String(i.id||idFactory('project'));db.prepare("INSERT INTO projects(id,company_id,branch_id,code,name,status,start_date,end_date,created_at,updated_at) VALUES(?,?,?,?,?,'PLANNED',?,?,?,?)").run(id,cid(a),i.branchId||null,String(i.code),String(i.name),i.startDate||null,i.endDate||null,ts(),ts());return one('SELECT * FROM projects WHERE id=?',id)}
 function addTask(projectId,i={},a){const p=one('SELECT * FROM projects WHERE id=? AND company_id=?',projectId,cid(a));if(!p)throw new Error('Projeto nao encontrado.');if(String(i.startDate)>String(i.endDate))throw new Error('Periodo invalido.');const id=String(i.id||idFactory('task'));db.prepare('INSERT INTO project_tasks(id,project_id,name,start_date,end_date,progress,resource,depends_on,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,projectId,String(i.name),String(i.startDate),String(i.endDate),Number(i.progress||0),i.resource||null,i.dependsOn||null,ts(),ts());return one('SELECT * FROM project_tasks WHERE id=?',id)}
 function project(id,a){const p=one('SELECT * FROM projects WHERE id=? AND company_id=?',id,cid(a));return p&&{...p,tasks:all('SELECT * FROM project_tasks WHERE project_id=? ORDER BY start_date,id',id)}}
 const listProjects=a=>all('SELECT * FROM projects WHERE company_id=? ORDER BY name',cid(a));
 return{createBranch,listBranches,saveDashboard,getDashboard,listDashboards,createAlert,listAlerts,alertAction,notify,notifications,markRead,createPriceTable,price,quotePrice,createWorkflow,startWorkflow,transition,requestApproval,approval,decideApproval,createAsset,listAssets,createServiceOrder,setServiceOrderStatus,listServiceOrders,createMaintenancePlan,completeMaintenance,dueMaintenance,createProject,addTask,project,listProjects};}
module.exports={createOperationsSuite};