'use strict';
const {json}=require('../http-utils');const {pathMatch,requireActor,queryBool,dateRange,body,asHttpError}=require('../router-utils');
function createFinanceRouter({runtime,sessions,bodyLimitBytes=1024*1024}={}){return async function(req,res,url){if(!url.pathname.startsWith('/api/v1/finance/'))return false;try{const actor=requireActor(req,sessions,['admin','manager']);const p=url.pathname;let m;
 if(p==='/api/v1/finance/accounts'){if(req.method==='GET'){json(res,200,runtime.finance.listAccounts({includeInactive:queryBool(url,'includeInactive')}));return true;}if(req.method==='POST'){json(res,201,runtime.finance.createAccount(await body(req,bodyLimitBytes),actor));return true;}}
 if(p==='/api/v1/finance/entries'){if(req.method==='GET'){json(res,200,runtime.finance.listEntries({kind:url.searchParams.get('kind'),status:url.searchParams.get('status'),accountId:url.searchParams.get('accountId'),categoryId:url.searchParams.get('categoryId'),costCenterId:url.searchParams.get('costCenterId'),query:url.searchParams.get('query')}));return true;}if(req.method==='POST'){json(res,201,runtime.finance.createEntry(await body(req,bodyLimitBytes),actor));return true;}}
 if((m=pathMatch(p,'/api/v1/finance/entries/:id'))&&req.method==='GET'){const row=runtime.finance.getEntry(m.id);if(!row)throw new Error('Lancamento financeiro nao encontrado.');json(res,200,row);return true;}
 if((m=pathMatch(p,'/api/v1/finance/entries/:id/settle'))&&req.method==='POST'){json(res,200,runtime.finance.settleEntry(m.id,await body(req,bodyLimitBytes),actor));return true;}
 if((m=pathMatch(p,'/api/v1/finance/entries/:id/cancel'))&&req.method==='POST'){json(res,200,runtime.finance.cancelEntry(m.id,await body(req,bodyLimitBytes),actor));return true;}
 if((m=pathMatch(p,'/api/v1/finance/settlements/:id/reverse'))&&req.method==='POST'){const data=await body(req,bodyLimitBytes);json(res,200,runtime.finance.reverseSettlement(m.id,{reason:data.reason,actor}));return true;}
 if(p==='/api/v1/finance/summary'&&req.method==='GET'){json(res,200,runtime.finance.getSummary({asOf:url.searchParams.get('asOf')||undefined}));return true;}
 if(p==='/api/v1/finance/dre-groups'&&req.method==='GET'){json(res,200,runtime.financeDimensions.listDreGroups({includeInactive:queryBool(url,'includeInactive')}));return true;}
 if(p==='/api/v1/finance/categories'){if(req.method==='GET'){json(res,200,runtime.financeDimensions.listCategories({includeInactive:queryBool(url,'includeInactive')}));return true;}if(req.method==='POST'){json(res,201,runtime.financeDimensions.saveCategory(await body(req,bodyLimitBytes),actor));return true;}}
 if(p==='/api/v1/finance/cost-centers'){if(req.method==='GET'){json(res,200,runtime.financeDimensions.listCostCenters({includeInactive:queryBool(url,'includeInactive')}));return true;}if(req.method==='POST'){json(res,201,runtime.financeDimensions.saveCostCenter(await body(req,bodyLimitBytes),actor));return true;}}
 if((m=pathMatch(p,'/api/v1/finance/entries/:id/dimensions'))&&req.method==='PATCH'){json(res,200,runtime.financeDimensions.setEntryDimensions(m.id,await body(req,bodyLimitBytes),actor));return true;}
 const range=dateRange(url);if(p==='/api/v1/finance/dashboard'&&req.method==='GET'){json(res,200,runtime.financeManagement.dashboard(range));return true;}if(p==='/api/v1/finance/dre'&&req.method==='GET'){json(res,200,runtime.financeManagement.dre({...range,basis:url.searchParams.get('basis')||'accrual'}));return true;}if(p==='/api/v1/finance/cashflow'&&req.method==='GET'){json(res,200,runtime.financeManagement.cashflow({...range,projectionDays:Number(url.searchParams.get('projectionDays')||30)}));return true;}if(p==='/api/v1/finance/compare'&&req.method==='GET'){json(res,200,runtime.financeManagement.compare({...range,previousFrom:url.searchParams.get('previousFrom'),previousTo:url.searchParams.get('previousTo'),basis:url.searchParams.get('basis')||'accrual'}));return true;}
 if(p==='/api/v1/finance/statements/preview'&&req.method==='POST'){json(res,200,await runtime.bankStatements.preview(await body(req,bodyLimitBytes)));return true;}
 if(p==='/api/v1/finance/statements'){if(req.method==='GET'){json(res,200,runtime.bankStatements.listBatches({accountId:url.searchParams.get('accountId')}));return true;}if(req.method==='POST'){json(res,201,await runtime.bankStatements.commit(await body(req,bodyLimitBytes),actor));return true;}}
 if((m=pathMatch(p,'/api/v1/finance/statements/:id/commit'))&&req.method==='POST'){json(res,201,await runtime.bankStatements.commit({...(await body(req,bodyLimitBytes)),batchId:m.id},actor));return true;}
 if(p==='/api/v1/finance/statement-transactions'&&req.method==='GET'){json(res,200,runtime.bankStatements.listTransactions({accountId:url.searchParams.get('accountId'),batchId:url.searchParams.get('batchId'),matchStatus:url.searchParams.get('matchStatus')}));return true;}
 if((m=pathMatch(p,'/api/v1/finance/reconciliation/:transactionId/suggestions'))&&req.method==='GET'){const rows=await runtime.financeReconciliation.suggest({accountId:url.searchParams.get('accountId')});json(res,200,rows.filter(x=>x.transactionId===m.transactionId));return true;}
 if((m=pathMatch(p,'/api/v1/finance/reconciliation/:transactionId/accept'))&&req.method==='POST'){json(res,200,runtime.financeReconciliation.confirm({...(await body(req,bodyLimitBytes)),transactionId:m.transactionId},actor));return true;}
 if((m=pathMatch(p,'/api/v1/finance/reconciliation/:transactionId/reject'))&&req.method==='POST'){json(res,200,runtime.financeReconciliation.reject({...(await body(req,bodyLimitBytes)),transactionId:m.transactionId},actor));return true;}
 if((m=pathMatch(p,'/api/v1/finance/reconciliation/:transactionId/manual'))&&req.method==='POST'){json(res,200,runtime.financeReconciliation.manual({...(await body(req,bodyLimitBytes)),transactionId:m.transactionId},actor));return true;}
 if(p==='/api/v1/finance/transfers/suggestions'&&req.method==='GET'){json(res,200,await runtime.financeReconciliation.suggestTransfers());return true;}if(p==='/api/v1/finance/transfers/confirm'&&req.method==='POST'){json(res,200,runtime.financeReconciliation.confirmTransfer(await body(req,bodyLimitBytes),actor));return true;}
 if(p==='/api/v1/finance/recurrences'){if(req.method==='GET'){json(res,200,runtime.financeRecurrences.listRules({status:url.searchParams.get('status')}));return true;}if(req.method==='POST'){json(res,201,runtime.financeRecurrences.createRule(await body(req,bodyLimitBytes),actor));return true;}}
 if(p==='/api/v1/finance/recurrences/generate'&&req.method==='POST'){json(res,200,runtime.financeRecurrences.generateDue(await body(req,bodyLimitBytes),actor));return true;}if((m=pathMatch(p,'/api/v1/finance/recurrences/:id/status'))&&req.method==='PATCH'){const data=await body(req,bodyLimitBytes);json(res,200,runtime.financeRecurrences.setRuleStatus(m.id,data.status,actor));return true;}
 if(p==='/api/v1/finance/alerts'&&req.method==='GET'){json(res,200,runtime.financeAlerts.list({includeHidden:queryBool(url,'includeHidden')}));return true;}if((m=pathMatch(p,'/api/v1/finance/alerts/:key/read'))&&req.method==='POST'){json(res,200,runtime.financeAlerts.markRead(m.key));return true;}if((m=pathMatch(p,'/api/v1/finance/alerts/:key/hide'))&&req.method==='POST'){json(res,200,runtime.financeAlerts.hide(m.key));return true;}if((m=pathMatch(p,'/api/v1/finance/alerts/:key/unhide'))&&req.method==='POST'){json(res,200,runtime.financeAlerts.unhide(m.key));return true;}
 return false;}catch(error){throw asHttpError(error);}};}
module.exports={createFinanceRouter};
