'use strict';
const {json}=require('../http-utils');const {pathMatch,requireActor,queryBool,body,asHttpError}=require('../router-utils');
function createInventoryRouter({runtime,sessions,bodyLimitBytes=1024*1024}={}){
 async function flushEvents(){try{const result=await runtime.events.dispatchPending();if(result.failed)runtime.logger?.warn('events.dispatch.failed',{failed:result.failed});}catch(error){runtime.logger?.warn('events.dispatch.error',{message:error.message});}}
 return async function(req,res,url){if(!url.pathname.startsWith('/api/v1/inventory/'))return false;try{const actor=requireActor(req,sessions),p=url.pathname;
  if(p==='/api/v1/inventory/locations'){if(req.method==='GET'){json(res,200,runtime.inventory.listLocations({includeInactive:queryBool(url,'includeInactive')}));return true;}if(req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventory.createLocation(await body(req,bodyLimitBytes),actor));return true;}}
  if(p==='/api/v1/inventory/balance'&&req.method==='GET'){const productId=url.searchParams.get('productId'),locationId=url.searchParams.get('locationId');if(!productId||!locationId)throw new Error('productId e locationId obrigatorios.');const balance=runtime.inventory.getBalance(productId,locationId),available=runtime.inventoryLogistics.getAvailable(productId,locationId);json(res,200,{productId,locationId,balance,reserved:balance-available,available});return true;}
  if(p==='/api/v1/inventory/balances'&&req.method==='GET'){const rows=runtime.inventory.listBalances({productId:url.searchParams.get('productId'),locationId:url.searchParams.get('locationId')}).map(row=>{const available=runtime.inventoryLogistics.getAvailable(row.productId,row.locationId);return{...row,reserved:row.balance-available,available};});json(res,200,rows);return true;}
  if(p==='/api/v1/inventory/movements'){if(req.method==='GET'){json(res,200,runtime.inventory.listMovements({productId:url.searchParams.get('productId'),locationId:url.searchParams.get('locationId'),sourceType:url.searchParams.get('sourceType'),sourceId:url.searchParams.get('sourceId')}));return true;}if(req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventory.move(await body(req,bodyLimitBytes),actor));return true;}}
  if(p==='/api/v1/inventory/operations'&&req.method==='GET'){json(res,200,runtime.inventoryOperations.listOperations({productId:url.searchParams.get('productId'),locationId:url.searchParams.get('locationId'),type:url.searchParams.get('type')}));return true;}
  if(p==='/api/v1/inventory/adjustments'&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);const result=runtime.inventoryOperations.adjust(await body(req,bodyLimitBytes),actor);await flushEvents();json(res,201,result);return true;}
  if(p==='/api/v1/inventory/transfers'&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);const result=runtime.inventoryOperations.transfer(await body(req,bodyLimitBytes),actor);await flushEvents();json(res,201,result);return true;}
  if(p==='/api/v1/inventory/reservations'){if(req.method==='GET'){json(res,200,runtime.inventoryLogistics.listReservations({productId:url.searchParams.get('productId'),locationId:url.searchParams.get('locationId'),status:url.searchParams.get('status'),sourceType:url.searchParams.get('sourceType'),sourceId:url.searchParams.get('sourceId')}));return true;}if(req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventoryLogistics.reserve(await body(req,bodyLimitBytes),actor));return true;}}
  if(p==='/api/v1/inventory/lots'){if(req.method==='GET'){json(res,200,runtime.inventoryDepth.listLots({productId:url.searchParams.get('productId'),locationId:url.searchParams.get('locationId')}));return true;}if(req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventoryDepth.createLot(await body(req,bodyLimitBytes),actor));return true;}}
  if(p==='/api/v1/inventory/serials'){if(req.method==='GET'){json(res,200,runtime.inventoryDepth.listSerials({productId:url.searchParams.get('productId'),status:url.searchParams.get('status')}));return true;}if(req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventoryDepth.createSerial(await body(req,bodyLimitBytes),actor));return true;}}
  if(p==='/api/v1/inventory/positions'){if(req.method==='GET'){json(res,200,runtime.inventoryDepth.listPositions({productId:url.searchParams.get('productId'),locationId:url.searchParams.get('locationId')}));return true;}if(req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventoryDepth.receiveTracked(await body(req,bodyLimitBytes),actor));return true;}}
  if(p==='/api/v1/inventory/pick-plan'&&req.method==='GET'){json(res,200,runtime.inventoryDepth.recommendPick({productId:url.searchParams.get('productId'),locationId:url.searchParams.get('locationId'),quantity:url.searchParams.get('quantity'),strategy:url.searchParams.get('strategy')}));return true;}
  if(p==='/api/v1/inventory/cycle-counts'){if(req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventoryDepth.startCycleCount(await body(req,bodyLimitBytes),actor));return true;}}
  if(p==='/api/v1/inventory/losses'&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,201,runtime.inventoryDepth.recordLoss(await body(req,bodyLimitBytes),actor));return true;}
  if(p==='/api/v1/inventory/analytics'&&req.method==='GET'){json(res,200,runtime.inventoryDepth.analytics({from:url.searchParams.get('from'),to:url.searchParams.get('to')}));return true;}
  if(p==='/api/v1/inventory/replenishment'&&req.method==='GET'){json(res,200,runtime.inventoryDepth.replenishment());return true;}
  let m;if((m=pathMatch(p,'/api/v1/inventory/cycle-counts/:id'))&&req.method==='GET'){json(res,200,runtime.inventoryDepth.getCycle(m.id));return true;}
  if((m=pathMatch(p,'/api/v1/inventory/cycle-counts/:id/count'))&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,200,runtime.inventoryDepth.count({...(await body(req,bodyLimitBytes)),cycleCountId:m.id},actor));return true;}
  if((m=pathMatch(p,'/api/v1/inventory/cycle-counts/:id/close'))&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,200,runtime.inventoryDepth.closeCycle(m.id,actor));return true;}
  if((m=pathMatch(p,'/api/v1/inventory/operations/:id/reverse'))&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);const result=runtime.inventoryOperations.reverse(m.id,await body(req,bodyLimitBytes),actor);await flushEvents();json(res,201,result);return true;}
  if((m=pathMatch(p,'/api/v1/inventory/reservations/:id/release'))&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);json(res,200,runtime.inventoryLogistics.release(m.id,actor));return true;}
  if((m=pathMatch(p,'/api/v1/inventory/reservations/:id/consume'))&&req.method==='POST'){requireActor(req,sessions,['admin','manager']);const data=await body(req,bodyLimitBytes);json(res,200,runtime.inventoryLogistics.consume(m.id,actor,{quantity:data.quantity??null}));return true;}
  return false;
 }catch(error){throw asHttpError(error);}};
}
module.exports={createInventoryRouter};
