'use strict';
function businessDate(value,label='data'){const text=String(value||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(text))throw new Error(`${label} invalida.`);const date=new Date(`${text}T00:00:00.000Z`);if(!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==text)throw new Error(`${label} invalida.`);return text;}
function createReportingService({db}={}){
 if(!db)throw new TypeError('Database is required.');
 function range(from,to){const a=businessDate(from,'Data inicial'),b=businessDate(to,'Data final');if(a>b)throw new Error('Data inicial nao pode ser posterior a data final.');return[a,b];}
 function buildSalesSummary({from,to,basis='accrual'}={}){const[a,b]=range(from,to);let revenue=0,cost=0,count=0;if(basis==='accrual'){const rows=db.prepare(`SELECT total_cents,total_cost_cents FROM sales_admin_invoices WHERE substr(created_at,1,10)>=? AND substr(created_at,1,10)<=?`).all(a,b);for(const row of rows){revenue+=Number(row.total_cents);cost+=Number(row.total_cost_cents);count++;}}else if(basis==='cash'){const rows=db.prepare(`SELECT i.total_cents,i.total_cost_cents,fs.amount_cents FROM sales_admin_invoices i JOIN financial_settlements fs ON fs.entry_id=i.receivable_entry_id WHERE fs.reversed_at IS NULL AND substr(fs.created_at,1,10)>=? AND substr(fs.created_at,1,10)<=?`).all(a,b);for(const row of rows){const paid=Number(row.amount_cents),total=Number(row.total_cents),totalCost=Number(row.total_cost_cents);revenue+=paid;cost+=total>0?Math.round(paid*totalCost/total):0;count++;}}else throw new Error('Base de vendas deve ser cash ou accrual.');return{basis,from:a,to:b,invoiceOrSettlementCount:count,netSalesCents:revenue,estimatedCostCents:cost,estimatedMarginCents:revenue-cost};}
 function buildPurchaseSummary({from,to}={}){const[a,b]=range(from,to);const row=db.prepare(`SELECT COUNT(*) count,COALESCE(SUM(total_cents),0) total FROM purchase_receipts WHERE substr(received_at,1,10)>=? AND substr(received_at,1,10)<=?`).get(a,b);return{from:a,to:b,receipts:Number(row?.count||0),receivedCents:Number(row?.total||0)};}
 function buildInventorySummary(){const products=Number(db.prepare('SELECT COUNT(*) n FROM products WHERE active=1').get()?.n||0);const row=db.prepare('SELECT COALESCE(SUM(delta_qty),0) qty FROM inventory_movements').get();const reserved=Number(db.prepare("SELECT COALESCE(SUM(quantity),0) qty FROM inventory_reservations WHERE status='ACTIVE'").get()?.qty||0);return{products,totalQuantity:Number(row?.qty||0),reservedQuantity:reserved,availableQuantity:Number(row?.qty||0)-reserved};}
 function listSalesInvoices({from,to}={}){const[a,b]=range(from,to);return db.prepare('SELECT * FROM sales_admin_invoices WHERE substr(created_at,1,10)>=? AND substr(created_at,1,10)<=? ORDER BY created_at,id').all(a,b).map(row=>({id:row.id,orderId:row.order_id,totalCents:Number(row.total_cents),totalCostCents:Number(row.total_cost_cents),receivableEntryId:row.receivable_entry_id,createdAt:row.created_at}));}
 return{buildSalesSummary,buildPurchaseSummary,buildInventorySummary,listSalesInvoices};
}
module.exports={createReportingService,businessDate};
