'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertCents}=require('../shared/money');

function createFinanceService({db,dimensions=null,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
  if(!db)throw new TypeError('Database is required.');
  const mapAccount=r=>r&&({id:r.id,name:r.name,type:r.type,ownership:r.ownership,active:Boolean(r.active),createdAt:r.created_at,updatedAt:r.updated_at});
  function normalizeAccount(input={},current=null){const name=input.name===undefined?current?.name:String(input.name||'').trim(),type=String(input.type===undefined?(current?.type||'OTHER'):input.type).toUpperCase(),ownership=String(input.ownership===undefined?(current?.ownership||'business'):input.ownership);if(!name)throw new Error('Nome da conta obrigatorio.');if(!['BANK','CARD','CASH','OTHER'].includes(type))throw new Error('Tipo de conta invalido.');if(!['business','personal'].includes(ownership))throw new Error('Propriedade da conta invalida.');return{name,type,ownership};}
  function createAccount(input={},actor=null){const id=String(input.id||idFactory('acct')),n=normalizeAccount(input),ts=now();db.prepare('INSERT INTO financial_accounts(id,name,type,ownership,active,created_at,updated_at) VALUES(?,?,?,?,1,?,?)').run(id,n.name,n.type,n.ownership,ts,ts);writeAudit(db,{action:'finance.account.create',entity:'financial-account',entityId:id,actor,context:{type:n.type,ownership:n.ownership}},now);return getAccount(id);}
  function getAccount(id){return mapAccount(db.prepare('SELECT * FROM financial_accounts WHERE id=?').get(String(id)));}
  function listAccounts({includeInactive=false}={}){return db.prepare(`SELECT * FROM financial_accounts${includeInactive?'':' WHERE active=1'} ORDER BY name,id`).all().map(mapAccount);}
  function updateAccount(id,input={},actor=null){const current=getAccount(id);if(!current)throw new Error('Conta financeira nao encontrada.');const n=normalizeAccount(input,current),ts=String(now());db.prepare('UPDATE financial_accounts SET name=?,type=?,ownership=?,updated_at=? WHERE id=?').run(n.name,n.type,n.ownership,ts,current.id);writeAudit(db,{action:'finance.account.update',entity:'financial-account',entityId:current.id,actor,context:{before:{name:current.name,type:current.type,ownership:current.ownership},after:n}},now);return getAccount(current.id);}
  function setAccountActive(id,active,actor=null){const current=getAccount(id);if(!current)throw new Error('Conta financeira nao encontrada.');db.prepare('UPDATE financial_accounts SET active=?,updated_at=? WHERE id=?').run(active?1:0,String(now()),current.id);writeAudit(db,{action:'finance.account.active',entity:'financial-account',entityId:current.id,actor,context:{active:Boolean(active)}},now);return getAccount(current.id);}
  function activeSettlements(entryId){return db.prepare('SELECT * FROM financial_settlements WHERE entry_id=? AND reversed_at IS NULL ORDER BY created_at,id').all(String(entryId));}
  function mapSettlement(r){return r&&({id:r.id,entryId:r.entry_id,amountCents:Number(r.amount_cents),method:r.method,note:r.note,createdBy:r.created_by,createdAt:r.created_at,reversedAt:r.reversed_at,reversalReason:r.reversal_reason});}
  function adjustmentTotal(entryId){return Number(db.prepare('SELECT COALESCE(SUM(delta_cents),0) total FROM financial_entry_adjustments WHERE entry_id=?').get(String(entryId))?.total||0);}
  function listAdjustments(entryId){return db.prepare('SELECT * FROM financial_entry_adjustments WHERE entry_id=? ORDER BY created_at,id').all(String(entryId)).map(r=>({id:r.id,entryId:r.entry_id,deltaCents:Number(r.delta_cents),reason:r.reason,sourceType:r.source_type,sourceId:r.source_id,idempotencyKey:r.idempotency_key,createdBy:r.created_by,createdAt:r.created_at}));}
  function effectiveAmount(row){return Number(row.amount_cents)+adjustmentTotal(row.id);}
  function mapEntry(row,asOf=now()){
    if(!row)return null;
    const settlements=activeSettlements(row.id).map(mapSettlement),settledCents=settlements.reduce((s,x)=>s+x.amountCents,0),baseAmountCents=Number(row.amount_cents),adjustmentCents=adjustmentTotal(row.id),effectiveAmountCents=baseAmountCents+adjustmentCents,openCents=Math.max(effectiveAmountCents-settledCents,0),dims=dimensions?.getEntryDimensions?.(row.id)||null;
    return{id:row.id,kind:row.kind,description:row.description,category:row.category,categoryId:dims?.categoryId||null,costCenterId:dims?.costCenterId||null,competencyDate:dims?.competencyDate||null,accountId:row.account_id,baseAmountCents,adjustmentCents,effectiveAmountCents,amountCents:effectiveAmountCents,dueAt:row.due_at,status:row.status,sourceType:row.source_type,sourceId:row.source_id,notes:row.notes,cancelReason:row.cancel_reason,createdAt:row.created_at,updatedAt:row.updated_at,cancelledAt:row.cancelled_at,settledCents,openCents,isOverdue:['OPEN','PARTIAL'].includes(row.status)&&Date.parse(row.due_at)<Date.parse(asOf),settlements,adjustments:listAdjustments(row.id)};
  }
  function getEntry(id,{asOf}={}){return mapEntry(db.prepare('SELECT * FROM financial_entries WHERE id=?').get(String(id)),asOf||now());}
  function validateAccountForEntry(accountId){if(!accountId)return null;const account=getAccount(accountId);if(!account)throw new Error('Conta financeira nao encontrada.');if(!account.active)throw new Error('Conta financeira inativa.');return account.id;}
  function createEntry(input={},actor=null){const kind=String(input.kind||'').toUpperCase();if(!['PAYABLE','RECEIVABLE'].includes(kind))throw new Error('Tipo de lancamento invalido.');const description=String(input.description||'').trim();if(!description)throw new Error('Descricao obrigatoria.');const amountCents=assertCents(input.amountCents,'amountCents');if(amountCents<=0)throw new Error('Valor do lancamento deve ser maior que zero.');const dueAt=String(input.dueAt||'').trim();if(!dueAt||!Number.isFinite(Date.parse(dueAt)))throw new Error('Vencimento invalido.');const accountId=validateAccountForEntry(input.accountId);if(dimensions)dimensions.validateEntryDimensions(input,kind);const id=String(input.id||idFactory('fin')),ts=now();return withTransaction(db,()=>{db.prepare("INSERT INTO financial_entries(id,kind,description,category,account_id,amount_cents,due_at,status,source_type,source_id,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'OPEN',?,?,?,?,?)").run(id,kind,description,input.category||null,accountId,amountCents,dueAt,input.sourceType||null,input.sourceId||null,input.notes||null,ts,ts);if(dimensions&&(input.categoryId||input.costCenterId||input.competencyDate))dimensions.setEntryDimensions(id,input,actor);writeAudit(db,{action:'finance.entry.create',entity:'financial-entry',entityId:id,actor,context:{kind,amountCents,dueAt,sourceType:input.sourceType||null,sourceId:input.sourceId||null}},now);return getEntry(id);});}
  function updateEntry(id,input={},actor=null){const raw=db.prepare('SELECT * FROM financial_entries WHERE id=?').get(String(id));if(!raw)throw new Error('Lancamento financeiro nao encontrado.');const current=getEntry(raw.id);if(current.status==='CANCELLED')throw new Error('Lancamento cancelado nao pode ser editado.');if(current.settledCents>0)throw new Error('Lancamento com baixa ativa nao pode ser editado.');const description=input.description===undefined?current.description:String(input.description||'').trim();if(!description)throw new Error('Descricao obrigatoria.');const dueAt=input.dueAt===undefined?current.dueAt:String(input.dueAt||'').trim();if(!dueAt||!Number.isFinite(Date.parse(dueAt)))throw new Error('Vencimento invalido.');const accountId=input.accountId===undefined?current.accountId:validateAccountForEntry(input.accountId);const baseAmountCents=input.amountCents===undefined?current.baseAmountCents:assertCents(input.amountCents,'amountCents');if(baseAmountCents<=0)throw new Error('Valor do lancamento deve ser maior que zero.');const projected=baseAmountCents+current.adjustmentCents;if(projected<=0)throw new Error('Valor efetivo do lancamento deve ser positivo.');const category=input.category===undefined?raw.category:(String(input.category||'').trim()||null),notes=input.notes===undefined?raw.notes:(String(input.notes||'').trim()||null);const dimensionInput={categoryId:input.categoryId===undefined?current.categoryId:input.categoryId,costCenterId:input.costCenterId===undefined?current.costCenterId:input.costCenterId,competencyDate:input.competencyDate===undefined?current.competencyDate:input.competencyDate};if(dimensions)dimensions.validateEntryDimensions(dimensionInput,current.kind);return withTransaction(db,()=>{db.prepare('UPDATE financial_entries SET description=?,category=?,account_id=?,amount_cents=?,due_at=?,notes=?,updated_at=? WHERE id=?').run(description,category,accountId,baseAmountCents,dueAt,notes,String(now()),raw.id);if(dimensions&&(input.categoryId!==undefined||input.costCenterId!==undefined||input.competencyDate!==undefined))dimensions.setEntryDimensions(raw.id,dimensionInput,actor);writeAudit(db,{action:'finance.entry.update',entity:'financial-entry',entityId:raw.id,actor,context:{before:{description:current.description,baseAmountCents:current.baseAmountCents,dueAt:current.dueAt,accountId:current.accountId},after:{description,baseAmountCents,dueAt,accountId}}},now);return getEntry(raw.id);});}
  function refreshStatus(id){const row=db.prepare('SELECT * FROM financial_entries WHERE id=?').get(String(id));if(!row||row.status==='CANCELLED')return;const settled=activeSettlements(id).reduce((s,r)=>s+Number(r.amount_cents),0),amount=effectiveAmount(row),status=settled<=0?'OPEN':settled>=amount?'SETTLED':'PARTIAL';db.prepare('UPDATE financial_entries SET status=?,updated_at=? WHERE id=?').run(status,now(),String(id));}
  function adjustEntry(id,input={},actor=null){const row=db.prepare('SELECT * FROM financial_entries WHERE id=?').get(String(id));if(!row)throw new Error('Lancamento financeiro nao encontrado.');if(row.status==='CANCELLED')throw new Error('Lancamento cancelado.');const key=String(input.idempotencyKey||'').trim();if(!key)throw new Error('Chave de idempotencia obrigatoria no ajuste.');const previous=db.prepare('SELECT * FROM financial_entry_adjustments WHERE idempotency_key=?').get(key);if(previous){if(previous.entry_id!==row.id)throw new Error('Chave de idempotencia pertence a outro lancamento.');return getEntry(row.id);}const deltaCents=input.deltaCents!==undefined?assertCents(input.deltaCents,'deltaCents'):(String(input.kind||'').toUpperCase()==='CREDIT'?-assertCents(input.amountCents,'amountCents'):assertCents(input.amountCents,'amountCents'));if(deltaCents===0)throw new Error('Ajuste nao pode ser zero.');const reason=String(input.reason||'').trim();if(!reason)throw new Error('Motivo do ajuste obrigatorio.');const current=effectiveAmount(row),settled=activeSettlements(row.id).reduce((s,r)=>s+Number(r.amount_cents),0),projected=current+deltaCents;if(projected<=0)throw new Error('Ajuste tornaria o lancamento sem valor positivo.');if(projected<settled)throw new Error('Ajuste excede o saldo financeiro disponivel.');return withTransaction(db,()=>{const again=db.prepare('SELECT * FROM financial_entry_adjustments WHERE idempotency_key=?').get(key);if(again)return getEntry(row.id);const aid=String(input.id||idFactory('fin-adj')),ts=String(now());db.prepare('INSERT INTO financial_entry_adjustments(id,entry_id,delta_cents,reason,source_type,source_id,idempotency_key,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(aid,row.id,deltaCents,reason,input.sourceType||null,input.sourceId||null,key,actor?.userId||null,ts);refreshStatus(row.id);writeAudit(db,{action:'finance.entry.adjust',entity:'financial-entry',entityId:row.id,actor,context:{adjustmentId:aid,deltaCents,reason,sourceType:input.sourceType||null,sourceId:input.sourceId||null}},now);return getEntry(row.id);});}
  function settleEntry(id,input={},actor=null){const entry=getEntry(id);if(!entry)throw new Error('Lancamento financeiro nao encontrado.');if(entry.status==='CANCELLED')throw new Error('Lancamento cancelado.');const amountCents=assertCents(input.amountCents,'amountCents');if(amountCents<=0)throw new Error('Valor de baixa invalido.');if(amountCents>entry.openCents)throw new Error('Valor de baixa excede saldo em aberto.');return withTransaction(db,()=>{const settlementId=String(input.id||idFactory('settlement')),ts=now();db.prepare('INSERT INTO financial_settlements(id,entry_id,amount_cents,method,note,created_by,created_at) VALUES(?,?,?,?,?,?,?)').run(settlementId,entry.id,amountCents,input.method||null,input.note||null,actor?.userId||null,ts);refreshStatus(entry.id);writeAudit(db,{action:'finance.entry.settle',entity:'financial-entry',entityId:entry.id,actor,context:{settlementId,amountCents,method:input.method||null}},now);return{entry:getEntry(entry.id),settlement:mapSettlement(db.prepare('SELECT * FROM financial_settlements WHERE id=?').get(settlementId))};});}
  function reverseSettlement(settlementId,{reason,actor}={}){const row=db.prepare('SELECT * FROM financial_settlements WHERE id=?').get(String(settlementId));if(!row)throw new Error('Baixa financeira nao encontrada.');if(row.reversed_at)return{entry:getEntry(row.entry_id),settlement:mapSettlement(row)};const text=String(reason||'').trim();if(!text)throw new Error('Motivo do estorno obrigatorio.');return withTransaction(db,()=>{db.prepare('UPDATE financial_settlements SET reversed_at=?,reversal_reason=?,reversed_by=? WHERE id=?').run(now(),text,actor?.userId||null,row.id);refreshStatus(row.entry_id);writeAudit(db,{action:'finance.settlement.reverse',entity:'financial-settlement',entityId:row.id,actor,context:{reason:text}},now);return{entry:getEntry(row.entry_id),settlement:mapSettlement(db.prepare('SELECT * FROM financial_settlements WHERE id=?').get(row.id))};});}
  function cancelEntry(id,{reason}={},actor=null){const entry=getEntry(id);if(!entry)throw new Error('Lancamento financeiro nao encontrado.');const text=String(reason||'').trim();if(!text)throw new Error('Motivo do cancelamento obrigatorio.');if(entry.settledCents>0)throw new Error('Lancamento com baixa ativa nao pode ser cancelado.');if(entry.status==='CANCELLED')return entry;db.prepare("UPDATE financial_entries SET status='CANCELLED',cancel_reason=?,cancelled_at=?,updated_at=? WHERE id=?").run(text,now(),now(),entry.id);writeAudit(db,{action:'finance.entry.cancel',entity:'financial-entry',entityId:entry.id,actor,context:{reason:text}},now);return getEntry(entry.id);}
  function listEntries(filters={}){const clauses=[],params=[];if(filters.kind){clauses.push('kind=?');params.push(String(filters.kind).toUpperCase());}if(filters.status){clauses.push('status=?');params.push(String(filters.status).toUpperCase());}if(filters.accountId){clauses.push('account_id=?');params.push(String(filters.accountId));}if(filters.query){clauses.push('LOWER(description) LIKE ?');params.push(`%${String(filters.query).toLowerCase()}%`);}return db.prepare(`SELECT * FROM financial_entries${clauses.length?` WHERE ${clauses.join(' AND ')}`:''} ORDER BY due_at,id`).all(...params).map(r=>mapEntry(r,filters.asOf||now())).filter(e=>filters.categoryId?e.categoryId===String(filters.categoryId):true).filter(e=>filters.costCenterId?e.costCenterId===String(filters.costCenterId):true).filter(e=>filters.overdue===true?e.isOverdue:true);}
  function getSummary({asOf=now()}={}){const result={receivableOpenCents:0,payableOpenCents:0,receivableSettledCents:0,payableSettledCents:0,overdueReceivableCents:0,overduePayableCents:0};for(const e of listEntries({asOf})){if(e.status==='CANCELLED')continue;result[e.kind==='RECEIVABLE'?'receivableOpenCents':'payableOpenCents']+=e.openCents;result[e.kind==='RECEIVABLE'?'receivableSettledCents':'payableSettledCents']+=e.settledCents;if(e.isOverdue)result[e.kind==='RECEIVABLE'?'overdueReceivableCents':'overduePayableCents']+=e.openCents;}return result;}
  return{createAccount,getAccount,listAccounts,updateAccount,setAccountActive,createEntry,getEntry,listEntries,updateEntry,adjustEntry,listAdjustments,settleEntry,reverseSettlement,cancelEntry,getSummary};
}
module.exports={createFinanceService};
