'use strict';
module.exports={id:'010-finance',up(db){db.exec(`
CREATE TABLE IF NOT EXISTS financial_accounts(id TEXT PRIMARY KEY,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('BANK','CARD','CASH','OTHER')),ownership TEXT NOT NULL DEFAULT 'business' CHECK(ownership IN ('business','personal')),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS financial_entries(id TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('PAYABLE','RECEIVABLE')),description TEXT NOT NULL,category TEXT,account_id TEXT REFERENCES financial_accounts(id),amount_cents INTEGER NOT NULL CHECK(amount_cents>0),due_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('OPEN','PARTIAL','SETTLED','CANCELLED')),source_type TEXT,source_id TEXT,notes TEXT,cancel_reason TEXT,cancelled_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_financial_entries_kind_status_due ON financial_entries(kind,status,due_at);CREATE INDEX IF NOT EXISTS idx_financial_entries_source ON financial_entries(source_type,source_id);
CREATE TABLE IF NOT EXISTS financial_settlements(id TEXT PRIMARY KEY,entry_id TEXT NOT NULL REFERENCES financial_entries(id) ON DELETE CASCADE,amount_cents INTEGER NOT NULL CHECK(amount_cents>0),method TEXT,note TEXT,created_by TEXT,created_at TEXT NOT NULL,reversed_at TEXT,reversal_reason TEXT,reversed_by TEXT);
CREATE INDEX IF NOT EXISTS idx_financial_settlements_entry ON financial_settlements(entry_id,created_at);
CREATE TABLE IF NOT EXISTS finance_dre_groups(id TEXT PRIMARY KEY,name TEXT NOT NULL,nature TEXT NOT NULL CHECK(nature IN ('REVENUE','COST','EXPENSE','OTHER')),sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS financial_categories(id TEXT PRIMARY KEY,name TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('INCOME','EXPENSE','BOTH')),dre_group_id TEXT REFERENCES finance_dre_groups(id),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cost_centers(id TEXT PRIMARY KEY,name TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS financial_entry_dimensions(entry_id TEXT PRIMARY KEY REFERENCES financial_entries(id) ON DELETE CASCADE,category_id TEXT REFERENCES financial_categories(id),cost_center_id TEXT REFERENCES cost_centers(id),competency_date TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_financial_dimensions_category ON financial_entry_dimensions(category_id);CREATE INDEX IF NOT EXISTS idx_financial_dimensions_center ON financial_entry_dimensions(cost_center_id);CREATE INDEX IF NOT EXISTS idx_financial_dimensions_competency ON financial_entry_dimensions(competency_date);
`);const now='1970-01-01T00:00:00.000Z';const group=db.prepare('INSERT OR IGNORE INTO finance_dre_groups(id,name,nature,sort_order,active,created_at,updated_at) VALUES(?,?,?,?,1,?,?)');for(const row of [['REVENUE','Receitas','REVENUE',10],['COGS','Custos','COST',20],['OPERATING_EXPENSE','Despesas operacionais','EXPENSE',30],['OTHER_RESULT','Outros resultados','OTHER',40]])group.run(...row,now,now);const cat=db.prepare('INSERT OR IGNORE INTO financial_categories(id,name,kind,dre_group_id,active,created_at,updated_at) VALUES(?,?,?,?,1,?,?)');for(const row of [['SALES','Vendas','INCOME','REVENUE'],['PURCHASES','Compras e mercadorias','EXPENSE','COGS'],['FEES','Taxas e tarifas','EXPENSE','OPERATING_EXPENSE'],['PAYROLL','Pessoal e folha','EXPENSE','OPERATING_EXPENSE'],['RENT','Aluguel','EXPENSE','OPERATING_EXPENSE'],['UTILITIES','Contas e utilidades','EXPENSE','OPERATING_EXPENSE'],['OTHER','Outros','BOTH','OTHER_RESULT']])cat.run(...row,now,now);}};
