'use strict';
const {randomUUID}=require('node:crypto');

function createTraceabilityService({db,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db)throw new TypeError('db is required.');
 const company=(input={},actor=null)=>{const requested=input.companyId==null?null:String(input.companyId),fromActor=actor?.companyId==null?null:String(actor.companyId);if(requested&&fromActor&&requested!==fromActor)throw new Error('Empresa divergente.');return requested||fromActor||'default';};
 function link(input={},actor=null){const companyId=company(input,actor),fromType=String(input.fromType||'').trim(),fromId=String(input.fromId||'').trim(),toType=String(input.toType||'').trim(),toId=String(input.toId||'').trim(),relationType=String(input.relationType||'').trim();if(!fromType||!fromId||!toType||!toId||!relationType)throw new Error('Vinculo de rastreabilidade incompleto.');const existing=db.prepare('SELECT * FROM traceability_links WHERE company_id=? AND from_type=? AND from_id=? AND to_type=? AND to_id=? AND relation_type=?').get(companyId,fromType,fromId,toType,toId,relationType);if(existing)return mapLink(existing);const id=String(input.id||idFactory('trace-link'));db.prepare('INSERT INTO traceability_links(id,company_id,from_type,from_id,to_type,to_id,relation_type,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,companyId,fromType,fromId,toType,toId,relationType,input.metadata==null?null:JSON.stringify(input.metadata),String(now()));return mapLink(db.prepare('SELECT * FROM traceability_links WHERE id=?').get(id));}
 const mapLink=row=>row&&({id:row.id,companyId:row.company_id,fromType:row.from_type,fromId:row.from_id,toType:row.to_type,toId:row.to_id,relationType:row.relation_type,metadata:row.metadata_json?JSON.parse(row.metadata_json):null,createdAt:row.created_at});
 function procurementProvenance(layer){if(!layer?.purchase_order_id)return null;const source=db.prepare('SELECT * FROM purchase_order_sources WHERE order_id=?').get(layer.purchase_order_id);if(!source)return{purchaseOrderId:layer.purchase_order_id,purchaseReceiptId:layer.purchase_receipt_id||null,supplierId:layer.supplier_id||null};const award=db.prepare('SELECT * FROM procurement_awards WHERE id=?').get(source.award_id);const items=db.prepare('SELECT * FROM procurement_award_items WHERE award_id=? AND product_id=? ORDER BY created_at,id').all(source.award_id,layer.product_id);return{purchaseOrderId:layer.purchase_order_id,purchaseReceiptId:layer.purchase_receipt_id||null,supplierId:layer.supplier_id||source.supplier_id||null,awardId:source.award_id,requisitionId:award?.requisition_id||null,quotationIds:[...new Set(items.map(x=>x.quotation_id).filter(Boolean))]};}
 function traceSource({type,id,companyId='default'}={}){const sourceType=String(type||''),sourceId=String(id||''),cid=String(companyId);const outgoing=db.prepare('SELECT * FROM traceability_links WHERE company_id=? AND from_type=? AND from_id=? ORDER BY created_at,id').all(cid,sourceType,sourceId).map(mapLink),incoming=db.prepare('SELECT * FROM traceability_links WHERE company_id=? AND to_type=? AND to_id=? ORDER BY created_at,id').all(cid,sourceType,sourceId).map(mapLink),layers=db.prepare('SELECT * FROM inventory_cost_layers WHERE company_id=? AND source_type=? AND source_id=? ORDER BY received_at,id').all(cid,sourceType.toLowerCase().replaceAll('_','-'),sourceId),allocations=db.prepare('SELECT * FROM inventory_cost_allocations WHERE company_id=? AND destination_type=? AND destination_id=? ORDER BY allocated_at,id').all(cid,sourceType,sourceId),facts=db.prepare('SELECT * FROM commercial_facts WHERE company_id=? AND source_type=? AND source_id=? ORDER BY occurred_at,id').all(cid,sourceType,sourceId);return{source:{type:sourceType,id:sourceId,companyId:cid},outgoing,incoming,layers:layers.map(row=>({...row,provenance:procurementProvenance(row)})),allocations,facts};}
 function traceProduct({productId,companyId='default'}={}){const pid=String(productId),cid=String(companyId),layers=db.prepare('SELECT * FROM inventory_cost_layers WHERE company_id=? AND product_id=? ORDER BY received_at,id').all(cid,pid);return{productId:pid,companyId:cid,layers:layers.map(row=>{const balances=db.prepare('SELECT location_id,available_quantity FROM inventory_cost_layer_balances WHERE company_id=? AND layer_id=? ORDER BY location_id').all(cid,row.id);return{...row,availableQuantity:balances.reduce((s,x)=>s+Number(x.available_quantity),0),balances,provenance:procurementProvenance(row)};}),allocations:db.prepare('SELECT * FROM inventory_cost_allocations WHERE company_id=? AND product_id=? ORDER BY allocated_at,id').all(cid,pid),facts:db.prepare('SELECT * FROM commercial_facts WHERE company_id=? AND product_id=? ORDER BY occurred_at,id').all(cid,pid)};}
 return{link,traceSource,traceProduct};
}
module.exports={createTraceabilityService};
