'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const {assertRole}=require('../auth/rbac');
const SAFE_EXT=new Set(['.pdf','.png','.jpg','.jpeg','.webp','.txt','.csv','.xml','.xlsx','.docx']);
function createDocumentService({db,storageDir,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`,maxBytes=10*1024*1024}={}){
 if(!db)throw new TypeError('Database is required.');if(!storageDir)throw new TypeError('storageDir is required.');fs.mkdirSync(storageDir,{recursive:true});
 const map=row=>row&&({id:row.id,companyId:row.company_id,entityType:row.entity_type,entityId:row.entity_id,title:row.title,originalName:row.original_name,storedName:row.stored_name,mimeType:row.mime_type,sizeBytes:Number(row.size_bytes),createdBy:row.created_by,createdAt:row.created_at,storedPath:path.join(storageDir,row.stored_name)});
 function importFile(input={},actor=null){assertRole(actor,['admin','manager','director']);const companyId=String(actor?.companyId||input.companyId||'default');const sourcePath=path.resolve(String(input.sourcePath||''));if(!fs.existsSync(sourcePath)||!fs.statSync(sourcePath).isFile())throw new Error('Arquivo de origem invalido.');const stat=fs.statSync(sourcePath);if(stat.size>maxBytes)throw new Error('Arquivo excede o limite permitido.');const ext=path.extname(sourcePath).toLowerCase();if(!SAFE_EXT.has(ext))throw new Error('Tipo de arquivo nao permitido.');const id=String(input.id||idFactory('document'));const originalName=path.basename(sourcePath);const storedName=`${id}${ext}`;const target=path.join(storageDir,storedName);fs.copyFileSync(sourcePath,target,fs.constants.COPYFILE_EXCL);const title=String(input.title||originalName).trim()||originalName;db.prepare('INSERT INTO documents(id,company_id,entity_type,entity_id,title,original_name,stored_name,mime_type,size_bytes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,companyId,input.entityType||null,input.entityId||null,title,originalName,storedName,input.mimeType||null,stat.size,actor?.userId||null,String(now()));return get(id,companyId);}
 function get(id,companyId='default'){return map(db.prepare('SELECT * FROM documents WHERE id=? AND company_id=?').get(String(id),String(companyId)));}
 function list({companyId='default',entityType=null,entityId=null,query=null,limit=100,offset=0}={}){const clauses=['company_id=?'],params=[String(companyId)];if(entityType){clauses.push('entity_type=?');params.push(String(entityType));}if(entityId){clauses.push('entity_id=?');params.push(String(entityId));}if(query){clauses.push('(LOWER(title) LIKE ? OR LOWER(original_name) LIKE ?)');const q=`%${String(query).toLowerCase()}%`;params.push(q,q);}const safeLimit=Math.min(200,Math.max(1,Number(limit)||100)),safeOffset=Math.max(0,Number(offset)||0);return db.prepare(`SELECT * FROM documents WHERE ${clauses.join(' AND ')} ORDER BY created_at DESC,id LIMIT ? OFFSET ?`).all(...params,safeLimit,safeOffset).map(map);}
 function remove(id,actor=null){assertRole(actor,['admin','manager']);const companyId=String(actor?.companyId||'default');const doc=get(id,companyId);if(!doc)throw new Error('Documento nao encontrado.');db.prepare('DELETE FROM documents WHERE id=? AND company_id=?').run(String(id),companyId);try{fs.rmSync(doc.storedPath,{force:true});}catch{}return true;}
 return{importFile,get,list,remove,storageDir,maxBytes};
}
module.exports={createDocumentService};
