'use strict';
(async()=>{
  const baseUrl=await window.erpDesktop.getBaseUrl();const api=new window.ErpApi(baseUrl);
  const login=document.getElementById('login'),app=document.getElementById('app'),content=document.getElementById('content'),title=document.getElementById('view-title'),subtitle=document.getElementById('view-subtitle'),badge=document.getElementById('user-badge');
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100);const esc=v=>window.ErpUi.escapeHtml(v);let currentView='dashboard';
  const today=()=>new Date().toISOString().slice(0,10),monthStart=()=>`${today().slice(0,7)}-01`;
  const panel=(name,body)=>`<div class="panel"><h3>${esc(name)}</h3>${body}</div>`;const metric=(name,value,hint='')=>`<div class="metric"><span>${esc(name)}</span><strong>${esc(value)}</strong>${hint?`<small>${esc(hint)}</small>`:''}</div>`;
  async function safe(path){try{return await api.request(path);}catch(error){return{__error:error.message};}}
  function setIdentity(data){const user=data?.user||{},companies=Array.isArray(data?.companies)?data.companies:[],active=data?.activeCompany;badge.innerHTML=`<div class="identity"><strong>${esc(user.name||'Usuário')}</strong><small>${esc(window.ErpUi.statusLabel(user.role||''))}</small></div>${companies.length>1?`<label class="company-select"><span>Empresa</span><select id="company-switch" data-testid="company-switch">${companies.map(c=>`<option value="${esc(c.id)}" ${c.id===active?.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`:`<div class="company-static"><span>Empresa</span><strong>${esc(active?.name||companies[0]?.name||'Empresa principal')}</strong></div>`}`;const select=badge.querySelector('#company-switch');if(select)select.addEventListener('change',async()=>{try{await api.request('/api/v1/auth/company',{method:'POST',body:{companyId:select.value}});window.ErpUi.toast('Empresa ativa alterada.');await refreshIdentity();await render(currentView);}catch(error){window.ErpUi.toast(error.message,{type:'error'});}});}
  async function refreshIdentity(){const me=await api.request('/api/v1/auth/me');setIdentity(me);return me;}
  async function renderDashboard(){title.textContent='Dashboard';subtitle.textContent='Visão geral do negócio';const from=monthStart(),to=today();const [finance,sales,purchases,inventory,alerts]=await Promise.all([safe(`/api/v1/finance/dashboard?from=${from}&to=${to}`),safe(`/api/v1/reports/sales?from=${from}&to=${to}`),safe(`/api/v1/reports/purchases?from=${from}&to=${to}`),safe('/api/v1/reports/inventory'),safe('/api/v1/finance/alerts')]);if(finance.__error){content.innerHTML=window.ErpUi.errorState(finance.__error);return;}const alertRows=Array.isArray(alerts)?alerts.filter(a=>!a.hiddenAt).slice(0,6):[];content.innerHTML=`<div data-testid="view-dashboard"><div class="grid metrics-4">${metric('A receber',money(finance.receivablesOpenCents??finance.receivableOpenCents))}${metric('A pagar',money(finance.payablesOpenCents??finance.payableOpenCents))}${metric('Caixa realizado',money(finance.cashNetCents??finance.netCashCents))}${metric('Resultado',money(finance.resultCents??finance.netResultCents))}${sales.__error?'':metric('Vendas no mês',money(sales.netSalesCents),`${sales.invoiceOrSettlementCount||0} faturamento(s)`)}${purchases.__error?'':metric('Compras recebidas',money(purchases.receivedCents),`${purchases.receipts||0} recebimento(s)`)}${inventory.__error?'':metric('Estoque disponível',String(inventory.availableQuantity??0),`${inventory.products||0} produto(s)`)}${metric('Alertas',String(alertRows.length),alertRows.length?'Requerem atenção':'Sem alertas visíveis')}</div><div class="grid dashboard-grid">${panel('Operação do mês',`<div class="kpi-list"><div><span>Vendas</span><strong>${sales.__error?'-':money(sales.netSalesCents)}</strong></div><div><span>Margem estimada</span><strong>${sales.__error?'-':money(sales.estimatedMarginCents)}</strong></div><div><span>Compras</span><strong>${purchases.__error?'-':money(purchases.receivedCents)}</strong></div><div><span>Reservado em estoque</span><strong>${inventory.__error?'-':String(inventory.reservedQuantity??0)}</strong></div></div>`)}${panel('Alertas e pendências',alertRows.length?`<div class="alert-list">${alertRows.map(a=>`<div class="alert-row"><span class="pill">${esc(window.ErpUi.statusLabel(a.severity))}</span><span>${esc(a.message)}</span></div>`).join('')}</div>`:window.ErpUi.empty('Nenhum alerta operacional visível.'))}</div></div>`;}
  async function render(view){currentView=view;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));content.innerHTML=window.ErpUi.loading();
    if(view==='dashboard'){await renderDashboard();return;}
    if(view==='cadastros'){title.textContent='Cadastros';subtitle.textContent='Clientes, fornecedores, categorias e produtos';await window.ErpViews.cadastros({api,root:content});return;}
    if(view==='estoque'){title.textContent='Estoque';subtitle.textContent='Saldos, ajustes, transferências e reservas';await window.ErpViews.estoque({api,root:content});return;}
    if(view==='compras'){title.textContent='Compras';subtitle.textContent='Solicitações, cotações, aprovações, pedidos e recebimentos';await window.ErpViews.compras({api,root:content});return;}
    if(view==='vendas'){title.textContent='Vendas';subtitle.textContent='Orçamentos, pedidos e faturamento administrativo';await window.ErpViews.vendas({api,root:content});return;}
    if(view==='financeiro'){title.textContent='Financeiro';subtitle.textContent='Contas, baixas, conciliação, recorrências e alertas';await window.ErpViews.financeiro({api,root:content});return;}
    if(view==='relatorios'){title.textContent='Relatórios';subtitle.textContent='Indicadores comerciais, operacionais e financeiros';await window.ErpViews.relatorios({api,root:content});return;}
    if(view==='administracao'){title.textContent='Administração';subtitle.textContent='Empresas, usuários, backups, documentos e integrações';await window.ErpViews.administracao({api,root:content});return;}
    title.textContent='Configurações';subtitle.textContent='Operação local do produto';const health=await safe('/api/v1/health');content.innerHTML=panel('Sistema',`<div class="grid">${metric('Produto','ArtiSys ERP')}${metric('Servidor',health.ok?'Online':'Indisponível')}${metric('Modo','Local-first')}${metric('Base local',baseUrl)}</div>`);
  }
  document.getElementById('login-form').addEventListener('submit',async event=>{event.preventDefault();const error=document.getElementById('login-error');error.textContent='';try{const data=await api.login(document.getElementById('username').value,document.getElementById('password').value);api.setToken(data.token);setIdentity(data);login.hidden=true;app.hidden=false;await render('dashboard');}catch(e){error.textContent=e.message;}});
  document.getElementById('nav').addEventListener('click',event=>{const button=event.target.closest('button[data-view]');if(button)render(button.dataset.view).catch(error=>{content.innerHTML=window.ErpUi.errorState(error.message);});});
  document.getElementById('logout').addEventListener('click',async()=>{try{await api.logout();}catch{}app.hidden=true;login.hidden=false;content.innerHTML='';badge.innerHTML='';currentView='dashboard';});
  document.addEventListener('erp:company-changed',async()=>{try{await refreshIdentity();await render(currentView);}catch(error){window.ErpUi.toast(error.message,{type:'error'});}});
  try{const health=await api.request('/api/v1/health');document.getElementById('server-status').textContent=health.ok?'Local · online':'Local';}catch{document.getElementById('server-status').textContent='Local · offline';}
})();
