'use strict';
(async()=>{
  const baseUrl=await window.erpDesktop.getBaseUrl();const api=new window.ErpApi(baseUrl);
  const login=document.getElementById('login'),app=document.getElementById('app'),content=document.getElementById('content'),title=document.getElementById('view-title'),subtitle=document.getElementById('view-subtitle'),badge=document.getElementById('user-badge');
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rows=(data,cols)=>Array.isArray(data)&&data.length?`<table><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${cols.map(c=>`<td>${esc(typeof c[1]==='function'?c[1](r):r[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum registro encontrado.</div>';
  const panel=(name,body)=>`<div class="panel"><h3>${esc(name)}</h3>${body}</div>`;const metric=(name,value)=>`<div class="metric"><span>${esc(name)}</span><strong>${esc(value)}</strong></div>`;
  async function safe(path){try{return await api.request(path);}catch(error){return{__error:error.message};}}
  async function render(view){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));content.innerHTML='<div class="panel">Carregando…</div>';
    if(view==='dashboard'){title.textContent='Dashboard';subtitle.textContent='Visão geral do negócio';const d=await safe('/api/v1/finance/dashboard');if(d.__error){content.innerHTML=panel('Dashboard',`<div class="notice">${esc(d.__error)}</div>`);return;}content.innerHTML=`<div class="grid">${metric('A receber',money(d.receivablesOpenCents??d.receivableOpenCents))}${metric('A pagar',money(d.payablesOpenCents??d.payableOpenCents))}${metric('Caixa realizado',money(d.cashNetCents??d.netCashCents))}${metric('Resultado',money(d.resultCents??d.netResultCents))}</div>`;return;}
    if(view==='cadastros'){title.textContent='Cadastros';subtitle.textContent='Clientes, fornecedores e produtos';const [c,s,p]=await Promise.all([safe('/api/v1/customers'),safe('/api/v1/suppliers'),safe('/api/v1/products')]);content.innerHTML=panel('Clientes',c.__error?esc(c.__error):rows(c,[['Nome','name'],['Documento','document'],['Ativo',x=>x.active?'Sim':'Não']]))+panel('Fornecedores',s.__error?esc(s.__error):rows(s,[['Nome','name'],['Documento','document'],['Ativo',x=>x.active?'Sim':'Não']]))+panel('Produtos',p.__error?esc(p.__error):rows(p,[['Produto','name'],['SKU','sku'],['Preço',x=>money(x.salePriceCents)],['Custo',x=>money(x.costCents)]]));return;}
    if(view==='estoque'){title.textContent='Estoque';subtitle.textContent='Locais e movimentações';const [l,m]=await Promise.all([safe('/api/v1/inventory/locations'),safe('/api/v1/inventory/movements')]);content.innerHTML=panel('Locais',l.__error?esc(l.__error):rows(l,[['Local','name'],['Ativo',x=>x.active?'Sim':'Não']]))+panel('Movimentações',m.__error?esc(m.__error):rows(m,[['Produto','productId'],['Local','locationId'],['Tipo','type'],['Quantidade','quantityDelta'],['Data','createdAt']]));return;}
    if(view==='compras'){title.textContent='Compras';subtitle.textContent='Pedidos e recebimentos';const [o,r]=await Promise.all([safe('/api/v1/procurement/orders'),safe('/api/v1/procurement/receipts')]);content.innerHTML=panel('Pedidos de compra',o.__error?esc(o.__error):rows(o,[['Pedido','orderNumber'],['Fornecedor','supplierName'],['Status','status'],['Total',x=>money(x.totalCents)]]))+panel('Recebimentos',r.__error?esc(r.__error):rows(r,[['Recebimento','receiptNumber'],['Pedido','purchaseOrderId'],['Total',x=>money(x.totalCents)],['Data','receivedAt']]));return;}
    if(view==='vendas'){title.textContent='Vendas';subtitle.textContent='Orçamentos, pedidos e faturamento administrativo';const [o,i]=await Promise.all([safe('/api/v1/sales/orders'),safe('/api/v1/sales/invoices')]);content.innerHTML=panel('Pedidos',o.__error?esc(o.__error):rows(o,[['Pedido','id'],['Cliente','customerName'],['Status','status'],['Total',x=>money(x.totalCents)]]))+panel('Faturamentos',i.__error?esc(i.__error):rows(i,[['Documento','id'],['Pedido','orderId'],['Total',x=>money(x.totalCents)],['Data','createdAt']]));return;}
    if(view==='financeiro'){title.textContent='Financeiro';subtitle.textContent='Contas, lançamentos e alertas';const [s,e,a]=await Promise.all([safe('/api/v1/finance/summary'),safe('/api/v1/finance/entries'),safe('/api/v1/finance/alerts')]);content.innerHTML=(s.__error?panel('Resumo',esc(s.__error)):`<div class="grid">${metric('A receber',money(s.receivableOpenCents??s.receivablesOpenCents))}${metric('A pagar',money(s.payableOpenCents??s.payablesOpenCents))}${metric('Recebido',money(s.receivedCents))}${metric('Pago',money(s.paidCents))}</div>`)+panel('Lançamentos',e.__error?esc(e.__error):rows(e,[['Descrição','description'],['Tipo','kind'],['Status','status'],['Valor',x=>money(x.amountCents)],['Vencimento','dueAt']]))+panel('Alertas',a.__error?esc(a.__error):rows(a,[['Tipo','type'],['Mensagem','message'],['Nível','severity']]));return;}
    if(view==='relatorios'){title.textContent='Relatórios';subtitle.textContent='Vendas, compras e estoque';const [s,p,i]=await Promise.all([safe('/api/v1/reports/sales'),safe('/api/v1/reports/purchases'),safe('/api/v1/reports/inventory')]);content.innerHTML=panel('Vendas',`<pre>${esc(JSON.stringify(s,null,2))}</pre>`)+panel('Compras',`<pre>${esc(JSON.stringify(p,null,2))}</pre>`)+panel('Estoque',`<pre>${esc(JSON.stringify(i,null,2))}</pre>`);return;}
    title.textContent='Configurações';subtitle.textContent='Operação local do produto';const health=await safe('/api/v1/health');content.innerHTML=panel('Sistema',`<div class="grid">${metric('Produto','ArtiSys ERP')}${metric('Servidor',health.ok?'Online':'Indisponível')}${metric('Modo','Local-first')}${metric('Base local',baseUrl)}</div>`);
  }
  document.getElementById('login-form').addEventListener('submit',async event=>{event.preventDefault();const error=document.getElementById('login-error');error.textContent='';try{const data=await api.login(document.getElementById('email').value,document.getElementById('password').value);api.setToken(data.token);badge.textContent=`${data.user.name} · ${data.user.role}`;login.hidden=true;app.hidden=false;await render('dashboard');}catch(e){error.textContent=e.message;}});
  document.getElementById('nav').addEventListener('click',event=>{const button=event.target.closest('button[data-view]');if(button)render(button.dataset.view);});
  document.getElementById('logout').addEventListener('click',async()=>{try{await api.logout();}catch{}app.hidden=true;login.hidden=false;content.innerHTML='';});
  try{const health=await api.request('/api/v1/health');document.getElementById('server-status').textContent=health.ok?'Local · online':'Local';}catch{document.getElementById('server-status').textContent='Local · offline';}
})();
