'use strict';
(async()=>{
  const baseUrl=await window.erpDesktop.getBaseUrl();
  const api=new window.ErpApi(baseUrl);
  const login=document.getElementById('login'),app=document.getElementById('app'),content=document.getElementById('content'),title=document.getElementById('view-title'),subtitle=document.getElementById('view-subtitle'),badge=document.getElementById('user-badge');
  let currentView='dashboard',pendingStatement=null;
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rows=(data,cols)=>Array.isArray(data)&&data.length?`<table><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${cols.map(c=>`<td>${esc(typeof c[1]==='function'?c[1](r):r[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum registro encontrado.</div>';
  const panel=(name,body)=>`<div class="panel"><h3>${esc(name)}</h3>${body}</div>`;
  const metric=(name,value)=>`<div class="metric"><span>${esc(name)}</span><strong>${esc(value)}</strong></div>`;
  async function safe(path,options){try{return await api.request(path,options);}catch(error){return{__error:error.message};}}
  function today(){return new Date().toISOString().slice(0,10);}
  function firstDay(){return `${today().slice(0,7)}-01`;}
  function selectedAccount(){return document.getElementById('statement-account')?.value||'';}
  function brlToCents(value){const raw=String(value||'').trim().replace(/\s+/g,'').replace(/^R\$/i,'');if(!raw)return 0;let normalized=raw;if(raw.includes(',')&&raw.includes('.'))normalized=raw.lastIndexOf(',')>raw.lastIndexOf('.')?raw.replace(/\./g,'').replace(',','.'):raw.replace(/,/g,'');else if(raw.includes(','))normalized=raw.replace(/\./g,'').replace(',','.');const n=Number(normalized);return Number.isFinite(n)?Math.round(Math.abs(n)*100):0;}
  function statementPreviewHtml(preview){if(preview.__error)return`<div class="error">${esc(preview.__error)}</div>`;const tx=preview.transactions||[];return`<div class="notice">Prévia: ${tx.length} movimentação(ões), ${preview.duplicates||0} duplicada(s). Nada foi gravado ainda.</div>${rows(tx,[['Data','date'],['Descrição','description'],['Direção',x=>x.direction==='credit'?'Crédito':'Débito'],['Valor',x=>money(x.amountCents)],['Duplicada',x=>x.duplicate?'Sim':'Não']])}<div class="toolbar"><button id="statement-commit" class="primary">Confirmar importação</button><button id="statement-cancel" class="secondary-inline">Cancelar</button></div>`;}
  function financeEntriesTable(entries){if(!Array.isArray(entries)||!entries.length)return'<div class="empty">Nenhum lançamento encontrado.</div>';return`<table><thead><tr><th>Descrição</th><th>Tipo</th><th>Status</th><th>Valor</th><th>Vencimento</th><th>Comprovante</th></tr></thead><tbody>${entries.map(entry=>{const settlement=(entry.settlements||[]).at(-1);const actions=settlement?`<div class="row-actions"><button class="tiny" data-receipt-pdf="${esc(settlement.id)}">PDF</button><button class="tiny" data-receipt-print="${esc(settlement.id)}">Imprimir</button></div>`:'—';return`<tr><td>${esc(entry.description)}</td><td>${esc(entry.kind)}</td><td>${esc(entry.status)}</td><td>${esc(money(entry.amountCents))}</td><td>${esc(String(entry.dueAt||'').slice(0,10))}</td><td>${actions}</td></tr>`;}).join('')}</tbody></table>`;}
  async function render(view){currentView=view;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));content.innerHTML='<div class="panel">Carregando…</div>';
    if(view==='dashboard'){title.textContent='Dashboard';subtitle.textContent='Visão geral do negócio';const d=await safe('/api/v1/finance/dashboard');if(d.__error){content.innerHTML=panel('Dashboard',`<div class="notice">${esc(d.__error)}</div>`);return;}content.innerHTML=`<div class="grid">${metric('A receber',money(d.receivablesOpenCents??d.receivableOpenCents))}${metric('A pagar',money(d.payablesOpenCents??d.payableOpenCents))}${metric('Caixa realizado',money(d.cashNetCents??d.netCashCents))}${metric('Resultado',money(d.resultCents??d.netResultCents))}</div>`;return;}
    if(view==='cadastros'){title.textContent='Cadastros';subtitle.textContent='Clientes, fornecedores e produtos';const [c,s,p]=await Promise.all([safe('/api/v1/customers'),safe('/api/v1/suppliers'),safe('/api/v1/products')]);content.innerHTML=panel('Clientes',c.__error?esc(c.__error):rows(c,[['Nome','name'],['Documento','document'],['Ativo',x=>x.active?'Sim':'Não']]))+panel('Fornecedores',s.__error?esc(s.__error):rows(s,[['Nome','name'],['Documento','document'],['Ativo',x=>x.active?'Sim':'Não']]))+panel('Produtos',p.__error?esc(p.__error):rows(p,[['Produto','name'],['SKU','sku'],['Preço',x=>money(x.salePriceCents)],['Custo',x=>money(x.costCents)]]));return;}
    if(view==='estoque'){title.textContent='Estoque';subtitle.textContent='Locais e movimentações';const [l,m]=await Promise.all([safe('/api/v1/inventory/locations'),safe('/api/v1/inventory/movements')]);content.innerHTML=panel('Locais',l.__error?esc(l.__error):rows(l,[['Local','name'],['Ativo',x=>x.active?'Sim':'Não']]))+panel('Movimentações',m.__error?esc(m.__error):rows(m,[['Produto','productId'],['Local','locationId'],['Tipo','type'],['Quantidade','quantityDelta'],['Data','createdAt']]));return;}
    if(view==='compras'){title.textContent='Compras';subtitle.textContent='Pedidos e recebimentos';const [o,r]=await Promise.all([safe('/api/v1/procurement/orders'),safe('/api/v1/procurement/receipts')]);content.innerHTML=panel('Pedidos de compra',o.__error?esc(o.__error):rows(o,[['Pedido','orderNumber'],['Fornecedor','supplierName'],['Status','status'],['Total',x=>money(x.totalCents)]]))+panel('Recebimentos',r.__error?esc(r.__error):rows(r,[['Recebimento','receiptNumber'],['Pedido','purchaseOrderId'],['Total',x=>money(x.totalCents)],['Data','receivedAt']]));return;}
    if(view==='vendas'){title.textContent='Vendas';subtitle.textContent='Orçamentos, pedidos e faturamento administrativo';const [o,i]=await Promise.all([safe('/api/v1/sales/orders'),safe('/api/v1/sales/invoices')]);content.innerHTML=panel('Pedidos',o.__error?esc(o.__error):rows(o,[['Pedido','id'],['Cliente','customerName'],['Status','status'],['Total',x=>money(x.totalCents)]]))+panel('Faturamentos',i.__error?esc(i.__error):rows(i,[['Documento','id'],['Pedido','orderId'],['Total',x=>money(x.totalCents)],['Data','createdAt']]));return;}
    if(view==='financeiro'){
      title.textContent='Financeiro';subtitle.textContent='Contas, lançamentos, extratos e comprovantes';
      const [s,e,a,accounts]=await Promise.all([safe('/api/v1/finance/summary'),safe('/api/v1/finance/entries'),safe('/api/v1/finance/alerts'),safe('/api/v1/finance/accounts')]);
      const options=Array.isArray(accounts)?accounts.filter(x=>['BANK','CARD'].includes(x.type)).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join(''):'';
      const importPanel=`<div class="form-grid"><label>Conta<select id="statement-account">${options}</select></label><div class="field-actions"><button id="statement-file" class="primary">Importar OFX / CSV / PDF</button></div></div><details><summary>Lançar movimentação de extrato manualmente</summary><form id="statement-manual" class="form-grid compact"><label>Data<input id="manual-date" type="date" value="${today()}" required></label><label>Descrição<input id="manual-description" required></label><label>Valor (R$)<input id="manual-amount" inputmode="decimal" placeholder="0,00" required></label><label>Direção<select id="manual-direction"><option value="debit">Débito</option><option value="credit">Crédito</option></select></label><div class="field-actions"><button class="primary" type="submit">Analisar</button></div></form></details><div id="statement-result"></div>`;
      content.innerHTML=(s.__error?panel('Resumo',esc(s.__error)):`<div class="grid">${metric('A receber',money(s.receivableOpenCents??s.receivablesOpenCents))}${metric('A pagar',money(s.payableOpenCents??s.payablesOpenCents))}${metric('Recebido',money(s.receivableSettledCents??s.receivedCents))}${metric('Pago',money(s.payableSettledCents??s.paidCents))}</div>`)+panel('Importar extrato',importPanel)+panel('Lançamentos',e.__error?esc(e.__error):financeEntriesTable(e))+panel('Alertas',a.__error?esc(a.__error):rows(a,[['Tipo','type'],['Mensagem','message'],['Nível','severity']]));return;
    }
    if(view==='relatorios'){
      title.textContent='Relatórios';subtitle.textContent='Indicadores e exportações locais';
      const [s,p,i]=await Promise.all([safe('/api/v1/reports/sales'),safe('/api/v1/reports/purchases'),safe('/api/v1/reports/inventory')]);
      const controls=`<form id="financial-report-form" class="form-grid compact"><label>De<input id="report-from" type="date" value="${firstDay()}" required></label><label>Até<input id="report-to" type="date" value="${today()}" required></label><div class="field-actions"><button type="submit" class="primary">Atualizar financeiro</button></div></form><div class="toolbar"><button class="tiny" data-export="csv">Salvar CSV</button><button class="tiny" data-export="xlsx">Salvar XLSX</button><button class="tiny" data-export="pdf">Salvar PDF</button><button class="tiny" data-export="print">Imprimir</button></div><div id="financial-report-result"></div>`;
      content.innerHTML=panel('Relatório financeiro',controls)+panel('Vendas',`<pre>${esc(JSON.stringify(s,null,2))}</pre>`)+panel('Compras',`<pre>${esc(JSON.stringify(p,null,2))}</pre>`)+panel('Estoque',`<pre>${esc(JSON.stringify(i,null,2))}</pre>`);await loadFinancialReport();return;
    }
    title.textContent='Configurações';subtitle.textContent='Operação local do produto';const health=await safe('/api/v1/health');content.innerHTML=panel('Sistema',`<div class="grid">${metric('Produto','ArtiSys ERP')}${metric('Servidor',health.ok?'Online':'Indisponível')}${metric('Modo','Local-first')}${metric('Base local',baseUrl)}</div>`);
  }
  async function previewStatement(payload){const result=document.getElementById('statement-result');if(result)result.innerHTML='<div class="notice">Analisando…</div>';const preview=await safe('/api/v1/finance/statements/preview',{method:'POST',body:payload});if(preview.__error){pendingStatement=null;if(result)result.innerHTML=statementPreviewHtml(preview);return;}pendingStatement=payload;if(result)result.innerHTML=statementPreviewHtml(preview);}
  async function loadFinancialReport(){const target=document.getElementById('financial-report-result');if(!target)return;const from=document.getElementById('report-from')?.value||firstDay(),to=document.getElementById('report-to')?.value||today(),report=await safe(`/api/v1/reports/financial?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`);if(report.__error){target.innerHTML=`<div class="error">${esc(report.__error)}</div>`;return;}target.innerHTML=`<div class="grid">${metric('Total',money(report.totals.amountCents))}${metric('Baixado',money(report.totals.settledCents))}${metric('Em aberto',money(report.totals.openCents))}</div>${rows(report.rows,[['Vencimento',x=>String(x.dueAt||'').slice(0,10)],['Tipo','kind'],['Descrição','description'],['Status','status'],['Valor',x=>money(x.amountCents)],['Conta','account'],['Categoria','category']])}`;}
  async function exportFinancial(format){const from=document.getElementById('report-from')?.value||firstDay(),to=document.getElementById('report-to')?.value||today(),query=`from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;if(format==='csv'||format==='xlsx'){const payload=await safe(`/api/v1/reports/financial.${format}?${query}`);if(payload.__error)throw new Error(payload.__error);await window.erpDesktop.saveExportFile(payload);return;}const payload=await safe(`/api/v1/reports/financial/print?${query}`);if(payload.__error)throw new Error(payload.__error);if(format==='pdf')await window.erpDesktop.savePdf(payload);else await window.erpDesktop.printHtml(payload);}
  content.addEventListener('click',async event=>{const fileButton=event.target.closest('#statement-file');if(fileButton){try{const file=await window.erpDesktop.selectImportFile();if(file)await previewStatement({sourceType:file.sourceType,accountId:selectedAccount(),sourceName:file.name,content:file.text});}catch(error){document.getElementById('statement-result').innerHTML=`<div class="error">${esc(error.message)}</div>`;}return;}if(event.target.closest('#statement-cancel')){pendingStatement=null;document.getElementById('statement-result').innerHTML='';return;}if(event.target.closest('#statement-commit')){if(!pendingStatement)return;const target=document.getElementById('statement-result');const saved=await safe('/api/v1/finance/statements',{method:'POST',body:pendingStatement});if(saved.__error){target.innerHTML=`<div class="error">${esc(saved.__error)}</div>`;return;}pendingStatement=null;target.innerHTML=`<div class="notice">Importação concluída: ${saved.inserted} nova(s), ${saved.duplicates} duplicada(s).</div>`;return;}const receiptPdf=event.target.closest('[data-receipt-pdf]');if(receiptPdf){const id=receiptPdf.dataset.receiptPdf,payload=await safe(`/api/v1/reports/settlements/${encodeURIComponent(id)}/receipt/print`);if(payload.__error)alert(payload.__error);else await window.erpDesktop.savePdf(payload);return;}const receiptPrint=event.target.closest('[data-receipt-print]');if(receiptPrint){const id=receiptPrint.dataset.receiptPrint,payload=await safe(`/api/v1/reports/settlements/${encodeURIComponent(id)}/receipt/print`);if(payload.__error)alert(payload.__error);else await window.erpDesktop.printHtml(payload);return;}const exportButton=event.target.closest('[data-export]');if(exportButton){try{await exportFinancial(exportButton.dataset.export);}catch(error){alert(error.message);}return;}});
  content.addEventListener('submit',async event=>{if(event.target.id==='statement-manual'){event.preventDefault();const amountCents=brlToCents(document.getElementById('manual-amount').value);await previewStatement({sourceType:'MANUAL',accountId:selectedAccount(),sourceName:'manual',rows:[{date:document.getElementById('manual-date').value,description:document.getElementById('manual-description').value,amountCents,direction:document.getElementById('manual-direction').value}]});return;}if(event.target.id==='financial-report-form'){event.preventDefault();await loadFinancialReport();}});
  document.getElementById('login-form').addEventListener('submit',async event=>{event.preventDefault();const error=document.getElementById('login-error');error.textContent='';try{const data=await api.login(document.getElementById('email').value,document.getElementById('password').value);api.setToken(data.token);badge.textContent=`${data.user.name} · ${data.user.role}`;login.hidden=true;app.hidden=false;await render('dashboard');}catch(e){error.textContent=e.message;}});
  document.getElementById('nav').addEventListener('click',event=>{const button=event.target.closest('button[data-view]');if(button)render(button.dataset.view);});
  document.getElementById('logout').addEventListener('click',async()=>{try{await api.logout();}catch{}app.hidden=true;login.hidden=false;content.innerHTML='';pendingStatement=null;});
  try{const health=await api.request('/api/v1/health');document.getElementById('server-status').textContent=health.ok?'Local · online':'Local';}catch{document.getElementById('server-status').textContent='Local · offline';}
})();
