'use strict';
(()=>{
  const root=document.getElementById('content');if(!root)return;
  const esc=value=>window.ErpUi.escapeHtml(value),money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(value)||0)/100);
  const baseUrlPromise=window.erpDesktop.getBaseUrl();let queued=false,pendingManual=null;
  const today=()=>new Date().toISOString().slice(0,10),firstDay=()=>`${today().slice(0,7)}-01`;
  async function request(path,options){const api=new window.ErpApi(await baseUrlPromise);return api.request(path,options);}
  function cents(value){const raw=String(value||'').trim().replace(/\s+/g,'').replace(/^R\$/i,'');if(!raw)return 0;let normalized=raw;if(raw.includes(',')&&raw.includes('.'))normalized=raw.lastIndexOf(',')>raw.lastIndexOf('.')?raw.replace(/\./g,'').replace(',','.'):raw.replace(/,/g,'');else if(raw.includes(','))normalized=raw.replace(/\./g,'').replace(',','.');const n=Number(normalized);return Number.isFinite(n)?Math.round(Math.abs(n)*100):0;}
  function rowsHtml(rows){return rows.length?`<table><thead><tr><th>Data</th><th>Descrição</th><th>Direção</th><th>Valor</th><th>Duplicada</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.date)}</td><td>${esc(row.description)}</td><td>${row.direction==='credit'?'Crédito':'Débito'}</td><td>${esc(money(row.amountCents))}</td><td>${row.duplicate?'Sim':'Não'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhuma movimentação.</div>';}
  async function enhanceFinance(){const financeRoot=root.querySelector('[data-testid="finance-root"]');if(!financeRoot)return;const tab=financeRoot.querySelector('[data-tab="statements"]');if(tab&&tab.textContent!=='Extratos / Conciliação')tab.textContent='Extratos / Conciliação';const select=financeRoot.querySelector('[data-testid="finance-ofx-select"]');if(select){if(select.textContent!=='Selecionar OFX / CSV / PDF e pré-visualizar')select.textContent='Selecionar OFX / CSV / PDF e pré-visualizar';const toolbar=select.closest('.toolbar');if(toolbar&&!financeRoot.querySelector('#finance-manual-statement')){const details=document.createElement('details');details.id='finance-manual-statement';details.innerHTML=`<summary>Lançar movimentação de extrato manualmente</summary><form id="finance-manual-form" class="form-grid"><label class="form-field"><span>Data</span><input name="date" type="date" value="${today()}" required></label><label class="form-field"><span>Descrição</span><input name="description" required></label><label class="form-field"><span>Valor (R$)</span><input name="amount" inputmode="decimal" placeholder="0,00" required></label><label class="form-field"><span>Direção</span><select name="direction"><option value="debit">Débito</option><option value="credit">Crédito</option></select></label><div class="toolbar"><button class="primary" type="submit">Analisar</button></div></form><div id="finance-manual-preview"></div>`;toolbar.insertAdjacentElement('afterend',details);}}
    const table=financeRoot.querySelector('[data-testid="finance-entry-table"]');if(table&&table.dataset.financeIoReceipts!=='1'){table.dataset.financeIoReceipts='1';const entries=await request('/api/v1/finance/entries');for(const entry of entries){const settlement=(entry.settlements||[]).filter(item=>!item.reversedAt).at(-1);if(!settlement)continue;const row=table.querySelector(`tr[data-entry="${CSS.escape(String(entry.id))}"]`),actions=row?.querySelector('td:last-child .toolbar');if(!actions||actions.querySelector(`[data-finance-receipt-id="${CSS.escape(String(settlement.id))}"]`))continue;const pdf=document.createElement('button');pdf.type='button';pdf.dataset.financeReceiptPdf=settlement.id;pdf.dataset.financeReceiptId=settlement.id;pdf.textContent='Comprovante PDF';const print=document.createElement('button');print.type='button';print.dataset.financeReceiptPrint=settlement.id;print.dataset.financeReceiptId=settlement.id;print.textContent='Imprimir';actions.append(pdf,print);}}
  }
  async function loadFinancialReport(){const panel=root.querySelector('#finance-io-report');if(!panel)return;const from=panel.querySelector('[name="from"]').value,to=panel.querySelector('[name="to"]').value,target=panel.querySelector('[data-report-result]');target.innerHTML='<div class="notice">Carregando relatório financeiro…</div>';const report=await request(`/api/v1/reports/financial?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`);target.innerHTML=`<div class="grid"><div class="metric"><span>Total</span><strong>${money(report.totals.amountCents)}</strong></div><div class="metric"><span>Baixado</span><strong>${money(report.totals.settledCents)}</strong></div><div class="metric"><span>Em aberto</span><strong>${money(report.totals.openCents)}</strong></div></div><table><thead><tr><th>Vencimento</th><th>Tipo</th><th>Descrição</th><th>Status</th><th>Valor</th><th>Conta</th><th>Categoria</th></tr></thead><tbody>${report.rows.map(row=>`<tr><td>${esc(String(row.dueAt||'').slice(0,10))}</td><td>${esc(row.kind)}</td><td>${esc(row.description)}</td><td>${esc(row.status)}</td><td>${esc(money(row.amountCents))}</td><td>${esc(row.account)}</td><td>${esc(row.category)}</td></tr>`).join('')}</tbody></table>`;}
  async function enhanceReports(){if(document.getElementById('view-title')?.textContent!=='Relatórios'||root.querySelector('#finance-io-report'))return;const panel=document.createElement('div');panel.className='panel';panel.id='finance-io-report';panel.innerHTML=`<h3>Relatório financeiro</h3><form id="finance-report-form" class="form-grid"><label class="form-field"><span>De</span><input name="from" type="date" value="${firstDay()}" required></label><label class="form-field"><span>Até</span><input name="to" type="date" value="${today()}" required></label><div class="toolbar"><button class="primary" type="submit">Atualizar</button></div></form><div class="toolbar"><button type="button" data-finance-export="csv">Salvar CSV</button><button type="button" data-finance-export="xlsx">Salvar XLSX</button><button type="button" data-finance-export="pdf">Salvar PDF</button><button type="button" data-finance-export="print">Imprimir</button></div><div data-report-result></div>`;root.prepend(panel);await loadFinancialReport();}
  async function enhance(){await enhanceFinance();await enhanceReports();}
  function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance().catch(error=>window.ErpUi.toast(error.message,{type:'error'}));});}
  root.addEventListener('submit',async event=>{if(event.target.id==='finance-manual-form'){event.preventDefault();const financeRoot=root.querySelector('[data-testid="finance-root"]'),accountId=financeRoot?.querySelector('[data-ofx-account]')?.value;if(!accountId){window.ErpUi.toast('Selecione a conta do extrato.',{type:'error'});return;}const form=new FormData(event.target),amountCents=cents(form.get('amount'));pendingManual={sourceType:'MANUAL',accountId,sourceName:'manual',rows:[{date:String(form.get('date')||''),description:String(form.get('description')||''),amountCents,direction:String(form.get('direction')||'')}]};try{const preview=await request('/api/v1/finance/statements/preview',{method:'POST',body:pendingManual}),box=financeRoot.querySelector('#finance-manual-preview');box.innerHTML=`<div class="notice">Prévia: ${preview.transactions.length} movimentação(ões), ${preview.duplicates} duplicada(s). Nada foi gravado.</div>${rowsHtml(preview.transactions)}<div class="toolbar"><button type="button" class="primary" data-finance-manual-commit>Confirmar importação</button></div>`;}catch(error){pendingManual=null;window.ErpUi.toast(error.message,{type:'error'});}return;}if(event.target.id==='finance-report-form'){event.preventDefault();try{await loadFinancialReport();}catch(error){window.ErpUi.toast(error.message,{type:'error'});}}});
  root.addEventListener('click',async event=>{const manual=event.target.closest('[data-finance-manual-commit]');if(manual){event.preventDefault();event.stopImmediatePropagation();if(!pendingManual)return;try{const saved=await request('/api/v1/finance/statements',{method:'POST',body:pendingManual});pendingManual=null;window.ErpUi.toast(`Importação concluída: ${saved.inserted} nova(s), ${saved.duplicates} duplicada(s).`);root.querySelector('[data-testid="finance-root"] [data-tab="statements"]')?.click();}catch(error){window.ErpUi.toast(error.message,{type:'error'});}return;}const pdf=event.target.closest('[data-finance-receipt-pdf]'),print=event.target.closest('[data-finance-receipt-print]');if(pdf||print){event.preventDefault();event.stopImmediatePropagation();const id=(pdf||print).dataset.financeReceiptPdf||(pdf||print).dataset.financeReceiptPrint;try{const payload=await request(`/api/v1/reports/settlements/${encodeURIComponent(id)}/receipt/print`);if(pdf)await window.erpDesktop.savePdf(payload);else await window.erpDesktop.printHtml(payload);}catch(error){window.ErpUi.toast(error.message,{type:'error'});}return;}const exportButton=event.target.closest('[data-finance-export]');if(exportButton){event.preventDefault();const panel=root.querySelector('#finance-io-report'),from=panel?.querySelector('[name="from"]')?.value||firstDay(),to=panel?.querySelector('[name="to"]')?.value||today(),query=`from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;try{const format=exportButton.dataset.financeExport;if(format==='csv'||format==='xlsx'){const payload=await request(`/api/v1/reports/financial.${format}?${query}`);await window.erpDesktop.saveExportFile(payload);}else{const payload=await request(`/api/v1/reports/financial/print?${query}`);if(format==='pdf')await window.erpDesktop.savePdf(payload);else await window.erpDesktop.printHtml(payload);}}catch(error){window.ErpUi.toast(error.message,{type:'error'});}return;}});
  new MutationObserver(schedule).observe(root,{childList:true,subtree:true});schedule();
})();
