'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
function createApprovalService({db,settings,events=null,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!settings)throw new TypeError('approval dependencies are required.');
 const submitter=a=>assertRole(a,['admin','manager']);
 function map(r){return r&&({id:r.id,awardId:r.award_id,status:r.status,currentLevel:Number(r.current_level),requestedTotalCents:Number(r.requested_total_cents),policySnapshotJson:r.policy_snapshot_json,createdBy:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at});}
 function getApproval(id){return map(db.prepare('SELECT * FROM procurement_approval_requests WHERE id=?').get(String(id)));}
 function latestForAward(awardId){return map(db.prepare('SELECT * FROM procurement_approval_requests WHERE award_id=? ORDER BY created_at DESC,id DESC LIMIT 1').get(String(awardId)));}
 function policyFor(total){const all=settings.get('procurement.approvalPolicy',{defaultValue:[{minCents:0,maxCents:null,levels:[{level:1,roles:['manager','admin']}]}]})||[];const p=all.find(x=>Number(total)>=Number(x.minCents||0)&&(x.maxCents===null||x.maxCents===undefined||Number(total)<=Number(x.maxCents)));if(!p||!Array.isArray(p.levels)||!p.levels.length)throw new Error('Politica de aprovacao nao configurada para este valor.');const levels=p.levels.map(x=>({level:Number(x.level),roles:(x.roles||[]).map(String)})).sort((a,b)=>a.level-b.level);if(levels.some(x=>!Number.isInteger(x.level)||x.level<1||!x.roles.length))throw new Error('Politica de aprovacao invalida.');return levels;}
 function submitAwardForApproval(awardId,actor=null){submitter(actor);const award=db.prepare('SELECT * FROM procurement_awards WHERE id=?').get(String(awardId));if(!award)throw new Error('Adjudicacao nao encontrada.');const existing=latestForAward(award.id);if(existing?.status==='PENDING')return existing;if(award.status!=='DRAFT')throw new Error('Adjudicacao nao pode ser enviada para aprovacao neste status.');const levels=policyFor(Number(award.total_cents)),id=idFactory('approval'),ts=String(now());return withTransaction(db,()=>{db.prepare('INSERT INTO procurement_approval_requests(id,award_id,status,current_level,requested_total_cents,policy_snapshot_json,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,award.id,'PENDING',levels[0].level,Number(award.total_cents),JSON.stringify(levels),actor?.userId||null,ts,ts);db.prepare("UPDATE procurement_awards SET status='PENDING_APPROVAL',updated_at=? WHERE id=?").run(ts,award.id);writeAudit(db,{action:'procurement.approval.request',entity:'procurement-approval',entityId:id,actor,context:{awardId:award.id,totalCents:Number(award.total_cents),levels:levels.length}},now);if(events)events.outbox.insert(events.create('procurement.approval.requested','procurement-award',award.id,{approvalId:id},actor));return getApproval(id);});}
 function approveLevel(id,{reason=null}={},actor=null){const r=db.prepare('SELECT * FROM procurement_approval_requests WHERE id=?').get(String(id));if(!r)throw new Error('Aprovacao nao encontrada.');if(r.status==='APPROVED')return getApproval(id);if(r.status!=='PENDING')throw new Error('Aprovacao nao esta pendente.');const levels=JSON.parse(r.policy_snapshot_json),idx=levels.findIndex(x=>Number(x.level)===Number(r.current_level));if(idx<0)throw new Error('Nivel de aprovacao invalido.');assertRole(actor,levels[idx].roles);const ts=String(now());return withTransaction(db,()=>{db.prepare('INSERT INTO procurement_approval_actions(id,request_id,level,action,actor_user_id,actor_role,reason,created_at) VALUES(?,?,?,?,?,?,?,?)').run(idFactory('approval-action'),r.id,Number(r.current_level),'APPROVED',actor?.userId||null,actor?.role||null,reason||null,ts);if(idx<levels.length-1){db.prepare('UPDATE procurement_approval_requests SET current_level=?,updated_at=? WHERE id=?').run(Number(levels[idx+1].level),ts,r.id);}else{db.prepare("UPDATE procurement_approval_requests SET status='APPROVED',updated_at=? WHERE id=?").run(ts,r.id);db.prepare("UPDATE procurement_awards SET status='APPROVED',updated_at=? WHERE id=?").run(ts,r.award_id);}writeAudit(db,{action:'procurement.approval.approve',entity:'procurement-approval',entityId:r.id,actor,context:{level:Number(r.current_level)}},now);if(events)events.outbox.insert(events.create('procurement.approval.approved','procurement-award',r.award_id,{approvalId:r.id,level:Number(r.current_level)},actor));return getApproval(r.id);});}
 function rejectApproval(id,{reason}={},actor=null){const r=db.prepare('SELECT * FROM procurement_approval_requests WHERE id=?').get(String(id));if(!r)throw new Error('Aprovacao nao encontrada.');if(r.status!=='PENDING')throw new Error('Aprovacao nao esta pendente.');const levels=JSON.parse(r.policy_snapshot_json),level=levels.find(x=>Number(x.level)===Number(r.current_level));assertRole(actor,level?.roles||[]);const text=String(reason||'').trim();if(!text)throw new Error('Motivo da rejeicao obrigatorio.');const ts=String(now());return withTransaction(db,()=>{db.prepare('INSERT INTO procurement_approval_actions(id,request_id,level,action,actor_user_id,actor_role,reason,created_at) VALUES(?,?,?,?,?,?,?,?)').run(idFactory('approval-action'),r.id,Number(r.current_level),'REJECTED',actor?.userId||null,actor?.role||null,text,ts);db.prepare("UPDATE procurement_approval_requests SET status='REJECTED',updated_at=? WHERE id=?").run(ts,r.id);db.prepare("UPDATE procurement_awards SET status='REJECTED',updated_at=? WHERE id=?").run(ts,r.award_id);writeAudit(db,{action:'procurement.approval.reject',entity:'procurement-approval',entityId:r.id,actor,context:{reason:text}},now);if(events)events.outbox.insert(events.create('procurement.approval.rejected','procurement-award',r.award_id,{approvalId:r.id},actor));return getApproval(r.id);});}
 function invalidateAward(awardId,actor=null,reason='Alteracao relevante apos aprovacao.'){const r=db.prepare("SELECT * FROM procurement_approval_requests WHERE award_id=? AND status IN ('PENDING','APPROVED') ORDER BY created_at DESC,id DESC LIMIT 1").get(String(awardId));if(!r)return null;const ts=String(now());db.prepare("UPDATE procurement_approval_requests SET status='INVALIDATED',updated_at=? WHERE id=?").run(ts,r.id);db.prepare('INSERT INTO procurement_approval_actions(id,request_id,level,action,actor_user_id,actor_role,reason,created_at) VALUES(?,?,?,?,?,?,?,?)').run(idFactory('approval-action'),r.id,Number(r.current_level),'INVALIDATED',actor?.userId||null,actor?.role||null,String(reason),ts);writeAudit(db,{action:'procurement.approval.invalidate',entity:'procurement-approval',entityId:r.id,actor,context:{reason}},now);return getApproval(r.id);}
 return{submitAwardForApproval,approveLevel,rejectApproval,getApproval,latestForAward,invalidateAward};
}
module.exports={createApprovalService};
