'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
const {positiveQuantity}=require('../inventory/inventory-rules');
const {assertCents}=require('../shared/money');
function createAwardService({db,scoring,requisitions,procurement,approvals,events=null,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!scoring||!requisitions||!procurement||!approvals)throw new TypeError('award dependencies are required.');
 const manager=a=>assertRole(a,['admin','manager']);
 const itemMap=r=>r&&({id:r.id,awardId:r.award_id,requisitionItemId:r.requisition_item_id,productId:r.product_id,supplierId:r.supplier_id,quotationId:r.quotation_id,quantity:Number(r.quantity),unitCostCents:Number(r.unit_cost_cents),allocatedFreightCents:Number(r.allocated_freight_cents),paymentDays:Number(r.payment_days),deliveryDays:Number(r.delivery_days),createdAt:r.created_at,updatedAt:r.updated_at});
 function map(r){if(!r)return null;const items=db.prepare('SELECT * FROM procurement_award_items WHERE award_id=? ORDER BY created_at,id').all(r.id).map(itemMap);return{id:r.id,requisitionId:r.requisition_id,status:r.status,revision:Number(r.revision),supersedesAwardId:r.supersedes_award_id,totalCents:Number(r.total_cents),createdBy:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at,items};}
 function getAward(id){return map(db.prepare('SELECT * FROM procurement_awards WHERE id=?').get(String(id)));}
 function listAwards({requisitionId=null,status=null}={}){const c=[],p=[];if(requisitionId){c.push('requisition_id=?');p.push(String(requisitionId));}if(status){c.push('status=?');p.push(String(status).toUpperCase());}return db.prepare(`SELECT * FROM procurement_awards${c.length?` WHERE ${c.join(' AND ')}`:''} ORDER BY created_at DESC,id DESC`).all(...p).map(map);}
 function normalizeItems(req,items){const reqMap=new Map(req.items.map(x=>[x.productId,x]));const seen=new Set();return items.map(x=>{const productId=String(x.productId),ri=reqMap.get(productId);if(!ri)throw new Error('Produto nao pertence a solicitacao.');const key=`${productId}:${String(x.supplierId)}`;if(seen.has(key))throw new Error('Item/fornecedor duplicado na adjudicacao.');seen.add(key);const quantity=positiveQuantity(x.quantity,'Quantidade'),unitCostCents=assertCents(x.unitCostCents,'unitCostCents'),allocatedFreightCents=assertCents(x.allocatedFreightCents??x.freightCents??0,'allocatedFreightCents');if(unitCostCents<0||allocatedFreightCents<0)throw new Error('Valor invalido na adjudicacao.');return{requisitionItemId:String(x.requisitionItemId||ri.id),productId,supplierId:String(x.supplierId),quotationId:String(x.quotationId),quantity,unitCostCents,allocatedFreightCents,paymentDays:Number(x.paymentDays||0),deliveryDays:Number(x.deliveryDays||0)};});}
 function insertAward({id,requisitionId,revision=1,supersedesAwardId=null,items,actor}){const req=requisitions.getRequisition(requisitionId);if(!req)throw new Error('Solicitacao nao encontrada.');const normalized=normalizeItems(req,items);const total=normalized.reduce((s,x)=>s+Math.round(x.quantity*x.unitCostCents)+x.allocatedFreightCents,0),ts=String(now());db.prepare("INSERT INTO procurement_awards(id,requisition_id,status,revision,supersedes_award_id,total_cents,created_by,created_at,updated_at) VALUES(?,?,'DRAFT',?,?,?,?,?,?)").run(id,req.id,revision,supersedesAwardId,total,actor?.userId||null,ts,ts);const ins=db.prepare('INSERT INTO procurement_award_items(id,award_id,requisition_item_id,product_id,supplier_id,quotation_id,quantity,unit_cost_cents,allocated_freight_cents,payment_days,delivery_days,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');for(const x of normalized)ins.run(idFactory('award-item'),id,x.requisitionItemId,x.productId,x.supplierId,x.quotationId,x.quantity,x.unitCostCents,x.allocatedFreightCents,x.paymentDays,x.deliveryDays,ts,ts);return getAward(id);}
 function createAwardFromSuggestion(requisitionId,actor=null){manager(actor);const s=scoring.suggest(requisitionId),id=idFactory('award');return withTransaction(db,()=>{const award=insertAward({id,requisitionId,items:s.items.map(x=>({...x.selected,requisitionItemId:x.requisitionItemId,productId:x.productId})),actor});writeAudit(db,{action:'procurement.award.create',entity:'procurement-award',entityId:id,actor,context:{requisitionId,supplierCount:new Set(award.items.map(x=>x.supplierId)).size}},now);return award;});}
 function updateAward(id,input={},actor=null){manager(actor);const current=getAward(id);if(!current)throw new Error('Adjudicacao nao encontrada.');const req=requisitions.getRequisition(current.requisitionId),items=input.items||current.items;if(current.status==='DRAFT'){const normalized=normalizeItems(req,items),total=normalized.reduce((s,x)=>s+Math.round(x.quantity*x.unitCostCents)+x.allocatedFreightCents,0),ts=String(now());return withTransaction(db,()=>{db.prepare('DELETE FROM procurement_award_items WHERE award_id=?').run(current.id);db.prepare('UPDATE procurement_awards SET total_cents=?,updated_at=? WHERE id=?').run(total,ts,current.id);const ins=db.prepare('INSERT INTO procurement_award_items(id,award_id,requisition_item_id,product_id,supplier_id,quotation_id,quantity,unit_cost_cents,allocated_freight_cents,payment_days,delivery_days,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');for(const x of normalized)ins.run(idFactory('award-item'),current.id,x.requisitionItemId,x.productId,x.supplierId,x.quotationId,x.quantity,x.unitCostCents,x.allocatedFreightCents,x.paymentDays,x.deliveryDays,ts,ts);writeAudit(db,{action:'procurement.award.update',entity:'procurement-award',entityId:current.id,actor,context:{}},now);return getAward(current.id);});}
 const newId=idFactory('award'),ts=String(now());return withTransaction(db,()=>{approvals.invalidateAward(current.id,actor);db.prepare("UPDATE procurement_awards SET status='SUPERSEDED',updated_at=? WHERE id=?").run(ts,current.id);const replacement=insertAward({id:newId,requisitionId:current.requisitionId,revision:current.revision+1,supersedesAwardId:current.id,items,actor});writeAudit(db,{action:'procurement.award.supersede',entity:'procurement-award',entityId:current.id,actor,context:{replacementAwardId:newId}},now);return replacement;});}
 function generateOrders(id,actor=null){manager(actor);const award=getAward(id);if(!award)throw new Error('Adjudicacao nao encontrada.');if(award.status==='ORDERS_CREATED'){const ids=db.prepare('SELECT order_id FROM purchase_order_sources WHERE award_id=? ORDER BY order_id').all(award.id);return ids.map(x=>procurement.getPurchaseOrder(x.order_id));}if(award.status!=='APPROVED')throw new Error('Adjudicacao precisa estar aprovada.');const req=requisitions.getRequisition(award.requisitionId),groups=new Map();for(const item of award.items){if(!groups.has(item.supplierId))groups.set(item.supplierId,[]);groups.get(item.supplierId).push(item);}return withTransaction(db,()=>{const orders=[];for(const [supplierId,items] of groups){const po=procurement.createPurchaseOrder({supplierId,locationId:req.locationId,notes:`Gerado da adjudicacao ${award.id}`,items:items.map(x=>({productId:x.productId,quantity:x.quantity,unitCostCents:x.unitCostCents}))},actor);db.prepare('INSERT INTO purchase_order_sources(order_id,award_id,supplier_id,created_at) VALUES(?,?,?,?)').run(po.id,award.id,supplierId,String(now()));orders.push(po);}const ts=String(now());db.prepare("UPDATE procurement_awards SET status='ORDERS_CREATED',updated_at=? WHERE id=?").run(ts,award.id);db.prepare("UPDATE purchase_requisitions SET status='AWARDED',updated_at=? WHERE id=?").run(ts,award.requisitionId);writeAudit(db,{action:'procurement.award.orders',entity:'procurement-award',entityId:award.id,actor,context:{orderCount:orders.length}},now);if(events)events.outbox.insert(events.create('procurement.order.created','procurement-award',award.id,{orderIds:orders.map(x=>x.id)},actor));return orders;});}
 return{createAwardFromSuggestion,updateAward,generateOrders,getAward,listAwards};
}
module.exports={createAwardService};
