'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
const {assertCents}=require('../shared/money');
const {positiveQuantity}=require('../inventory/inventory-rules');
function createQuotationService({db,contacts,catalog,requisitions,events=null,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!contacts||!catalog||!requisitions)throw new TypeError('quotation dependencies are required.');
 const manager=a=>assertRole(a,['admin','manager']);
 const itemMap=r=>r&&({id:r.id,quotationId:r.quotation_id,requisitionItemId:r.requisition_item_id,productId:r.product_id,unitCostCents:Number(r.unit_cost_cents),availableQuantity:Number(r.available_quantity),deliveryDays:Number(r.delivery_days),createdAt:r.created_at,updatedAt:r.updated_at});
 function map(r){if(!r)return null;const items=db.prepare('SELECT * FROM supplier_quotation_items WHERE quotation_id=? ORDER BY created_at,id').all(r.id).map(itemMap);return{id:r.id,requisitionId:r.requisition_id,supplierId:r.supplier_id,status:r.status,freightCents:Number(r.freight_cents),paymentDays:Number(r.payment_days),validUntil:r.valid_until,notes:r.notes,createdBy:r.created_by,submittedAt:r.submitted_at,createdAt:r.created_at,updatedAt:r.updated_at,items};}
 function getQuotation(id){return map(db.prepare('SELECT * FROM supplier_quotations WHERE id=?').get(String(id)));}
 function requireQuote(id){const r=db.prepare('SELECT * FROM supplier_quotations WHERE id=?').get(String(id));if(!r)throw new Error('Cotacao nao encontrada.');return r;}
 function normalize(input,req){contacts.requireSupplier(input.supplierId);const freightCents=assertCents(input.freightCents??0,'freightCents');if(freightCents<0)throw new Error('Frete invalido.');const paymentDays=Math.trunc(Number(input.paymentDays??0));if(!Number.isFinite(paymentDays)||paymentDays<0)throw new Error('Prazo de pagamento invalido.');if(!Array.isArray(input.items)||!input.items.length)throw new Error('Cotacao deve possuir itens.');const reqItems=new Map(req.items.map(x=>[x.productId,x]));const seen=new Set();const items=input.items.map(x=>{const p=catalog.requireActiveProduct(x.productId);if(seen.has(p.id))throw new Error('Produto duplicado na cotacao.');seen.add(p.id);const ri=reqItems.get(p.id);if(!ri)throw new Error('Produto nao pertence a solicitacao.');const unitCostCents=assertCents(x.unitCostCents,'unitCostCents');if(unitCostCents<0)throw new Error('Preco invalido.');const availableQuantity=Number(x.availableQuantity);if(!Number.isFinite(availableQuantity)||availableQuantity<0)throw new Error('Disponibilidade invalida.');const deliveryDays=Math.trunc(Number(x.deliveryDays??0));if(!Number.isFinite(deliveryDays)||deliveryDays<0)throw new Error('Prazo de entrega invalido.');return{requisitionItemId:ri.id,productId:p.id,unitCostCents,availableQuantity,deliveryDays};});return{freightCents,paymentDays,validUntil:input.validUntil||null,notes:input.notes||null,items};}
 function createQuotation(input={},actor=null){manager(actor);const req=requisitions.getRequisition(input.requisitionId);if(!req)throw new Error('Solicitacao de compra nao encontrada.');if(req.status!=='QUOTING')throw new Error('Solicitacao nao esta em cotacao.');const n=normalize(input,req),id=String(input.id||idFactory('quote')),ts=String(now());return withTransaction(db,()=>{db.prepare("INSERT INTO supplier_quotations(id,requisition_id,supplier_id,status,freight_cents,payment_days,valid_until,notes,created_by,created_at,updated_at) VALUES(?,?,?,'DRAFT',?,?,?,?,?,?,?)").run(id,req.id,String(input.supplierId),n.freightCents,n.paymentDays,n.validUntil,n.notes,actor?.userId||null,ts,ts);const ins=db.prepare('INSERT INTO supplier_quotation_items(id,quotation_id,requisition_item_id,product_id,unit_cost_cents,available_quantity,delivery_days,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');for(const x of n.items)ins.run(idFactory('qi'),id,x.requisitionItemId,x.productId,x.unitCostCents,x.availableQuantity,x.deliveryDays,ts,ts);writeAudit(db,{action:'procurement.quotation.create',entity:'supplier-quotation',entityId:id,actor,context:{requisitionId:req.id,supplierId:input.supplierId}},now);return getQuotation(id);});}
 function updateQuotation(id,input={},actor=null){manager(actor);const q=requireQuote(id);if(q.status!=='DRAFT')throw new Error('Somente cotacao em rascunho pode ser alterada.');const current=getQuotation(id),req=requisitions.getRequisition(q.requisition_id);const n=normalize({supplierId:input.supplierId??current.supplierId,freightCents:input.freightCents??current.freightCents,paymentDays:input.paymentDays??current.paymentDays,validUntil:input.validUntil??current.validUntil,notes:input.notes??current.notes,items:input.items??current.items},req);const ts=String(now());return withTransaction(db,()=>{db.prepare('UPDATE supplier_quotations SET supplier_id=?,freight_cents=?,payment_days=?,valid_until=?,notes=?,updated_at=? WHERE id=?').run(String(input.supplierId??current.supplierId),n.freightCents,n.paymentDays,n.validUntil,n.notes,ts,q.id);if(input.items){db.prepare('DELETE FROM supplier_quotation_items WHERE quotation_id=?').run(q.id);const ins=db.prepare('INSERT INTO supplier_quotation_items(id,quotation_id,requisition_item_id,product_id,unit_cost_cents,available_quantity,delivery_days,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');for(const x of n.items)ins.run(idFactory('qi'),q.id,x.requisitionItemId,x.productId,x.unitCostCents,x.availableQuantity,x.deliveryDays,ts,ts);}writeAudit(db,{action:'procurement.quotation.update',entity:'supplier-quotation',entityId:q.id,actor,context:{}},now);return getQuotation(q.id);});}
 function submitQuotation(id,actor=null){manager(actor);const q=requireQuote(id);if(q.status==='SUBMITTED')return getQuotation(id);if(q.status!=='DRAFT')throw new Error('Cotacao nao pode ser enviada neste status.');if(q.valid_until&&Date.parse(q.valid_until)<Date.parse(now()))throw new Error('Cotacao vencida.');const ts=String(now());return withTransaction(db,()=>{db.prepare("UPDATE supplier_quotations SET status='SUBMITTED',submitted_at=?,updated_at=? WHERE id=?").run(ts,ts,q.id);const full=getQuotation(q.id),ins=db.prepare('INSERT INTO supplier_price_history(id,product_id,supplier_id,quotation_id,unit_cost_cents,freight_cents,payment_days,delivery_days,quoted_at) VALUES(?,?,?,?,?,?,?,?,?)');for(const x of full.items)ins.run(idFactory('price'),x.productId,full.supplierId,full.id,x.unitCostCents,full.freightCents,full.paymentDays,x.deliveryDays,ts);writeAudit(db,{action:'procurement.quotation.submit',entity:'supplier-quotation',entityId:q.id,actor,context:{}},now);if(events)events.outbox.insert(events.create('procurement.quotation.received','supplier-quotation',q.id,{requisitionId:q.requisition_id},actor));return getQuotation(q.id);});}
 function listQuotations({requisitionId=null,supplierId=null,status=null}={}){const c=[],p=[];if(requisitionId){c.push('requisition_id=?');p.push(String(requisitionId));}if(supplierId){c.push('supplier_id=?');p.push(String(supplierId));}if(status){c.push('status=?');p.push(String(status).toUpperCase());}return db.prepare(`SELECT * FROM supplier_quotations${c.length?` WHERE ${c.join(' AND ')}`:''} ORDER BY created_at,id`).all(...p).map(map);}
 return{createQuotation,updateQuotation,submitQuotation,getQuotation,listQuotations};
}
module.exports={createQuotationService};
