'use strict';
const {randomUUID}=require('node:crypto');

function createReceiptService({db,settings=null,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db)throw new TypeError('Database is required.');
 function tolerancePercent(){const raw=settings?.get?.('procurement.receiptExcessTolerancePercent',{defaultValue:0});const n=Number(raw);return Number.isFinite(n)&&n>=0?n:0;}
 function calculate(poItem,quantity,excessAuthorization=null){const ordered=Number(poItem.quantity),previous=Number(poItem.received_quantity),receivedThisTime=Number(quantity),projected=previous+receivedThisTime,missing=Math.max(ordered-projected,0),excess=Math.max(projected-ordered,0),variancePercent=ordered>0?(excess/ordered)*100:0,tolerance=tolerancePercent();if(excess>0&&variancePercent>tolerance){const reason=String(excessAuthorization?.reason||'').trim();if(!reason)throw new Error('Excedente acima da tolerancia exige autorizacao com motivo.');}return{orderedQuantity:ordered,previousReceived:previous,receivedThisTime,receivedTotal:projected,missingQuantity:missing,excessQuantity:excess,variancePercent,tolerancePercent:tolerance,status:excess>0?'EXCESS':missing>0?'PARTIAL':'COMPLETE',authorizationReason:String(excessAuthorization?.reason||'').trim()||null};}
 function persist({receiptId,poItem,variance,actor=null}){db.prepare('INSERT INTO purchase_receipt_variances(id,receipt_id,order_item_id,ordered_quantity,previous_received,received_this_time,projected_total,missing_quantity,excess_quantity,variance_percent,tolerance_percent,authorized_by,authorization_reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(idFactory('prv'),String(receiptId),String(poItem.id),variance.orderedQuantity,variance.previousReceived,variance.receivedThisTime,variance.receivedTotal,variance.missingQuantity,variance.excessQuantity,variance.variancePercent,variance.tolerancePercent,variance.excessQuantity>0&&variance.authorizationReason?actor?.userId||null:null,variance.authorizationReason,String(now()));return variance;}
 function get(receiptId,orderItemId){const r=db.prepare('SELECT * FROM purchase_receipt_variances WHERE receipt_id=? AND order_item_id=? ORDER BY created_at DESC,id DESC LIMIT 1').get(String(receiptId),String(orderItemId));return r&&{orderedQuantity:Number(r.ordered_quantity),previousReceived:Number(r.previous_received),receivedThisTime:Number(r.received_this_time),receivedTotal:Number(r.projected_total),missingQuantity:Number(r.missing_quantity),excessQuantity:Number(r.excess_quantity),variancePercent:Number(r.variance_percent),tolerancePercent:Number(r.tolerance_percent),status:Number(r.excess_quantity)>0?'EXCESS':Number(r.missing_quantity)>0?'PARTIAL':'COMPLETE',authorizedBy:r.authorized_by,authorizationReason:r.authorization_reason};}
 return{calculate,persist,get,tolerancePercent};
}
module.exports={createReceiptService};
