'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
const {positiveQuantity}=require('../inventory/inventory-rules');
function createRequisitionService({db,catalog,inventory,events=null,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!catalog||!inventory)throw new TypeError('requisition dependencies are required.');
 const manager=a=>assertRole(a,['admin','manager']);
 const items=id=>db.prepare('SELECT * FROM purchase_requisition_items WHERE requisition_id=? ORDER BY created_at,id').all(String(id)).map(r=>({id:r.id,requisitionId:r.requisition_id,productId:r.product_id,quantity:Number(r.quantity),createdAt:r.created_at,updatedAt:r.updated_at}));
 const map=r=>r&&({id:r.id,locationId:r.location_id,status:r.status,justification:r.justification,notes:r.notes,createdBy:r.created_by,submittedAt:r.submitted_at,cancelledAt:r.cancelled_at,cancellationReason:r.cancellation_reason,createdAt:r.created_at,updatedAt:r.updated_at,items:items(r.id)});
 function getRequisition(id){return map(db.prepare('SELECT * FROM purchase_requisitions WHERE id=?').get(String(id)));}
 function requireReq(id){const r=db.prepare('SELECT * FROM purchase_requisitions WHERE id=?').get(String(id));if(!r)throw new Error('Solicitacao de compra nao encontrada.');return r;}
 function normalize(input){inventory.requireLocation(input.locationId||'MAIN');const justification=String(input.justification||'').trim();if(!justification)throw new Error('Justificativa obrigatoria.');if(!Array.isArray(input.items)||!input.items.length)throw new Error('Solicitacao deve possuir itens.');const seen=new Set();const list=input.items.map(x=>{const p=catalog.requireActiveProduct(x.productId);if(seen.has(p.id))throw new Error('Produto duplicado na solicitacao.');seen.add(p.id);return{productId:p.id,quantity:positiveQuantity(x.quantity,'Quantidade')};});return{locationId:String(input.locationId||'MAIN'),justification,notes:input.notes||null,items:list};}
 function createRequisition(input={},actor=null){manager(actor);const n=normalize(input),id=String(input.id||idFactory('req')),ts=String(now());return withTransaction(db,()=>{db.prepare("INSERT INTO purchase_requisitions(id,location_id,status,justification,notes,created_by,created_at,updated_at) VALUES(?,?,'DRAFT',?,?,?,?,?)").run(id,n.locationId,n.justification,n.notes,actor?.userId||null,ts,ts);const ins=db.prepare('INSERT INTO purchase_requisition_items(id,requisition_id,product_id,quantity,created_at,updated_at) VALUES(?,?,?,?,?,?)');for(const x of n.items)ins.run(idFactory('reqi'),id,x.productId,x.quantity,ts,ts);writeAudit(db,{action:'procurement.request.create',entity:'purchase-requisition',entityId:id,actor,context:{itemCount:n.items.length}},now);if(events)events.outbox.insert(events.create('procurement.request.created','purchase-requisition',id,{itemCount:n.items.length},actor));return getRequisition(id);});}
 function updateRequisition(id,input={},actor=null){manager(actor);const r=requireReq(id);if(r.status!=='DRAFT')throw new Error('Somente solicitacao em rascunho pode ser alterada.');const current=getRequisition(id);const n=normalize({locationId:input.locationId??current.locationId,justification:input.justification??current.justification,notes:input.notes??current.notes,items:input.items??current.items});const ts=String(now());return withTransaction(db,()=>{db.prepare('UPDATE purchase_requisitions SET location_id=?,justification=?,notes=?,updated_at=? WHERE id=?').run(n.locationId,n.justification,n.notes,ts,r.id);if(input.items){db.prepare('DELETE FROM purchase_requisition_items WHERE requisition_id=?').run(r.id);const ins=db.prepare('INSERT INTO purchase_requisition_items(id,requisition_id,product_id,quantity,created_at,updated_at) VALUES(?,?,?,?,?,?)');for(const x of n.items)ins.run(idFactory('reqi'),r.id,x.productId,x.quantity,ts,ts);}writeAudit(db,{action:'procurement.request.update',entity:'purchase-requisition',entityId:r.id,actor,context:{}},now);return getRequisition(r.id);});}
 function submitForQuotation(id,actor=null){manager(actor);const r=requireReq(id);if(r.status==='QUOTING')return getRequisition(id);if(r.status!=='DRAFT')throw new Error('Solicitacao nao pode entrar em cotacao neste status.');const ts=String(now());db.prepare("UPDATE purchase_requisitions SET status='QUOTING',submitted_at=?,updated_at=? WHERE id=?").run(ts,ts,r.id);writeAudit(db,{action:'procurement.request.quote',entity:'purchase-requisition',entityId:r.id,actor,context:{}},now);return getRequisition(r.id);}
 function cancelRequisition(id,{reason}={},actor=null){manager(actor);const r=requireReq(id);if(r.status==='CANCELLED')return getRequisition(id);const text=String(reason||'').trim();if(!text)throw new Error('Motivo do cancelamento obrigatorio.');const ts=String(now());db.prepare("UPDATE purchase_requisitions SET status='CANCELLED',cancelled_at=?,cancellation_reason=?,updated_at=? WHERE id=?").run(ts,text,ts,r.id);writeAudit(db,{action:'procurement.request.cancel',entity:'purchase-requisition',entityId:r.id,actor,context:{reason:text}},now);return getRequisition(r.id);}
 function listRequisitions({status=null}={}){const rows=status?db.prepare('SELECT * FROM purchase_requisitions WHERE status=? ORDER BY created_at DESC,id').all(String(status).toUpperCase()):db.prepare('SELECT * FROM purchase_requisitions ORDER BY created_at DESC,id').all();return rows.map(map);}
 return{createRequisition,updateRequisition,submitForQuotation,cancelRequisition,getRequisition,listRequisitions};
}
module.exports={createRequisitionService};
