'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
const {positiveQuantity}=require('../inventory/inventory-rules');
function createReturnService({db,inventory,finance,supplierCredits,events=null,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db||!inventory||!finance||!supplierCredits)throw new TypeError('return dependencies are required.');
 const manager=a=>assertRole(a,['admin','manager']);
 function map(r){if(!r)return null;const items=db.prepare('SELECT * FROM purchase_return_items WHERE return_id=? ORDER BY created_at,id').all(r.id).map(x=>({id:x.id,returnId:x.return_id,receiptItemId:x.receipt_item_id,productId:x.product_id,quantity:Number(x.quantity),unitCostCents:Number(x.unit_cost_cents),totalCents:Number(x.total_cents),createdAt:x.created_at}));return{id:r.id,receiptId:r.receipt_id,supplierId:r.supplier_id,idempotencyKey:r.idempotency_key,totalCents:Number(r.total_cents),reason:r.reason,createdBy:r.created_by,createdAt:r.created_at,items};}
 function getReturn(id){return map(db.prepare('SELECT * FROM purchase_returns WHERE id=?').get(String(id)));}
 function listReturns({receiptId=null,supplierId=null}={}){const c=[],p=[];if(receiptId){c.push('receipt_id=?');p.push(String(receiptId));}if(supplierId){c.push('supplier_id=?');p.push(String(supplierId));}return db.prepare(`SELECT * FROM purchase_returns${c.length?` WHERE ${c.join(' AND ')}`:''} ORDER BY created_at DESC,id DESC`).all(...p).map(map);}
 function createReturn(receiptId,input={},actor=null){manager(actor);const key=String(input.idempotencyKey||'').trim();if(!key)throw new Error('Chave de idempotencia obrigatoria na devolucao.');const prev=db.prepare('SELECT * FROM purchase_returns WHERE idempotency_key=?').get(key);if(prev)return map(prev);const reason=String(input.reason||'').trim();if(!reason)throw new Error('Motivo da devolucao obrigatorio.');const receipt=db.prepare('SELECT * FROM purchase_receipts WHERE id=?').get(String(receiptId));if(!receipt)throw new Error('Recebimento nao encontrado.');const order=db.prepare('SELECT * FROM purchase_orders WHERE id=?').get(receipt.order_id);if(!order)throw new Error('Pedido de compra nao encontrado.');if(!Array.isArray(input.items)||!input.items.length)throw new Error('Devolucao deve possuir itens.');const receiptItems=db.prepare('SELECT * FROM purchase_receipt_items WHERE receipt_id=?').all(receipt.id),byProduct=new Map(receiptItems.map(x=>[x.product_id,x])),seen=new Set(),items=[];let totalCents=0;for(const x of input.items){const productId=String(x.productId||'');if(seen.has(productId))throw new Error('Produto duplicado na devolucao.');seen.add(productId);const ri=byProduct.get(productId);if(!ri)throw new Error('Produto nao pertence ao recebimento.');const quantity=positiveQuantity(x.quantity,'Quantidade devolvida');const already=Number(db.prepare('SELECT COALESCE(SUM(i.quantity),0) n FROM purchase_return_items i JOIN purchase_returns r ON r.id=i.return_id WHERE i.receipt_item_id=?').get(ri.id)?.n||0);if(quantity>Number(ri.quantity)-already)throw new Error('Quantidade devolvida excede saldo do recebimento.');const line=Math.round(quantity*Number(ri.unit_cost_cents));items.push({receiptItem:ri,productId,quantity,unitCostCents:Number(ri.unit_cost_cents),totalCents:line});totalCents+=line;}
 const returnId=String(input.id||idFactory('return')),ts=String(now());return withTransaction(db,()=>{const again=db.prepare('SELECT * FROM purchase_returns WHERE idempotency_key=?').get(key);if(again)return map(again);db.prepare('INSERT INTO purchase_returns(id,receipt_id,supplier_id,idempotency_key,total_cents,reason,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)').run(returnId,receipt.id,order.supplier_id,key,totalCents,reason,actor?.userId||null,ts);const ins=db.prepare('INSERT INTO purchase_return_items(id,return_id,receipt_item_id,product_id,quantity,unit_cost_cents,total_cents,created_at) VALUES(?,?,?,?,?,?,?,?)');for(const x of items){inventory.move({productId:x.productId,locationId:order.location_id,delta:-x.quantity,unitCostCents:x.unitCostCents,sourceType:'purchase-return',sourceId:returnId},actor);ins.run(idFactory('return-item'),returnId,x.receiptItem.id,x.productId,x.quantity,x.unitCostCents,x.totalCents,ts);}let creditCents=totalCents;if(receipt.payable_entry_id){const payable=finance.getEntry(receipt.payable_entry_id);const reducible=Math.min(totalCents,payable?.openCents||0);if(reducible>0){finance.adjustEntry(receipt.payable_entry_id,{deltaCents:-reducible,reason:`Devolucao ${returnId}: ${reason}`,sourceType:'purchase-return',sourceId:returnId,idempotencyKey:`purchase-return:${returnId}:payable`},actor);creditCents-=reducible;}}if(creditCents>0)supplierCredits.createCredit({supplierId:order.supplier_id,sourceReturnId:returnId,amountCents:creditCents},actor);writeAudit(db,{action:'procurement.return.create',entity:'purchase-return',entityId:returnId,actor,context:{receiptId:receipt.id,totalCents,creditCents,reason}},now);if(events)events.outbox.insert(events.create('procurement.return.completed','purchase-return',returnId,{receiptId:receipt.id,totalCents,creditCents},actor,key));return getReturn(returnId);});}
 return{createReturn,getReturn,listReturns};
}
module.exports={createReturnService};
