'use strict';
(()=>{
 window.ErpViews=window.ErpViews||{};const esc=v=>window.ErpUi.escapeHtml(v),status=v=>window.ErpUi.statusLabel(v),bytes=v=>{const n=Number(v)||0;if(n<1024)return`${n} B`;if(n<1024*1024)return`${(n/1024).toFixed(1)} KB`;return`${(n/1024/1024).toFixed(1)} MB`;};
 window.ErpViews.administracao=async function administracao({api,root}){
  let tab='companies';root.innerHTML=`<section data-testid="admin-root"><div class="tabs" id="admin-tabs"><button data-tab="companies" class="active">Empresas</button><button data-tab="users">Usuários</button><button data-tab="backups">Backups</button><button data-tab="documents">Documentos</button><button data-tab="integrations">Integrações</button></div><div id="admin-content">${window.ErpUi.loading()}</div></section>`;const area=root.querySelector('#admin-content');
  const formError=(form,error)=>{let box=form.querySelector('.form-error');if(!box){box=document.createElement('div');box.className='form-error';form.append(box);}box.textContent=error?.message||String(error);};
  function companyForm(){const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field full"><span>Razão/nome da empresa</span><input name="name" data-testid="admin-company-name" required></label><label class="form-field full"><span>CNPJ/CPF</span><input name="taxId" placeholder="Opcional"></label>`;return f;}
  function userForm(companies){const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field"><span>Usuário</span><input name="username" data-testid="admin-user-username" required></label><label class="form-field"><span>Nome</span><input name="name" data-testid="admin-user-name" required></label><label class="form-field"><span>Senha inicial</span><input name="password" type="password" data-testid="admin-user-password" required></label><label class="form-field"><span>Perfil</span><select name="role"><option value="operator">Operador</option><option value="manager">Gerente</option><option value="director">Diretor</option><option value="admin">Administrador</option></select></label><fieldset class="form-field full"><legend>Empresas permitidas</legend>${companies.map((c,i)=>`<label class="check-row"><input type="checkbox" name="company-${esc(c.id)}" value="${esc(c.id)}" ${i===0?'checked':''}> ${esc(c.name)}</label>`).join('')}</fieldset>`;return f;}
  async function renderCompanies(){const companies=await api.request('/api/v1/admin/companies');area.innerHTML=`<div class="panel"><div class="section-head"><div><h3>Empresas</h3><p class="muted">Separe acessos e contexto operacional por empresa.</p></div><button class="primary" data-testid="admin-company-new">Nova empresa</button></div>${companies.length?`<table><thead><tr><th>Empresa</th><th>Documento</th><th>Status</th><th>Ação</th></tr></thead><tbody>${companies.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.taxId||'-')}</td><td>${c.active?'Ativa':'Inativa'}</td><td><button data-company-use="${esc(c.id)}">Usar esta empresa</button></td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty()}</div>`;}
  async function renderUsers(){const users=await api.request('/api/v1/admin/users');area.innerHTML=`<div class="panel"><div class="section-head"><div><h3>Usuários</h3><p class="muted">Perfis e acesso por empresa.</p></div><button class="primary" data-testid="admin-user-new">Novo usuário</button></div>${users.length?`<table><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th>Empresas</th><th>Status</th><th>Ação</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${esc(status(u.role))}</td><td>${esc((u.companies||[]).map(c=>c.name).join(', ')||'-')}</td><td>${u.active?'Ativo':'Inativo'}</td><td><button data-user-active="${esc(u.id)}" data-active="${u.active?'0':'1'}">${u.active?'Inativar':'Reativar'}</button></td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty()}</div>`;}
  async function renderBackups(){const backups=await api.request('/api/v1/admin/backups');area.innerHTML=`<div class="panel"><div class="section-head"><div><h3>Backups</h3><p class="muted">Snapshots consistentes do banco local. A restauração é preparada e exige reinício.</p></div><button class="primary" data-testid="admin-backup-create">Criar backup agora</button></div>${backups.length?`<table><thead><tr><th>Arquivo</th><th>Tamanho</th><th>Data</th><th>Ação</th></tr></thead><tbody>${backups.map(b=>`<tr><td>${esc(b.name)}</td><td>${esc(bytes(b.size))}</td><td>${esc(String(b.modifiedAt||'').replace('T',' ').slice(0,19))}</td><td><button class="danger" data-backup-restore="${esc(b.name)}">Preparar restauração</button></td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhum backup criado.')}</div>`;}
  async function renderDocuments(){const docs=await api.request('/api/v1/admin/documents');area.innerHTML=`<div class="panel"><div class="section-head"><div><h3>Documentos</h3><p class="muted">Arquivos copiados para o armazenamento local controlado do ERP.</p></div><button class="primary" data-testid="admin-document-import">Adicionar documento</button></div>${docs.length?`<table><thead><tr><th>Título</th><th>Arquivo</th><th>Tamanho</th><th>Vínculo</th><th>Data</th><th>Ação</th></tr></thead><tbody>${docs.map(d=>`<tr><td>${esc(d.title)}</td><td>${esc(d.originalName)}</td><td>${esc(bytes(d.sizeBytes))}</td><td>${esc(d.entityType||'-')}${d.entityId?` · ${esc(d.entityId)}`:''}</td><td>${esc(String(d.createdAt||'').replace('T',' ').slice(0,19))}</td><td><button class="danger" data-document-delete="${esc(d.id)}">Excluir</button></td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhum documento armazenado.')}</div>`;}
  async function renderIntegrations(){const [integrations,banks]=await Promise.all([api.request('/api/v1/admin/integrations'),api.request('/api/v1/admin/bank-connections')]);area.innerHTML=`<div class="grid"><div class="panel"><div class="section-head"><div><h3>Integrações externas</h3><p class="muted">Configurações opcionais; o core funciona sem elas.</p></div><button class="primary" data-testid="admin-integration-new">Nova integração</button></div>${integrations.length?`<table><thead><tr><th>Nome</th><th>Tipo</th><th>Endpoint</th><th>Status</th></tr></thead><tbody>${integrations.map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.kind)}</td><td>${esc(i.endpoint||'-')}</td><td>${i.active?'Ativa':'Inativa'}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhuma integração configurada.')}</div><div class="panel"><div class="section-head"><div><h3>Conexões bancárias</h3><p class="muted">OFX/CSV/PDF/manual continuam disponíveis sem conexão remota.</p></div><button data-testid="admin-bank-new">Nova conexão</button></div>${banks.length?`<table><thead><tr><th>Nome</th><th>Provedor</th><th>Conta</th><th>Status</th></tr></thead><tbody>${banks.map(b=>`<tr><td>${esc(b.name)}</td><td>${esc(b.provider)}</td><td>${esc(b.accountId||'-')}</td><td>${b.active?'Ativa':'Inativa'}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhuma conexão bancária configurada.')}</div></div>`;}
  async function render(){area.innerHTML=window.ErpUi.loading();try{if(tab==='companies')await renderCompanies();if(tab==='users')await renderUsers();if(tab==='backups')await renderBackups();if(tab==='documents')await renderDocuments();if(tab==='integrations')await renderIntegrations();}catch(error){area.innerHTML=window.ErpUi.errorState(error.message);}}
  root.querySelector('#admin-tabs').addEventListener('click',event=>{const b=event.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;root.querySelectorAll('#admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));render();});
  root.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{
   if(b.matches('[data-testid="admin-company-new"]')){const f=companyForm();window.ErpUi.openModal({title:'Nova empresa',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId:'admin-company-save',onClick:async()=>{try{await api.request('/api/v1/admin/companies',{method:'POST',body:window.ErpForms.values(f)});window.ErpUi.closeModal();await render();}catch(e){formError(f,e);}}}]});return;}
   if(b.dataset.companyUse){await api.request('/api/v1/auth/company',{method:'POST',body:{companyId:b.dataset.companyUse}});window.ErpUi.toast('Empresa ativa alterada.');document.dispatchEvent(new CustomEvent('erp:company-changed'));return;}
   if(b.matches('[data-testid="admin-user-new"]')){const companies=await api.request('/api/v1/admin/companies'),f=userForm(companies);window.ErpUi.openModal({title:'Novo usuário',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Criar',primary:true,testId:'admin-user-save',onClick:async()=>{try{const values=window.ErpForms.values(f),companyIds=companies.filter(c=>f.querySelector(`[name="company-${CSS.escape(c.id)}"]`)?.checked).map(c=>c.id);await api.request('/api/v1/admin/users',{method:'POST',body:{username:values.username,name:values.name,password:values.password,role:values.role,companyIds}});window.ErpUi.closeModal();await render();}catch(e){formError(f,e);}}}]});return;}
   if(b.dataset.userActive){await api.request(`/api/v1/admin/users/${encodeURIComponent(b.dataset.userActive)}/active`,{method:'POST',body:{active:b.dataset.active==='1'}});await render();return;}
   if(b.matches('[data-testid="admin-backup-create"]')){await api.request('/api/v1/admin/backups',{method:'POST',body:{label:'manual'}});window.ErpUi.toast('Backup criado.');await render();return;}
   if(b.dataset.backupRestore){const ok=await window.ErpUi.confirm({title:'Preparar restauração',message:'O backup será preparado para restauração. Feche e reinicie o ERP para concluir a troca do banco.',confirmLabel:'Preparar',danger:true});if(!ok)return;await api.request('/api/v1/admin/backups/restore',{method:'POST',body:{name:b.dataset.backupRestore}});window.ErpUi.toast('Restauração preparada. Reinicie o ERP.');return;}
   if(b.matches('[data-testid="admin-document-import"]')){const file=await window.erpDesktop.selectAttachment();if(!file)return;const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<div class="notice full">${esc(file.name)} · ${esc(bytes(file.size))}</div><label class="form-field full"><span>Título</span><input name="title" value="${esc(file.name)}" data-testid="admin-document-title"></label><label class="form-field"><span>Tipo de vínculo</span><input name="entityType" placeholder="Ex.: cliente, fornecedor"></label><label class="form-field"><span>ID do vínculo</span><input name="entityId" placeholder="Opcional"></label>`;window.ErpUi.openModal({title:'Adicionar documento',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId:'admin-document-save',onClick:async()=>{try{const values=window.ErpForms.values(f);await api.request('/api/v1/admin/documents/import',{method:'POST',body:{...values,sourcePath:file.sourcePath}});window.ErpUi.closeModal();await render();}catch(e){formError(f,e);}}}]});return;}
   if(b.dataset.documentDelete){const ok=await window.ErpUi.confirm({title:'Excluir documento',message:'Excluir o arquivo do armazenamento local?',confirmLabel:'Excluir',danger:true});if(ok){await api.request(`/api/v1/admin/documents/${encodeURIComponent(b.dataset.documentDelete)}`,{method:'DELETE'});await render();}return;}
   if(b.matches('[data-testid="admin-integration-new"]')){const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field"><span>Nome</span><input name="name" data-testid="admin-integration-name" required></label><label class="form-field"><span>Tipo</span><select name="kind"><option value="BANK_API">Banco / Open Finance</option><option value="PAYMENT">Pagamentos</option><option value="EMAIL">E-mail</option><option value="WHATSAPP">WhatsApp</option><option value="GENERIC">Genérica</option></select></label><label class="form-field full"><span>Endpoint</span><input name="endpoint" placeholder="https://..."></label><label class="form-field full"><span>Token/API key</span><input name="token" type="password" autocomplete="off"></label>`;window.ErpUi.openModal({title:'Nova integração',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId:'admin-integration-save',onClick:async()=>{try{const v=window.ErpForms.values(f);await api.request('/api/v1/admin/integrations',{method:'POST',body:{kind:v.kind,name:v.name,endpoint:v.endpoint,config:v.token?{token:v.token}:{}}});window.ErpUi.closeModal();await render();}catch(e){formError(f,e);}}}]});return;}
   if(b.matches('[data-testid="admin-bank-new"]')){const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field full"><span>Nome</span><input name="name" data-testid="admin-bank-name" required></label><label class="form-field"><span>Provedor</span><select name="provider"><option value="manual">Manual / importação</option><option value="open-finance">Open Finance</option><option value="api">API bancária</option></select></label><label class="form-field"><span>ID da conta financeira</span><input name="accountId" placeholder="Opcional"></label>`;window.ErpUi.openModal({title:'Nova conexão bancária',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId:'admin-bank-save',onClick:async()=>{try{await api.request('/api/v1/admin/bank-connections',{method:'POST',body:window.ErpForms.values(f)});window.ErpUi.closeModal();await render();}catch(e){formError(f,e);}}}]});return;}
  }catch(error){window.ErpUi.toast(error.message,{type:'error'});}});
  await render();
 };
})();
