'use strict';
(()=>{
  window.ErpViews=window.ErpViews||{};
  const esc=value=>window.ErpUi.escapeHtml(value);
  const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
  const endpoint={customers:'/api/v1/customers',suppliers:'/api/v1/suppliers',categories:'/api/v1/product-categories',products:'/api/v1/products'};

  window.ErpViews.cadastros=async function cadastros({api,root}){
    let tab='customers',includeInactive=false,query='';
    root.innerHTML=`<section data-testid="cadastros-root"><div class="tabs">
      <button data-tab="customers" data-testid="cadastros-tab-customers" class="active">Clientes</button>
      <button data-tab="suppliers" data-testid="cadastros-tab-suppliers">Fornecedores</button>
      <button data-tab="categories" data-testid="cadastros-tab-categories">Categorias</button>
      <button data-tab="products" data-testid="cadastros-tab-products">Produtos</button>
    </div><div class="panel"><div class="toolbar"><input data-testid="cadastros-search" placeholder="Buscar"><label><input type="checkbox" data-testid="include-inactive"> Inativos</label><button class="primary" data-testid="record-new">Novo</button></div><div id="cadastros-table" style="margin-top:14px"></div></div></section>`;
    const table=root.querySelector('#cadastros-table'),newButton=root.querySelector('[data-testid="record-new"]'),search=root.querySelector('[data-testid="cadastros-search"]'),inactive=root.querySelector('[data-testid="include-inactive"]');

    function configureNewButton(){const names={customers:'customer-new',suppliers:'supplier-new',categories:'category-new',products:'product-new'};newButton.dataset.testid=names[tab];newButton.textContent={customers:'Novo cliente',suppliers:'Novo fornecedor',categories:'Nova categoria',products:'Novo produto'}[tab];}
    async function list(){const params=new URLSearchParams();if(includeInactive)params.set('includeInactive','true');if(query)params.set('query',query);return api.request(`${endpoint[tab]}${params.size?`?${params}`:''}`);}
    function actionButton(label,testId,action,danger=false){return `<button class="table-action${danger?' danger':''}" data-action="${action}" data-testid="${testId}">${esc(label)}</button>`;}
    function status(record){return `<span class="${record.active?'status-active':'status-inactive'}">${record.active?'Ativo':'Inativo'}</span>`;}
    async function render(){configureNewButton();table.innerHTML='<div class="empty">Carregando…</div>';try{const records=await list();if(!records.length){table.innerHTML='<div class="empty">Nenhum registro encontrado.</div>';return;}if(tab==='customers'||tab==='suppliers'){const prefix=tab==='customers'?'customer':'supplier';table.innerHTML=`<table><thead><tr><th>Nome</th><th>Documento</th><th>Contato</th><th>Status</th><th>Ações</th></tr></thead><tbody>${records.map(r=>`<tr data-record-id="${esc(r.id)}"><td>${esc(r.name)}</td><td>${esc(r.taxId||'')}</td><td>${esc(r.phone||r.email||'')}</td><td>${status(r)}</td><td>${actionButton('Editar',`${prefix}-edit-${r.id}`,'edit')}${r.active?actionButton('Inativar',`${prefix}-deactivate-${r.id}`,'deactivate',true):actionButton('Reativar',`${prefix}-reactivate-${r.id}`,'reactivate')}</td></tr>`).join('')}</tbody></table>`;return;}if(tab==='categories'){table.innerHTML=`<table><thead><tr><th>Categoria</th><th>Status</th><th>Ações</th></tr></thead><tbody>${records.map(r=>`<tr data-record-id="${esc(r.id)}"><td>${esc(r.name)}</td><td>${status(r)}</td><td>${actionButton('Editar',`category-edit-${r.id}`,'edit')}${r.active?actionButton('Inativar',`category-deactivate-${r.id}`,'deactivate',true):actionButton('Reativar',`category-reactivate-${r.id}`,'reactivate')}</td></tr>`).join('')}</tbody></table>`;return;}table.innerHTML=`<table><thead><tr><th>Produto</th><th>SKU</th><th>Preço</th><th>Custo</th><th>Status</th><th>Ações</th></tr></thead><tbody>${records.map(r=>`<tr data-record-id="${esc(r.id)}"><td>${esc(r.name)}</td><td>${esc(r.sku||'')}</td><td>${esc(money(r.salePriceCents))}</td><td>${esc(money(r.costCents))}</td><td>${status(r)}</td><td>${actionButton('Editar',`product-edit-${r.id}`,'edit')}${r.active?actionButton('Inativar',`product-deactivate-${r.id}`,'deactivate',true):actionButton('Reativar',`product-reactivate-${r.id}`,'reactivate')}</td></tr>`).join('')}</tbody></table>`;}catch(error){table.innerHTML=`<div class="error">${esc(error.message)}</div>`;}}

    function errorBox(form){let box=form.querySelector('.form-error');if(!box){box=document.createElement('div');box.className='form-error';form.append(box);}return box;}
    async function openContact(record=null){const prefix=tab==='customers'?'customer':'supplier',form=document.createElement('form');form.className='form-grid';form.innerHTML=`<label class="form-field full"><span>Nome</span><input name="name" data-testid="${prefix}-form-name" required value="${esc(record?.name||'')}"></label><label class="form-field"><span>Documento</span><input name="taxId" value="${esc(record?.taxId||'')}"></label><label class="form-field"><span>Telefone</span><input name="phone" data-testid="${prefix}-form-phone" value="${esc(record?.phone||'')}"></label><label class="form-field full"><span>E-mail</span><input name="email" type="email" value="${esc(record?.email||'')}"></label>`;const modal=window.ErpUi.openModal({title:record?'Editar contato':'Novo contato',content:form,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId:`${prefix}-form-save`,onClick:async({button})=>{window.ErpUi.setBusy(button,true);errorBox(form).textContent='';try{const payload=window.ErpForms.values(form);await api.request(record?`${endpoint[tab]}/${record.id}`:endpoint[tab],{method:record?'PATCH':'POST',body:payload});window.ErpUi.closeModal();window.ErpUi.toast('Cadastro salvo.');await render();}catch(error){errorBox(form).textContent=error.message;}finally{window.ErpUi.setBusy(button,false);}}}]});modal.body.querySelector('input')?.focus();}
    async function openCategory(record=null){const form=document.createElement('form');form.className='form-grid';form.innerHTML=`<label class="form-field full"><span>Nome</span><input name="name" data-testid="category-form-name" required value="${esc(record?.name||'')}"></label>`;window.ErpUi.openModal({title:record?'Editar categoria':'Nova categoria',content:form,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId:'category-form-save',onClick:async({button})=>{window.ErpUi.setBusy(button,true);try{await api.request(record?`${endpoint.categories}/${record.id}`:endpoint.categories,{method:record?'PATCH':'POST',body:window.ErpForms.values(form)});window.ErpUi.closeModal();await render();}catch(error){errorBox(form).textContent=error.message;}finally{window.ErpUi.setBusy(button,false);}}}]});}
    async function openProduct(record=null){let categories=await api.request('/api/v1/product-categories');if(!Array.isArray(categories))categories=categories.items||[];const form=document.createElement('form');form.className='form-grid';form.innerHTML=`<label class="form-field"><span>SKU</span><input name="sku" data-testid="product-form-sku" value="${esc(record?.sku||'')}"></label><label class="form-field"><span>Nome</span><input name="name" data-testid="product-form-name" required value="${esc(record?.name||'')}"></label><label class="form-field"><span>Categoria</span><select name="categoryId" data-testid="product-form-category"><option value="">Sem categoria</option>${categories.map(c=>`<option value="${esc(c.id)}" ${record?.categoryId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label class="form-field"><span>Preço de venda</span><input name="salePriceCents" data-type="cents" data-testid="product-form-price" value="${record?String((record.salePriceCents/100).toFixed(2)).replace('.',','):'0,00'}"></label><label class="form-field"><span>Custo</span><input name="costCents" data-type="cents" value="${record?String((record.costCents/100).toFixed(2)).replace('.',','):'0,00'}"></label><label class="form-field"><span><input name="trackStock" type="checkbox" ${record?.trackStock===false?'':'checked'}> Controlar estoque</span></label><label class="form-field"><span>Estoque mínimo</span><input name="minStock" data-type="number" value="${esc(record?.minStock??0)}"></label><label class="form-field"><span>Estoque alvo</span><input name="targetStock" data-type="number" value="${esc(record?.targetStock??'')}"></label><label class="form-field"><span>Estratégia de saída</span><select name="removalStrategy"><option value="MANUAL" ${record?.removalStrategy==='MANUAL'||!record?'selected':''}>Manual</option><option value="FIFO" ${record?.removalStrategy==='FIFO'?'selected':''}>FIFO</option><option value="FEFO" ${record?.removalStrategy==='FEFO'?'selected':''}>FEFO</option></select></label>`;window.ErpUi.openModal({title:record?'Editar produto':'Novo produto',content:form,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId:'product-form-save',onClick:async({button})=>{window.ErpUi.setBusy(button,true);try{await api.request(record?`${endpoint.products}/${record.id}`:endpoint.products,{method:record?'PATCH':'POST',body:window.ErpForms.values(form)});window.ErpUi.closeModal();await render();}catch(error){errorBox(form).textContent=error.message;}finally{window.ErpUi.setBusy(button,false);}}}]});}
    async function getRecord(id){return api.request(`${endpoint[tab]}/${encodeURIComponent(id)}`);}
    async function changeActive(id,active){const ok=await window.ErpUi.confirm({title:active?'Reativar registro':'Inativar registro',message:active?'Deseja reativar este registro?':'Deseja inativar este registro?',confirmLabel:active?'Reativar':'Inativar',danger:!active});if(!ok)return;await api.request(`${endpoint[tab]}/${encodeURIComponent(id)}/${active?'reactivate':'deactivate'}`,{method:'POST',body:{}});await render();}

    root.querySelector('.tabs').addEventListener('click',async event=>{const button=event.target.closest('[data-tab]');if(!button)return;tab=button.dataset.tab;root.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));search.value='';query='';await render();});
    newButton.addEventListener('click',()=>tab==='customers'||tab==='suppliers'?openContact():tab==='categories'?openCategory():openProduct());
    inactive.addEventListener('change',()=>{includeInactive=inactive.checked;render();});
    search.addEventListener('input',()=>{query=search.value.trim();render();});
    table.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const row=button.closest('[data-record-id]'),id=row?.dataset.recordId;if(!id)return;if(button.dataset.action==='edit'){const record=await getRecord(id);if(tab==='customers'||tab==='suppliers')openContact(record);else if(tab==='categories')openCategory(record);else openProduct(record);return;}if(button.dataset.action==='deactivate')await changeActive(id,false);if(button.dataset.action==='reactivate')await changeActive(id,true);});
    await render();
  };
})();
