'use strict';
(()=>{
  window.ErpViews=window.ErpViews||{};
  const esc=v=>window.ErpUi.escapeHtml(v),label=v=>window.ErpUi.statusLabel(v),money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100),today=()=>new Date().toISOString().slice(0,10);
  window.ErpViews.financeiro=async function financeiro({api,root}){
    let tab='entries',entryPage=1,entryTotal=0,entries=[],accounts=[],categories=[],centers=[],recurrences=[],alerts=[],credits=[],batches=[],transactions=[],pendingStatement=null;const entryPageSize=50;
    root.innerHTML=`<section data-testid="finance-root"><div class="tabs" id="finance-tabs"><button data-tab="entries" class="active">Lançamentos</button><button data-tab="accounts">Contas</button><button data-tab="dimensions">Dimensões</button><button data-tab="recurrences">Recorrências</button><button data-tab="statements">OFX / Conciliação</button><button data-tab="credits">Créditos fornecedor</button><button data-tab="alerts">Alertas</button></div><div id="finance-content"></div></section>`;
    const area=root.querySelector('#finance-content');
    const opts=(xs,labelKey='name',blank='')=>`${blank?`<option value="">${esc(blank)}</option>`:''}${xs.map(x=>`<option value="${esc(x.id)}">${esc(x[labelKey]||x.id)}</option>`).join('')}`;
    const fail=(form,error)=>{let box=form.querySelector('.form-error');if(!box){box=document.createElement('div');box.className='form-error';form.append(box);}box.textContent=error?.message||String(error);};
    async function loadEntries(){const result=await api.request(`/api/v1/finance/entries?page=${entryPage}&pageSize=${entryPageSize}`);entries=result.items||[];entryTotal=Number(result.total||entries.length);}
    async function loadForTab(){if(tab==='entries'){[accounts,categories,centers]=await Promise.all([api.request('/api/v1/finance/accounts?includeInactive=true'),api.request('/api/v1/finance/categories?includeInactive=true'),api.request('/api/v1/finance/cost-centers?includeInactive=true')]);await loadEntries();return;}if(tab==='accounts'){accounts=await api.request('/api/v1/finance/accounts?includeInactive=true');return;}if(tab==='dimensions'){[categories,centers]=await Promise.all([api.request('/api/v1/finance/categories?includeInactive=true'),api.request('/api/v1/finance/cost-centers?includeInactive=true')]);const result=await api.request('/api/v1/finance/entries?page=1&pageSize=200');entries=result.items||[];return;}if(tab==='recurrences'){recurrences=await api.request('/api/v1/finance/recurrences');return;}if(tab==='statements'){[accounts,batches,transactions]=await Promise.all([api.request('/api/v1/finance/accounts?includeInactive=true'),api.request('/api/v1/finance/statements'),api.request('/api/v1/finance/statement-transactions')]);return;}if(tab==='credits'){credits=await api.request('/api/v1/finance/supplier-credits');return;}if(tab==='alerts'){alerts=await api.request('/api/v1/finance/alerts?includeHidden=true');}}
    function pager(){const pages=Math.max(1,Math.ceil(entryTotal/entryPageSize)),from=entryTotal?(entryPage-1)*entryPageSize+1:0,to=Math.min(entryPage*entryPageSize,entryTotal);return `<div class="pager"><small>${from}–${to} de ${entryTotal}</small><div class="toolbar"><button data-entry-page-prev ${entryPage<=1?'disabled':''}>Anterior</button><span>Página ${entryPage} de ${pages}</span><button data-entry-page-next ${entryPage>=pages?'disabled':''}>Próxima</button></div></div>`;}
    async function render(){area.innerHTML=window.ErpUi.loading();try{await loadForTab();if(tab==='entries'){const s=await api.request('/api/v1/finance/summary');area.innerHTML=`<div class="grid"><div class="metric"><span>A receber</span><strong>${money(s.receivableOpenCents)}</strong></div><div class="metric"><span>A pagar</span><strong>${money(s.payableOpenCents)}</strong></div></div><div class="panel"><div class="section-head"><div><h3>Lançamentos</h3><p class="muted">Página limitada a ${entryPageSize} registros para manter resposta rápida em bases grandes.</p></div><div class="toolbar"><button class="primary" data-testid="finance-entry-new-payable" data-new-kind="PAYABLE">Nova conta a pagar</button><button data-testid="finance-entry-new-receivable" data-new-kind="RECEIVABLE">Nova conta a receber</button></div></div>${entries.length?`<table data-testid="finance-entry-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Status</th><th>Total</th><th>Baixado</th><th>Aberto</th><th>Vencimento</th><th>Ações</th></tr></thead><tbody>${entries.map(e=>`<tr data-entry="${esc(e.id)}"><td>${esc(e.description)}</td><td>${esc(label(e.kind))}</td><td>${esc(label(e.status))}</td><td>${money(e.amountCents)}</td><td>${money(e.settledCents)}</td><td>${money(e.openCents)}</td><td>${esc(String(e.dueAt||'').slice(0,10))}</td><td><div class="toolbar">${e.status!=='CANCELLED'&&e.settledCents===0?`<button data-entry-edit="${esc(e.id)}">Editar</button>`:''}${e.openCents>0&&e.status!=='CANCELLED'?`<button data-entry-settle="${esc(e.id)}" data-testid="finance-entry-settle-${esc(e.id)}">Baixar</button>`:''}${e.status!=='CANCELLED'&&e.settledCents===0?`<button class="danger" data-entry-cancel="${esc(e.id)}">Cancelar</button>`:''}${(e.settlements||[]).map(x=>x.reversedAt?'':`<button data-settlement-reverse="${esc(x.id)}">Estornar ${money(x.amountCents)}</button>`).join('')}</div></td></tr>`).join('')}</tbody></table>${pager()}`:window.ErpUi.empty('Nenhum lançamento financeiro.')}</div>`;return;}
      if(tab==='accounts'){area.innerHTML=`<div class="panel"><div class="section-head"><h3>Contas financeiras</h3><button class="primary" data-testid="finance-account-new">Nova conta</button></div>${accounts.length?`<table><thead><tr><th>Nome</th><th>Tipo</th><th>Propriedade</th><th>Status</th><th>Ações</th></tr></thead><tbody>${accounts.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(label(a.type))}</td><td>${a.ownership==='business'?'Empresa':'Pessoal'}</td><td>${a.active?'Ativa':'Inativa'}</td><td><button data-account-edit="${esc(a.id)}">Editar</button><button data-account-active="${esc(a.id)}" data-active="${a.active?'0':'1'}">${a.active?'Inativar':'Reativar'}</button></td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty()}</div>`;return;}
      if(tab==='dimensions'){area.innerHTML=`<div class="grid"><div class="panel"><div class="section-head"><h3>Categorias</h3><button class="primary" data-new-category>Nova categoria</button></div>${categories.map(x=>`<div>${esc(x.name)} · ${esc(label(x.kind))} · ${x.active?'ativa':'inativa'}</div>`).join('')||window.ErpUi.empty('Nenhuma categoria.')}</div><div class="panel"><div class="section-head"><h3>Centros de custo</h3><button class="primary" data-new-center>Novo centro de custo</button></div>${centers.map(x=>`<div>${esc(x.name)} · ${x.active?'ativo':'inativo'}</div>`).join('')||window.ErpUi.empty('Nenhum centro de custo.')}</div></div><div class="panel"><h3>Atribuir dimensões</h3><div class="toolbar"><select data-dim-entry>${opts(entries,'description','Selecione lançamento')}</select><select data-dim-category>${opts(categories.filter(x=>x.active),'name','Sem categoria')}</select><select data-dim-center>${opts(centers.filter(x=>x.active),'name','Sem centro')}</select><input type="date" data-dim-date><button data-dim-save>Salvar dimensões</button></div><div data-dim-message></div></div>`;return;}
      if(tab==='recurrences'){area.innerHTML=`<div class="panel"><div class="section-head"><h3>Recorrências</h3><div class="toolbar"><button class="primary" data-testid="finance-recurrence-new">Nova recorrência</button><input type="date" data-generate-date value="${today()}"><button data-generate>Gerar até data</button></div></div>${recurrences.length?`<table><thead><tr><th>Descrição</th><th>Tipo</th><th>Valor</th><th>Dia</th><th>Próximo</th><th>Status</th><th>Ações</th></tr></thead><tbody>${recurrences.map(r=>`<tr><td>${esc(r.description)}</td><td>${esc(label(r.kind))}</td><td>${money(r.amountCents)}</td><td>${esc(r.dueDay)}</td><td>${esc(r.nextDueAt)}</td><td>${esc(label(r.status))}</td><td><button data-rec-status="${esc(r.id)}" data-status="${r.status==='ACTIVE'?'PAUSED':'ACTIVE'}">${r.status==='ACTIVE'?'Pausar':'Ativar'}</button></td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhuma recorrência.')}</div>`;return;}
      if(tab==='statements'){area.innerHTML=`<div class="panel"><div class="section-head"><div><h3>Importar extrato</h3><p class="muted">OFX, CSV, PDF com texto ou lançamento manual.</p></div><div class="toolbar"><select data-ofx-account>${opts(accounts.filter(a=>a.active&&['BANK','CARD'].includes(a.type)),'name','Selecione conta')}</select><button class="primary" data-testid="finance-ofx-select">Selecionar arquivo e pré-visualizar</button></div></div><div id="ofx-preview"></div></div><div class="panel"><h3>Importações</h3>${batches.length?`<table><thead><tr><th>Arquivo</th><th>Inseridos</th><th>Duplicados</th><th>Data</th></tr></thead><tbody>${batches.map(b=>`<tr><td>${esc(b.sourceName)}</td><td>${esc(b.inserted)}</td><td>${esc(b.duplicates)}</td><td>${esc(String(b.createdAt||'').replace('T',' ').slice(0,19))}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhuma importação.')}</div><div class="panel"><div class="section-head"><h3>Transações para conciliar</h3><button data-transfer-suggestions>Revisar transferências próprias</button></div>${transactions.length?`<table><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>${transactions.map(t=>`<tr data-statement-transaction="${esc(t.id)}"><td>${esc(t.date)}</td><td>${esc(t.description)}</td><td>${money(t.amountCents)}</td><td>${esc(label(t.matchStatus))}</td><td>${t.matchStatus==='UNMATCHED'?`<button data-reconcile="${esc(t.id)}" data-account="${esc(t.accountId)}">Conciliar</button>`:''}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhuma transação importada.')}</div>`;return;}
      if(tab==='credits'){area.innerHTML=`<div class="panel"><h3>Créditos de fornecedor</h3>${credits.length?`<table><thead><tr><th>Fornecedor</th><th>Origem</th><th>Original</th><th>Aplicado</th><th>Disponível</th><th>Status</th><th>Ações</th></tr></thead><tbody>${credits.map(c=>`<tr><td>${esc(c.supplierId)}</td><td>${esc(c.sourceReturnId)}</td><td>${money(c.originalCents)}</td><td>${money(c.appliedCents)}</td><td>${money(c.openCents)}</td><td>${esc(label(c.status))}</td><td>${c.openCents>0?`<button data-credit-apply="${esc(c.id)}">Aplicar</button>`:''}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhum crédito disponível.')}</div>`;return;}
      if(tab==='alerts'){area.innerHTML=`<div class="panel"><h3>Alertas</h3>${alerts.length?`<table><thead><tr><th>Mensagem</th><th>Severidade</th><th>Estado</th><th>Ações</th></tr></thead><tbody>${alerts.map(a=>`<tr><td>${esc(a.message)}</td><td>${esc(label(a.severity))}</td><td>${a.hiddenAt?'Oculto':a.readAt?'Lido':'Novo'}</td><td>${!a.readAt?`<button data-alert-read="${esc(a.key)}">Marcar lido</button>`:''}${a.hiddenAt?`<button data-alert-unhide="${esc(a.key)}">Reexibir</button>`:`<button data-alert-hide="${esc(a.key)}">Ocultar</button>`}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhum alerta.')}</div>`;}
    }catch(error){area.innerHTML=window.ErpUi.errorState(error.message);}}
    function accountForm(a=null){const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field"><span>Nome</span><input name="name" data-testid="finance-account-name" value="${esc(a?.name||'')}"></label><label class="form-field"><span>Tipo</span><select name="type"><option value="BANK">Banco</option><option value="CARD">Cartão</option><option value="CASH">Caixa</option><option value="OTHER">Outro</option></select></label><label class="form-field"><span>Propriedade</span><select name="ownership"><option value="business">Empresa</option><option value="personal">Pessoal</option></select></label>`;if(a){f.elements.type.value=a.type;f.elements.ownership.value=a.ownership;}return f;}
    function entryForm(kind,e=null){const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field full"><span>Descrição</span><input name="description" data-testid="finance-entry-description" value="${esc(e?.description||'')}"></label><label class="form-field"><span>Valor (R$)</span><input name="amountCents" data-type="cents" data-testid="finance-entry-amount" value="${esc(((e?.baseAmountCents||0)/100).toFixed(2).replace('.',','))}"></label><label class="form-field"><span>Vencimento</span><input type="date" name="dueAt" data-testid="finance-entry-due" value="${esc(String(e?.dueAt||'').slice(0,10))}"></label><label class="form-field"><span>Conta</span><select name="accountId">${opts(accounts.filter(a=>a.active),'name','Sem conta')}</select></label><label class="form-field"><span>Categoria</span><select name="categoryId">${opts(categories.filter(x=>x.active),'name','Sem categoria')}</select></label><label class="form-field"><span>Centro de custo</span><select name="costCenterId">${opts(centers.filter(x=>x.active),'name','Sem centro')}</select></label><label class="form-field"><span>Competência</span><input type="date" name="competencyDate" value="${esc(e?.competencyDate||'')}"></label><label class="form-field full"><span>Notas</span><input name="notes" value="${esc(e?.notes||'')}"></label>`;if(e){f.elements.accountId.value=e.accountId||'';f.elements.categoryId.value=e.categoryId||'';f.elements.costCenterId.value=e.costCenterId||'';}return f;}
    function modal(title,form,save,testId='modal-save'){window.ErpUi.openModal({title,content:form,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Salvar',primary:true,testId,onClick:async({button})=>{window.ErpUi.setBusy(button,true);try{await save();window.ErpUi.closeModal();await render();}catch(error){fail(form,error);}finally{window.ErpUi.setBusy(button,false);}}}]});}
    root.querySelector('#finance-tabs').addEventListener('click',event=>{const b=event.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;entryPage=1;root.querySelectorAll('#finance-tabs button').forEach(x=>x.classList.toggle('active',x===b));render();});
    root.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{
      if(b.matches('[data-entry-page-prev]')&&!b.disabled){entryPage--;await render();return;}if(b.matches('[data-entry-page-next]')&&!b.disabled){entryPage++;await render();return;}
      if(b.dataset.newKind){const kind=b.dataset.newKind,f=entryForm(kind);modal(kind==='PAYABLE'?'Nova conta a pagar':'Nova conta a receber',f,async()=>{const v=window.ErpForms.values(f);await api.request('/api/v1/finance/entries',{method:'POST',body:{...v,kind,dueAt:`${v.dueAt}T12:00:00.000Z`}});},'finance-entry-save');return;}
      if(b.matches('[data-testid="finance-account-new"]')){const f=accountForm();modal('Nova conta financeira',f,()=>api.request('/api/v1/finance/accounts',{method:'POST',body:window.ErpForms.values(f)}),'finance-account-save');return;}
      if(b.dataset.accountEdit){const a=accounts.find(x=>x.id===b.dataset.accountEdit),f=accountForm(a);modal('Editar conta',f,()=>api.request(`/api/v1/finance/accounts/${encodeURIComponent(a.id)}`,{method:'PATCH',body:window.ErpForms.values(f)}));return;}
      if(b.dataset.accountActive){await api.request(`/api/v1/finance/accounts/${encodeURIComponent(b.dataset.accountActive)}/${b.dataset.active==='1'?'reactivate':'deactivate'}`,{method:'POST'});await render();return;}
      if(b.dataset.entryEdit){const e=entries.find(x=>x.id===b.dataset.entryEdit),f=entryForm(e.kind,e);modal('Editar lançamento',f,async()=>{const v=window.ErpForms.values(f);await api.request(`/api/v1/finance/entries/${encodeURIComponent(e.id)}`,{method:'PATCH',body:{...v,dueAt:`${v.dueAt}T12:00:00.000Z`}});});return;}
      if(b.dataset.entrySettle){const e=entries.find(x=>x.id===b.dataset.entrySettle),f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field"><span>Valor (R$)</span><input name="amountCents" data-type="cents" data-testid="finance-settle-amount" value="${esc((e.openCents/100).toFixed(2).replace('.',','))}"></label><label class="form-field"><span>Método</span><select name="method"><option>PIX</option><option>TED</option><option>DINHEIRO</option><option>CARTAO</option><option>OUTRO</option></select></label><label class="form-field full"><span>Observação</span><input name="note"></label>`;modal('Baixar lançamento',f,()=>api.request(`/api/v1/finance/entries/${encodeURIComponent(e.id)}/settle`,{method:'POST',body:window.ErpForms.values(f)}),'finance-settle-save');return;}
      if(b.dataset.settlementReverse){const id=b.dataset.settlementReverse,f=document.createElement('form');f.className='form-grid';f.innerHTML='<label class="form-field full"><span>Motivo</span><input name="reason" required></label>';window.ErpUi.openModal({title:'Estornar baixa',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Estornar',danger:true,onClick:async()=>{try{await api.request(`/api/v1/finance/settlements/${encodeURIComponent(id)}/reverse`,{method:'POST',body:window.ErpForms.values(f)});window.ErpUi.closeModal();await render();}catch(error){fail(f,error);}}}]});return;}
      if(b.dataset.entryCancel){const id=b.dataset.entryCancel,f=document.createElement('form');f.className='form-grid';f.innerHTML='<label class="form-field full"><span>Motivo</span><input name="reason" required></label>';window.ErpUi.openModal({title:'Cancelar lançamento',content:f,actions:[{label:'Voltar',onClick:window.ErpUi.closeModal},{label:'Cancelar lançamento',danger:true,onClick:async()=>{try{await api.request(`/api/v1/finance/entries/${encodeURIComponent(id)}/cancel`,{method:'POST',body:window.ErpForms.values(f)});window.ErpUi.closeModal();await render();}catch(error){fail(f,error);}}}]});return;}
      if(b.hasAttribute('data-new-category')){const f=document.createElement('form');f.className='form-grid';f.innerHTML='<label class="form-field"><span>Nome</span><input name="name" required></label><label class="form-field"><span>Tipo</span><select name="kind"><option value="EXPENSE">Despesa</option><option value="INCOME">Receita</option><option value="BOTH">Ambos</option></select></label>';modal('Nova categoria',f,()=>api.request('/api/v1/finance/categories',{method:'POST',body:window.ErpForms.values(f)}));return;}
      if(b.hasAttribute('data-new-center')){const f=document.createElement('form');f.className='form-grid';f.innerHTML='<label class="form-field full"><span>Nome</span><input name="name" required></label>';modal('Novo centro de custo',f,()=>api.request('/api/v1/finance/cost-centers',{method:'POST',body:window.ErpForms.values(f)}));return;}
      if(b.hasAttribute('data-dim-save')){const entryId=root.querySelector('[data-dim-entry]')?.value;if(!entryId)throw new Error('Selecione um lançamento.');await api.request(`/api/v1/finance/entries/${encodeURIComponent(entryId)}/dimensions`,{method:'PATCH',body:{categoryId:root.querySelector('[data-dim-category]')?.value||null,costCenterId:root.querySelector('[data-dim-center]')?.value||null,competencyDate:root.querySelector('[data-dim-date]')?.value||null}});root.querySelector('[data-dim-message]').innerHTML='<div class="notice">Dimensões salvas.</div>';return;}
      if(b.matches('[data-testid="finance-recurrence-new"]')){const f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field full"><span>Descrição</span><input name="description" required></label><label class="form-field"><span>Tipo</span><select name="kind"><option value="PAYABLE">A pagar</option><option value="RECEIVABLE">A receber</option></select></label><label class="form-field"><span>Valor (R$)</span><input name="amountCents" data-type="cents" required></label><label class="form-field"><span>Início</span><input type="date" name="startDate" value="${today()}" required></label><label class="form-field"><span>Dia do vencimento</span><input type="number" min="1" max="31" name="dueDay" required></label>`;modal('Nova recorrência',f,()=>api.request('/api/v1/finance/recurrences',{method:'POST',body:window.ErpForms.values(f)}));return;}
      if(b.hasAttribute('data-generate')){await api.request('/api/v1/finance/recurrences/generate',{method:'POST',body:{asOf:root.querySelector('[data-generate-date]')?.value||today()}});window.ErpUi.toast('Recorrências geradas.');await render();return;}
      if(b.dataset.recStatus){await api.request(`/api/v1/finance/recurrences/${encodeURIComponent(b.dataset.recStatus)}/status`,{method:'PATCH',body:{status:b.dataset.status}});await render();return;}
      if(b.matches('[data-testid="finance-ofx-select"]')){const accountId=root.querySelector('[data-ofx-account]')?.value;if(!accountId)throw new Error('Selecione a conta do extrato.');const file=await window.erpDesktop.selectImportFile();if(!file)return;pendingStatement={accountId,sourceName:file.name,sourceType:file.sourceType,content:file.text};const preview=await api.request('/api/v1/finance/statements/preview',{method:'POST',body:pendingStatement});const box=root.querySelector('#ofx-preview');box.innerHTML=`<div class="notice">${esc(file.name)} · ${preview.transactions.length} transações · ${preview.duplicates||0} duplicadas. Nada foi gravado.</div>${preview.transactions.length?`<table><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th><th>Direção</th></tr></thead><tbody>${preview.transactions.map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(t.description)}</td><td>${money(t.amountCents)}</td><td>${t.direction==='credit'?'Crédito':'Débito'}</td></tr>`).join('')}</tbody></table>`:''}<div class="toolbar"><button class="primary" data-statement-commit>Confirmar importação</button></div>`;return;}
      if(b.hasAttribute('data-statement-commit')){if(!pendingStatement)return;await api.request('/api/v1/finance/statements',{method:'POST',body:pendingStatement});pendingStatement=null;window.ErpUi.toast('Importação concluída.');await render();return;}
      if(b.dataset.reconcile){const id=b.dataset.reconcile,suggestions=await api.request(`/api/v1/finance/reconciliation/${encodeURIComponent(id)}/suggestions`),f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field full"><span>Lançamento sugerido</span><select name="entryId"><option value="">Melhor sugestão automática</option>${suggestions.map(s=>`<option value="${esc(s.entryId)}">${esc(s.description||s.entryId)} · ${money(s.amountCents||0)}</option>`).join('')}</select></label>`;window.ErpUi.openModal({title:'Conciliar transação',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Conciliar',primary:true,onClick:async()=>{try{const values=window.ErpForms.values(f);await api.request(`/api/v1/finance/reconciliation/${encodeURIComponent(id)}/accept`,{method:'POST',body:values});window.ErpUi.closeModal();await render();}catch(error){fail(f,error);}}}]});return;}
      if(b.hasAttribute('data-transfer-suggestions')){const rows=await api.request('/api/v1/finance/transfers/suggestions');window.ErpUi.openModal({title:'Transferências próprias sugeridas',content:rows.length?`<table><thead><tr><th>Débito</th><th>Crédito</th><th>Valor</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.debitTransactionId)}</td><td>${esc(x.creditTransactionId)}</td><td>${money(x.amountCents)}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhuma transferência sugerida.'),actions:[{label:'Fechar',onClick:window.ErpUi.closeModal}]});return;}
      if(b.dataset.creditApply){const credit=credits.find(x=>x.id===b.dataset.creditApply),page=await api.request('/api/v1/finance/entries?kind=PAYABLE&page=1&pageSize=200'),payables=(page.items||[]).filter(x=>x.openCents>0),f=document.createElement('form');f.className='form-grid';f.innerHTML=`<label class="form-field full"><span>Conta a pagar</span><select name="payableEntryId">${opts(payables,'description','Selecione')}</select></label><label class="form-field"><span>Valor (R$)</span><input name="amountCents" data-type="cents" value="${esc((credit.openCents/100).toFixed(2).replace('.',','))}"></label>`;modal('Aplicar crédito de fornecedor',f,async()=>{const v=window.ErpForms.values(f);await api.request(`/api/v1/finance/supplier-credits/${encodeURIComponent(credit.id)}/apply`,{method:'POST',body:v});});return;}
      if(b.dataset.alertRead){await api.request(`/api/v1/finance/alerts/${encodeURIComponent(b.dataset.alertRead)}/read`,{method:'POST'});await render();return;}if(b.dataset.alertHide){await api.request(`/api/v1/finance/alerts/${encodeURIComponent(b.dataset.alertHide)}/hide`,{method:'POST'});await render();return;}if(b.dataset.alertUnhide){await api.request(`/api/v1/finance/alerts/${encodeURIComponent(b.dataset.alertUnhide)}/unhide`,{method:'POST'});await render();}
    }catch(error){window.ErpUi.toast(error.message,{type:'error'});}});
    await render();
  };
})();
