'use strict';
(()=>{
 window.ErpViews=window.ErpViews||{};
 const esc=v=>window.ErpUi.escapeHtml(v),key=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
 const docsHtml=state=>{const docs=state?.documents||[];if(docs.length)return `<div class="notice"><strong>Documentos fiscais</strong>${docs.map(d=>`<div>${esc(String(d.documentType||'').toUpperCase())} · ${esc(d.status||'PENDING')} · ${esc(d.number||d.id||'')}</div>`).join('')}</div>`;const reasons=state?.pendingReasons||[];return reasons.length?`<div class="notice error">${reasons.map(esc).join('<br>')}</div>`:'<div class="notice">Pronto para preparação fiscal.</div>';};
 async function sourceState(api,type,id){return api.request(`/api/v1/tax/sources/${encodeURIComponent(type)}/${encodeURIComponent(id)}`);}
 async function prepareSource(api,type,id){return api.request(`/api/v1/tax/sources/${encodeURIComponent(type)}/${encodeURIComponent(id)}/prepare`,{method:'POST',body:{idempotencyKey:key(`ui-${type.toLowerCase()}`)}});}
 function showSourceModal(api,{type,id,title,label='Preparar documento',allowIssue=false}){sourceState(api,type,id).then(state=>{const first=state.documents?.[0];const actions=[{label:'Fechar',onClick:window.ErpUi.closeModal}];if(state.ready&&!first)actions.push({label,primary:true,onClick:async()=>{try{await prepareSource(api,type,id);window.ErpUi.closeModal();window.ErpUi.toast('Documento fiscal preparado.',{type:'success'});}catch(e){window.ErpUi.toast(e.message,{type:'error'});}}});if(allowIssue&&first&&first.status==='PENDING')actions.push({label:'Transmitir',primary:true,onClick:async()=>{try{await api.request(`/api/v1/tax/documents/${encodeURIComponent(first.id)}/issue`,{method:'POST',body:{}});window.ErpUi.closeModal();window.ErpUi.toast('Documento enviado ao runtime fiscal.',{type:'success'});}catch(e){window.ErpUi.toast(e.message,{type:'error'});}}});window.ErpUi.openModal({title,content:docsHtml(state),actions});}).catch(e=>window.ErpUi.toast(e.message,{type:'error'}));}
 function observe(root,decorate){let busy=false;const run=()=>{if(busy)return;busy=true;try{decorate();}finally{busy=false;}};run();const observer=new MutationObserver(run);observer.observe(root,{subtree:true,childList:true});return observer;}
 function wrapSales(){const original=window.ErpViews.vendas;if(typeof original!=='function'||original.__fiscalContext)return;const wrapped=async function(ctx){await original(ctx);const{api,root}=ctx;root.addEventListener('click',e=>{const b=e.target.closest('[data-fiscal-invoice]');if(!b)return;e.preventDefault();e.stopPropagation();showSourceModal(api,{type:'ADMIN_INVOICE',id:b.dataset.fiscalInvoice,title:'Fiscal da fatura',label:'Preparar NF-e',allowIssue:true});},true);observe(root,()=>{const table=root.querySelector('[data-testid="sales-invoice-table"]');if(!table)return;const head=table.querySelector('thead tr');if(head&&!head.querySelector('[data-fiscal-head]'))head.insertAdjacentHTML('beforeend','<th data-fiscal-head>Fiscal</th>');table.querySelectorAll('tbody tr[data-invoice-id]').forEach(row=>{if(row.querySelector('[data-fiscal-invoice]'))return;const id=row.dataset.invoiceId;row.insertAdjacentHTML('beforeend',`<td><button class="table-action" data-fiscal-invoice="${esc(id)}">Fiscal</button></td>`);});});};wrapped.__fiscalContext=true;window.ErpViews.vendas=wrapped;}
 function inboundModal(api,receiptId){const f=document.createElement('form');f.className='form-grid';f.innerHTML='<label class="form-field full"><span>Chave de acesso</span><input name="accessKey" required></label><label class="form-field"><span>Série</span><input name="series" required></label><label class="form-field"><span>Número</span><input name="number" type="number" required></label><label class="form-field full"><span>CNPJ/CPF do emitente</span><input name="issuerTaxId" required></label><label class="form-field full"><span>XML (opcional)</span><textarea name="xml"></textarea></label>';window.ErpUi.openModal({title:'Vincular NF-e recebida',content:f,actions:[{label:'Cancelar',onClick:window.ErpUi.closeModal},{label:'Vincular NF-e',primary:true,onClick:async()=>{try{const v=window.ErpForms.values(f);await api.request(`/api/v1/tax/inbound/purchase-receipts/${encodeURIComponent(receiptId)}`,{method:'POST',body:{...v,number:Number(v.number),idempotencyKey:key('inbound-nfe')}});window.ErpUi.closeModal();window.ErpUi.toast('NF-e vinculada ao recebimento sem repetir estoque/financeiro.',{type:'success'});}catch(e){window.ErpUi.toast(e.message,{type:'error'});}}}]});}
 function wrapProcurement(){const original=window.ErpViews.compras;if(typeof original!=='function'||original.__fiscalContext)return;const wrapped=async function(ctx){await original(ctx);const{api,root}=ctx;root.addEventListener('click',e=>{const inbound=e.target.closest('[data-fiscal-receipt]');if(inbound){e.preventDefault();e.stopPropagation();inboundModal(api,inbound.dataset.fiscalReceipt);return;}const ret=e.target.closest('[data-fiscal-purchase-return]');if(ret){e.preventDefault();e.stopPropagation();showSourceModal(api,{type:'PURCHASE_RETURN',id:ret.dataset.fiscalPurchaseReturn,title:'Fiscal da devolução ao fornecedor',label:'Preparar NF-e de devolução'});}},true);observe(root,()=>{root.querySelectorAll('tr[data-receipt-id]').forEach(row=>{if(row.querySelector('[data-fiscal-receipt]'))return;const cell=row.lastElementChild;if(cell)cell.insertAdjacentHTML('afterbegin',`<button class="table-action" data-fiscal-receipt="${esc(row.dataset.receiptId)}">Vincular NF-e</button> `);});const returnsTab=root.querySelector('[data-testid="procurement-tab-returns"]');const active=returnsTab?.classList.contains('active');if(!active)return;const table=root.querySelector('#procurement-content table');if(!table)return;const head=table.querySelector('thead tr');if(head&&!head.querySelector('[data-fiscal-return-head]'))head.insertAdjacentHTML('beforeend','<th data-fiscal-return-head>Fiscal</th>');table.querySelectorAll('tbody tr').forEach(row=>{if(row.querySelector('[data-fiscal-purchase-return]'))return;const id=row.cells?.[0]?.textContent?.trim();if(!id)return;row.insertAdjacentHTML('beforeend',`<td><button class="table-action" data-fiscal-purchase-return="${esc(id)}">Fiscal</button></td>`);});});};wrapped.__fiscalContext=true;window.ErpViews.compras=wrapped;}
 wrapSales();wrapProcurement();
})();
