'use strict';
(()=>{
 window.ErpViews=window.ErpViews||{};const esc=v=>window.ErpUi.escapeHtml(v),status=v=>window.ErpUi.statusLabel(v),money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100),today=()=>new Date().toISOString().slice(0,10),firstDay=()=>`${today().slice(0,7)}-01`;
 window.ErpViews.relatorios=async function relatorios({api,root}){
  root.innerHTML=`<section data-testid="reports-root"><div class="panel"><form id="reports-overview-form" class="toolbar"><label>De <input name="from" type="date" value="${firstDay()}"></label><label>Até <input name="to" type="date" value="${today()}"></label><button class="primary" type="submit">Atualizar</button></form></div><div id="reports-overview">${window.ErpUi.loading()}</div><div class="panel" id="finance-io-report"><div class="section-head"><div><h3>Relatório financeiro</h3><p class="muted">Lançamentos, baixas e valores em aberto no período.</p></div><div class="toolbar"><button type="button" data-finance-export="csv">CSV</button><button type="button" data-finance-export="xlsx">XLSX</button><button type="button" data-finance-export="pdf">PDF</button><button type="button" data-finance-export="print">Imprimir</button></div></div><form id="finance-report-form" class="form-grid compact"><label class="form-field"><span>De</span><input name="from" type="date" value="${firstDay()}" required></label><label class="form-field"><span>Até</span><input name="to" type="date" value="${today()}" required></label><div class="toolbar"><button class="primary" type="submit">Atualizar financeiro</button></div></form><div data-report-result>${window.ErpUi.loading()}</div></div></section>`;
  const overview=root.querySelector('#reports-overview'),financeResult=root.querySelector('[data-report-result]');
  async function renderOverview(){const form=root.querySelector('#reports-overview-form'),from=form.elements.from.value,to=form.elements.to.value;overview.innerHTML=window.ErpUi.loading();try{const [sales,purchases,inventory]=await Promise.all([api.request(`/api/v1/reports/sales?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),api.request(`/api/v1/reports/purchases?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),api.request('/api/v1/reports/inventory')]);overview.innerHTML=`<div class="grid metrics-4"><div class="metric"><span>Vendas líquidas</span><strong>${money(sales.netSalesCents)}</strong><small>${esc(sales.invoiceOrSettlementCount)} faturamento(s)</small></div><div class="metric"><span>Margem estimada</span><strong>${money(sales.estimatedMarginCents)}</strong><small>Custo ${money(sales.estimatedCostCents)}</small></div><div class="metric"><span>Compras recebidas</span><strong>${money(purchases.receivedCents)}</strong><small>${esc(purchases.receipts)} recebimento(s)</small></div><div class="metric"><span>Estoque disponível</span><strong>${esc(inventory.availableQuantity)}</strong><small>${esc(inventory.products)} produto(s) · ${esc(inventory.reservedQuantity)} reservado(s)</small></div></div><div class="grid reports-cards"><div class="panel"><h3>Vendas</h3><table><tbody><tr><th>Vendas</th><td>${money(sales.netSalesCents)}</td></tr><tr><th>Custo estimado</th><td>${money(sales.estimatedCostCents)}</td></tr><tr><th>Margem</th><td>${money(sales.estimatedMarginCents)}</td></tr></tbody></table></div><div class="panel"><h3>Compras</h3><table><tbody><tr><th>Recebimentos</th><td>${esc(purchases.receipts)}</td></tr><tr><th>Valor recebido</th><td>${money(purchases.receivedCents)}</td></tr></tbody></table></div><div class="panel"><h3>Estoque</h3><table><tbody><tr><th>Produtos ativos</th><td>${esc(inventory.products)}</td></tr><tr><th>Quantidade total</th><td>${esc(inventory.totalQuantity)}</td></tr><tr><th>Reservado</th><td>${esc(inventory.reservedQuantity)}</td></tr><tr><th>Disponível</th><td>${esc(inventory.availableQuantity)}</td></tr></tbody></table></div></div>`;}catch(error){overview.innerHTML=window.ErpUi.errorState(error.message);}}
  async function renderFinance(){const form=root.querySelector('#finance-report-form'),from=form.elements.from.value,to=form.elements.to.value;financeResult.innerHTML=window.ErpUi.loading();try{const report=await api.request(`/api/v1/reports/financial?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`);financeResult.innerHTML=`<div class="grid"><div class="metric"><span>Total</span><strong>${money(report.totals.amountCents)}</strong></div><div class="metric"><span>Baixado</span><strong>${money(report.totals.settledCents)}</strong></div><div class="metric"><span>Em aberto</span><strong>${money(report.totals.openCents)}</strong></div></div>${report.rows.length?`<table data-testid="financial-report-table"><thead><tr><th>Vencimento</th><th>Tipo</th><th>Descrição</th><th>Status</th><th>Valor</th><th>Baixado</th><th>Em aberto</th><th>Conta</th><th>Categoria</th></tr></thead><tbody>${report.rows.map(row=>`<tr><td>${esc(String(row.dueAt||'').slice(0,10))}</td><td>${esc(status(row.kind))}</td><td>${esc(row.description)}</td><td>${esc(status(row.status))}</td><td>${money(row.amountCents)}</td><td>${money(row.settledCents)}</td><td>${money(row.openCents)}</td><td>${esc(row.account||'-')}</td><td>${esc(row.category||'-')}</td></tr>`).join('')}</tbody></table>`:window.ErpUi.empty('Nenhum lançamento financeiro no período.')}`;}catch(error){financeResult.innerHTML=window.ErpUi.errorState(error.message);}}
  root.querySelector('#reports-overview-form').addEventListener('submit',event=>{event.preventDefault();renderOverview();});root.querySelector('#finance-report-form').addEventListener('submit',event=>{event.preventDefault();renderFinance();});
  await Promise.all([renderOverview(),renderFinance()]);
 };
})();
