import{useState}from'react';import{Panel}from'../components/Panel';import type{ErpApi}from'../services/api';
const money=(cents=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(cents||0)/100);
export function DepthPage({api}:{api:ErpApi}){
 const[accounting,setAccounting]=useState('Pronto para consultar.');const[projectId,setProjectId]=useState('');const[project,setProject]=useState('Informe um projeto.');const[leadName,setLeadName]=useState('');const[crm,setCrm]=useState('Informe um lead.');const[operationName,setOperationName]=useState('');const[shop,setShop]=useState('Informe uma operação.');const[stockProduct,setStockProduct]=useState('');const[stock,setStock]=useState('Informe um produto.');const[assetId,setAssetId]=useState('');const[asset,setAsset]=useState('Informe um ativo.');const[error,setError]=useState('');
 const run=async(fn:()=>Promise<void>)=>{setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}};
 return <div data-testid="view-depth"><Panel title="Profundidade ERP"><p>Seis frentes integradas ao núcleo local-first do ArtiSys ERP.</p>{error&&<p className="error">{error}</p>}</Panel><div className="report-grid">
  <Panel title="Accounting Core"><p>Plano de contas, lançamentos balanceados, períodos e demonstrativos.</p><button data-testid="depth-accounting-refresh" onClick={()=>run(async()=>{const x=await api.request<any>('/api/v1/accounting/trial-balance?from=2000-01-01&to=2999-12-31');setAccounting(`Balanceado: ${x.balanced?'sim':'não'} · Débitos ${money(x.totalDebitCents)} · Créditos ${money(x.totalCreditCents)}`)})}>Atualizar balancete</button><p data-testid="depth-accounting-result">{accounting}</p></Panel>
  <Panel title="Projects 2.0"><p>Horas, custos, receitas, orçamento e rentabilidade por projeto.</p><input data-testid="depth-project-id" value={projectId} onChange={e=>setProjectId(e.target.value)} placeholder="ID do projeto"/><button data-testid="depth-project-load" onClick={()=>run(async()=>{const x=await api.request<any>(`/api/v1/projects/${encodeURIComponent(projectId)}/profitability`);setProject(`Lucro: ${money(x.profitCents)} · Receita ${money(x.revenueCents)} · Custo ${money(x.costCents)}`)})}>Carregar rentabilidade</button><p data-testid="depth-project-result">{project}</p></Panel>
  <Panel title="CRM"><p>Leads, conversão, oportunidades, atividades e pipeline.</p><input data-testid="depth-crm-lead-name" value={leadName} onChange={e=>setLeadName(e.target.value)} placeholder="Nome do lead"/><button data-testid="depth-crm-create" onClick={()=>run(async()=>{const x=await api.request<any>('/api/v1/crm/leads',{method:'POST',body:{name:leadName}});setCrm(`Lead criado: ${x.name||leadName} · ${x.status||'OPEN'}`)})}>Criar lead</button><p data-testid="depth-crm-result">{crm}</p></Panel>
  <Panel title="Manufacturing Shop Floor"><p>Operações, postos, roteiros, job cards, apontamento e qualidade.</p><input data-testid="depth-shop-operation-name" value={operationName} onChange={e=>setOperationName(e.target.value)} placeholder="Nome da operação"/><button data-testid="depth-shop-operation-create" onClick={()=>run(async()=>{const x=await api.request<any>('/api/v1/shop-floor/operations',{method:'POST',body:{name:operationName,defaultMinutes:30}});setShop(`Operação criada: ${x.name||operationName}`)})}>Criar operação</button><p data-testid="depth-shop-result">{shop}</p></Panel>
  <Panel title="Stock Logistics"><p>Putaway, picking, packing, shipment e landed cost.</p><input data-testid="depth-stock-product" value={stockProduct} onChange={e=>setStockProduct(e.target.value)} placeholder="ID do produto"/><button data-testid="depth-stock-suggest" onClick={()=>run(async()=>{const x=await api.request<any>(`/api/v1/stock-logistics/putaway-suggestion?productId=${encodeURIComponent(stockProduct)}`);setStock(`Destino sugerido: ${x.locationId}`)})}>Sugerir armazenagem</button><p data-testid="depth-stock-result">{stock}</p></Panel>
  <Panel title="Asset Accounting"><p>Capitalização, depreciação, custódia, valor contábil e baixa.</p><input data-testid="depth-asset-id" value={assetId} onChange={e=>setAssetId(e.target.value)} placeholder="ID do ativo"/><button data-testid="depth-asset-load" onClick={()=>run(async()=>{const x=await api.request<any>(`/api/v1/asset-accounting/assets/${encodeURIComponent(assetId)}`);setAsset(`Valor contábil líquido: ${money(x.netBookValueCents)} · Aquisição ${money(x.acquisitionCostCents)}`)})}>Carregar ativo</button><p data-testid="depth-asset-result">{asset}</p></Panel>
 </div></div>;
}
