import{useEffect,useState}from'react';
import{Panel}from'../components/Panel';
import type{ErpApi}from'../services/api';

type Line={id:string;lineType:'SERVICE'|'PART';productId:string;description:string;quantity:number;unitPriceCents:number;consumedQuantity:number};
type Order={id:string;number:string;title:string;customerId?:string;locationId?:string;status:string;serviceTotalCents:number;partsTotalCents:number;totalCents:number;lines:Line[]};
const status:Record<string,string>={OPEN:'Aberta',APPROVED:'Aprovada',WAITING_PARTS:'Aguardando peças',IN_PROGRESS:'Em execução',COMPLETED:'Concluída',CANCELLED:'Cancelada'};
const money=(v=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);

export function ServiceOrdersPage({api}:{api:ErpApi}){
 const[orders,setOrders]=useState<Order[]>([]),[current,setCurrent]=useState<Order|null>(null),[customerId,setCustomerId]=useState(''),[locationId,setLocationId]=useState('MAIN'),[title,setTitle]=useState(''),[lineProduct,setLineProduct]=useState(''),[lineType,setLineType]=useState<'SERVICE'|'PART'>('SERVICE'),[linePrice,setLinePrice]=useState('0'),[message,setMessage]=useState('');
 const load=async(selectId?:string)=>{const rows=await api.request<Order[]>('/api/v1/ops/service-orders?limit=100');setOrders(rows);const id=selectId||current?.id;if(id){const detail=await api.request<Order>(`/api/v1/ops/service-orders/${id}`);setCurrent(detail);}else if(rows[0]){const detail=await api.request<Order>(`/api/v1/ops/service-orders/${rows[0].id}`);setCurrent(detail);}};
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
 const run=async(fn:()=>Promise<Order>)=>{try{const result=await fn();setCurrent(result);setMessage('');await load(result.id);}catch(e){setMessage(e instanceof Error?e.message:String(e));}};
 const create=()=>run(async()=>{const base=await api.request<{id:string}>('/api/v1/ops/service-orders',{method:'POST',body:{number:`OS-${Date.now()}`,customerId,title}});return api.request<Order>(`/api/v1/ops/service-orders/${base.id}`,{method:'PATCH',body:{customerId,locationId,title}})});
 const addLine=()=>current?run(()=>api.request<Order>(`/api/v1/ops/service-orders/${current.id}/lines`,{method:'POST',body:{lineType,productId:lineProduct,quantity:1,unitPriceCents:Number(linePrice)}}).then(()=>api.request<Order>(`/api/v1/ops/service-orders/${current.id}`))):Promise.resolve();
 const action=(name:string,body:unknown={})=>current?run(()=>api.request<Order>(`/api/v1/ops/service-orders/${current.id}/${name}`,{method:'POST',body})):Promise.resolve();
 const consume=(line:Line)=>current?run(()=>api.request(`/api/v1/ops/service-orders/${current.id}/parts/${line.id}/consume`,{method:'POST',body:{quantity:1,idempotencyKey:crypto.randomUUID()}}).then(()=>api.request<Order>(`/api/v1/ops/service-orders/${current.id}`))):Promise.resolve();
 return <div data-testid="view-service-orders">
  {message&&<div className="notice error">{message}</div>}
  <Panel title="Nova ordem de serviço"><div className="form-grid"><label>Cliente<input data-testid="service-order-customer" value={customerId} onChange={e=>setCustomerId(e.target.value)}/></label><label>Local de estoque<input data-testid="service-order-location" value={locationId} onChange={e=>setLocationId(e.target.value)}/></label><label>Título<input data-testid="service-order-title" value={title} onChange={e=>setTitle(e.target.value)}/></label></div><button data-testid="service-order-create" onClick={create}>Criar OS</button></Panel>
  <div className="grid"><Panel title="Ordens"><div className="table-wrap"><table><thead><tr><th>Número</th><th>Título</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} onClick={()=>load(o.id)}><td>{o.number}</td><td>{o.title}</td><td>{status[o.status]||o.status}</td></tr>)}</tbody></table></div></Panel>
  {current&&<Panel title={current.title}><div className="metric"><small>Status</small><strong data-testid="service-order-status">{status[current.status]||current.status}</strong></div><p>Total: <strong>{money(current.totalCents)}</strong></p>
   {current.status==='OPEN'&&<><div className="form-grid"><label>Produto/serviço<input data-testid="service-order-line-product" value={lineProduct} onChange={e=>setLineProduct(e.target.value)}/></label><label>Tipo<select data-testid="service-order-line-type" value={lineType} onChange={e=>setLineType(e.target.value as 'SERVICE'|'PART')}><option value="SERVICE">Serviço</option><option value="PART">Peça</option></select></label><label>Preço em centavos<input data-testid="service-order-line-price" value={linePrice} onChange={e=>setLinePrice(e.target.value)}/></label></div><button data-testid="service-order-line-add" onClick={addLine}>Adicionar item</button></>}
   <div className="table-wrap"><table><thead><tr><th>Item</th><th>Tipo</th><th>Qtd.</th><th>Consumido</th><th>Preço</th><th></th></tr></thead><tbody>{current.lines.map(l=><tr key={l.id}><td>{l.description}</td><td>{l.lineType==='SERVICE'?'Serviço':'Peça'}</td><td>{l.quantity}</td><td>{l.lineType==='PART'?`Consumido: ${l.consumedQuantity}`:'—'}</td><td>{money(l.unitPriceCents)}</td><td>{current.status==='IN_PROGRESS'&&l.lineType==='PART'&&l.consumedQuantity<l.quantity&&<button onClick={()=>consume(l)} aria-label={`Consumir 1 ${l.description}`}>Consumir 1</button>}</td></tr>)}</tbody></table></div>
   <div className="toolbar">{current.status==='OPEN'&&<button data-testid="service-order-approve" onClick={()=>action('approve')}>Aprovar</button>}{current.status==='WAITING_PARTS'&&<button onClick={()=>action('retry-parts')}>Tentar reservar peças</button>}{current.status==='APPROVED'&&<button data-testid="service-order-start" onClick={()=>action('start')}>Iniciar execução</button>}{current.status==='IN_PROGRESS'&&<button data-testid="service-order-complete" onClick={()=>action('complete',{idempotencyKey:`ui-complete-${current.id}`})}>Concluir OS</button>}{['OPEN','APPROVED','WAITING_PARTS','IN_PROGRESS'].includes(current.status)&&<button className="secondary" onClick={()=>action('cancel',{reason:'Cancelamento pelo usuário'})}>Cancelar</button>}{current.status==='COMPLETED'&&<><button onClick={()=>window.erpDesktop.printHtml({html:`<h1>${current.title}</h1><p>${status[current.status]}</p><p>Total: ${money(current.totalCents)}</p>`})}>Imprimir</button><button onClick={()=>window.erpDesktop.savePdf({filename:`${current.number}.pdf`,html:`<h1>${current.title}</h1><p>${status[current.status]}</p><p>Total: ${money(current.totalCents)}</p>`})}>Salvar PDF</button></>}</div>
  </Panel>}</div>
 </div>;
}
