import{useEffect,useState}from'react';
import{Metric}from'../components/Metric';
import{Panel}from'../components/Panel';
import{FeedbackBanner}from'../components/advanced/FeedbackBanner';
import{FormField}from'../components/advanced/FormField';
import{ConfirmActionButton}from'../components/operational/OperationalFields';
import type{ErpApi}from'../services/api';

type Feedback={tone:'success'|'danger'|'info'|'warning';text:string};

export function SettingsPage({api,baseUrl}:{api:ErpApi;baseUrl:string}){
 const[online,setOnline]=useState(false),[lan,setLan]=useState<any>(null),[pair,setPair]=useState<any>(null),[devices,setDevices]=useState<any[]>([]),[update,setUpdate]=useState<any>(null),[feedback,setFeedback]=useState<Feedback|null>(null);
 const refresh=()=>{api.request<any>('/api/v1/lan/status').then(setLan).catch(e=>setFeedback({tone:'danger',text:e instanceof Error?e.message:String(e)}));api.request<any[]>('/api/v1/lan/devices').then(setDevices).catch(e=>setFeedback({tone:'danger',text:e instanceof Error?e.message:String(e)}));window.erpDesktop.getUpdateStatus().then(setUpdate).catch(()=>{})};
 useEffect(()=>{api.request<{ok:boolean}>('/api/v1/health').then(x=>setOnline(Boolean(x.ok))).catch(()=>setOnline(false));refresh()},[api]);
 return <div data-testid="view-settings" className="operational-page">
  {feedback&&<FeedbackBanner tone={feedback.tone}>{feedback.text}</FeedbackBanner>}
  <Panel title="Sistema"><div className="grid"><Metric name="Produto" value="ArtiSys ERP"/><Metric name="Servidor" value={online?'Online':'Indisponível'}/><Metric name="Modo" value="Local-first"/><Metric name="Base local" value={baseUrl}/></div></Panel>
  <Panel title="Multiusuário na rede local"><p>Servidor atual: <strong>{baseUrl}</strong></p><form className="operational-form-stack" onSubmit={e=>{e.preventDefault();const value=String(new FormData(e.currentTarget).get('serverUrl')||'').trim().replace(/\/$/,'');if(value)localStorage.setItem('erp-server-url',value);else localStorage.removeItem('erp-server-url');location.reload()}}><FormField label="Servidor LAN" hint="Use apenas quando este computador acessar outro PC que hospeda o ERP."><input data-testid="settings-lan-url" name="serverUrl" defaultValue={localStorage.getItem('erp-server-url')||''} placeholder="http://192.168.1.10:4174"/></FormField><div className="operational-inline-actions"><button className="primary" data-testid="settings-lan-use">Usar servidor LAN</button><button data-testid="settings-lan-local" type="button" onClick={()=>{localStorage.removeItem('erp-server-url');location.reload()}}>Voltar ao servidor deste PC</button></div></form><p>O servidor mantém o banco autoritativo. Outros computadores acessam pela API; não compartilhe o arquivo SQLite pela rede.</p><div className="grid"><Metric name="Endereços LAN" value={(lan?.addresses||[]).join(', ')||'Somente local'}/><Metric name="Dispositivos" value={String(devices.length)}/></div><div className="toolbar"><button className="primary" data-testid="settings-lan-pair" onClick={async()=>{try{const p=await api.request<any>('/api/v1/lan/pair',{method:'POST',body:{}});setPair(p);setFeedback({tone:'success',text:'Código de pareamento gerado.'})}catch(e){setFeedback({tone:'danger',text:e instanceof Error?e.message:String(e)})}}}>Gerar código de pareamento</button><button data-testid="settings-lan-refresh" onClick={refresh}>Atualizar dispositivos</button></div>{pair&&<p data-testid="settings-lan-pair-code"><strong>Código: {pair.code}</strong> · válido por 10 minutos</p>}{devices.map(device=><div data-testid="settings-lan-device" key={device.id} className="device-row"><div><strong>{device.name}</strong><small>{device.revoked?'Acesso revogado':'Dispositivo ativo'}</small></div>{!device.revoked&&<ConfirmActionButton label="Revogar acesso" title="Revogar acesso deste dispositivo?" description="O dispositivo deixará de acessar o ERP pela rede local." impact={<p>As sessões e permissões desse dispositivo serão invalidadas. Para usar novamente, será necessário um novo pareamento.</p>} confirmLabel="Revogar dispositivo" onConfirm={async()=>{const revoked=await api.request<any>('/api/v1/lan/devices/'+device.id+'/revoke',{method:'POST',body:{}});setDevices(current=>current.map(item=>item.id===revoked.id?revoked:item));setFeedback({tone:'success',text:`Acesso de ${device.name} revogado.`})}}/>}</div>)}</Panel>
  <Panel title="Atualizações"><p>Atualização opcional via manifesto configurado. O instalador só é liberado após validação SHA-256.</p><div className="grid"><Metric name="Estado" value={update?.status||'idle'}/><Metric name="Versão disponível" value={update?.available?.version||'Nenhuma'}/></div><div className="operational-inline-actions"><button onClick={async()=>{const value=await window.erpDesktop.checkForUpdates();setUpdate(value);setFeedback({tone:'info',text:value?.available?'Nova versão disponível.':'Nenhuma atualização disponível.'})}}>Verificar atualização</button>{update?.available&&<button className="primary" onClick={async()=>{const value=await window.erpDesktop.downloadUpdate();setUpdate(value);setFeedback({tone:'success',text:'Atualização baixada e validada por SHA-256.'})}}>Baixar e validar</button>}{update?.status==='downloaded'&&<button className="primary" onClick={()=>window.erpDesktop.installUpdate()}>Instalar atualização</button>}</div></Panel>
 </div>;
}
