import{useState}from'react';
import{Panel}from'../components/Panel';
import type{ErpApi}from'../services/api';

type SupplierRow={supplierId:string|null;quantity:number;costCents:number;revenueCents:number;marginCents:number};
type Performance={productId:string;quantity:number;revenueCents:number;costCents:number;marginCents:number;marginPercent:number;purchasedQuantity:number;averageAcquisitionCostCents:number;lastAcquisitionCostCents:number;currentQuantity:number;currentValueCents:number;averageOrderToReceiptDays:number|null;averageReceiptToSaleDays:number|null;averageOrderToSaleDays:number|null;suppliers:SupplierRow[]};
type Layer={id:string;source_type:string;source_id:string;supplier_id?:string|null;purchase_order_id?:string|null;purchase_receipt_id?:string|null;unit_cost_cents:number;original_quantity:number;availableQuantity?:number;received_at:string};
type Trace={productId:string;layers:Layer[];allocations:unknown[];facts:unknown[]};
type Health={ok:boolean;discrepancyCount:number;orphanAllocations:number;orphanFacts:number};
const money=(v=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const days=(v:number|null)=>v==null?'—':`${v.toFixed(1)} dias`;

export function TraceabilityPage({api}:{api:ErpApi}){
 const[productId,setProductId]=useState(''),[from,setFrom]=useState('2000-01-01'),[to,setTo]=useState('2999-12-31'),[performance,setPerformance]=useState<Performance|null>(null),[trace,setTrace]=useState<Trace|null>(null),[health,setHealth]=useState<Health|null>(null),[message,setMessage]=useState('');
 const load=async()=>{const id=productId.trim();if(!id){setMessage('Informe o produto.');return;}try{const[p,t,h]=await Promise.all([api.request<Performance>(`/api/v1/traceability/products/${encodeURIComponent(id)}/performance?from=${from}&to=${to}`),api.request<Trace>(`/api/v1/traceability/products/${encodeURIComponent(id)}`),api.request<Health>('/api/v1/traceability/health')]);setPerformance(p);setTrace(t);setHealth(h);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:String(e));}};
 return <div data-testid="view-traceability">
  {message&&<div className="notice error">{message}</div>}
  <Panel title="Rastreabilidade por produto"><div className="form-grid"><label>Produto<input data-testid="trace-product" value={productId} onChange={e=>setProductId(e.target.value)} placeholder="ID/SKU do produto"/></label><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to==='2999-12-31'?'':to} onChange={e=>setTo(e.target.value||'2999-12-31')}/></label></div><button data-testid="trace-search" onClick={load}>Consultar trilha</button></Panel>
  {health&&<Panel title="Integridade"><div className="grid"><div className="metric"><small>Estado</small><strong>{health.ok?'Íntegra':'Requer reconciliação'}</strong></div><div className="metric"><small>Divergências</small><strong>{health.discrepancyCount}</strong></div><div className="metric"><small>Alocações órfãs</small><strong>{health.orphanAllocations}</strong></div></div></Panel>}
  {performance&&<><Panel title="Resultado econômico"><div className="grid"><div className="metric"><small>Receita</small><strong>{money(performance.revenueCents)}</strong></div><div className="metric"><small>CMV realizado</small><strong>{money(performance.costCents)}</strong></div><div className="metric"><small>Margem bruta</small><strong>{money(performance.marginCents)} · {performance.marginPercent.toFixed(1)}%</strong></div><div className="metric"><small>Estoque rastreado</small><strong>{performance.currentQuantity} · {money(performance.currentValueCents)}</strong></div></div></Panel>
  <Panel title="Tempos e aquisição"><div className="grid"><div className="metric"><small>Custo médio de aquisição</small><strong>{money(performance.averageAcquisitionCostCents)}</strong></div><div className="metric"><small>Último custo</small><strong>{money(performance.lastAcquisitionCostCents)}</strong></div><div className="metric"><small>Pedido → recebimento</small><strong>{days(performance.averageOrderToReceiptDays)}</strong></div><div className="metric"><small>Recebimento → venda</small><strong>{days(performance.averageReceiptToSaleDays)}</strong></div><div className="metric"><small>Pedido → venda</small><strong>{days(performance.averageOrderToSaleDays)}</strong></div></div></Panel>
  <Panel title="Margem por fornecedor"><div className="table-wrap"><table><thead><tr><th>Fornecedor</th><th>Qtd.</th><th>Receita</th><th>Custo</th><th>Margem</th></tr></thead><tbody>{performance.suppliers.map((s,i)=><tr key={`${s.supplierId||'na'}-${i}`}><td>{s.supplierId||'Origem não atribuída'}</td><td>{s.quantity}</td><td>{money(s.revenueCents)}</td><td>{money(s.costCents)}</td><td>{money(s.marginCents)}</td></tr>)}</tbody></table></div></Panel></>}
  {trace&&<Panel title="Camadas de origem"><div className="table-wrap"><table><thead><tr><th>Origem</th><th>Fornecedor</th><th>Pedido/recebimento</th><th>Qtd. original</th><th>Saldo</th><th>Custo unit.</th><th>Data</th></tr></thead><tbody>{trace.layers.map(l=><tr key={l.id}><td>{l.source_type} · {l.source_id}</td><td>{l.supplier_id||'—'}</td><td>{l.purchase_order_id||'—'} / {l.purchase_receipt_id||'—'}</td><td>{Number(l.original_quantity)}</td><td>{Number(l.availableQuantity||0)}</td><td>{money(Number(l.unit_cost_cents||0))}</td><td>{String(l.received_at||'').slice(0,10)}</td></tr>)}</tbody></table></div><p>{trace.allocations.length} alocações · {trace.facts.length} fatos comerciais</p></Panel>}
 </div>;
}
