'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {launchErpElectron}=require('./fixtures/erp-electron');
async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}

test('desktop finance runs account AP settlement reversal dimensions recurrence OFX and reconciliation without web dialogs',async()=>{const erp=await launchErpElectron();const dialogs=[];erp.page.on('dialog',d=>{dialogs.push(d.type());d.dismiss().catch(()=>{});});try{const p=erp.page;await login(p);await p.getByTestId('nav-financeiro').click();await p.getByTestId('finance-root').waitFor();
await p.getByRole('button',{name:'Contas',exact:true}).click();await p.getByTestId('finance-account-new').click();let modal=p.getByRole('dialog');await p.getByTestId('finance-account-name').fill('Banco E2E');await modal.locator('select[name="type"]').selectOption('BANK');await p.getByTestId('finance-account-save').click();await p.getByText('Banco E2E',{exact:true}).waitFor();
await p.getByRole('button',{name:'Lançamentos',exact:true}).click();await p.getByTestId('finance-entry-new-payable').click();modal=p.getByRole('dialog');await p.getByTestId('finance-entry-description').fill('FORNECEDOR E2E');await p.getByTestId('finance-entry-amount').fill('100,00');await p.getByTestId('finance-entry-due').fill('2026-09-25');await modal.locator('select[name="accountId"]').selectOption({label:'Banco E2E'});await p.getByTestId('finance-entry-save').click();const row=p.locator('[data-entry]').filter({hasText:'FORNECEDOR E2E'});await row.waitFor();await row.getByRole('button',{name:'Baixar'}).click();await p.getByTestId('finance-settle-amount').fill('40,00');await p.getByTestId('finance-settle-save').click();await row.getByText('R$ 60,00',{exact:true}).waitFor();await row.getByRole('button',{name:/^Estornar/}).click();modal=p.getByRole('dialog');await modal.locator('input[name="reason"]').fill('Correção E2E');await modal.getByRole('button',{name:'Estornar',exact:true}).click();await row.getByText('R$ 100,00',{exact:true}).last().waitFor();
await p.getByRole('button',{name:'Dimensões',exact:true}).click();await p.getByRole('button',{name:'Nova categoria'}).click();modal=p.getByRole('dialog');await modal.locator('input[name="name"]').fill('Despesa E2E');await modal.getByRole('button',{name:'Salvar'}).click();await p.getByText('Despesa E2E',{exact:false}).waitFor();await p.getByRole('button',{name:'Novo centro de custo'}).click();modal=p.getByRole('dialog');await modal.locator('input[name="name"]').fill('Centro E2E');await modal.getByRole('button',{name:'Salvar'}).click();await p.getByText('Centro E2E',{exact:false}).waitFor();await p.locator('[data-dim-entry]').selectOption({label:'FORNECEDOR E2E'});await p.locator('[data-dim-category]').selectOption({label:'Despesa E2E'});await p.locator('[data-dim-center]').selectOption({label:'Centro E2E'});await p.locator('[data-dim-date]').fill('2026-09-01');await p.getByRole('button',{name:'Salvar dimensões'}).click();await p.getByText('Dimensões salvas.',{exact:true}).waitFor();
await p.getByRole('button',{name:'Recorrências',exact:true}).click();await p.getByTestId('finance-recurrence-new').click();modal=p.getByRole('dialog');await modal.locator('input[name="description"]').fill('Recorrência E2E');await modal.locator('input[name="amountCents"]').fill('5,00');await modal.locator('input[name="startDate"]').fill('2026-09-25');await modal.locator('input[name="dueDay"]').fill('25');await modal.getByRole('button',{name:'Salvar'}).click();await p.getByText('Recorrência E2E',{exact:true}).waitFor();await p.locator('[data-generate-date]').fill('2026-09-25');await p.getByRole('button',{name:'Gerar até data'}).click();
await p.getByRole('button',{name:'OFX / Conciliação',exact:true}).click();await p.locator('[data-ofx-account]').selectOption({label:'Banco E2E'});await p.getByTestId('finance-ofx-select').click();await p.getByText(/sample\.ofx · 1 transações · 0 duplicadas/).waitFor();await p.getByRole('button',{name:'Confirmar importação'}).click();await p.getByText('sample.ofx',{exact:true}).waitFor();const tx=p.locator('tr').filter({hasText:'FORNECEDOR E2E'}).last();await tx.getByRole('button',{name:'Conciliar'}).click();modal=p.getByRole('dialog');await modal.getByRole('button',{name:'Conciliar',exact:true}).click();await p.getByText('MATCHED',{exact:true}).waitFor();assert.deepEqual(dialogs,[]);
}finally{await erp.close();}});
