'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {launchErpElectron}=require('./fixtures/erp-electron');

async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}
async function seed(p){await p.evaluate(async()=>{const base=await window.erpDesktop.getBaseUrl(),token=sessionStorage.getItem('erp-token');const api=async(path,body,method='POST')=>{const r=await fetch(base+path,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json();};await api('/api/v1/customers',{id:'C-FISCAL',name:'Cliente Fiscal'});await api('/api/v1/inventory/locations',{id:'MAIN',name:'Principal'});await api('/api/v1/products',{id:'S-FISCAL',name:'Serviço fiscal',sku:'SERV-FISCAL',salePriceCents:2500,trackStock:false});await api('/api/v1/retail/products/S-FISCAL',{productType:'SERVICE'},'PATCH');await api('/api/v1/products',{id:'P-FISCAL',name:'Peça fiscal',sku:'PEC-FISCAL',salePriceCents:1000,trackStock:true});await api('/api/v1/inventory/adjustments',{productId:'P-FISCAL',locationId:'MAIN',quantity:2,direction:'IN',reason:'fixture',idempotencyKey:'seed-fiscal-part'});await api('/api/v1/tax/settings',{provider:'acbr-local',environment:'homologation',cnpj:'12345678000199',stateRegistration:'123',legalName:'Empresa Fiscal',crt:'1',seriesNfce:'1',seriesNfe:'1',seriesNfse:'1',operationNature:'VENDA'},'PUT');await api('/api/v1/tax/profiles',{id:'PF-FISCAL',name:'Fiscal E2E',ncm:'12345678',cfop:'5102',origin:'0',csosn:'102',pisCst:'49',cofinsCst:'49',unit:'UN'});await api('/api/v1/tax/products/S-FISCAL',{profileId:'PF-FISCAL',serviceCode:'1401',serviceDescription:'Serviço técnico'},'PUT');await api('/api/v1/tax/products/P-FISCAL',{profileId:'PF-FISCAL'},'PUT');});}
async function expectStatus(p,value){await p.getByTestId('service-order-status').filter({hasText:value}).waitFor();assert.equal(await p.getByTestId('service-order-status').textContent(),value);}

test('desktop mixed service order prepares separate service and parts fiscal trails',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await seed(p);await p.getByTestId('nav-servicos').click();await p.getByTestId('view-service-orders').waitFor();await p.getByTestId('service-order-customer').fill('C-FISCAL');await p.getByTestId('service-order-location').fill('MAIN');await p.getByTestId('service-order-title').fill('OS Fiscal E2E');await p.getByTestId('service-order-create').click();await p.getByRole('heading',{name:'OS Fiscal E2E',exact:true}).waitFor();await p.getByTestId('service-order-line-product').fill('S-FISCAL');await p.getByTestId('service-order-line-type').selectOption('SERVICE');await p.getByTestId('service-order-line-price').fill('2500');await p.getByTestId('service-order-line-add').click();await p.getByText('Serviço fiscal',{exact:true}).waitFor();await p.getByTestId('service-order-line-product').fill('P-FISCAL');await p.getByTestId('service-order-line-type').selectOption('PART');await p.getByTestId('service-order-line-price').fill('1000');await p.getByTestId('service-order-line-add').click();await p.getByText('Peça fiscal',{exact:true}).waitFor();await p.getByTestId('service-order-approve').click();await expectStatus(p,'Aprovada');await p.getByTestId('service-order-start').click();await expectStatus(p,'Em execução');await p.getByRole('button',{name:'Consumir 1 Peça fiscal'}).click();await p.getByText('Consumido: 1').waitFor();await p.getByTestId('service-order-complete').click();await expectStatus(p,'Concluída');await p.getByTestId('service-order-fiscal-prepare').click();const service= p.getByTestId('service-order-fiscal-SERVICE_ORDER_SERVICE'),parts=p.getByTestId('service-order-fiscal-SERVICE_ORDER_PARTS');await service.waitFor();await parts.waitFor();assert.match(await service.textContent(),/NFS-e serviço.*PENDING/);assert.match(await parts.textContent(),/NF-e peças.*PENDING/);}finally{await erp.close();}});
