'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{launchErpElectron}=require('./fixtures/erp-electron');
async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}
async function seed(p){await p.evaluate(async()=>{const base=await window.erpDesktop.getBaseUrl(),token=sessionStorage.getItem('erp-token');const r=await fetch(base+'/api/v1/products',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({id:'P-PRICE-E2E',sku:'P-PRICE-E2E',name:'Produto Pricing E2E',salePriceCents:1000,trackStock:false})});if(!r.ok)throw new Error(await r.text());});}
async function clickGet(p,button,path){await Promise.all([p.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname===path&&r.ok()),button.click()]);}
test('intelligence tabs pricing and workflow controls execute real operations',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await seed(p);await p.getByTestId('nav-inteligencia').click();await p.getByTestId('view-intelligence').waitFor();await p.getByText('Top produtos',{exact:true}).waitFor();
await p.getByTestId('intelligence-tab-alerts').click();await p.getByText('Central de alertas',{exact:true}).waitFor();await clickGet(p,p.getByTestId('intelligence-alerts-refresh'),'/api/v1/ops/alerts');
await p.getByTestId('intelligence-tab-assets').click();await p.getByText('Ativos e Ordens de Serviço',{exact:true}).waitFor();await clickGet(p,p.getByRole('button',{name:'Listar ativos'}),'/api/v1/ops/assets');
await p.getByTestId('intelligence-tab-maintenance').click();await p.getByText('Manutenção preventiva',{exact:true}).waitFor();await clickGet(p,p.getByRole('button',{name:'Ver vencimentos'}),'/api/v1/ops/maintenance/due');
await p.getByTestId('intelligence-tab-projects').click();await p.getByText('Projetos e obras',{exact:true}).waitFor();await clickGet(p,p.getByRole('button',{name:'Listar projetos'}),'/api/v1/ops/projects');
await p.getByTestId('intelligence-tab-pricing').click();await p.getByTestId('pricing-id').fill('PRICE-E2E');await p.getByTestId('pricing-name').fill('Tabela E2E');await p.getByTestId('pricing-product').fill('P-PRICE-E2E');await p.getByTestId('pricing-min-quantity').fill('1');await p.getByTestId('pricing-unit-price').fill('1000');await p.getByTestId('pricing-discount').fill('10');await p.getByTestId('pricing-create').click();await p.getByTestId('intelligence-result').getByText(/PRICE-E2E/).waitFor();await p.getByTestId('pricing-quote-table').fill('PRICE-E2E');await p.getByTestId('pricing-quote-product').fill('P-PRICE-E2E');await p.getByTestId('pricing-quote-quantity').fill('2');await p.getByTestId('pricing-quote').click();await p.getByTestId('intelligence-result').getByText(/900/).waitFor();
await p.getByTestId('intelligence-tab-workflow').click();await p.getByTestId('workflow-id').fill('WF-E2E');await p.getByTestId('workflow-name').fill('Fluxo E2E');await p.getByTestId('workflow-states').fill('OPEN,APPROVED');await p.getByTestId('workflow-initial').fill('OPEN');await p.getByTestId('workflow-transitions').fill(JSON.stringify([{from:'OPEN',to:'APPROVED'}]));await p.getByTestId('workflow-create').click();await p.getByTestId('intelligence-result').getByText(/WF-E2E/).waitFor();await p.getByTestId('workflow-instance-id').fill('WFI-E2E');await p.getByTestId('workflow-instance-definition').fill('WF-E2E');await p.getByTestId('workflow-subject-kind').fill('test');await p.getByTestId('workflow-subject-id').fill('SUBJECT-E2E');await p.getByTestId('workflow-start').click();await p.getByTestId('intelligence-result').getByText(/OPEN/).waitFor();await p.getByTestId('workflow-transition-instance').fill('WFI-E2E');await p.getByTestId('workflow-transition-to').fill('APPROVED');await p.getByTestId('workflow-transition').click();await p.getByTestId('intelligence-result').getByText(/APPROVED/).waitFor();assert.equal(await p.locator('.notice.error').count(),0);
}finally{await erp.close();}});
