'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {launchErpElectron}=require('./fixtures/erp-electron');
async function login(page){await page.getByTestId('login-username').fill('admin');await page.getByTestId('login-password').fill('admin123');await page.getByTestId('login-submit').click();await page.getByTestId('view-dashboard').waitFor({state:'visible'});}

test('desktop inventory supports locations adjustment transfer and persistent balances',async()=>{const erp=await launchErpElectron();const dialogs=[];erp.page.on('dialog',d=>{dialogs.push(d.type());d.dismiss().catch(()=>{});});try{const p=erp.page;await login(p);await p.getByTestId('nav-cadastros').click();await p.getByTestId('cadastros-tab-products').click();await p.getByTestId('product-new').click();await p.getByTestId('product-form-sku').fill('EST-1');await p.getByTestId('product-form-name').fill('Produto Estoque');await p.getByTestId('product-form-save').click();await p.getByText('Produto Estoque',{exact:true}).waitFor();
await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-root').waitFor();for(const name of ['Local A','Local B']){await p.getByTestId('inventory-location-new').click();await p.getByTestId('inventory-location-name').fill(name);await p.getByTestId('inventory-location-save').click();await p.getByText(name,{exact:true}).waitFor();}
await p.getByTestId('inventory-adjust').click();await p.getByTestId('inventory-adjust-product').selectOption({label:'Produto Estoque'});await p.getByTestId('inventory-adjust-location').selectOption({label:'Local A'});await p.getByTestId('inventory-adjust-quantity').fill('10');await p.getByTestId('inventory-adjust-reason').fill('Saldo inicial');await p.getByTestId('inventory-operation-save').click();await p.getByText('10',{exact:true}).first().waitFor();
await p.getByTestId('inventory-transfer').click();await p.getByTestId('inventory-transfer-product').selectOption({label:'Produto Estoque'});await p.getByTestId('inventory-transfer-from').selectOption({label:'Local A'});await p.getByTestId('inventory-transfer-to').selectOption({label:'Local B'});await p.getByTestId('inventory-transfer-quantity').fill('3');await p.getByTestId('inventory-transfer-reason').fill('Reposição');await p.getByTestId('inventory-operation-save').click();await p.getByTestId('inventory-balance-table').getByText('7',{exact:true}).waitFor();await p.getByTestId('inventory-balance-table').getByText('3',{exact:true}).waitFor();
await p.getByTestId('nav-cadastros').click();await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-balance-table').getByText('7',{exact:true}).waitFor();assert.deepEqual(dialogs,[]);
}finally{await erp.close();}});
