'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {launchErpElectron}=require('./fixtures/erp-electron');
async function login(page){await page.getByTestId('login-username').fill('admin');await page.getByTestId('login-password').fill('admin123');await page.getByTestId('login-submit').click();await page.getByTestId('view-dashboard').waitFor({state:'visible'});}

test('desktop inventory supports locations adjustment transfer and persistent balances',async()=>{const erp=await launchErpElectron();const dialogs=[];erp.page.on('dialog',d=>{dialogs.push(d.type());d.dismiss().catch(()=>{});});try{const p=erp.page;await login(p);await p.getByTestId('nav-cadastros').click();await p.getByTestId('cadastros-tab-products').click();await p.getByTestId('product-new').click();await p.getByTestId('product-form-sku').fill('EST-1');await p.getByTestId('product-form-name').fill('Produto Estoque');await p.getByTestId('product-form-save').click();await p.getByText('Produto Estoque',{exact:true}).waitFor();
await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-root').waitFor();for(const name of ['Local A','Local B']){await p.getByTestId('inventory-location-new').click();await p.getByTestId('inventory-location-name').fill(name);await p.getByTestId('inventory-location-save').click();await p.locator('#inventory-locations').getByText(name,{exact:true}).waitFor();}
await p.getByTestId('inventory-adjust').click();await p.getByTestId('inventory-adjust-product').selectOption({label:'Produto Estoque'});await p.getByTestId('inventory-adjust-location').selectOption({label:'Local A'});await p.getByTestId('inventory-adjust-quantity').fill('10');await p.getByTestId('inventory-adjust-reason').fill('Saldo inicial');await p.getByTestId('inventory-operation-save').click();await p.getByTestId('inventory-balance-table').getByText('10',{exact:true}).first().waitFor();
await p.getByTestId('inventory-transfer').click();await p.getByTestId('inventory-transfer-product').selectOption({label:'Produto Estoque'});await p.getByTestId('inventory-transfer-from').selectOption({label:'Local A'});await p.getByTestId('inventory-transfer-to').selectOption({label:'Local B'});await p.getByTestId('inventory-transfer-quantity').fill('3');await p.getByTestId('inventory-transfer-reason').fill('Reposição');await p.getByTestId('inventory-operation-save').click();await p.getByTestId('inventory-balance-table').getByText('7',{exact:true}).first().waitFor();await p.getByTestId('inventory-balance-table').getByText('3',{exact:true}).first().waitFor();
await p.getByTestId('nav-cadastros').click();await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-balance-table').getByText('7',{exact:true}).first().waitFor();
const transferRow=p.locator('[data-operation-id]').filter({hasText:'TRANSFER'}).first();await transferRow.getByRole('button',{name:'Reverter'}).click();await p.getByTestId('confirm-accept').click();await p.getByTestId('inventory-history').getByText('REVERSAL',{exact:true}).waitFor();await p.getByTestId('inventory-balance-table').getByText('10',{exact:true}).first().waitFor();
await p.getByTestId('inventory-transfer').click();await p.getByTestId('inventory-transfer-product').selectOption({label:'Produto Estoque'});await p.getByTestId('inventory-transfer-from').selectOption({label:'Local A'});await p.getByTestId('inventory-transfer-to').selectOption({label:'Local B'});await p.getByTestId('inventory-transfer-quantity').fill('999');await p.getByTestId('inventory-transfer-reason').fill('Saldo insuficiente');await p.getByTestId('inventory-operation-save').click();await p.getByRole('dialog').locator('.form-error').waitFor({state:'visible'});assert.match(await p.getByRole('dialog').locator('.form-error').innerText(),/insuficiente|saldo/i);await p.getByRole('dialog').getByRole('button',{name:'Cancelar'}).click();
await p.getByTestId('inventory-reservations').click();await p.getByRole('button',{name:'Nova reserva'}).click();let reserve=p.getByRole('dialog');await reserve.locator('select[name="productId"]').selectOption({label:'Produto Estoque'});await reserve.locator('select[name="locationId"]').selectOption({label:'Local A'});await reserve.locator('input[name="quantity"]').fill('2');await reserve.getByRole('button',{name:'Reservar'}).click();await p.getByTestId('inventory-reservations').click();reserve=p.getByRole('dialog');await reserve.getByText('ACTIVE',{exact:true}).waitFor();await reserve.getByRole('button',{name:'Liberar'}).click();await p.getByTestId('inventory-reservations').click();reserve=p.getByRole('dialog');await reserve.getByText('RELEASED',{exact:true}).waitFor();await reserve.getByRole('button',{name:'Fechar'}).click();assert.deepEqual(dialogs,[]);
}finally{await erp.close();}});


test('desktop inventory exposes lot traceability cycle count losses and analytics',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await p.getByTestId('nav-cadastros').click();await p.getByTestId('cadastros-tab-products').click();await p.getByTestId('product-new').click();await p.getByTestId('product-form-sku').fill('WMS-1');await p.getByTestId('product-form-name').fill('Produto WMS');await p.getByTestId('product-form-save').click();await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-location-new').click();await p.getByTestId('inventory-location-name').fill('WMS Principal');await p.getByTestId('inventory-location-save').click();
await p.getByTestId('inventory-traceability').click();await p.getByRole('button',{name:'Novo lote'}).click();let d=p.getByRole('dialog');await d.locator('select[name="productId"]').selectOption({label:'Produto WMS'});await d.locator('select[name="locationId"]').selectOption({label:'WMS Principal'});await d.locator('input[name="code"]').fill('LOTE-001');await d.locator('input[name="expiresAt"]').fill('2027-01-01');await d.getByRole('button',{name:'Salvar'}).click();
await p.getByTestId('inventory-traceability').click();await p.getByRole('button',{name:'Entrada rastreada'}).click();d=p.getByRole('dialog');await d.locator('select[name="productId"]').selectOption({label:'Produto WMS'});await d.locator('select[name="locationId"]').selectOption({label:'WMS Principal'});await d.locator('select[name="lotId"]').selectOption({label:'LOTE-001'});await d.locator('input[name="quantity"]').fill('10');await d.getByRole('button',{name:'Registrar'}).click();await p.getByTestId('inventory-balance-table').getByText('10',{exact:true}).first().waitFor();
await p.getByTestId('inventory-cycle').click();d=p.getByRole('dialog');await d.locator('select[name="locationId"]').selectOption({label:'WMS Principal'});await d.getByRole('button',{name:'Iniciar'}).click();d=p.getByRole('dialog');await d.locator('[data-line]').fill('10');await d.getByRole('button',{name:'Salvar contagem'}).click();
await p.getByTestId('inventory-loss').click();d=p.getByRole('dialog');await d.locator('select[name="productId"]').selectOption({label:'Produto WMS'});await d.locator('select[name="locationId"]').selectOption({label:'WMS Principal'});await d.locator('select[name="kind"]').selectOption('DAMAGE');await d.locator('input[name="quantity"]').fill('1');await d.locator('input[name="reason"]').fill('Avaria operacional');await d.getByRole('button',{name:'Registrar'}).click();await p.getByTestId('inventory-balance-table').getByText('9',{exact:true}).first().waitFor();
await p.getByTestId('inventory-analytics').click();d=p.getByRole('dialog');await d.getByText('Curva ABC',{exact:true}).waitFor();await d.getByText('Produto WMS',{exact:false}).first().waitFor();
}finally{await erp.close();}});
