'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {launchErpElectron}=require('./fixtures/erp-electron');

async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}
async function seed(p){await p.evaluate(async()=>{const base=await window.erpDesktop.getBaseUrl(),token=sessionStorage.getItem('erp-token');const api=async(path,body,method='POST')=>{const r=await fetch(base+path,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json();};await api('/api/v1/inventory/locations',{id:'MAIN',name:'Principal'});await api('/api/v1/products',{id:'C-MFG',name:'Componente produção',sku:'C-MFG',costCents:100,salePriceCents:200,trackStock:true});await api('/api/v1/products',{id:'FG-MFG',name:'Produto acabado',sku:'FG-MFG',salePriceCents:1200,trackStock:true});await api('/api/v1/retail/products/FG-MFG',{productType:'MANUFACTURED'},'PATCH');await api('/api/v1/retail/products/FG-MFG/boms',{items:[{productId:'C-MFG',quantity:2}]});await api('/api/v1/inventory/adjustments',{productId:'C-MFG',locationId:'MAIN',quantity:4,direction:'IN',reason:'fixture produção',idempotencyKey:'seed-mfg-e2e'});});}

test('desktop executes manufacturing order and exposes MRP workspace',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await seed(p);await p.getByTestId('nav-producao').click();await p.getByTestId('view-manufacturing').waitFor();await p.getByTestId('manufacturing-product').fill('FG-MFG');await p.getByTestId('manufacturing-location').fill('MAIN');await p.getByTestId('manufacturing-quantity').fill('2');await p.getByTestId('manufacturing-create').click();await p.getByText('FG-MFG',{exact:true}).waitFor();await p.getByTestId('manufacturing-release').click();await p.getByText('Liberada',{exact:true}).waitFor();await p.getByTestId('manufacturing-start').click();await p.getByText('Em produção',{exact:true}).waitFor();await p.getByRole('button',{name:'Consumir restante C-MFG'}).click();await p.getByText('Consumido: 4').waitFor();await p.getByTestId('manufacturing-output-quantity').fill('2');await p.getByTestId('manufacturing-output').click();await p.getByText('Produzido: 2').waitFor();await p.getByTestId('manufacturing-complete').click();await p.getByText('Concluída',{exact:true}).waitFor();await p.getByTestId('manufacturing-mrp-refresh').click();assert.equal(await p.getByTestId('manufacturing-status').textContent(),'Concluída');}finally{await erp.close();}});
