'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {launchErpElectron}=require('./fixtures/erp-electron');
async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}
test('desktop procurement runs request quote approval partial/excess receipt and return without web dialogs',async()=>{const erp=await launchErpElectron();const dialogs=[];erp.page.on('dialog',d=>{dialogs.push(d.type());d.dismiss().catch(()=>{});});try{const p=erp.page;await login(p);
await p.getByTestId('nav-cadastros').click();await p.getByTestId('cadastros-tab-suppliers').click();await p.getByTestId('supplier-new').click();await p.getByTestId('supplier-form-name').fill('Fornecedor E2E');await p.getByTestId('supplier-form-save').click();await p.getByText('Fornecedor E2E',{exact:true}).waitFor();await p.getByTestId('cadastros-tab-products').click();await p.getByTestId('product-new').click();await p.getByTestId('product-form-sku').fill('COMP-1');await p.getByTestId('product-form-name').fill('Produto Compras');await p.getByTestId('product-form-save').click();await p.getByText('Produto Compras',{exact:true}).waitFor();
await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-location-new').click();await p.getByTestId('inventory-location-name').fill('Almoxarifado');await p.getByTestId('inventory-location-save').click();await p.locator('#inventory-locations').getByText('Almoxarifado',{exact:true}).waitFor();
await p.getByTestId('nav-compras').click();await p.getByTestId('procurement-root').waitFor();await p.getByTestId('procurement-requisition-new').click();await p.getByTestId('procurement-requisition-location').selectOption({label:'Almoxarifado'});await p.getByTestId('procurement-requisition-justification').fill('Reposição E2E');await p.getByTestId('procurement-requisition-product-0').selectOption({label:'Produto Compras'});await p.getByTestId('procurement-requisition-quantity-0').fill('10');await p.getByTestId('procurement-requisition-save').click();const row=p.locator('[data-requisition-id]').filter({hasText:'Reposição E2E'});await row.waitFor();await row.getByRole('button',{name:'Editar'}).click();await p.getByTestId('procurement-requisition-justification').fill('Reposição Editada E2E');await p.getByTestId('procurement-requisition-save').click();const editedRow=p.locator('[data-requisition-id]').filter({hasText:'Reposição Editada E2E'});await editedRow.waitFor();await editedRow.getByRole('button',{name:'Iniciar cotação'}).click();
await p.getByTestId('procurement-tab-quotations').click();await p.getByTestId('procurement-quotation-new').click();await p.getByTestId('procurement-quotation-requisition').selectOption({index:0});await p.getByTestId('procurement-quotation-supplier').selectOption({label:'Fornecedor E2E'});await p.getByTestId('procurement-quotation-cost-0').fill('1,00');await p.getByTestId('procurement-quotation-available-0').fill('10');await p.getByTestId('procurement-quotation-save').click();const quoteRow=p.locator('[data-quotation-id]').filter({hasText:'Fornecedor E2E'});await quoteRow.getByRole('button',{name:'Editar'}).click();await p.getByTestId('procurement-quotation-cost-0').fill('1,25');await p.getByTestId('procurement-quotation-save').click();await quoteRow.getByRole('button',{name:'Enviar cotação'}).click();
await p.getByTestId('procurement-tab-requisitions').click();const quotingRow=p.locator('[data-requisition-id]').filter({hasText:'Reposição Editada E2E'});await quotingRow.getByRole('button',{name:'Gerar adjudicação'}).click();await p.getByTestId('procurement-tab-approvals').click();const award=p.locator('[data-award-id]').first();await award.getByRole('button',{name:'Enviar para aprovação'}).click();await award.getByRole('button',{name:'Aprovar'}).click();await award.getByRole('button',{name:'Gerar pedidos'}).click();
await p.getByTestId('procurement-tab-orders').click();const order=p.locator('[data-order-id]').first();await order.getByRole('button',{name:'Enviar pedido'}).click();await order.getByRole('button',{name:'Receber'}).click();await p.getByTestId('procurement-receipt-quantity-0').fill('8');await p.getByTestId('procurement-receipt-save').click();await p.getByText('Faltam 2',{exact:false}).waitFor();
await order.getByRole('button',{name:'Receber'}).click();await p.getByTestId('procurement-receipt-quantity-0').fill('3');await p.getByTestId('procurement-receipt-excess-reason').fill('Aceite E2E');await p.getByTestId('procurement-receipt-save').click();await p.getByText('Excedente 1',{exact:false}).waitFor();
await p.getByTestId('procurement-tab-receipts').click();const receipt=p.locator('[data-receipt-id]').last();await receipt.getByRole('button',{name:'Devolver'}).click();await p.getByTestId('procurement-return-quantity-0').fill('1');await p.getByTestId('procurement-return-reason').fill('Avaria E2E');await p.getByTestId('procurement-return-save').click();await p.getByTestId('procurement-tab-returns').click();await p.getByText('Avaria E2E',{exact:true}).waitFor();assert.deepEqual(dialogs,[]);
}finally{await erp.close();}});


test('procurement exposes cancellation and approval rejection through UI',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await p.getByTestId('nav-cadastros').click();await p.getByTestId('cadastros-tab-suppliers').click();await p.getByTestId('supplier-new').click();await p.getByTestId('supplier-form-name').fill('Fornecedor Reject E2E');await p.getByTestId('supplier-form-save').click();await p.getByTestId('cadastros-tab-products').click();await p.getByTestId('product-new').click();await p.getByTestId('product-form-sku').fill('REJ-1');await p.getByTestId('product-form-name').fill('Produto Reject');await p.getByTestId('product-form-save').click();await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-location-new').click();await p.getByTestId('inventory-location-name').fill('Local Reject');await p.getByTestId('inventory-location-save').click();await p.getByTestId('nav-compras').click();await p.getByTestId('procurement-requisition-new').click();await p.getByTestId('procurement-requisition-location').selectOption({label:'Local Reject'});await p.getByTestId('procurement-requisition-justification').fill('Cancelar E2E');await p.getByTestId('procurement-requisition-product-0').selectOption({label:'Produto Reject'});await p.getByTestId('procurement-requisition-quantity-0').fill('1');await p.getByTestId('procurement-requisition-save').click();const cancelRow=p.locator('[data-requisition-id]').filter({hasText:'Cancelar E2E'});await cancelRow.getByRole('button',{name:'Cancelar'}).click();await cancelRow.getByText('CANCELLED',{exact:true}).waitFor();}finally{await erp.close();}});


test('procurement rejection is executable from approval UI',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await p.getByTestId('nav-cadastros').click();await p.getByTestId('cadastros-tab-suppliers').click();await p.getByTestId('supplier-new').click();await p.getByTestId('supplier-form-name').fill('Fornecedor Rejeicao');await p.getByTestId('supplier-form-save').click();await p.getByTestId('cadastros-tab-products').click();await p.getByTestId('product-new').click();await p.getByTestId('product-form-sku').fill('APR-REJ');await p.getByTestId('product-form-name').fill('Produto Rejeicao');await p.getByTestId('product-form-save').click();await p.getByTestId('nav-estoque').click();await p.getByTestId('inventory-location-new').click();await p.getByTestId('inventory-location-name').fill('Local Rejeicao');await p.getByTestId('inventory-location-save').click();await p.getByTestId('nav-compras').click();await p.getByTestId('procurement-requisition-new').click();await p.getByTestId('procurement-requisition-location').selectOption({label:'Local Rejeicao'});await p.getByTestId('procurement-requisition-justification').fill('Aprovar ou rejeitar');await p.getByTestId('procurement-requisition-product-0').selectOption({label:'Produto Rejeicao'});await p.getByTestId('procurement-requisition-quantity-0').fill('1');await p.getByTestId('procurement-requisition-save').click();let r=p.locator('[data-requisition-id]').filter({hasText:'Aprovar ou rejeitar'});await r.getByRole('button',{name:'Iniciar cotação'}).click();await p.getByTestId('procurement-tab-quotations').click();await p.getByTestId('procurement-quotation-new').click();await p.getByTestId('procurement-quotation-supplier').selectOption({label:'Fornecedor Rejeicao'});await p.getByTestId('procurement-quotation-cost-0').fill('10,00');await p.getByTestId('procurement-quotation-save').click();await p.locator('[data-quotation-id]').filter({hasText:'Fornecedor Rejeicao'}).getByRole('button',{name:'Enviar cotação'}).click();await p.getByTestId('procurement-tab-requisitions').click();r=p.locator('[data-requisition-id]').filter({hasText:'Aprovar ou rejeitar'});await r.getByRole('button',{name:'Gerar adjudicação'}).click();await p.getByTestId('procurement-tab-approvals').click();const a=p.locator('[data-award-id]').first();await a.getByRole('button',{name:'Enviar para aprovação'}).click();await a.getByRole('button',{name:'Rejeitar'}).click();await a.getByText('REJECTED',{exact:true}).waitFor();}finally{await erp.close();}});
