'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{launchErpElectron}=require('./fixtures/erp-electron');

async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}
async function seed(p){await p.evaluate(async()=>{const base=await window.erpDesktop.getBaseUrl(),token=sessionStorage.getItem('erp-token');const api=async(path,body,method='POST')=>{const r=await fetch(base+path,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json();};await api('/api/v1/inventory/locations',{id:'MAIN',name:'Principal'});await api('/api/v1/inventory/locations',{id:'SECOND',name:'Secundário'});await api('/api/v1/products',{id:'P-PDV',sku:'PDV-001',name:'Produto PDV E2E',salePriceCents:1000,trackStock:true});await api('/api/v1/inventory/adjustments',{productId:'P-PDV',locationId:'MAIN',quantity:10,direction:'IN',reason:'fixture PDV',idempotencyKey:'seed-retail-e2e'});});}

test('desktop retail completes cash sale return close and transfer lifecycle',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await seed(p);await p.getByTestId('nav-operacao').click();await p.getByTestId('view-retail').waitFor();
await p.getByTestId('retail-tab-caixa').click();await p.getByTestId('retail-cash-location').fill('MAIN');await p.getByTestId('retail-cash-opening').fill('0');await p.getByTestId('retail-cash-open').click();await p.getByTestId('retail-cash-summary').getByText(/OPEN/).waitFor();
await p.getByTestId('retail-sale-code').fill('PDV-001');await p.getByTestId('retail-sale-quantity').fill('1');await p.getByTestId('retail-sale-method').selectOption('CASH');await p.getByTestId('retail-sale-amount').fill('1000');await p.getByTestId('retail-sale-submit').click();const saleText=await p.getByTestId('retail-sale-summary').innerText();const saleId=saleText.match(/Venda\s+([^\s·]+)/)?.[1];assert.ok(saleId);
await p.getByTestId('retail-tab-devolucao').click();await p.getByTestId('retail-return-sale').fill(saleId);await p.getByTestId('retail-return-reason').fill('Troca E2E');await p.getByTestId('retail-return-method').selectOption('CASH');await p.getByTestId('retail-return-submit').click();await p.getByTestId('retail-return-summary').getByText(/Devolução/).waitFor();
await p.getByTestId('retail-tab-caixa').click();await p.getByTestId('retail-cash-closing').fill('1000');await p.getByTestId('retail-cash-close').click();await p.getByTestId('retail-cash-summary').getByText(/CLOSED/).waitFor();
await p.getByTestId('retail-tab-transferencias').click();await p.getByTestId('retail-transfer-product').fill('P-PDV');await p.getByTestId('retail-transfer-from').fill('MAIN');await p.getByTestId('retail-transfer-to').fill('SECOND');await p.getByTestId('retail-transfer-quantity').fill('2');await p.getByTestId('retail-transfer-reason').fill('Reposição filial');await p.getByTestId('retail-transfer-request').click();const row=p.getByTestId('retail-transfer-row').first();await row.getByText(/REQUESTED/).waitFor();await row.getByRole('button',{name:'Enviar'}).click();await row.getByText(/IN_TRANSIT/).waitFor();await row.getByRole('button',{name:'Receber'}).click();await row.getByText(/RECEIVED/).waitFor();
}finally{await erp.close();}});

test('desktop retail collapses a double click into one POS mutation',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await seed(p);await p.getByTestId('nav-operacao').click();await p.getByTestId('retail-cash-open').click();await p.getByTestId('retail-cash-summary').getByText(/OPEN/).waitFor();await p.getByTestId('retail-sale-code').fill('PDV-001');await p.getByTestId('retail-sale-quantity').fill('1');await p.getByTestId('retail-sale-method').selectOption('CASH');await p.getByTestId('retail-sale-amount').fill('1000');let posts=0;p.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/retail/sales')posts++;});await p.getByTestId('retail-sale-submit').dblclick();await p.getByTestId('retail-sale-summary').waitFor();await p.waitForTimeout(100);assert.equal(posts,1);}finally{await erp.close();}});

test('desktop retail validates and imports product rows from UI',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await p.getByTestId('nav-operacao').click();await p.getByTestId('retail-tab-importacao').click();await p.getByTestId('retail-import-entity').selectOption('PRODUCT');await p.getByTestId('retail-import-format').selectOption('CSV');await p.getByTestId('retail-import-source').fill('e2e.csv');await p.getByTestId('retail-import-rows').fill(JSON.stringify([{id:'IMP-E2E',sku:'IMP-E2E',name:'Produto Importado E2E',salePriceCents:500,trackStock:false}]));await p.getByTestId('retail-import-submit').click();await p.getByText('Operação concluída.',{exact:true}).waitFor();await p.getByTestId('nav-cadastros').click();await p.getByTestId('cadastros-tab-products').click();await p.getByText('Produto Importado E2E',{exact:true}).waitFor();}finally{await erp.close();}});
