'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {launchErpElectron}=require('./fixtures/erp-electron');

async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}

async function seed(p){await p.evaluate(async()=>{const base=await window.erpDesktop.getBaseUrl(),token=sessionStorage.getItem('erp-token');const api=async(path,body,method='POST')=>{const r=await fetch(base+path,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json();};await api('/api/v1/customers',{id:'C-E2E',name:'Cliente Serviços'});await api('/api/v1/inventory/locations',{id:'MAIN',name:'Principal'});await api('/api/v1/products',{id:'S-E2E',name:'Reparo técnico',sku:'SERV-E2E',salePriceCents:2500,trackStock:false});await api('/api/v1/retail/products/S-E2E',{productType:'SERVICE'},'PATCH');await api('/api/v1/products',{id:'P-E2E',name:'Peça E2E',sku:'PEC-E2E',salePriceCents:1000,trackStock:true});await api('/api/v1/inventory/adjustments',{productId:'P-E2E',locationId:'MAIN',quantity:2,direction:'IN',reason:'fixture',idempotencyKey:'seed-os-e2e'});});}

async function expectStatus(p,value){await p.getByTestId('service-order-status').waitFor();assert.equal(await p.getByTestId('service-order-status').textContent(),value);}

test('desktop completes a service order using services and reserved parts',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await seed(p);await p.getByTestId('nav-servicos').click();await p.getByTestId('view-service-orders').waitFor();await p.getByTestId('service-order-customer').fill('C-E2E');await p.getByTestId('service-order-location').fill('MAIN');await p.getByTestId('service-order-title').fill('Reparo E2E');await p.getByTestId('service-order-create').click();await p.getByRole('heading',{name:'Reparo E2E',exact:true}).waitFor();await p.getByTestId('service-order-line-product').fill('S-E2E');await p.getByTestId('service-order-line-type').selectOption('SERVICE');await p.getByTestId('service-order-line-price').fill('2500');await p.getByTestId('service-order-line-add').click();await p.getByText('Reparo técnico',{exact:true}).waitFor();await p.getByTestId('service-order-line-product').fill('P-E2E');await p.getByTestId('service-order-line-type').selectOption('PART');await p.getByTestId('service-order-line-price').fill('1000');await p.getByTestId('service-order-line-add').click();await p.getByText('Peça E2E',{exact:true}).waitFor();await p.getByTestId('service-order-approve').click();await expectStatus(p,'Aprovada');await p.getByTestId('service-order-start').click();await expectStatus(p,'Em execução');await p.getByRole('button',{name:'Consumir 1 Peça E2E'}).click();await p.getByText('Consumido: 1').waitFor();await p.getByTestId('service-order-complete').click();await expectStatus(p,'Concluída');await p.getByText('R$ 35,00').waitFor();assert.equal(await p.getByTestId('service-order-status').textContent(),'Concluída');}finally{await erp.close();}});
