'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{launchErpElectron}=require('./fixtures/erp-electron');
async function login(p){await p.getByTestId('login-username').fill('admin');await p.getByTestId('login-password').fill('admin123');await p.getByTestId('login-submit').click();await p.getByTestId('view-dashboard').waitFor();}
async function openView(p,view){const button=p.locator(`button[data-view="${view}"]`);if(!(await button.isVisible())){const group=['administracao','configuracoes'].includes(view)?'sistema':['producao','rastreabilidade','inteligencia','gestao-avancada'].includes(view)?'controle':null;if(group){const toggle=p.locator(`[data-nav-group="${group}"] .nav-group-toggle`);if(await toggle.getAttribute('aria-expanded')!=='true')await toggle.click();}}await button.click();}
test('settings pairs and revokes LAN device and switches local server override',async()=>{const erp=await launchErpElectron();try{const p=erp.page;await login(p);await openView(p,'configuracoes');await p.getByTestId('settings-lan-pair').click();const code=(await p.getByTestId('settings-lan-pair-code').innerText()).match(/Código:\s*(\S+)/)?.[1];assert.ok(code);await p.evaluate(async code=>{const base=await window.erpDesktop.getBaseUrl();const r=await fetch(base+'/api/v1/lan/pair/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,deviceName:'Dispositivo E2E'})});if(!r.ok)throw new Error(await r.text());},code);await p.getByTestId('settings-lan-refresh').click();const device=p.getByTestId('settings-lan-device').filter({hasText:'Dispositivo E2E'});await device.waitFor();await device.getByRole('button',{name:'Revogar'}).click();await device.getByText(/Revogado/).waitFor();
const base=await p.evaluate(()=>window.erpDesktop.getBaseUrl());await p.getByTestId('settings-lan-url').fill(base);await p.getByTestId('settings-lan-use').click();await p.getByTestId('login-submit').waitFor();await login(p);assert.equal(await p.evaluate(()=>localStorage.getItem('erp-server-url')),base);await openView(p,'configuracoes');await p.getByTestId('settings-lan-local').click();await p.getByTestId('login-submit').waitFor();await login(p);assert.equal(await p.evaluate(()=>localStorage.getItem('erp-server-url')),null);
}finally{await erp.close();}});
