'use strict';
const {randomUUID}=require('node:crypto');
const {assertRole}=require('../auth/rbac');
const SECRET=/token|secret|password|api.?key|credential/i;
function createIntegrationService({db,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db)throw new TypeError('Database is required.');
 const redact=value=>{if(Array.isArray(value))return value.map(redact);if(value&&typeof value==='object'){const out={};for(const [k,v] of Object.entries(value))out[k]=SECRET.test(k)?'[REDACTED]':redact(v);return out;}return value;};
 const map=row=>row&&({id:row.id,companyId:row.company_id,kind:row.kind,name:row.name,endpoint:row.endpoint,config:redact(JSON.parse(row.config_json||'{}')),active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at});
 function create(input={},actor=null){assertRole(actor,['admin']);const companyId=String(actor?.companyId||'default');const kind=String(input.kind||'GENERIC').trim().toUpperCase();const name=String(input.name||'').trim();if(!name)throw new Error('Nome da integracao obrigatorio.');const id=String(input.id||idFactory('integration')),ts=String(now());db.prepare('INSERT INTO integrations(id,company_id,kind,name,endpoint,config_json,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').run(id,companyId,kind,name,String(input.endpoint||'').trim()||null,JSON.stringify(input.config||{}),ts,ts);return get(id,companyId);}
 function get(id,companyId='default'){return map(db.prepare('SELECT * FROM integrations WHERE id=? AND company_id=?').get(String(id),String(companyId)));}
 function list({companyId='default',kind=null,includeInactive=false}={}){const clauses=['company_id=?'],params=[String(companyId)];if(kind){clauses.push('kind=?');params.push(String(kind).toUpperCase());}if(!includeInactive)clauses.push('active=1');return db.prepare(`SELECT * FROM integrations WHERE ${clauses.join(' AND ')} ORDER BY name,id`).all(...params).map(map);}
 function setActive(id,active,actor=null){assertRole(actor,['admin']);const companyId=String(actor?.companyId||'default');const result=db.prepare('UPDATE integrations SET active=?,updated_at=? WHERE id=? AND company_id=?').run(active?1:0,String(now()),String(id),companyId);if(!result.changes)throw new Error('Integracao nao encontrada.');return get(id,companyId);}
 function createBankConnection(input={},actor=null){assertRole(actor,['admin','manager']);const companyId=String(actor?.companyId||'default');const name=String(input.name||'').trim();if(!name)throw new Error('Nome da conexao bancaria obrigatorio.');const provider=String(input.provider||'manual').trim().toLowerCase();const id=String(input.id||idFactory('bank-connection')),ts=String(now());db.prepare('INSERT INTO bank_connections(id,company_id,name,provider,account_id,integration_id,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').run(id,companyId,name,provider,input.accountId||null,input.integrationId||null,ts,ts);return getBankConnection(id,companyId);}
 function getBankConnection(id,companyId='default'){const row=db.prepare('SELECT * FROM bank_connections WHERE id=? AND company_id=?').get(String(id),String(companyId));return row&&({id:row.id,companyId:row.company_id,name:row.name,provider:row.provider,accountId:row.account_id,integrationId:row.integration_id,active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at});}
 function listBankConnections({companyId='default',includeInactive=false}={}){return db.prepare(`SELECT * FROM bank_connections WHERE company_id=?${includeInactive?'':' AND active=1'} ORDER BY name,id`).all(String(companyId)).map(row=>({id:row.id,companyId:row.company_id,name:row.name,provider:row.provider,accountId:row.account_id,integrationId:row.integration_id,active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at}));}
 return{create,get,list,setActive,createBankConnection,getBankConnection,listBankConnections,redact};
}
module.exports={createIntegrationService};
