'use strict';
const {randomUUID}=require('node:crypto');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
const {assertCents}=require('../shared/money');
function createCatalogService({db,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db)throw new TypeError('Database is required.');
 const mapCategory=row=>row&&({id:row.id,name:row.name,active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at});
 const mapProduct=row=>row&&({id:row.id,sku:row.sku,name:row.name,categoryId:row.category_id,costCents:Number(row.cost_cents),salePriceCents:Number(row.sale_price_cents),trackStock:Boolean(row.track_stock),active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at});
 function createCategory(input={},actor=null){assertRole(actor,['admin','manager']);const id=String(input.id||idFactory('pcat')),name=String(input.name||'').trim();if(!name)throw new Error('Nome da categoria obrigatorio.');const ts=String(now());db.prepare('INSERT INTO product_categories(id,name,active,created_at,updated_at) VALUES(?,?,1,?,?)').run(id,name,ts,ts);writeAudit(db,{action:'catalog.category.create',entity:'product-category',entityId:id,actor,context:{}},now);return getCategory(id);}
 function getCategory(id){return mapCategory(db.prepare('SELECT * FROM product_categories WHERE id=?').get(String(id)));}
 function listCategories({includeInactive=false}={}){return db.prepare(`SELECT * FROM product_categories${includeInactive?'':' WHERE active=1'} ORDER BY name,id`).all().map(mapCategory);}
 function createProduct(input={},actor=null){assertRole(actor,['admin','manager']);const id=String(input.id||idFactory('product')),name=String(input.name||'').trim(),sku=String(input.sku||'').trim()||null;if(!name)throw new Error('Nome do produto obrigatorio.');const costCents=assertCents(input.costCents??0,'costCents'),salePriceCents=assertCents(input.salePriceCents??0,'salePriceCents');if(costCents<0||salePriceCents<0)throw new Error('Preco/custo nao pode ser negativo.');const categoryId=String(input.categoryId||'').trim()||null;if(categoryId){const cat=getCategory(categoryId);if(!cat)throw new Error('Categoria de produto nao encontrada.');if(!cat.active)throw new Error('Categoria de produto inativa.');}const ts=String(now());db.prepare('INSERT INTO products(id,sku,name,category_id,cost_cents,sale_price_cents,track_stock,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)').run(id,sku,name,categoryId,costCents,salePriceCents,input.trackStock===false?0:1,ts,ts);writeAudit(db,{action:'catalog.product.create',entity:'product',entityId:id,actor,context:{sku,trackStock:input.trackStock!==false}},now);return getProduct(id);}
 function getProduct(id){return mapProduct(db.prepare('SELECT * FROM products WHERE id=?').get(String(id)));}
 function requireActiveProduct(id){const product=getProduct(id);if(!product)throw new Error('Produto nao encontrado.');if(!product.active)throw new Error('Produto inativo.');return product;}
 function listProducts({includeInactive=false,query=null}={}){const clauses=[],params=[];if(!includeInactive)clauses.push('active=1');if(query){clauses.push('(LOWER(name) LIKE ? OR LOWER(COALESCE(sku,\'\')) LIKE ?)');const q=`%${String(query).toLowerCase()}%`;params.push(q,q);}return db.prepare(`SELECT * FROM products${clauses.length?` WHERE ${clauses.join(' AND ')}`:''} ORDER BY name,id`).all(...params).map(mapProduct);}
 function updateCost(id,costCents,actor=null){assertRole(actor,['admin','manager','system']);const value=assertCents(costCents,'costCents');if(value<0)throw new Error('Custo invalido.');const result=db.prepare('UPDATE products SET cost_cents=?,updated_at=? WHERE id=?').run(value,String(now()),String(id));if(!result.changes)throw new Error('Produto nao encontrado.');writeAudit(db,{action:'catalog.product.cost',entity:'product',entityId:String(id),actor,context:{costCents:value}},now);return getProduct(id);}
 function setProductActive(id,active,actor){assertRole(actor,['admin','manager']);const result=db.prepare('UPDATE products SET active=?,updated_at=? WHERE id=?').run(active?1:0,String(now()),String(id));if(!result.changes)throw new Error('Produto nao encontrado.');writeAudit(db,{action:'catalog.product.active',entity:'product',entityId:String(id),actor,context:{active:Boolean(active)}},now);return getProduct(id);}
 return{createCategory,getCategory,listCategories,createProduct,getProduct,requireActiveProduct,listProducts,updateCost,setProductActive};
}
module.exports={createCatalogService};
