'use strict';
const {randomUUID}=require('node:crypto');
const {writeAudit}=require('../../core/audit/audit-log');
const {assertRole}=require('../../core/auth/rbac');
const {assertCents}=require('../shared/money');
function createCatalogService({db,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db)throw new TypeError('Database is required.');
 const mapCategory=row=>row&&({id:row.id,name:row.name,active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at});
 const mapProduct=row=>row&&({id:row.id,sku:row.sku,name:row.name,categoryId:row.category_id,costCents:Number(row.cost_cents),salePriceCents:Number(row.sale_price_cents),trackStock:Boolean(row.track_stock),minStock:Number(row.min_stock||0),targetStock:row.target_stock==null?null:Number(row.target_stock),removalStrategy:row.removal_strategy||'MANUAL',active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at});
 function createCategory(input={},actor=null){assertRole(actor,['admin','manager']);const id=String(input.id||idFactory('pcat')),name=String(input.name||'').trim();if(!name)throw new Error('Nome da categoria obrigatorio.');const ts=String(now());db.prepare('INSERT INTO product_categories(id,name,active,created_at,updated_at) VALUES(?,?,1,?,?)').run(id,name,ts,ts);writeAudit(db,{action:'catalog.category.create',entity:'product-category',entityId:id,actor,context:{}},now);return getCategory(id);}
 function getCategory(id){return mapCategory(db.prepare('SELECT * FROM product_categories WHERE id=?').get(String(id)));}
 function listCategories({includeInactive=false,query=null}={}){const clauses=[],params=[];if(!includeInactive)clauses.push('active=1');if(query){clauses.push('LOWER(name) LIKE ?');params.push(`%${String(query).toLowerCase()}%`);}return db.prepare(`SELECT * FROM product_categories${clauses.length?` WHERE ${clauses.join(' AND ')}`:''} ORDER BY name,id`).all(...params).map(mapCategory);}
 function updateCategory(id,input={},actor=null){assertRole(actor,['admin','manager']);const current=getCategory(id);if(!current)throw new Error('Categoria de produto nao encontrada.');const name=input.name===undefined?current.name:String(input.name||'').trim();if(!name)throw new Error('Nome da categoria obrigatorio.');db.prepare('UPDATE product_categories SET name=?,updated_at=? WHERE id=?').run(name,String(now()),current.id);writeAudit(db,{action:'catalog.category.update',entity:'product-category',entityId:current.id,actor,context:{before:{name:current.name},after:{name}}},now);return getCategory(current.id);}
 function setCategoryActive(id,active,actor){assertRole(actor,['admin','manager']);const result=db.prepare('UPDATE product_categories SET active=?,updated_at=? WHERE id=?').run(active?1:0,String(now()),String(id));if(!result.changes)throw new Error('Categoria de produto nao encontrada.');writeAudit(db,{action:'catalog.category.active',entity:'product-category',entityId:String(id),actor,context:{active:Boolean(active)}},now);return getCategory(id);}
 function createProduct(input={},actor=null){assertRole(actor,['admin','manager']);const id=String(input.id||idFactory('product')),name=String(input.name||'').trim(),sku=String(input.sku||'').trim()||null;if(!name)throw new Error('Nome do produto obrigatorio.');const costCents=assertCents(input.costCents??0,'costCents'),salePriceCents=assertCents(input.salePriceCents??0,'salePriceCents');if(costCents<0||salePriceCents<0)throw new Error('Preco/custo nao pode ser negativo.');const categoryId=String(input.categoryId||'').trim()||null;if(categoryId){const cat=getCategory(categoryId);if(!cat)throw new Error('Categoria de produto nao encontrada.');if(!cat.active)throw new Error('Categoria de produto inativa.');}const ts=String(now());db.prepare('INSERT INTO products(id,sku,name,category_id,cost_cents,sale_price_cents,track_stock,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)').run(id,sku,name,categoryId,costCents,salePriceCents,input.trackStock===false?0:1,ts,ts);if(input.minStock!==undefined||input.targetStock!==undefined||input.removalStrategy!==undefined)db.prepare('UPDATE products SET min_stock=?,target_stock=?,removal_strategy=? WHERE id=?').run(Number(input.minStock||0),input.targetStock==null?null:Number(input.targetStock),String(input.removalStrategy||'MANUAL').toUpperCase(),id);writeAudit(db,{action:'catalog.product.create',entity:'product',entityId:id,actor,context:{sku,trackStock:input.trackStock!==false}},now);return getProduct(id);}
 function getProduct(id){return mapProduct(db.prepare('SELECT * FROM products WHERE id=?').get(String(id)));}
 function requireActiveProduct(id){const product=getProduct(id);if(!product)throw new Error('Produto nao encontrado.');if(!product.active)throw new Error('Produto inativo.');return product;}
 function listProducts({includeInactive=false,query=null}={}){const clauses=[],params=[];if(!includeInactive)clauses.push('active=1');if(query){clauses.push('(LOWER(name) LIKE ? OR LOWER(COALESCE(sku,\'\')) LIKE ?)');const q=`%${String(query).toLowerCase()}%`;params.push(q,q);}return db.prepare(`SELECT * FROM products${clauses.length?` WHERE ${clauses.join(' AND ')}`:''} ORDER BY name,id`).all(...params).map(mapProduct);}
 function updateProduct(id,input={},actor=null){assertRole(actor,['admin','manager']);const current=getProduct(id);if(!current)throw new Error('Produto nao encontrado.');const name=input.name===undefined?current.name:String(input.name||'').trim();if(!name)throw new Error('Nome do produto obrigatorio.');const sku=input.sku===undefined?current.sku:(String(input.sku||'').trim()||null);let categoryId=input.categoryId===undefined?current.categoryId:(String(input.categoryId||'').trim()||null);if(categoryId){const cat=getCategory(categoryId);if(!cat)throw new Error('Categoria de produto nao encontrada.');if(!cat.active)throw new Error('Categoria de produto inativa.');}const costCents=input.costCents===undefined?current.costCents:assertCents(input.costCents,'costCents');const salePriceCents=input.salePriceCents===undefined?current.salePriceCents:assertCents(input.salePriceCents,'salePriceCents');if(costCents<0||salePriceCents<0)throw new Error('Preco/custo nao pode ser negativo.');const trackStock=input.trackStock===undefined?current.trackStock:Boolean(input.trackStock);const minStock=input.minStock===undefined?current.minStock:Number(input.minStock);const targetStock=input.targetStock===undefined?current.targetStock:(input.targetStock==null?null:Number(input.targetStock));const removalStrategy=input.removalStrategy===undefined?current.removalStrategy:String(input.removalStrategy).toUpperCase();if(minStock<0||(targetStock!=null&&targetStock<0)||!['MANUAL','FIFO','FEFO'].includes(removalStrategy))throw new Error('Política de estoque inválida.');db.prepare('UPDATE products SET sku=?,name=?,category_id=?,cost_cents=?,sale_price_cents=?,track_stock=?,min_stock=?,target_stock=?,removal_strategy=?,updated_at=? WHERE id=?').run(sku,name,categoryId,costCents,salePriceCents,trackStock?1:0,minStock,targetStock,removalStrategy,String(now()),current.id);writeAudit(db,{action:'catalog.product.update',entity:'product',entityId:current.id,actor,context:{before:{sku:current.sku,name:current.name,categoryId:current.categoryId,costCents:current.costCents,salePriceCents:current.salePriceCents,trackStock:current.trackStock},after:{sku,name,categoryId,costCents,salePriceCents,trackStock}}},now);return getProduct(current.id);}
 function updateCost(id,costCents,actor=null){assertRole(actor,['admin','manager','system']);const value=assertCents(costCents,'costCents');if(value<0)throw new Error('Custo invalido.');const result=db.prepare('UPDATE products SET cost_cents=?,updated_at=? WHERE id=?').run(value,String(now()),String(id));if(!result.changes)throw new Error('Produto nao encontrado.');writeAudit(db,{action:'catalog.product.cost',entity:'product',entityId:String(id),actor,context:{costCents:value}},now);return getProduct(id);}
 function setProductActive(id,active,actor){assertRole(actor,['admin','manager']);const result=db.prepare('UPDATE products SET active=?,updated_at=? WHERE id=?').run(active?1:0,String(now()),String(id));if(!result.changes)throw new Error('Produto nao encontrado.');writeAudit(db,{action:'catalog.product.active',entity:'product',entityId:String(id),actor,context:{active:Boolean(active)}},now);return getProduct(id);}
 return{createCategory,getCategory,listCategories,updateCategory,setCategoryActive,createProduct,getProduct,requireActiveProduct,listProducts,updateProduct,updateCost,setProductActive};
}
module.exports={createCatalogService};
