'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {assertRole}=require('../../core/auth/rbac');
const {writeAudit}=require('../../core/audit/audit-log');

function createAccountingService({db,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
 if(!db)throw new TypeError('db is required.');
 const cid=a=>String(a?.companyId||'default');
 const manage=a=>assertRole(a,['admin','manager','director']);
 const cents=(v,label)=>{const n=Number(v||0);if(!Number.isSafeInteger(n)||n<0)throw new Error(`${label} invalido.`);return n;};
 const isoDate=(v,label='Data')=>{const s=String(v||'').slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(`${s}T00:00:00Z`)))throw new Error(`${label} invalida.`);return s;};
 const accountMap=r=>r&&({companyId:r.company_id,id:r.id,code:r.code,name:r.name,type:r.type,normalBalance:r.normal_balance,parentId:r.parent_id||null,active:Boolean(r.active)});
 function getAccount(id,a){return accountMap(db.prepare('SELECT * FROM accounting_accounts WHERE company_id=? AND id=?').get(cid(a),String(id)));}
 function listAccounts(a){return db.prepare('SELECT * FROM accounting_accounts WHERE company_id=? ORDER BY code,id').all(cid(a)).map(accountMap);}
 function createAccount(i={},a=null){manage(a);const companyId=cid(a),id=String(i.id||idFactory('acct')),code=String(i.code||'').trim(),name=String(i.name||'').trim(),type=String(i.type||'').toUpperCase(),normal=String(i.normalBalance||'').toUpperCase();if(!code||!name)throw new Error('Codigo e nome da conta obrigatorios.');if(!['ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE'].includes(type))throw new Error('Tipo de conta invalido.');if(!['DEBIT','CREDIT'].includes(normal))throw new Error('Saldo normal invalido.');if(i.parentId&&!getAccount(i.parentId,a))throw new Error('Conta pai nao encontrada.');const ts=String(now());db.prepare('INSERT INTO accounting_accounts(company_id,id,code,name,type,normal_balance,parent_id,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)').run(companyId,id,code,name,type,normal,i.parentId||null,ts,ts);writeAudit(db,{action:'accounting.account.create',entity:'accounting-account',entityId:id,actor:a,context:{code,type}},now);return getAccount(id,a);}
 const periodMap=r=>r&&({id:r.id,name:r.name,startDate:r.start_date,endDate:r.end_date,status:r.status,closedAt:r.closed_at||null,closedBy:r.closed_by||null});
 function createPeriod(i={},a=null){manage(a);const companyId=cid(a),id=String(i.id||idFactory('period')),start=isoDate(i.startDate,'Inicio'),end=isoDate(i.endDate,'Fim');if(start>end)throw new Error('Periodo invalido.');const ts=String(now());db.prepare("INSERT INTO accounting_periods(company_id,id,name,start_date,end_date,status,created_at,updated_at) VALUES(?,?,?,?,?,'OPEN',?,?)").run(companyId,id,String(i.name||id),start,end,ts,ts);return periodMap(db.prepare('SELECT * FROM accounting_periods WHERE company_id=? AND id=?').get(companyId,id));}
 function closePeriod(id,a=null){manage(a);const companyId=cid(a),p=db.prepare('SELECT * FROM accounting_periods WHERE company_id=? AND id=?').get(companyId,String(id));if(!p)throw new Error('Periodo contabil nao encontrado.');if(p.status==='CLOSED')return periodMap(p);const ts=String(now());db.prepare("UPDATE accounting_periods SET status='CLOSED',closed_at=?,closed_by=?,updated_at=? WHERE company_id=? AND id=?").run(ts,a?.userId||null,ts,companyId,String(id));return periodMap(db.prepare('SELECT * FROM accounting_periods WHERE company_id=? AND id=?').get(companyId,String(id)));}
 function assertOpen(date,a){const row=db.prepare("SELECT 1 FROM accounting_periods WHERE company_id=? AND status='CLOSED' AND start_date<=? AND end_date>=? LIMIT 1").get(cid(a),date,date);if(row)throw new Error('Periodo contabil fechado/bloqueado.');}
 function journalMap(row,a){if(!row)return null;const lines=db.prepare('SELECT * FROM accounting_journal_lines WHERE journal_id=? ORDER BY rowid').all(row.id).map(x=>({id:x.id,accountId:x.account_id,debitCents:Number(x.debit_cents),creditCents:Number(x.credit_cents),description:x.description||null}));return{id:row.id,companyId:row.company_id,date:row.journal_date,description:row.description,status:row.status,sourceType:row.source_type||null,sourceId:row.source_id||null,reversalOf:row.reversal_of||null,reversedBy:row.reversed_by||null,createdBy:row.created_by||null,createdAt:row.created_at,postedAt:row.posted_at,lines};}
 function getJournal(id,a=null){return journalMap(db.prepare('SELECT * FROM accounting_journals WHERE company_id=? AND id=?').get(cid(a),String(id)),a);}
 function postJournal(i={},a=null){manage(a);const companyId=cid(a),date=isoDate(i.date),description=String(i.description||'').trim();if(!description)throw new Error('Descricao contabil obrigatoria.');assertOpen(date,a);if(i.sourceType&&i.sourceId){const prior=db.prepare('SELECT * FROM accounting_journals WHERE company_id=? AND source_type=? AND source_id=?').get(companyId,String(i.sourceType),String(i.sourceId));if(prior)return journalMap(prior,a);}const raw=Array.isArray(i.lines)?i.lines:[];if(raw.length<2)throw new Error('Lancamento deve possuir ao menos duas linhas.');let debit=0,credit=0;const lines=raw.map(x=>{const account=getAccount(x.accountId,a);if(!account||!account.active)throw new Error(`Conta contabil invalida: ${x.accountId}`);const d=cents(x.debitCents,'Debito'),c=cents(x.creditCents,'Credito');if((d>0)===(c>0))throw new Error('Cada linha deve possuir somente debito ou credito.');debit+=d;credit+=c;return{accountId:account.id,debitCents:d,creditCents:c,description:String(x.description||'').trim()||null};});if(debit<=0||debit!==credit)throw new Error('Lancamento contabil deve estar balanceado entre debitos e creditos.');const id=String(i.id||idFactory('journal')),ts=String(now());return withTransaction(db,()=>{db.prepare("INSERT INTO accounting_journals(id,company_id,journal_date,description,status,source_type,source_id,reversal_of,reversed_by,created_by,created_at,posted_at) VALUES(?,?,?,?,'POSTED',?,?,?,?,?,?,?)").run(id,companyId,date,description,i.sourceType||null,i.sourceId||null,i.reversalOf||null,null,a?.userId||null,ts,ts);const insLine=db.prepare('INSERT INTO accounting_journal_lines(id,journal_id,account_id,debit_cents,credit_cents,description) VALUES(?,?,?,?,?,?)'),insLedger=db.prepare('INSERT INTO accounting_ledger_entries(id,company_id,journal_id,line_id,account_id,entry_date,debit_cents,credit_cents,description,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)');for(const line of lines){const lineId=idFactory('journal-line');insLine.run(lineId,id,line.accountId,line.debitCents,line.creditCents,line.description);insLedger.run(idFactory('ledger'),companyId,id,lineId,line.accountId,date,line.debitCents,line.creditCents,line.description,ts);}writeAudit(db,{action:'accounting.journal.post',entity:'accounting-journal',entityId:id,actor:a,context:{debitCents:debit,creditCents:credit}},now);return getJournal(id,a);});}
 function reverseJournal(id,{date,reason}={},a=null){manage(a);const original=getJournal(id,a);if(!original)throw new Error('Lancamento contabil nao encontrado.');if(original.reversedBy)return getJournal(original.reversedBy,a);const reversal=postJournal({date:date||String(now()).slice(0,10),description:`Estorno: ${reason||original.description}`,reversalOf:original.id,lines:original.lines.map(x=>({accountId:x.accountId,debitCents:x.creditCents,creditCents:x.debitCents,description:x.description}))},a);db.prepare('UPDATE accounting_journals SET reversed_by=? WHERE company_id=? AND id=?').run(reversal.id,cid(a),original.id);writeAudit(db,{action:'accounting.journal.reverse',entity:'accounting-journal',entityId:original.id,actor:a,context:{reversalId:reversal.id}},now);return getJournal(reversal.id,a);}
 function trialBalance({from=null,to=null}={},a=null){const companyId=cid(a),clauses=['l.company_id=?'],params=[companyId];if(from){clauses.push('l.entry_date>=?');params.push(isoDate(from));}if(to){clauses.push('l.entry_date<=?');params.push(isoDate(to));}const rows=db.prepare(`SELECT a.id,a.code,a.name,a.type,a.normal_balance,COALESCE(SUM(l.debit_cents),0) debit,COALESCE(SUM(l.credit_cents),0) credit FROM accounting_accounts a LEFT JOIN accounting_ledger_entries l ON l.company_id=a.company_id AND l.account_id=a.id AND ${clauses.slice(1).join(' AND ')||'1=1'} WHERE a.company_id=? GROUP BY a.id,a.code,a.name,a.type,a.normal_balance ORDER BY a.code,a.id`).all(...params.slice(1),companyId).map(r=>({accountId:r.id,code:r.code,name:r.name,type:r.type,normalBalance:r.normal_balance,debitCents:Number(r.debit),creditCents:Number(r.credit),balanceCents:r.normal_balance==='CREDIT'?Number(r.credit)-Number(r.debit):Number(r.debit)-Number(r.credit)}));const totalDebitCents=rows.reduce((s,x)=>s+x.debitCents,0),totalCreditCents=rows.reduce((s,x)=>s+x.creditCents,0);return{rows,totalDebitCents,totalCreditCents,balanced:totalDebitCents===totalCreditCents};}
 function balanceSheet(filters={},a=null){const tb=trialBalance(filters,a),rows=tb.rows.filter(x=>['ASSET','LIABILITY','EQUITY'].includes(x.type));return{rows,totalAssetsCents:rows.filter(x=>x.type==='ASSET').reduce((s,x)=>s+x.balanceCents,0),totalLiabilitiesCents:rows.filter(x=>x.type==='LIABILITY').reduce((s,x)=>s+x.balanceCents,0),totalEquityCents:rows.filter(x=>x.type==='EQUITY').reduce((s,x)=>s+x.balanceCents,0)};}
 function incomeStatement(filters={},a=null){const tb=trialBalance(filters,a),rows=tb.rows.filter(x=>['REVENUE','EXPENSE'].includes(x.type)),revenueCents=rows.filter(x=>x.type==='REVENUE').reduce((s,x)=>s+x.balanceCents,0),expenseCents=rows.filter(x=>x.type==='EXPENSE').reduce((s,x)=>s+x.balanceCents,0);return{rows,revenueCents,expenseCents,netIncomeCents:revenueCents-expenseCents};}
 return{createAccount,getAccount,listAccounts,createPeriod,closePeriod,postJournal,getJournal,reverseJournal,trialBalance,balanceSheet,incomeStatement};
}
module.exports={createAccountingService};
