'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {BrowserWindow,dialog}=require('electron');
function trustedSender(event){const senderUrl=String(event?.senderFrame?.url||'');try{return new URL(senderUrl).protocol==='file:';}catch{return false;}}
function safeFilename(value,fallback='documento'){const name=path.basename(String(value||fallback)).replace(/[<>:"/\\|?*\x00-\x1f]/g,'-').trim();return name||fallback;}
async function loadHtmlWindow(html){const win=new BrowserWindow({show:false,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}});await win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(String(html||''))}`);return win;}
function registerDocumentBridge({ipcMain,app}={}){if(!ipcMain||!app)throw new TypeError('ipcMain and app are required.');ipcMain.handle('erp:save-export-file',async(event,input={})=>{if(!trustedSender(event))throw new Error('Untrusted sender.');const filename=safeFilename(input.filename,'exportacao.dat'),result=await dialog.showSaveDialog({title:'Salvar exportação',defaultPath:path.join(app.getPath('downloads'),filename)});if(result.canceled||!result.filePath)return{canceled:true};const data=input.dataBase64?Buffer.from(String(input.dataBase64),'base64'):Buffer.from(String(input.data??''),'utf8');fs.writeFileSync(result.filePath,data);return{canceled:false,path:result.filePath,bytes:data.length};});ipcMain.handle('erp:save-pdf',async(event,input={})=>{if(!trustedSender(event))throw new Error('Untrusted sender.');const filename=safeFilename(input.filename,'documento.pdf').replace(/\.pdf$/i,'')+'.pdf',result=await dialog.showSaveDialog({title:'Salvar PDF',defaultPath:path.join(app.getPath('downloads'),filename),filters:[{name:'PDF',extensions:['pdf']}]});if(result.canceled||!result.filePath)return{canceled:true};const win=await loadHtmlWindow(input.html);try{const data=await win.webContents.printToPDF({printBackground:true,pageSize:'A4'});fs.writeFileSync(result.filePath,data);return{canceled:false,path:result.filePath,bytes:data.length};}finally{if(!win.isDestroyed())win.destroy();}});ipcMain.handle('erp:print-html',async(event,input={})=>{if(!trustedSender(event))throw new Error('Untrusted sender.');const win=await loadHtmlWindow(input.html);try{return await new Promise((resolve,reject)=>win.webContents.print({silent:false,printBackground:true},(success,failureReason)=>success?resolve({printed:true}):failureReason==='Print job canceled'?resolve({printed:false,canceled:true}):reject(new Error(failureReason||'Falha ao imprimir.'))));}finally{if(!win.isDestroyed())win.destroy();}});}
module.exports={trustedSender,safeFilename,registerDocumentBridge};
