'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {dialog}=require('electron');
const MAX_IMPORT_BYTES=10*1024*1024;
function trustedSender(event){const senderUrl=String(event?.senderFrame?.url||'');try{return new URL(senderUrl).protocol==='file:';}catch{return false;}}
function fileStat(filePath){const resolved=path.resolve(filePath),stat=fs.statSync(resolved);if(!stat.isFile()||stat.size>MAX_IMPORT_BYTES)throw new Error('Import exceeds max allowed size.');return{resolved,stat};}
function readOfx(filePath){const {resolved,stat}=fileStat(filePath);if(path.extname(resolved).toLowerCase()!=='.ofx')throw new Error('Only .ofx files are accepted.');const text=fs.readFileSync(resolved,'utf8').replace(/^\uFEFF/,'');return{name:path.basename(resolved),size:stat.size,sourceType:'OFX',encoding:'utf-8',text};}
async function extractPdfText(buffer){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const loading=pdfjs.getDocument({data:Uint8Array.from(buffer),disableWorker:true,useSystemFonts:true});const document=await loading.promise;const lines=[];try{for(let pageNumber=1;pageNumber<=document.numPages;pageNumber++){const page=await document.getPage(pageNumber),content=await page.getTextContent();let line='';for(const item of content.items){const text=String(item?.str||'').trim();if(text)line+=`${line?' ':''}${text}`;if(item?.hasEOL&&line.trim()){lines.push(line.trim());line='';}}if(line.trim())lines.push(line.trim());}}finally{await document.destroy();}const text=lines.join('\n');if(!text.trim())throw new Error('PDF não possui texto extraível. PDF escaneado exige OCR opcional e não faz parte do núcleo.');return text;}
async function readSpreadsheet(filePath){const {resolved,stat}=fileStat(filePath),ext=path.extname(resolved).toLowerCase();if(ext==='.csv'){const text=fs.readFileSync(resolved,'utf8').replace(/^\uFEFF/,'');return{name:path.basename(resolved),size:stat.size,sourceType:'CSV',encoding:'utf-8',text};}if(ext!=='.xlsx')throw new Error('Formato de planilha nao suportado.');const XLSX=require('xlsx'),book=XLSX.readFile(resolved,{cellDates:false,raw:true}),sheet=book.Sheets[book.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{defval:''});return{name:path.basename(resolved),size:stat.size,sourceType:'XLSX',rows};}
function readStatement(filePath){const {resolved,stat}=fileStat(filePath),ext=path.extname(resolved).toLowerCase();if(!['.ofx','.csv','.pdf','.xlsx'].includes(ext))throw new Error('Formato de extrato não suportado.');if(ext==='.xlsx')return readSpreadsheet(resolved);if(ext==='.pdf'){const text=await extractPdfText(fs.readFileSync(resolved));return{name:path.basename(resolved),size:stat.size,sourceType:'PDF_TEXT',encoding:'utf-8',text};}const text=fs.readFileSync(resolved,'utf8').replace(/^\uFEFF/,'');return{name:path.basename(resolved),size:stat.size,sourceType:ext==='.csv'?'CSV':'OFX',encoding:'utf-8',text};}
function registerImportBridge({ipcMain,app}={}){if(!ipcMain||!app)throw new TypeError('ipcMain and app are required.');ipcMain.handle('erp:select-import-file',async event=>{if(!trustedSender(event))throw new Error('Untrusted sender.');if(process.env.ERP_E2E==='1'&&process.env.ERP_E2E_IMPORT_FILE)return readStatement(process.env.ERP_E2E_IMPORT_FILE);const result=await dialog.showOpenDialog({title:'Selecionar extrato',properties:['openFile'],filters:[{name:'Extratos suportados',extensions:['ofx','csv','xlsx','pdf']},{name:'OFX',extensions:['ofx']},{name:'Planilhas',extensions:['csv','xlsx']},{name:'PDF com texto',extensions:['pdf']}]});if(result.canceled||!result.filePaths?.[0])return null;return readStatement(result.filePaths[0]);});}
module.exports={MAX_IMPORT_BYTES,trustedSender,registerImportBridge,readOfx,readStatement,readSpreadsheet,extractPdfText};
