'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),https=require('node:https'),http=require('node:http');
function sha256(file){const h=crypto.createHash('sha256');h.update(fs.readFileSync(file));return h.digest('hex');}
function getJson(url){return new Promise((resolve,reject)=>{const lib=url.startsWith('https:')?https:http;lib.get(url,{headers:{'user-agent':'ArtiSys-ERP-Updater'}},r=>{if(r.statusCode<200||r.statusCode>=300)return reject(new Error('Manifest HTTP '+r.statusCode));let b='';r.on('data',c=>b+=c);r.on('end',()=>{try{resolve(JSON.parse(b))}catch(e){reject(e)}})}).on('error',reject)});}
function download(url,target){return new Promise((resolve,reject)=>{const lib=url.startsWith('https:')?https:http,part=target+'.part';lib.get(url,{headers:{'user-agent':'ArtiSys-ERP-Updater'}},r=>{if(r.statusCode<200||r.statusCode>=300)return reject(new Error('Download HTTP '+r.statusCode));const f=fs.createWriteStream(part);r.pipe(f);f.on('finish',()=>f.close(()=>{fs.renameSync(part,target);resolve(target)}));f.on('error',reject)}).on('error',reject)});}
function cmp(a,b){const x=String(a).split('.').map(Number),y=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((x[i]||0)!==(y[i]||0))return(x[i]||0)-(y[i]||0)}return 0;}
function createUpdateService({app,shell,manifestUrl=process.env.ERP_UPDATE_MANIFEST_URL||''}={}){let state={status:'idle',available:null,error:null};
 async function check(){if(!manifestUrl){state={status:'disabled',available:null,error:null};return state;}try{const m=await getJson(manifestUrl);if(!m.version||!m.url||!m.sha256)throw new Error('Manifesto de atualizacao incompleto.');state={status:'checked',available:cmp(m.version,app.getVersion())>0?m:null,error:null};return state;}catch(e){state={status:'error',available:null,error:e.message};return state;}}
 async function downloadUpdate(){const m=state.available;if(!m)throw new Error('Nenhuma atualizacao disponivel.');const dir=path.join(app.getPath('userData'),'updates');fs.mkdirSync(dir,{recursive:true});const target=path.join(dir,'ArtiSys-ERP-'+m.version+'-Setup.exe');await download(m.url,target);if(sha256(target).toLowerCase()!==String(m.sha256).toLowerCase()){fs.rmSync(target,{force:true});throw new Error('Falha de integridade SHA-256 da atualizacao.');}state={...state,status:'downloaded',installerPath:target};return state;}
 async function install(){if(!state.installerPath||!fs.existsSync(state.installerPath))throw new Error('Instalador validado nao encontrado.');await shell.openPath(state.installerPath);setTimeout(()=>app.quit(),500);return{ok:true};}
 return{check,download:downloadUpdate,install,status:()=>state};}
module.exports={createUpdateService,cmp,sha256};